<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-14 12:05+0000
// PO revision date:  2012-07-12 21:33+0000

$lang = array (
  'am' => 'am',
  'friday' => 
  array (
    'abbv' => 'Vie',
    'full' => 'Viernes',
  ),
  'monday' => 
  array (
    'abbv' => 'Lun',
    'full' => 'Lunes',
  ),
  'pm' => 'pm',
  'saturday' => 
  array (
    'abbv' => 'Sáb',
    'full' => 'Sábado',
  ),
  'sunday' => 
  array (
    'abbv' => 'Dom',
    'full' => 'Domingo',
  ),
  'thursday' => 
  array (
    'abbv' => 'Jue',
    'full' => 'Jueves',
  ),
  'tuesday' => 
  array (
    'abbv' => 'Mar',
    'full' => 'Martes',
  ),
  'wednesday' => 
  array (
    'abbv' => 'Mié',
    'full' => 'Miércoles',
  ),
);

