<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-11-27 06:06+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Por favor verifica que has seleccionado un ítem.',
		'numeric' => 'Por favor verifica que has seleccionado un ítem.',
		'categories_required' => 'Los reportes deben ser categorizados antes de ser aprobados.',
	) ,
	'action' => array(
		'permission' => 'No tienes permisos para realizar esta acción.',
	) ,
);
