<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-21 00:03+0000
// PO revision date:  2012-07-12 21:50+0000

$lang = array (
  'description' => 
  array (
    'length' => 'El campo descripción debe tener al menos 3 y no más de 100 caracteres.',
    'required' => 'El campo descripción es requerido.',
  ),
  'name' => 
  array (
    'alpha_numeric' => 'El campo nombre debe contener solo números y letras.',
    'length' => 'El campo nombre debe tener al menos 2 y no más de 30 caracteres.',
    'nomodify' => 'El rol de SuperAdmin no puede ser modificado.',
    'required' => 'El campo nombre es requerido.',
  ),
);

