<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-31 00:04+0000
// PO revision date:  2012-08-17 07:01+0000
$lang = array(
	'date' => 'Fecha de ingreso',
	'date_added' => 'Agregado el',
	'last_access' => 'Último acceso',
	'sharing_color' => array(
		'length' => 'El campo color debe tener 6 caracteres de largo.',
		'required' => 'El campo color es obligatorio.',
	) ,
	'sharing_url' => array(
		'exists' => 'The site url already exists',
		'length' => 'La URL del sitio no es válida.',
		'required' => 'La URL del sitio es obligatoria.',
		'url' => 'The site url field does not appear to contain a valid URL?',
	) ,
);
