<?php
	$lang = array(
	'upgrade' => array(
		'between' => 'Invalid input data. It can either be 0 for No or 1 for Yes.',
	),
	'upgrade_automatic' => 'Actualización automática',
	'upgrade_available' => 'Actualizaciones disponibles',
	'upgrade_continue_btn_text' => 'Continuar',
	'upgrade_db_btn_text' => 'Actualizar',
	'upgrade_db_text_1' => 'Voy a actualizar su base de datos desde la versión',
	'upgrade_db_text_2' => 'a la nueva versión de la base de datos.',
	'upgrade_db_text_3' => 'Haga click en el botón "Actualizar" y solo relajese mientras realizo la magia.',
	'upgrade_db_text_4' => 'Adicionalmente, si quiere respaladr su base de datos, marque  el checkbox de abajo y yo lo haré en un instante.',
	'upgrade_db_text_5' => '¿Respaldar base de datos antes de la actualización? (<strong style="color:#FF0000;">Altamente recomendado</strong>)',
	'upgrade_db_title' => 'Ushahidi database upgrade',
	'upgrade_failed' => 'La actualización fallo en algún punto',
	'upgrade_manual' => 'Actualización manual',
	'upgrade_status' => 'Ushahidi upgrade status',
	'upgrade_text_1' => 'Estas instrucciones lo guiarán para actualizar manualmente Ushahidi',
	'upgrade_text_2' => '<strong>Paso 1:</strong> Descargue la última versión de Ushahidi desde <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
	'upgrade_text_3' => '<strong>Paso 2:</strong> Dependiendo del sistema operativo en que corre el servidor web, use su método preferido para ingresar al servidor (i.e: telnet, ftp, ssh) y reemplace el contenido de todos los directorios con los de la última versión. <strong>Todos EXCEPTO:</strong>',
	'upgrade_text_4' => 'Paso 3: Utilizando un cliente de MySQL (ejemplo: phpMyAdmin) ejecute <code>upgrade.sql</code>. Este programa actualizar',
	'upgrade_tables' => '<strong>Step 3:</strong> Look inside the <strong>sql</strong> folder. Manuall run the upgrade<xx>-<xx>.sql file starting from the current db version of your install through to the final sql upgrade file.',
	'upgrade_text_5' => 'Para una actualización automática, haga click en el botón de abajo.',
	'upgrade_text_6' => 'For automatic upgrade, click on the button below.',
	'upgrade_title_text_1' => 'Usted está actualmente usando Ushahidi v',
    'upgrade_title_text_2' => 'with database version ',
	'upgrade_title_text_3' => 'running on',
	'upgrading' => 'Actualizando',
    'upgrade_ftp_text' => 'To continue with the easy upgrade, the following information is required for the FTP server that your website is hosted on.',
    'upgrade_ftp_hostname' => 'FTP Hostname: <span>Example: "localhost"</span>',
    'upgrade_ftp_password' => 'FTP Password:',
    'upgrade_ftp_username' => 'FTP User Name:',
    'upgrade_status_info' => 'You have the latest version of Ushahidi.',
    'upgrade_db_version' => 'Database version: ',
    'upgrade_warning_software_version' => 'Warning: Software version in version.php and database do not match.',
    'upgrade_warning_db_version' => 'Warning: Database version in version.php and database do not match.',
    'upgrade_database' => 'Database:'
	);
?>
