<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-16 06:03+0000
// PO revision date:  2012-07-12 21:32+0000

$lang = array (
  'am' => 'صباحاً',
  'friday' => 
  array (
    'abbv' => 'الجمعة',
    'full' => 'الجمعة',
  ),
  'monday' => 
  array (
    'abbv' => 'الاثنين',
    'full' => 'الاثنين',
  ),
  'pm' => 'مساءً',
  'saturday' => 
  array (
    'abbv' => 'السبت',
    'full' => 'السبت',
  ),
  'sunday' => 
  array (
    'abbv' => 'الأحد',
    'full' => 'الأحد',
  ),
  'thursday' => 
  array (
    'abbv' => 'الخميس',
    'full' => 'الخميس',
  ),
  'tuesday' => 
  array (
    'abbv' => 'الثلاثاء',
    'full' => 'الثلاثاء',
  ),
  'wednesday' => 
  array (
    'abbv' => 'الأربعاء',
    'full' => 'الأربعاء',
  ),
);

