<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-11-27 06:06+0000
$lang = array(
	'incident_id' => array(
		'required' => 'يرجى التحقق من انك قد قمت باختيار عنصر',
		'numeric' => 'يرجى التحقق من انك قد قمت باختيار عنصر',
		'categories_required' => 'التقارير يجب أن تصنف قبل أن يتم الموافقة عليها',
	) ,
	'action' => array(
		'permission' => 'أنك لا تملك إذن لتنفيذ هذا الإجراء',
	) ,
);
