<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-15 12:00+0000
$lang = array(
	'email' => array(
		'email' => 'E-mail адрес введен неверно',
		'exists' => 'Данный e-mail уже используется',
		'length' => 'Длина e-mail адреса должна быть от 4 до 64 символов.',
		'required' => 'Введите e-mail',
	) ,
	'name' => array(
		'length' => 'Имя должно быть от 3 до 100 символов',
		'required' => 'Поле Имя обязательно для заполнения',
		'standard_text' => 'Поле Имя содержит недопустимые символы.',
	) ,
	'password' => array(
		'length' => 'Длина Пароля должна быть от 5 до 16 символов',
		'login error' => 'Пароль введен неверно',
		'matches' => 'Введите идентичный пароль в двух соответствующих полях',
		'required' => 'Введите пароль',
	) ,
	'password_confirm' => array(
		'matches' => 'Введенные пароли должны совпадать',
	) ,
	'resetemail' => array(
		'email' => 'Введите правильный e-mail адрес',
		'invalid' => 'Ваш e-mail не зарегистрирован в нашей системе',
		'required' => 'Введите e-mail',
	) ,
	'roles' => array(
		'required' => 'Вы должны задать хотя бы одну роль',
		'values' => 'Выберите АДМИНИСТРАТОР или ПОЛЬЗОВАТЕЛЬ',
	) ,
	'username' => array(
		'admin' => 'Роль пользователя Администратор не может быть изменена',
		'exists' => 'Имя пользователя уже используется',
		'length' => 'Длина Имени пользователя должна быть от 2 до 16 символов',
		'login error' => 'Введите правильное имя пользователя',
		'required' => 'Введите имя пользователя.',
		'superadmin' => 'Роль пользователя Суперадминистратор не может быть изменена',
	) ,
);
