<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:27+0000
$lang = array(
	'category_color' => array(
		'length' => 'Поле цвет должно содержать 6 знаков (например 00FF00).',
		'required' => 'Задайте цвет категории.',
	) ,
	'category_description' => array(
		'required' => 'Введите описание категории.',
	) ,
	'category_image' => array(
		'size' => 'Изображение должно быть меньше 50 kВ.',
		'type' => 'Вы действительно загрузили изображение? Поддерживаются форматы JPG / PNG / GIF.',
		'valid' => 'Не могу открыть изображение, файл испорчен.',
	) ,
	'category_title' => array(
		'length' => 'Название должно содержать от 3 до 80 символов.',
		'required' => 'Введите название.',
	) ,
	'parent_id' => array(
		'exists' => 'Родительская категория не существует.',
		'numeric' => 'Родительская категория должна быть числом.',
		'required' => 'Родительская категория обязательна.',
		'same' => 'Категория и родительская категория не могут быть одинаковыми.',
	) ,
);
