<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-03 00:02+0000
$lang = array(
	'field_default' => array(
		'length' => 'Имя поля не может быть короче 3-х и длиннее 100 символов.',
	) ,
	'field_height' => array(
		'between' => 'Введите значение поля от 0 до 50',
	) ,
	'field_isdate' => array(
		'between' => 'Вы выбрали неправильное значение поля "Дата"',
		'required' => 'Выберите Да или Нет',
	) ,
	'field_name' => array(
		'length' => 'Имя поля не может быть короче 3-х и длиннее 100 символов.',
		'required' => 'Введите имя поля.',
	) ,
	'field_required' => array(
		'between' => 'Вы ввели неправильное значения для обязательного поля',
		'required' => 'Выберите "Да" или "Нет" для обязательного поля',
	) ,
	'field_type' => array(
		'numeric' => 'Выберите правильный тип поля.',
		'required' => 'Выберите тип поля.',
	) ,
	'field_width' => array(
		'between' => 'Введите значение от 0 до 300 для ширины поля',
	) ,
	'form_description' => array(
		'required' => 'Введите описание формы.',
	) ,
	'form_id' => array(
		'default' => 'Форма по-умолчанию не может быть удалена.',
		'numeric' => 'Выберите, в какую форму нужно добавить данное поле.',
		'required' => 'Выберите, в какую форму нужно добавить данное поле.',
	) ,
	'form_title' => array(
		'length' => 'Длина имени формы не может быть менее 3х и более 100 символов.',
		'required' => 'Введите имя формы.',
	) ,
);
