<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-11 14:37+0000
$lang = array(
	'reports_view' => 'Просмотреть отчёты',
	'reports_edit' => 'Создать/Редактировать/Удалить отчёты',
	'reports_approve' => 'Одобрить отчёты',
	'reports_verify' => 'Подтвердить отчёты',
	'reports_comments' => 'Управление комментариями',
	'reports_download' => 'Скачать отчёты',
	'reports_upload' => 'Загрузить отчёты',
	'stats' => 'Просмотреть статистику',
	'settings' => 'Управление настройками',
	'users' => 'Управление пользователями',
);
