<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-01 06:04+0000
// PO revision date:  2012-07-12 21:49+0000

$lang = array (
  'latitude' => 
  array (
    'between' => 'Введите верное значение широты',
    'required' => 'Введите широту или выберите место на карте.',
  ),
  'level_id' => 
  array (
    'numeric' => 'The Reporter Level field does not appear to contain a valid Level?',
    'required' => 'The Reporter Level field does not appear to contain a valid Level?',
  ),
  'location_name' => 
  array (
    'length' => 'Имя локации должно быть от 3 до 200 символов.',
    'required' => 'Заполните имя локации',
  ),
  'longitude' => 
  array (
    'between' => 'Введите верное значение долготы',
    'required' => 'Введите долготу или выберите место на карте.',
  ),
  'reporter_id' => 
  array (
    'numeric' => 'Invalid Reporter',
    'required' => 'Invalid Reporter',
  ),
);

