<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:50+0000
$lang = array(
	'description' => array(
		'length' => 'Поле "Описание" должно быть от 3-х до 100 символов.',
		'required' => 'Поле "Описание" должно быть заполнено.',
	) ,
	'name' => array(
		'alpha_numeric' => 'Поле "Имя" может содержать только буквы или цифры.',
		'length' => 'Поле Имя должно быть от 2-х до 30 символов.',
		'nomodify' => 'Роль Суперадминистратора не может быть изменена.',
		'required' => 'Поле "Имя" должно быть заполнено.',
	) ,
	'access_level' => array(
		'numeric' => 'Поле "Уровень доступа" должно быть числом от 0 до 100.',
		'required' => 'Поле "Уровень доступа" должно быть числом от 0 до 100.',
	) ,
);
