<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-17 07:02+0000
$lang = array(
	'date' => 'Дата регистрации',
	'date_added' => 'Дата добавления',
	'last_access' => 'Последнее посещение',
	'sharing_color' => array(
		'length' => 'Значение цвета должно быть 6-значным (FF00FF)',
		'required' => 'Введите цвет',
	) ,
	'sharing_name' => array(
		'length' => 'The Sharing name ведено неверно',
		'required' => 'Введите Sharing name.',
	) ,
	'sharing_url' => array(
		'exists' => 'URL сайта уже существует',
		'required' => 'Введите URL сайта',
		'url' => 'Адрес сайта введен неверно',
	) ,
);
