<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-30 12:11+0000
// PO revision date:  2012-10-25 00:01+0000
$lang = array(
	'about' => 'متعلق ',
	'alerts' => 'الرٹ حاصل کریں',
	'all' => 'فلٹرز',
	'contact' => 'ہم سے رابطہ',
	'feedback' => 'ائے دیں',
	'filters' => 'سب کچھ',
	'home' => 'صفحۂ اوّل',
	'news' => 'تصاویر',
	'pictures' => 'خبریں',
	'remove' => 'remove',
	'reports' => ' رپورٹس',
	'submit' => 'رپورٹ بھیجیں ',
	'video' => ' رپورٹس',
);
