<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-03 00:02+0000
$lang = array(
	'field_default' => array(
		'length' => 'F&auml;ltnamnet m&aring;ste vara mellan 3 och 200 tecken.',
	) ,
	'field_height' => array(
		'between' => 'Ange ett v&auml;rde mellan 0 och 50 f&ouml;r f&auml;ltets h&ouml;jd',
	) ,
	'field_isdate' => array(
		'between' => 'Du har angett ett ogiltigt v&auml;rde f&ouml;r datumf&auml;ltet',
		'required' => 'V&auml;lj Ja eller Nej f&ouml;r datumf&auml;ltet',
	) ,
	'field_name' => array(
		'length' => 'F&auml;ltnamnet m&aring;ste vara mellan 3 och 100 tecken.',
		'required' => 'Ange f&auml;ltnamn.',
	) ,
	'field_required' => array(
		'between' => 'Du har angett ett felaktigt v&auml;rde f&ouml;r f&auml;ltet',
		'required' => 'V&auml;lj om f&auml;ltet m&aring;ste fyllas i',
	) ,
	'field_type' => array(
		'numeric' => 'V&auml;lj en giltig f&auml;lttyp.',
		'required' => 'V&auml;lj en f&auml;lttyp.',
	) ,
	'field_width' => array(
		'between' => 'Ange ett v&auml;rde mellan 0 och 300 f&ouml;r f&auml;ltets bredd',
	) ,
	'form_description' => array(
		'required' => 'Formul&auml;rets beskrivning.',
	) ,
	'form_id' => array(
		'default' => 'Standardformul&auml;ret kan inte tas bort.',
		'numeric' => 'V&auml;lj vilket i vilket formul&auml;r du vill l&auml;gga till f&auml;ltet.',
		'required' => 'V&auml;lj vilket i vilket formul&auml;r du vill l&auml;gga till f&auml;ltet.',
	) ,
	'form_title' => array(
		'length' => 'Formul&auml;rnamnet m&aring;ste vara mellan 3 och 100 tecken.',
		'required' => 'Formul&auml;rets namn.',
	) ,
);
