<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:42+0000
$lang = array(
	'akismet_cannot_connect' => 'Kan inte ansluta till akismet servern',
	'akismet_cannot_retrieve' => 'F&aring;r inget svar fr&aring;n Akismet',
	'askimet_invalid_apikey' => 'Ogiltig Akismet API nyckel',
	'clickatell_fopen_error' => 'Fel n&auml;r fopen inskicksmetod k&ouml;rdes!<br>Kontrollera om PHP st&ouml;djer OpenSSL och kontrollera att PHP &auml;r minst version 5.2',
	'clickatell_message_too_long' => 'Ditt unicode-meddelande &auml;r f&ouml;r l&aring;ngt! (Nuvarande l&auml;ngd=',
	'clickatell_no_destination_address' => 'Ange destinationsadress (TILL)!',
	'clickatell_no_sender_address' => 'Ange uppeh&aring;llsadress (FR&Aring;N)!',
	'clickatell_unicode_message_too_long' => 'Ditt unicode-meddelande &auml;r f&ouml;r l&aring;ngt! (Nuvarande l&auml;ngd=',
	'clickatell_unsupported_method' => 'Inskicksmetod st&ouml;ds inte!',
	'upgrade_directory_not_deleted' => 'Biblioteket <code>%s</coded> kunde inte tas bort',
	'upgrade_extracting_error' => 'Fel vid &ouml;ppnade: <code>%s</code>',
	'upgrade_failed' => 'Misslyckades vid nedladdning av senaste ushahidiversionen. HTTP status kod',
	'upgrade_file_not_copied' => 'Filen <code>%s</coded> kunde inte kopieras',
	'upgrade_file_not_deleted' => 'Filen <code>%s</coded> kunde inte tas bort',
	'upgrade_title' => 'Ushahidi upgraderings script',
	'upgrade_zip_error' => 'Den nedladdade ushahidi zip-filen <code>%s</code>, kunde inte skrivas',
);
