<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 23:07+0000
$lang = array(
	'admin_footer' => 'Detta meddelande skickades fr&aring;n din hemsida',
	'admin_new_comment' => array(
		'message' => 'En ny kommentar har skrivits in till:',
		'subject' => 'Ny kommentar',
	) ,
	'admin_new_email' => array(
		'message' => 'Ett nytt e-postmeddelande har skickats in.',
		'subject' => 'Nytt meddelande',
	) ,
	'admin_new_report' => array(
		'message' => 'En ny rapport har skickats till din hemsida.',
		'subject' => 'Ny rapport',
	) ,
	'admin_new_sms' => array(
		'message' => 'Ett nytt SMS har skickats in.',
		'subject' => 'Nytt SMS',
	) ,
);
