<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-10 18:05+0000
// PO revision date:  2012-07-12 21:30+0000

$lang = array (
  'config' => 'config file',
  'controller' => 'controller',
  'driver' => 'driver',
  'driver_implements' => '%s დრაივერმა %s ბიბლიოთეკისათვის უნდა  განახორციელოს  %s ინტერფეისი',
  'driver_not_found' => ' %s ბიბლიოთეკისათვის %s დრაივერის ვერ მოიძებნა',
  'errors_disabled' => 'თქვენ შეგიძლიათ გადახვიდეთ <ტექნიკური კონფერენცია="%s">მთავარი გვერდი</a> ან <ტექნიკური კონფერენცია="%s">კვლავ სცადეთ</a>.',
  'error_file_line' => '<tt>%s <ძლიერი>[%s]:</ძლიერი></tt>',
  'generic_error' => 'შეუძლებელია მოთხოვნის დასრულება',
  'helper' => 'დამხმარე',
  'invalid_filetype' => 'მოთხოვნილი ფაილის ტიპი, .%s, არ არის დასაშვები თქვენი კონფიგურაციის ფაილში',
  'invalid_method' => 'არასწორი მეთოდი %s გამოძახებულია %s',
  'invalid_property' => '%s მახასიათებელი არ არსებობს %s კლასში.',
  'library' => 'ბიბლიოთეკა',
  'log_dir_unwritable' => 'დირექტორიის ჩანაწერები არ არის გადაწერადი: %s',
  'model' => 'მოდელი',
  'no_controller' => 'Ushahidi–მ ვერ შეძლო აღმოეჩინა მაკონტროლებელი, რათაგადაემუშავებინა მოცემული მოთხოვნა: %s',
  'no_default_route' => 'გთხოვთ დააყენოთ ავტომატურიმიმართულება კონფიგ/მიმართულებაში.php',
  'page_not_found' => 'გვერდი, რომელიც თქვენ მოითხოვეთ, %s, არ იძებნება.',
  'report_bug' => '<ტექნიკური კონფერენცია="%s" id="ჩენება_დეფექტები">შეატყობინე ეს პრობლემა Ushahidi–ს</a>',
  'resource_not_found' => 'The requested %s, %s, could not be found',
  'stack_trace' => 'Stack Trace',
  'stats_footer' => 'ჩატვირთული {შესრულება_დრო} წამებში, მეხსიერების {მეხსიერება_გამოყენება} გამოყენება. გენერირებულია Ushahidi v%s მიერ.',
  'there_can_be_only_one' => 'გვერდის მოთხოვნისას შესაძლებელია იყოს Ushahidi–ის მხოლოდ ერთი ნიმუში',
  'uncaught_exception' => 'დაუჭერელი %s: %s ფაილში %s ხაზზე %s',
  'view' => 'view',
  'view_set_filename' => 'თქვენ უნდა დააყენოთ წარმოდგენის ფაილის სახელი, სანამ გამოიძახებთ რენდერს',
);

