<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-17 18:03+0000
// PO revision date:  2012-07-12 21:33+0000

$lang = array (
  'am' => 'am',
  'friday' => 
  array (
    'abbv' => 'Fri',
    'full' => 'არასკევი',
  ),
  'monday' => 
  array (
    'abbv' => 'Mon',
    'full' => 'ორშაბათი',
  ),
  'pm' => 'pm',
  'saturday' => 
  array (
    'abbv' => 'Sat',
    'full' => 'შაბათი',
  ),
  'sunday' => 
  array (
    'abbv' => 'Sun',
    'full' => 'კვირა',
  ),
  'thursday' => 
  array (
    'abbv' => 'Thu',
    'full' => 'ხუთშაბათი',
  ),
  'tuesday' => 
  array (
    'abbv' => 'Tue',
    'full' => 'სამშაბათი',
  ),
  'wednesday' => 
  array (
    'abbv' => 'Wed',
    'full' => 'ოთხშაბათი',
  ),
);

