<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-13 04:30+0000
// PO revision date:  2012-07-13 04:22+0000

$lang = array (
  'description' => 
  array (
    'length' => 'აღწერის ველი უნდა შედგებოდეს არანაკლებ 3 და არაუმეტეს 100 სიმბოლოსგან.',
    'required' => 'აღწერის ველი სავალდებულოა.',
  ),
  'name' => 
  array (
    'alpha_numeric' => 'სახელის ველი უნდა შეიცავდეს მხოლოდ ასოებსა და ციფრებს.',
    'length' => 'სახელის ველი უნდა შედგებოდეს არანაკლებ 2 და არაუმეტეს 30 სიმბოლოსგან.',
    'nomodify' => 'SuperAdmin–ის ფუნქციის შეცვლა შეუძლებელია.',
    'required' => 'სახელის ველი სავალდებულოა.',
  ),
);

