<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:23+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Érvénytelen email cím szerepel az email mezőben?',
		'email_check' => 'Ez a cím már regisztrálva lett ennek a helyszínnek az értesítőire',
		'length' => 'Az email mező legalább 4 és legfeljebb 64 karakter hosszú lehet.',
		'required' => 'Az email mezőt kötelező kitölteni, ha jelölőnégyzetben ki lett pipálva.',
	) ,
	'alert_lat' => array(
		'between' => 'Érvénytelen helyszínt jelölt meg a térképen.',
		'required' => 'Érvénytelen helyszínt jelölt meg a térképen.',
	) ,
	'alert_lon' => array(
		'between' => 'Érvénytelen helyszínt jelölt meg a térképen.',
		'required' => 'Nem jelölt ki érvényes helyszínt a térképen.',
	) ,
	'alert_mobile' => array(
		'length' => 'A mobiltelefon mezőben nem megfelelő a számjegyek darabszáma.',
		'mobile_check' => 'Ez a mobiltelefonszám már regisztrálva lett ennek a helyszínnek az értesítőire.',
		'numeric' => 'A mobiltelefon mezőben nem megfelelő a számok mennyisége. Csak a ország hívószámát tartalmazó számot írja be.',
		'one_required' => 'Mobiltelefonszám vagy email cím szükséges.(most csak az email küldést funkció működik)',
		'required' => 'A mobiltelefon szükséges, ha a jelölőnégyzet ki van pipálva.',
	) ,
	'alert_radius' => array(
		'in_array' => 'Még nincs beállítva érvényes hatókör a térképen.',
		'required' => 'Még nincs beállítva a hatókör a térképen.',
	) ,
	'code_already_verified' => 'Ezt a kódot már hitelesítettük!',
	'code_not_found' => 'A megadott kód nem található. Ellenőrizze a kapott URL-t!',
	'code_verified' => 'A kódja hitelesített. Mostantól azonnal kap értesítőt ha a közelbe történik esemény.',
	'confirm_request' => 'Hogy megerősítse az értesítésék kérését, kérjük, látogasson el a ',
	'create_more_alerts' => 'Térjen vissza a értesítésék oldalra, hogy új riasztást állítson be',
	'email_alert_request_created' => 'A kért email értesítő elkészült, visszaigazoló üzenetet küldtünk a',
	'email_code' => 'Kérjük, adja meg az emailben kapott visszaigazoló kódot: ',
	'email_error_head' => 'Az email értesítések kérése NINCS elmentve!',
	'email_ok_head' => 'Az email értesítések kérése elmentve!',
	'error' => 'A rendszer nem volt képes feldolgozni a megerősítési kérést!',
	'mobile_alert_request_created' => 'A mobil értesítések kérése létrejött, visszaigazoló üzenetet küldtünk a  ',
	'mobile_code' => 'Kérjük, adja meg a visszaigazoló SMS-kódot, ami a mobiltelefonjára érkezett: ',
	'mobile_error_head' => 'A mobil értesítések kérése NINCS elmentve!',
	'mobile_ok_head' => 'A mobil értesítések kérése elmentve!',
	'settings_error' => 'Ez a bevitel nincs beállítva helyesen ahhoz, hogy pontosan dolgozza fel az értesítéseket',
	'unsubscribe' => 'Ön azért kapta ezt a levelet, mert feliratkozott értesítésekre. Ha nem szeretne kapni a jövőben értesítéseket, klikkeljen ide.',
	'unsubscribed' => 'Nem fog több értesítést kapni.',
	'unsubscribe_failed' => 'Nem tudott leiratkozni. Kérjük, erősítse meg, hogy a megfelelő URL-t adta meg.',
	'verification_email_subject' => 'értesítés - megerősítés ',
	'verify_code' => 'Ezen a címen nem fog értesítéseket kapni, amíg meg nem erősíti a kérést.',
);
