<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-24 06:19+0000
// PO revision date:  2013-03-23 23:38+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Érvénytelen email cím szerepel az email mezőben?',
		'email_check' => 'Ez a cím már regisztrálva lett ennek a helyszínnek az értesítőire',
		'length' => 'Az email mező legalább 4 és legfeljebb 64 karakter hosszú lehet.',
		'required' => 'Az email mezőt kötelező kitölteni, ha jelölőnégyzetben ki lett pipálva.',
	) ,
	'alert_country' => array(
		'single_country' => 'Ez a telepítés csak egy országra terjed ki. Kérjük győződjön meg róla, hogy a riasztási helyszín az országon belül van: %s!',
	) ,
	'alert_lat' => array(
		'between' => 'Érvénytelen helyszínt jelölt meg a térképen.',
		'required' => 'Érvénytelen helyszínt jelöltél meg a térképen.',
	) ,
	'alert_lon' => array(
		'between' => 'Érvénytelen helyszínt jelöltél meg a térképen.',
		'required' => 'Nem jelöltél ki érvényes helyszínt a térképen.',
	) ,
	'alert_mobile' => array(
		'length' => 'A mobiltelefonszám mezőben nem megfelelő a számjegyek darabszáma.',
		'mobile_check' => 'Ez a mobiltelefonszám már regisztrálva lett ennek a helyszínnek az értesítőire.',
		'numeric' => 'A mobiltelefon mezőben nem megfelelő a számok mennyisége. Kérjük, hogy az ország hívószámát is írd be. Magyarország: 36',
		'one_required' => 'A mobiltelefonszám vagy az email cím megadása szükséges - jelenleg csak az emailben történő értesítés funkció működik.',
		'required' => 'A mobiltelefon szükséges, ha a jelölőnégyzet ki van pipálva.',
	) ,
	'alert_radius' => array(
		'in_array' => 'Még nincs beállítva érvényes hatókör a térképen.',
		'required' => 'Még nincs beállítva a hatókör a térképen.',
	) ,
	'alert_recipient' => array(
		'required' => 'Nem adtál meg elérhetőségi adatokat az értesítésekhez.',
	) ,
	'alerts_subscribed' => 'A következő kategóriák értesítéseire iratkoztál fel:',
	'code_already_verified' => 'Ezt a kódot már hitelesítettük!',
	'code_not_found' => 'A megadott hitelesítési kód nem található. Kérjük, hogy ellenőrizd a kapott linket!',
	'code_verified' => 'A kód hitelesítése megtörtént. Mostantól értesítőt küldünk, ha a megadott körzetben megfelelő kategóriájú bejelentés érkezik.',
	'confirm_request' => 'Annak érdekében, hogy megerősítsd az értesítések kérését, kérjük, látogass el a ',
	'create_more_alerts' => 'Visszatérés az értesítések oldalára',
	'email_alert_request_created' => 'A kért email értesítő elkészült, visszaigazoló üzenetet küldtünk a',
	'email_code' => 'Kérjük, adja meg az emailben kapott visszaigazoló kódot: ',
	'email_error_head' => 'Az email értesítések kérése NINCS elmentve!',
	'email_ok_head' => 'Az email értesítések kérése elmentve!',
	'error' => 'A rendszer nem volt képes feldolgozni a megerősítési kérést!',
	'mobile_alert_request_created' => 'Az SMS értesítések kérése létrejött, visszaigazoló üzenetet küldtünk a  ',
	'mobile_code' => 'Kérjük, add meg a visszaigazoló SMS kódot, ami a mobiltelefonodra érkezett: ',
	'mobile_error_head' => 'AZ SMS értesítések kérése NINCS elmentve!',
	'mobile_ok_head' => 'Az SMS értesítések kérése elmentve!',
	'settings_error' => 'A rendszer még nem alkalmas az értesítés kérések feldolgozására.',
	'unsubscribe' => 'Azért kaptad ezt a levelet, mert feliratkoztál a joszolgalat.hu weboldal értesítéseire. Ha a jövőben nem szeretnél értesítéseket kapni, kérjük kattints ide:',
	'unsubscribed' => 'A jövőben nem fogsz több értesítést kapni.',
	'unsubscribe_failed' => 'Nem volt sikeres a leiratkozás. Kérjük, ellenőrizd, hogy a megfelelő linket adtad-e meg.',
	'verification_email_subject' => 'értesítés - megerősítés ',
	'verify_code' => 'Ezen a címen nem fogsz értesítéseket kapni, amíg meg nem erősíted a kérést.',
);
