<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:28+0000
$lang = array(
	'captcha' => array(
		'default' => 'Kérem, adjon meg érvényes biztonsági kódot',
		'required' => 'Kérem, adja meg a biztonsági kódot.',
	) ,
	'comment_author' => array(
		'length' => 'A névnek legalább 3 karakter hosszúnak kell lennie.',
		'required' => 'A név mezőt kötelező kitölteni.',
	) ,
	'comment_description' => array(
		'required' => 'A komment mezőt kötelező kitölteni.',
	) ,
	'comment_email' => array(
		'email' => 'Érvénytelen e-mail címet adott meg?',
		'length' => 'Az e-mailnek legalább 4, maximum 64 karakternek kell lennie.',
		'required' => 'Az e-mail mezőt kötelező kitölteni, ha a jelölőnégyzetben ki van pipálva.',
	) ,
);
