<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:29+0000
$lang = array(
	'captcha' => array(
		'default' => 'Kérem, érvényes biztonsági kódot adjon meg!',
		'required' => 'Kérem, adja meg a biztonsági kódot!',
	) ,
	'contact_email' => array(
		'email' => 'Lehet hogy rosszul töltötte ki az emailcímét?',
		'length' => 'Az emailnek minimum 4, maximum 64 karakter hosszúnak kell lennie.',
		'required' => 'Az email mezőt kötelező kitölteni, ha a jelölőnégyzetben ki van pipálva',
	) ,
	'contact_message' => array(
		'required' => 'Az üzenet mezőt kötelező kitölteni.',
	) ,
	'contact_name' => array(
		'length' => 'A névnek legalább 3 karakter hosszúnak kell lennie.',
		'required' => 'A név mezőt kötelező kitölteni.',
	) ,
	'contact_subject' => array(
		'length' => 'A témának legalább 3 karakter hosszúnak kell lennie.',
		'required' => 'A téma mező kitöltése kötelező.',
	) ,
);
