<?php
	$lang = array(
	'config' => 'konfiguracios fajl',
	'controller' => 'vezérlő',
	'driver' => 'meghajtó',
	'driver_implements' => 'A %s meghajtónak a %s könyvtárhoz a %s interfészt kell implementálnia',
	'driver_not_found' => 'A %s meghajtó a %s könyvtárhoz nem található.',
	'errors_disabled' => 'Látogasson el a <a href="%s">főoldalra</a> vagy <a href="%s">próbálja újra</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'A kérést nem sikerült teljesíteni.',
	'helper' => 'helper',
	'invalid_filetype' => 'A kért fájltípust, .%s, nem támogatja a nézethez tartozó konfigurációs fájl.',
	'invalid_method' => 'Érvénytelen folyamatot %s indított el a %s',
	'invalid_property' => 'A %s property fájl nem található a %s osztályban.',
	'library' => 'könyvtár',
	'log_dir_unwritable' => 'A log könyvtár nem írható: %s\'',
	'model' => 'modell',
	'no_controller' => 'Az \'Ushahidi nem tudott controllert meghatározni a kérés feldolgozásához: %s',
	'no_default_route' => 'Kérem, adjon meg egy alapértelmezett elérési utat a következőn: config/routes.php',
	'page_not_found' => 'A kért oldal, %s, nem található.',
	'report_bug' => '<a href="%s" id="show_bugs">Jelentem ezt az esetet az Ushahidinek</a>',
	'resource_not_found' => 'A kért %s, %s, nem található',
	'stack_trace' => 'Stack Trace',
	'stats_footer' => 'A betöltéshez igénybevett idő {execution_time} másodperc, felhasznált memória {memory_usage}. Az Ushahidi v%s által létrehozva.',
	'there_can_be_only_one' => 'Csak egy Ushahidi eset lehet egy oldalkérésen',
	'uncaught_exception' => 'Nem talált %s: %s %s fájlban %s sorban',
	'view' => 'nézet',
	'view_set_filename' => 'Beküldés előtt a nézet fájlnevet kell meg kell adni',
	);
?>
