<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:33+0000
$lang = array(
	'am' => 'de',
	'friday' => array(
		'abbv' => 'Pntk.',
		'full' => 'Péntek',
	) ,
	'monday' => array(
		'abbv' => 'Htf',
		'full' => 'Hétfő',
	) ,
	'pm' => 'du',
	'saturday' => array(
		'abbv' => 'Szomb',
		'full' => 'Szombat',
	) ,
	'sunday' => array(
		'abbv' => 'Vasr',
		'full' => 'Vasárnap',
	) ,
	'thursday' => array(
		'abbv' => 'Csüt',
		'full' => 'Csütörtök',
	) ,
	'tuesday' => array(
		'abbv' => 'Kedd',
		'full' => 'Kedd',
	) ,
	'wednesday' => array(
		'abbv' => 'Szer',
		'full' => 'Szerda',
	) ,
);
