<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-16 06:12+0000
// PO revision date:  2013-03-15 12:53+0000
$lang = array(
	'am' => 'de',
	'friday' => array(
		'abbv' => 'Pntk.',
		'full' => 'Péntek',
	) ,
	'monday' => array(
		'abbv' => 'Htf',
		'full' => 'Hétfő',
	) ,
	'pm' => 'du',
	'saturday' => array(
		'abbv' => 'Szomb',
		'full' => 'Szombat',
	) ,
	'sunday' => array(
		'abbv' => 'Vasr',
		'full' => 'Vasárnap',
	) ,
	'thursday' => array(
		'abbv' => 'Csüt',
		'full' => 'Csütörtök',
	) ,
	'tuesday' => array(
		'abbv' => 'Kedd',
		'full' => 'Kedd',
	) ,
	'wednesday' => array(
		'abbv' => 'Szer',
		'full' => 'Szerda',
	) ,
	'january' => array(
		'abbv' => 'Jan',
		'full' => 'Január',
	) ,
	'february' => array(
		'abbv' => 'Feb',
		'full' => 'Február',
	) ,
	'march' => array(
		'abbv' => 'Márc',
		'full' => 'Március',
	) ,
	'april' => array(
		'abbv' => 'Ápr',
		'full' => 'Április',
	) ,
	'may' => array(
		'abbv' => 'Máj',
		'full' => 'Május',
	) ,
	'june' => array(
		'abbv' => 'Jún',
		'full' => 'Június',
	) ,
	'july' => array(
		'abbv' => 'Júl',
		'full' => 'Július',
	) ,
	'august' => array(
		'abbv' => 'Aug',
		'full' => 'Augusztus',
	) ,
	'september' => array(
		'abbv' => 'Szept',
		'full' => 'Szeptember',
	) ,
	'october' => array(
		'abbv' => 'Okt',
		'full' => 'Október',
	) ,
	'november' => array(
		'abbv' => 'Nov',
		'full' => 'November',
	) ,
	'december' => array(
		'abbv' => 'Dec',
		'full' => 'December',
	) ,
);
