<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-03 00:02+0000
$lang = array(
	'field_default' => array(
		'length' => 'A mező neve legalább 3 és legfeljebb 200 karakterből állhat.',
	) ,
	'field_height' => array(
		'between' => '\'Kérem, egy 0 es 50 közötti számmal adja meg a mező magasságát.',
	) ,
	'field_isdate' => array(
		'between' => 'Érvénytelen értéket adott meg a dátum mezőben.',
		'required' => 'Kérem, válasszon az IGEN vagy NEM közül a dátum mező engedélyezéséhez',
	) ,
	'field_name' => array(
		'length' => 'A mező neve legalabb 3 és legfeljebb 200 karakterből állhat.',
		'required' => 'Kérem, adja meg a mező nevét.',
	) ,
	'field_required' => array(
		'between' => 'Érvenytelen számot adott meg a kötelező mezőben',
		'required' => 'Kérem, válasszon az IGEN vagy a NEM közül a kötelező mezőben',
	) ,
	'field_type' => array(
		'numeric' => 'Kérem, adjon meg egy érvényes mező típust.',
		'required' => 'Kérem, válassza ki a mező típusát.',
	) ,
	'field_width' => array(
		'between' => 'Kérem, egy 0 és 300 közötti számmal határozza meg a mező szelességét',
	) ,
	'form_description' => array(
		'required' => 'Kérem, adja meg az űrlap leírását.',
	) ,
	'form_id' => array(
		'default' => 'Az alapértelmezett űrlap nem törölhető.',
		'numeric' => 'Kérem, válassza ki, melyik űrlaphoz tartozik ez a mező.',
		'required' => 'Kérem, válassza ki, melyik űrlaphoz tartozik ez a mező.',
	) ,
	'form_title' => array(
		'length' => 'Az űrlap neve legalább 3 és legfeljebb 200 karakterből állhat.',
		'required' => 'Kérem, adja meg az űrlap nevét.',
	) ,
);
