<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-24 06:19+0000
// PO revision date:  2013-03-23 23:02+0000
$lang = array(
	'captcha' => array(
		'default' => 'Kérem, adjon meg érvényes biztonsági kódot.',
		'required' => 'Kérjük add meg a biztonsági kódot.',
	) ,
	'email' => array(
		'email' => 'Az email mező nem tartalmaz érvényes email címet.',
		'length' => 'Az email mező legalább 4 és legfeljebb 64 karakter hosszúságú lehet.',
		'required' => 'Az email mező kitöltése kötelező, ha a jelölőnégyzetet bejelölte.',
	) ,
	'message' => array(
		'required' => 'A leírás mező kitöltése kötelező.',
	) ,
	'name' => array(
		'length' => 'A név mezőnek legalább 3 karakter hosszúnak kell lennie.',
		'required' => 'A név mező kitöltése kötelező.',
	) ,
	'phone' => array(
		'length' => 'A telefonszám mező érvénytelen.',
	) ,
);
