<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:46+0000
$lang = array(
	'admin_footer' => 'Ezt az üzenetet a weboldaláról küldték.',
	'admin_login_url' => 'Adminisztrátor bejelentkezés',
	'admin_new_comment' => array(
		'message' => 'Új hozzászólás érkezett a weboldalára az alábbira válaszolva:',
		'subject' => 'Új hozzászólás',
	) ,
	'admin_new_email' => array(
		'message' => 'Új email üzenet érkezett a weboldalára.',
		'subject' => 'Új email üzenet',
	) ,
	'admin_new_report' => array(
		'message' => 'Új jelentés érkezett a weboldalára.',
		'subject' => 'Új jelentés',
	) ,
	'admin_new_sms' => array(
		'message' => 'Új szöveges üzenet érkezett a weboldalára.',
		'subject' => 'Új szöveges üzenet',
	) ,
);
