<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-16 06:12+0000
// PO revision date:  2013-03-15 13:06+0000
$lang = array(
	'reports_view' => 'Bejelentések megtekintése',
	'reports_edit' => 'Bejelentések Léterhozása/Szerkesztése/Törlése',
	'reports_approve' => 'Bejelentések jóváhagyása',
	'reports_verify' => 'Bejelentések ellenőrzése',
	'reports_comments' => 'Jelentés megjegyzések kezelése',
	'reports_download' => 'Bejelentések letöltése',
	'reports_upload' => 'Bejelentések feltöltése',
	'messages' => 'Üzenetek kezelése',
	'messages_reporters' => 'Üzenet Bejelentők kezelése',
	'stats' => 'Staisztika megtekintése',
	'settings' => 'Beállítások módosítása',
	'manage' => 'Kezelőpanel',
	'users' => 'Felhasználók kezelése',
	'manage_roles' => 'Szabályok kezelése',
	'admin_ui' => 'Hozzáférés a Rendszergazda felülethez',
	'member_ui' => 'Hozzáférés a Tagok felülethez',
);
