<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:49+0000
$lang = array(
	'latitude' => array(
		'between' => 'A földrajzi szélesség mező nem tartalmaz valós szélességi fokot.',
		'required' => 'A szélességi fok megadása kötelező! Kérem, kattintson a térképre a pontos helymeghatározáshoz.',
	) ,
	'level_id' => array(
		'numeric' => 'A jelentési szint mező nem tartalmaz valós értéket.',
		'required' => 'A Jelentési szint mező nem tartalmaz valós értéket.',
	) ,
	'location_name' => array(
		'length' => 'A helyzetmegnevezés mező legalább 3 legfeljebb 200 karaktert tartalmazhat.',
		'required' => 'A helyzetmegnevezés mező kitöltése kötelező.',
	) ,
	'longitude' => array(
		'between' => 'A földrajzi hosszúság mező nem tartalmaz érvényes hosszúsági fokot.',
		'required' => 'A hosszúsági fok megadása kötelező. Kérem, kattintson a térképre a pontos helymeghatározáshoz!',
	) ,
	'reporter_id' => array(
		'numeric' => 'Érvénytelen Bejelentő.',
		'required' => 'Érvénytelen Bejelentő.',
	) ,
);
