<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-16 06:12+0000
// PO revision date:  2013-03-15 15:13+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Kérem ellenőrizze, hogy kiválasztott-e egy elemet',
		'numeric' => 'Kérem ellenőrizze, hogy kiválasztott-e egy elemet',
		'categories_required' => 'Jóváhagyás előtt a jelentéseket kategórizálni kell',
	) ,
	'action' => array(
		'permission' => 'Önnek nincs engedélye a művelet elvégzésére',
	) ,
	'uploadfile' => array(
		'required' => 'Ki kell jelölnie egy fájlt a feltöltéshez',
		'type' => 'A feltölteni kívánt fájl formátuma .csv vagy .xml lehet',
		'valid' => 'A feltöltés mező úgy tűnik, nem tartalmaz érvényes fájlnevet',
	) ,
);
