<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:48+0000
$lang = array(
	'custom_field' => array(
		'values' => 'Kérem, adja meg a kiválasztott elemek valós mennyiségét.',
	) ,
	'data_include' => array(
		'between' => 'Kérem, válasszon valós elemet, amelyet le kíván tölteni.',
		'numeric' => 'Kérem, válasszon valós elemet, amelyet le kíván tölteni.',
	) ,
	'data_point' => array(
		'between' => 'Kérem, válasszon érvényes felajánlás típus, amelyet le kíván tölteni.',
		'numeric' => 'Kérem, válasszon érvényes felajánlás típus, amelyet le kíván tölteni.',
		'required' => 'Kérem, válasszon érvényes felajánlás típus, amelyet le kíván tölteni.',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'A "FROM" dátummező nem tartalmaz érvényes adatot.',
		'range' => 'Kérem, adjon meg érvényes "FROM" dátumot. Nem lehet több a mai dátumnál.',
	) ,
	'incident_active' => array(
		'between' => 'Kérem, adjon meg valós értéket a felajánlás jóváhagyásához!',
		'required' => 'Kérem, adjon meg valós értéket a felajánlás jóváhagyásához!',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'Az de/du mező nem tartalmaz érvényes értéket!',
	) ,
	'incident_category' => array(
		'numeric' => 'A kategóriamező nem tartalmaz érvényes kategóriát!',
		'required' => 'A kategóriamező kitöltése kötelező!',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'A dátummező nem tartalmaz érvényes dátumot!',
		'date_mmddyyyy' => 'A dátummező nem tartalmaz érvényes dátumot!',
		'required' => 'A dátummező kitöltése kötelező!',
	) ,
	'incident_description' => array(
		'required' => 'A leírás mező kitöltése kötelező!',
	) ,
	'incident_hour' => array(
		'between' => 'Az óramező nem tartalmaz érvényes időpontot!',
		'required' => 'Az óramező kitöltése kötelező!',
	) ,
	'incident_information' => array(
		'alpha' => 'Kérem, adjon meg valós értéket az információ valószínűséghez.',
		'length' => 'Kérem, adjon meg valós értéket az információ valószínűséghez.',
	) ,
	'incident_minute' => array(
		'between' => 'A percmező nem tartalmaz valós értéket!',
		'required' => 'A percmező kitöltése kötelező!',
	) ,
	'incident_news' => array(
		'url' => 'A hírforrás-link mező nem tartalmaz érvényes URL-t!',
	) ,
	'incident_photo' => array(
		'size' => 'Kérem, vegye figyelembe, hogy a feltöltött képek összmérete 2 MB-ig terjedhet!',
		'type' => 'A Képfeltöltés mező nem tartalmaz érvényes képet. Elfogadott kiterjesztések: .JPG, .PNG és .GIF.',
		'valid' => 'A Képfeltöltés mező nem tartalmaz valós fájlt!',
	) ,
	'incident_source' => array(
		'alpha' => 'Kérem, adjon meg valós értéket a forrás megbízhatósághoz.',
		'length' => 'Kérem, adjon meg valós értéket a forrás megbízhatósághoz.',
	) ,
	'incident_title' => array(
		'length' => 'A címmező legalább 3 legfeljebb 200 karaktert tartalmazhat.',
		'required' => 'A címmező kitöltése kötelező!',
	) ,
	'incident_verified' => array(
		'between' => 'Kérem, adjon meg valós értéket a felajánlás megerősítéséhez!',
		'required' => 'Kérem, adjon meg valós értéket a felajánlás megerősítéséhez!',
	) ,
	'incident_video' => array(
		'url' => 'A videó-link mező nem tartalmaz érvényes URL-t!',
	) ,
	'latitude' => array(
		'between' => 'A földrajzi szélesség mező nem tartalmaz valós szélességi fokot!',
		'required' => 'A földrajzi szélességi fok megadása kötelező. Pontos helymeghatározáshoz kérem, kattintson a térképre.!',
	) ,
	'locale' => array(
		'alpha_dash' => 'A helyzet mező helytelen értéket tartalmaz.',
		'exists' => 'Erről a felajánlásról már készült fordítás erre a nyelvre.',
		'length' => 'A helyzet mező helytelen értéket tartalmaz.',
		'locale' => 'Az eredeti felajánlás és a fordításnak nyelve megegyező.',
		'required' => 'A helyzet meghatározása kötelező.',
	) ,
	'location_name' => array(
		'length' => 'A helyzet mező legalább 3 legfeljebb 200 karaktert tartalmazhat',
		'required' => 'A helyzet megadása kötelező!',
	) ,
	'longitude' => array(
		'between' => 'A földrajzi hosszúsági mező nem tartalmaz valós értéket.',
		'required' => 'A földrajzi hosszúság megadása kötelező. Pontos helymeghatározáshoz, kérem kattintson a térképre!',
	) ,
	'person_email' => array(
		'email' => 'Az email-cím mező nem tartalmaz érvényes email-címet!',
		'length' => 'Az email-cím mező legalább 4 legfeljebb 64 karaktert tartalmazhat.',
	) ,
	'person_first' => array(
		'length' => 'A keresztnév-mező legalább 3 legfeljebb 100 karaktert tartalmazhat.',
	) ,
	'person_last' => array(
		'length' => 'Az vezetéknév-mező legalább 3 legfeljebb 100 karaktert tartalmazhat.',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'A "TO" dátummező nem tartalmaz érvényes dátumot.',
		'range' => 'Kérem, adjon meg érvényes "TO" dátumot. Ez a mai dátumot nem haladhatja meg.',
		'range_greater' => 'A "FROM"-ban megadott dátum nem haladhatja meg a "TO"-ban megadott dátumot.',
	) ,
);
