<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:50+0000
$lang = array(
	'description' => array(
		'length' => 'A Leírás mező legalább 3 legfeljebb 100 karaktert tartalmazhat.',
		'required' => 'A Leírás mező kitöltése kötelező.',
	) ,
	'name' => array(
		'alpha_numeric' => 'A névmező csak betűket és számokat tartalmazhat.',
		'length' => 'A névmező legalább 2 legfeljebb 30 karaktert tartalmazhat.',
		'nomodify' => 'SuperAdmin Szerep nem módosítható.',
		'required' => 'A névmező kitöltése kötelező.',
	) ,
);
