<?php
	$lang = array(
	'allow_comments' => array(
		'between' => 'A kommentek engedélyezése mezőben érvénytelen értéket adott meg.',
		'required' => 'A kommentek engedélyezése mezőt kötelező kitölteni.',
	),
	'allow_feed' => array(
		'between' => 'A tartalom mezőben érvénytelen értéket adott meg.',
		'required' => 'A tartalom mező kitöltése kötelező.',
	),
	'allow_reports' => array(
		'between' => 'A jelentések engedélyezése mezőben érvénytelen értéket adott meg.',
		'required' => 'A jelentések engedélyezése mezőt kötelező kitölteni.',
	),
	'allow_stat_sharing' => array(
		'between' => 'A statisztika megosztása mezőben érvénytelen értéket adott meg.',
		'required' => 'A statisztika megosztása mező kitültése kötelező.',
	),
	'api_akismet' => array(
		'alpha_numeric' => 'Az Akismet mezőben érvénytelen értéket adott meg.',
		'length' => 'Az Akismet mezőben érvénytelen értéket adott meg.',
	),
	'cleanurl' => array(
		'clean_url_disabled' => 'Úgy tűnik, az Ön szervere nincs beállítva arra, hogy a clean URL-eket kezelje. Meg kell változtatnia a szerver konfigurációját mielőtt engedélyezi a clean URL-eket. További információ arról, hogyan engedélyezze a clean URL-eket ebben <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">a fórum posztban</a> található (angolul).',
		'clean_url_enabled' => 'Ez az opció lehetővé teszi, hogy "clean" URL-ről lehessen elérni az Ushahidit, "index.php" kiterjesztés nélkül a honlapcímben.',
		'enable_clean_url' => 'Clean URL-ek engedélyezése',
		'title' => 'Clean URL-ek',
	),
	'clickatell_api' => array(
		'length' => 'A Clickatell API számának legalább 20 karakter hosszúnak kell lennie.',
		'required' => 'A Clickatell API szám megadása kötelező.',
	),
	'clickatell_password' => array(
		'length' => 'A Clickatell jelszavának legalább 5 és maximum 50 karakter hosszúnak kell lennie.',
		'required' => 'Clickatell jelszó megadása kötelező.',
	),
	'clickatell_username' => array(
		'length' => 'A Clickatell felhasználónév nem lehet hosszabb 50 karakternél.',
		'required' => 'Clickatell felhasználónév megadása kötelező.',
	),
	'configure_map' => 'Térkép beállítás',
	'default_location' => 'Alapértelmezett helyszín',
	'default_map_all' => array(
		'alpha_numeric' => 'A szín betöltés mezőben érvénytelen értéket adott meg.',
		'length' => 'A szín mező nem lehet 6 karakternél hosszabb.',
		'required' => 'A szín mező kitöltése kötelező.',
	),
	'default_map_view' => 'Alapértelmezett térképnézet',
	'default_zoom_level' => 'Nézet alapértelmezett magassága',
	'download_city_list' => 'Városnevek behúzása a Geonamesről.',
	'email_host' => array(
		'length' => 'Az mail szerver port mezőben túl hosszú értéket adott meg.',
		'numeric' => 'A mail szerver port mezőben csak számok szerepelhetnek.',
	),
	'email_password' => array(
		'length' => 'A mail szerver jelszó legalább 5 és maximum 50 karakter hosszú lehet.',
		'required' => 'A mail szerverhez jelszó megadása kötelező.',
	),
	'email_port' => array(
		'length' => 'Az mail szerver port mezőben túl hosszú értéket adott meg.',
		'numeric' => 'A mail szerver port mezőben csak számok szerepelhetnek.',
	),
	'email_servertype' => array(
		'length' => 'Az mail szerver port mezőben túl hosszú értéket adott meg.',
		'required' => 'Mail szerver típusa mező kitöltése kötelező.',
	),
	'email_username' => array(
		'length' => 'A mail szerverhez megadott felhasználónév nem lehet hosszabb 50 karakternél.',
		'required' => 'A mail szerver felhasználónevének megadása kötelező.',
	),
	'google_analytics' => array(
		'length' => 'A Google Analyticshez megadott értéknek érvényes Web Property azonosító számot kell tartalmaznia a következő formátumban: UA-XXXXX-XX.',
	),
	'items_per_page' => array(
		'between' => '',
		'required' => '',
	),
	'items_per_page_admin' => array(
		'between' => '',
		'required' => '',
	),
	'map' => array(
		'default_location' => '',
		'zoom' => '',
	),
	'map_provider' => array(
		'choose' => '',
		'enter_api' => '',
		'get_api' => '',
		'info' => '',
		'name' => '',
	),
	'map_settings' => '',
	'multiple_countries' => '',
	'select_default_location' => '',
	'set_location' => '',
	'site' => array(
		'allow_clustering' => '',
		'allow_comments' => '',
		'allow_feed' => '',
		'allow_reports' => '',
		'api_akismet' => '',
		'default_category_colors' => '',
		'display_contact_page' => '',
		'display_howtohelp_page' => '',
		'email_alerts' => '',
		'email_notice' => '',
		'email_site' => '',
		'google_analytics' => '',
		'google_analytics_example' => '',
		'items_per_page' => '',
		'items_per_page_admin' => '',
		'kismet_notice' => '',
		'laconica_configuration' => '',
		'laconica_site' => '',
		'language' => '',
		'message' => '',
		'name' => '',
		'share_site_stats' => '',
		'tagline' => '',
		'title' => '',
		'twitter_configuration' => '',
		'twitter_hashtags' => '',
	),
	'site_email' => array(
		'email' => '',
		'length' => '',
	),
	'site_name' => array(
		'length' => '',
		'required' => '',
	),
	'site_tagline' => array(
		'length' => '',
		'required' => '',
	),
	'sms' => array(
		'clickatell_api' => '',
		'clickatell_check_balance' => '',
		'clickatell_load_balance' => '',
		'clickatell_password' => '',
		'clickatell_text_1' => '',
		'clickatell_text_2' => '',
		'clickatell_username' => '',
		'flsms_description' => '',
		'flsms_download' => '',
		'flsms_instructions' => '',
		'flsms_key' => '',
		'flsms_link' => '',
		'flsms_synchronize' => '',
		'flsms_text_1' => '',
		'flsms_text_2' => '',
		'option_1' => '',
		'option_2' => '',
		'title' => '',
	),
	'sms_no1' => array(
		'length' => '',
		'numeric' => '',
	),
	'sms_no2' => array(
		'length' => '',
		'numeric' => '',
	),
	'sms_no3' => array(
		'length' => '',
		'numeric' => '',
	));
?>
