<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-16 06:12+0000
// PO revision date:  2013-03-15 15:21+0000
$lang = array(
	'approved' => 'Jóváhagyott',
	'categories' => 'Kategóriák',
	'category_impact' => 'Kategória Hatás',
	'category_impact_description' => 'Ez az ábra időben lineáris nézetét adja a riportoknak. Balról jobbra gördítve összehasonlíthatod a különböző kategóriákat. Az egérrel az ábrák fölé állva részletesebb információkat kapsz.',
	'choose_date_range' => 'Válassz egy dátum ',
	'countries' => 'Országok',
	'country' => 'Ország',
	'country_breakdown' => 'Ország üzemzavar',
	'description' => 'Hello, ez a statisztikai szekció. Általános leírás a későbbiekben lesz. Most böngészd az alkategóriák linkjeit fent!',
	'error' => 'Hiba',
	'glossary' => 'Szószedet',
	'legend' => 'Jelmagyarázat',
	'pageviews' => 'Oldalletöltések',
	'pageviews_description' => 'Az összes oldalszám melyet a látogatók megtekintettek',
	'reports' => 'Riportok',
	'reports_categories' => 'Riport kategóriák',
	'reports_statistics' => 'Riport statisztikák',
	'reports_status' => 'Riportok státusza',
	'report_stats' => 'Bejelentés statisztika',
	'stats_not_setup' => 'Statisztika nincs beállítva',
	'time_range_1' => '1 Hónap',
	'time_range_2' => '3 Hónap',
	'time_range_3' => '6 Hónap',
	'time_range_all' => 'Mind',
	'unapproved' => 'Nem jóváhagyott',
	'unique_visitors' => 'Egyedi Látogató',
	'unique_visitors_description' => 'A példányba érkező személyek. Az egyedi látogatók cookie-k segítségével lesznek meghatározva. Azok a látogatók akiknél nincs cookie engedélyezve, egy egyszerű heurisztikával lesznek azonosítva az IP címet, felbontást, böngészőt, OS-t stb felhasználva.',
	'unverified' => 'Nem ellenőrzött',
	'verified' => 'Ellenőrzött',
	'visitor_summary' => 'Látogatók összegzése',
	'visits' => 'Látogatások',
	'visits_description' => 'A látogatás az egyedi látogatók rögzítése, akik legalább 30 perce nem jártak az oldalon',
);
