<?php
	$lang = array(
	'approved' => 'Jóváhagyott',
	'categories' => 'Kategóriák',
	'category_impact' => 'Kategória Hatás',
	'category_impact_description' => 'Ez az ábra időben lineáris nézetét adja a riportoknak. Balról jobbra gördítve összehasonlíthatod a különböző kategóriákat. Az egérrel az ábrák fölé állva részletesebb információkat kapsz.',
	'choose_date_range' => 'Válassz egy dátum ',
	'countries' => 'Országok',
	'country' => 'Ország',
	'description' => 'Hello, ez a statisztikai szekció. Általános leírás a későbbiekben lesz. Most böngészd az alkategóriák linkjeit fent!',
	'error' => 'Hiba',
	'reports' => 'Riportok',
	'reports_categories' => 'Riport kategóriák',
	'reports_statistics' => 'Riport statisztikák',
	'reports_status' => 'Riportok státusza',
	'time_range_2' => '3 Hónap',
	'time_range_3' => '6 Hónap',
	'time_range_all' => 'Mind',
	'unapproved' => 'Nem jóváhagyott',
	'unique_visitors' => 'Egyedi Látogató',
	'unverified' => 'Nem ellenőrzött',
	'verified' => 'Ellenőrzött',
	'visitor_summary' => 'Látogatók összegzése',
	'visits' => 'Látogatások',
	'visits_description' => 'A látogatás az egyedi látogatók rögzítése, akik legalább 30 perce nem jártak az oldalon',
	);
?>
