<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-20 12:02+0000
$lang = array(
	'profile_email' => 'Az email címed',
	'profile_name' => 'A teljes neved',
	'profile_notify' => 'Ha az IGEN-t választod, akkor emailben kapsz értesítőt, amikor új felajánlás vagy megjegyzés kerül beküldésre a joszolgalat.hu-ra',
	'profile_password' => 'A jelszavad. Hagyd üresen, ha meg szeretnéd tartani a jelenlegit.',
	'profile_username' => 'A felhasználói nevedet nem tudod megváltoztatni.',
	'settings_alert_email' => 'Ezt az email címet fogjuk használni, hogy értesítéseket küldjünk',
	'settings_allow_comments' => 'A felhasználók megjegyzéseket fűzhetnek a főoldalon publikált jelentésekhez.',
	'settings_allow_feed' => 'RSS csatornák megjelenítésének engedélyezés a főoldalon.',
	'settings_allow_reports' => 'A felhasználók a űrlapok segítségével küldhetnek információt.',
	'settings_cache_pages' => 'Engedélyezni, és tiltani lehet a gyorsítótárat. Engedélyezése esetén a lapok gyorsabban fognak betöltődni a böngészőbe. Engedélyezése ajánlott. **Figyelem: a lapok gyorsító tárazása az alábbi beállítás alapján szabályozható. (időtartam)',
	'settings_cache_pages_lifetime' => 'Állítsd be a gyorsítótár időtartamát',
	'settings_configure_map' => 'Egy meghatározott helyre beállítja a térképet',
	'settings_default_category_colors' => 'Egy színkód kiválasztása az összes kategóriára a site-on',
	'settings_default_location' => 'Ebben az országban lett az alkalmazás telepítve',
	'settings_display_contact' => 'A kapcsolati fül be és kikapcsolása a főoldalon.',
	'settings_display_howtohelp' => '\'Hogyan segíthetsz\' fül be-, ill. kikapcsolása a főoldalon.',
	'settings_display_items_per_page' => 'Jelentések száma melyek megjelennek a főoldalon, oldalanként.',
	'settings_display_items_per_page_admin' => 'Jelentések száma melyek megjelennek az admin felületen, oldalanként.',
	'settings_flsms_download' => 'Ez a bejövő üzenetek központja',
	'settings_flsms_synchronize' => 'Ez szinkronizálja a központ üzeneteit az Ushahidi platformmal',
	'settings_flsms_text_1' => 'Telefonszámok, amelyekre az üzenetek érkeznek',
	'settings_google_analytics' => 'Kövesd a site látogatókat. ',
	'settings_locale' => 'Állítsd be a site nyelvét',
	'settings_map_provider' => 'Meghatározza, hogy melyik térképet használja az oldalon.',
	'settings_server_username' => 'Ez az emailcím fogadja a jelentéseket.',
	'settings_share_site_stats' => 'A nézettségi statisztikák az Ushahidi szerverein vannak tárolva. Ezen beállítás engedélyezése esetén hozzáférést nyer a nézettségi statisztikákhoz az admin panelén. Kikapcsolása esetén leállíthatja az adatgyűjtést, azonban arra az időre nem gyűjt adatokat a rendszer.',
	'settings_site_email' => 'emailcím, amire email jelentéseket és a kapcsolati adatlap üzeneteit fogadod',
	'settings_site_message' => 'Ez a szöveg fog a térkép fölött megjelenni a honlapon. Hasznos a látogatók számára fontos információk közléséhez.Ha törölni akarod a dobozt -csak töröld ki ezt az üzenetet.',
	'settings_site_name' => 'Ez az a név, ami a főoldal tetején látszik.',
	'settings_site_tagline' => 'Néhány mondatban mondd el, miről szól ez az oldal..',
	'settings_twitter_configuration' => 'Itt állítsd be a twitter hash-tagjét.',
);
