<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 22:26+0000
$lang = array(
	'upgrade' => array(
		'between' => 'Hibás adat. A lehetséges értékek: 0 (nem) vagy 1 (igen).',
	) ,
	'upgrade_continue_btn_text' => 'Folytatás',
	'upgrade_db_btn_text' => 'Frissítés',
	'upgrade_db_title' => 'Az Ushahidi adatbázis frissítése',
	'upgrade_failed' => 'A frissítést nem sikerült végrehajtani',
	'upgrade_status' => 'Az Ushahidi frissítésenek az állapota',
	'upgrade_text_1' => 'Útmutató az Ushadishi letelepitése manuális frissítéséhez',
	'upgrade_text_2' => '<strong>Lépés 1:</strong> Töltse le a legújabb Ushahidi buildet innen: <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
	'upgrade_text_3' => '<strong>Lépés 2: </strong> Válassza ki a webszervert futtató operációs rendszernek megfelelő eszközt/módszert (pl.: telnet, ftp, ssh), majd lépjen be a webszerverre, és a legújabb builddel írja felül a mappa tartalmát! <strong>Mindet, KIVÉTEL:</strong>',
	'upgrade_text_4' => '<strong>Lépés 4: </strong> A táblázatok frissítéséhez kattintson a <strong>"Folytatás"</strong> gombra',
	'upgrade_text_5' => 'Automatikus frissítéshez kattintson az alábbi gombra.',
	'upgrading' => 'Frissítés',
);
