<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-15 12:00+0000
$lang = array(
	'email' => array(
		'email' => 'Bu e-posta alanı geçerli bir adres içermiyor.',
		'exists' => 'Üzgünüz, bu e-posta adresi için zaten bir hesap var.',
		'length' => 'E-posta adresi en az 4, en fazla 64 karakter uzunluğunda olmalıdır.',
		'required' => 'E-posta alanı boş bırakılamaz.',
	) ,
	'name' => array(
		'length' => 'İsim en az 3, en fazla 100 karakter uzunluğuna olmalıdır.',
		'required' => 'İsim alanı boş bırakılamaz.',
		'standard_text' => 'Kullanıcı ismi geçersiz karakterler içeriyor.',
	) ,
	'password' => array(
		'length' => 'Şifreniz en az 5, en fazla 16 karakterden oluşmalıdır.',
		'matches' => 'Lütfen iki alana da aynı şifreyi girin.',
		'required' => 'Şifre alanı boş bırakılamaz.',
	) ,
	'password_confirm' => array(
		'matches' => 'Şifre doğrulama alanı içeriği şifre ile aynı olmalıdır.',
	) ,
	'resetemail' => array(
		'email' => 'Geçersiz bir e-posta adresi girdiniz.',
		'invalid' => 'Üzgünüz, e-posta adresiniz kayıtlı değil.',
		'required' => 'E-posta alanı boş bırakılamaz.',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Geçersiz ünvan formatı.',
		'length' => 'Ünvan kısmı en az 5, en fazla 30 karakterden oluşmalıdır.',
		'required' => 'En az 1 adet ünvan belitmelisiniz.',
		'values' => 'Yönetici veya kullanıcı ünvanlarından birini seçmelisiniz.',
	) ,
	'username' => array(
		'admin' => 'Yönetici ünvanı düzenlenemez.',
		'exists' => 'Üzgünüz, bu kullanıcı ismi zaten kullanılıyor.',
		'length' => 'Kullanıcı ismi en az 2, en fazla 16 karakterden oluşmalıdır.',
		'required' => 'Kullanıcı ismi boş bırakılamaz.',
		'superadmin' => 'Süper Yönetici ünvanı düzenlenemez.',
	) ,
);
