<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-02 06:04+0000
// PO revision date:  2012-07-12 21:25+0000

$lang = array (
  'captcha' => 
  array (
    'default' => 'Lütfen geçerli güvenlik kodunu girin.',
    'required' => 'Lütfen güvenlik kodunu girin',
  ),
  'email' => 
  array (
    'email' => 'E-posta adresinizi girdiğiniz alanda geçerli bir adres gözükmüyor?',
    'length' => 'E-posta adresi en az 4, en fazla 64 karakterden oluşmalıdır.',
    'required' => 'Kullanım koşullarını kabul ettiyseniz mutlaka sisteme bir e-posta adresi girmeniz gereklidir.',
  ),
  'error' => 
  array (
    'required' => 'Hata bölümü boş bırakılamaz',
  ),
  'subject' => 
  array (
    'length' => 'Başlık kısmı en az 3 karakterden oluşmalıdır.',
    'required' => 'Başlık kısmı boş bırakılamaz.',
  ),
  'yourname' => 
  array (
    'length' => 'İsim kısmı en az 3 karakterden oluşmalıdır.',
    'required' => 'İsim kısmı boş bırakılamaz.',
  ),
);

