<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:29+0000
$lang = array(
	'captcha' => array(
		'default' => 'Lütfen geçerli bir güvenlik kodu girin',
		'required' => 'Lütfen güvenlik kodunu girin',
	) ,
	'contact_email' => array(
		'email' => 'Girilen e-posta adresi geçerli değil',
		'length' => 'E-posta adresi en az 4, en fazla 64 karakter uzunluğunda olmalıdır.',
		'required' => 'Kullanım koşullarını kabul ettiyseniz sisteme e-posta girmeniz gereklidir.',
	) ,
	'contact_message' => array(
		'required' => 'Mesaj kısmı boş bırakılamaz.',
	) ,
	'contact_name' => array(
		'length' => 'İsim kısmı en az 3 karakterden oluşmalıdır.',
		'required' => 'İsim kısmı boş bırakılamaz.',
	) ,
	'contact_subject' => array(
		'length' => 'Başlık kısmı en az 3 karakterden oluşmalıdır.',
		'required' => 'Başlık kısmı boş bırakılamaz.',
	) ,
);
