<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:32+0000
$lang = array(
	'am' => 'öö',
	'friday' => array(
		'abbv' => 'Cum',
		'full' => 'Cuma',
	) ,
	'monday' => array(
		'abbv' => 'Pzt',
		'full' => 'Pazartesi',
	) ,
	'pm' => 'ös',
	'saturday' => array(
		'abbv' => 'Cmt',
		'full' => 'Cumartesi',
	) ,
	'sunday' => array(
		'abbv' => 'Paz',
		'full' => 'Pazar',
	) ,
	'thursday' => array(
		'abbv' => 'Perş',
		'full' => 'Perşembe',
	) ,
	'tuesday' => array(
		'abbv' => 'Sal',
		'full' => 'Salı',
	) ,
	'wednesday' => array(
		'abbv' => 'Çarş',
		'full' => 'Çarşamba',
	) ,
);
