<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-01 12:04+0000
// PO revision date:  2012-07-12 21:40+0000

$lang = array (
  'layer_color' => 
  array (
    'length' => 'Renk kısmı en az 6 karakterden oluşmalıdır.',
    'required' => 'Renk kısmı boş bırakılamaz.',
  ),
  'layer_file' => 
  array (
    'type' => 'Dosya uzantısı geçersiz. .KMZ, .KML uzantılı dosyalar kabul edilmektedir.',
    'valid' => 'Dosya geçersiz.',
  ),
  'layer_name' => 
  array (
    'length' => 'İsim kısmı en az 3, en fazla 80 karakterden oluşmalıdır.',
    'required' => 'İsim kısmı boş bırakılamaz.',
  ),
  'layer_url' => 
  array (
    'atleast' => 'Bir KML URLsi ya da Dosyası gereklidir',
    'both' => 'Aynı anda hem bir KML dosyasına ve bir KML urlsine sahip olamazsınız',
    'url' => 'Lütfen geçerli bir adres giriniz. Örn. http://www.ushahidi.com/layerl.kml',
  ),
);

