<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-23 11:10+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'Lütfen geçerli bir güvenlik kodu giriniz.',
		'required' => 'Lütfen güvenlik kodunu giriniz.',
	) ,
	'contact_email' => array(
		'email' => 'E-posta adresi geçerli değil gibi görünüyor.',
		'required' => 'Lütfen geçerli bir e-posta adresi giriniz.',
	) ,
	'contact_message' => array(
		'required' => 'Mesaj alanı boş bırakılamaz.',
	) ,
	'contact_subject' => array(
		'length' => 'Başlık en az 3 karakterden oluşmalıdır.',
		'required' => 'Başlık alanı boş bırakılamaz.',
	) ,
);
