<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-24 18:04+0000
// PO revision date:  2012-07-12 21:48+0000

$lang = array (
  'latitude' => 
  array (
    'between' => 'Geçersiz bir enlem girdiniz.',
    'required' => 'Enlem kısmı boş bırakılamaz. Lütfen haritada bir nokta belirleyiniz.',
  ),
  'level_id' => 
  array (
    'numeric' => 'Haberci Seviyesi geçerli değil',
    'required' => 'Haberci Seviyesi geçerli değil',
  ),
  'location_name' => 
  array (
    'length' => 'Yer ismi kısmı en az 3, en fazla 200 karakterden oluşmalıdır.',
    'required' => 'Yer ismi kısmı boş bırakılamaz.',
  ),
  'longitude' => 
  array (
    'between' => 'Geçersiz boylam girdiniz.',
    'required' => 'Boylam kısmı boş bırakılamaz. Lütfen haritada bir nokta belirleyiniz.',
  ),
  'reporter_id' => 
  array (
    'numeric' => 'Geçersiz Haberci',
    'required' => 'Geçersiz Haberci',
  ),
);

