<?php
	$lang = array(
	'approved' => 'Onaylandı',
	'categories' => 'Kategoriler',
	'category_impact' => 'Kategori Etkisi',
	'category_impact_description' => 'Bu tablo size raporların doğrusal bir görünümünü verir. Fareyi soldan sağa doğru götürerek farklı kategorilerde görünüme sahip olabilirsiniz. Daha fazla detay için fare ile grafiğin üzerine gidiniz.',
	'choose_date_range' => 'Bir tarih aralığı seçin',
	'countries' => 'Ülkeler',
	'country' => 'Ülke',
	'description' => 'Merhaba, burası istatistiksel bölümdür. Genel açıklama yakında burada olacaktır. Şimdilik aşağıda bulunan alt kategorilere göz atabilirsiniz.',
	'error' => 'Hata',
	'glossary' => 'Sözlük',
	'hit_summary' => 'Tıklanma özeti',
	'legend' => 'Açıklama',
	'pageviews' => 'Tıklanma sayısı',
	'pageviews_description' => 'Sayfanızı ziyaret eden toplam kişi sayısı',
	'reports' => 'Raporlar',
	'reports_categories' => 'Rapor Kategorileri',
	'reports_statistics' => 'Rapor İstatistikleri',
	'reports_status' => 'Rapor Durumları',
	'report_stats' => 'Rapor İstatistikleri',
	'time_range_1' => '1 Ay',
	'time_range_2' => '3 Ay',
	'time_range_3' => '6 Ay',
	'time_range_all' => 'Hepsi',
	'unapproved' => 'Onaylanmamış',
	'unique_visitors' => 'Tekil ziyaretçiler',
	'unverified' => 'Doğrulanmamış',
	'verified' => 'Doğrulanmış',
	'visitor_summary' => 'Ziyaretçi Özeti',
	'visits' => 'Ziyaretler',
	);
?>
