<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 22:26+0000
$lang = array(
	'upgrade' => array(
		'between' => 'Geçersiz girdi verisi. Hayır için 0, Evet için 1 olabilir.',
	) ,
	'upgrade_automatic' => 'Otomatik Yükseltme',
	'upgrade_available' => 'Mevcut Güncellemeler',
	'upgrade_continue_btn_text' => 'Devam Et',
	'upgrade_db_btn_text' => 'Yükselt',
	'upgrade_db_text_1' => 'Böylelikle, veritabanınızı mevcut sürümden yükselteceğim',
	'upgrade_db_text_2' => 'en yeni veritabanı sürümüne',
	'upgrade_db_text_3' => '"Yükselt" butonuna tıkla ve ben büyüyü gerçekleştirirken sadece arkana yaslan.',
	'upgrade_db_text_4' => 'Ek olarak, eğer veritabanınızın bir yedeğini almamı istiyorsanız, yapmanız gereken sadece aşağıdaki kutucuğu işaretlemek ve ben bunu sizin için zahmetsizce yapacağım.',
	'upgrade_db_text_5' => 'Yükseltmeden önce veritabanının yedeğini al?  (<strong style="color:#FF0000;">Highly recommended</strong>)',
	'upgrade_db_title' => 'Ushahidi veritabanı yükseltmesi',
	'upgrade_failed' => 'Yükseltme işlemi bir yerde başarısız oldu',
	'upgrade_manual' => 'El ile Yükseltme',
	'upgrade_status' => 'Ushahidi yükseltme durumu',
	'upgrade_text_1' => 'Aşağıdaki açıklamalar Ushahidi yayınınızı nasıl el ile yükseltebileceğinizi detaylı bir şekilde açıklıyor',
	'upgrade_text_2' => '<strong>Step 1:</strong> En yeni ushahidi sürümünü karşıdan yüklemek için: <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
	'upgrade_text_3' => '<strong>Step 2:</strong> Web sunucusunu yürüten sisteme bağlı olarak, web sunucusuna giriş yapmak ve en yeni sürümdeki tüm klasör içeriklerini eskileri ile değiştirmek için tercih ettiğiniz araç/mod kullanın  (örneğin: telnet, ftp, ssh).',
	'upgrade_text_4' => ' <strong>Step 4:</strong> Gerekli tabloları yükseltmek için "Devam et" butonuna tıklayın.',
	'upgrade_text_5' => 'Otomatik yükseltme için, aşağıdaki butona tıklayın.',
	'upgrading' => 'Yükseltiliyor',
);
