<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-15 12:00+0000
$lang = array(
	'email' => array(
		'email' => 'O campo do Email parece conter um endereço de email inválido?',
		'exists' => 'Desculpe, mas já existe uma conta de utilizador para este endereço de email.',
		'length' => 'O campo do email deve ter entre 4 a 64 caracteres.',
		'required' => 'O campo do email é obrigatório.',
	) ,
	'name' => array(
		'length' => 'O campo do nome completo deve ter entre 3 a 100 caracteres.',
		'required' => 'O campo do nome completo é obrigatório.',
		'standard_text' => 'O campo do nome de utilizador contém caracteres não autorizados.',
	) ,
	'password' => array(
		'length' => 'O campo da palavra-chave deve ter entre 6 a 12 caracteres.',
		'login error' => 'Por favor, certifique que colocou a password correcta.',
		'matches' => 'Por favor insira a mesma palavra-chave nos dois campos de palavra-chave.',
		'required' => 'O campo da palavra-chave é obrigatório.',
	) ,
	'password_confirm' => array(
		'matches' => 'O campo da confirmação da password deve ser igual ao campo da palavra-chave.',
	) ,
	'resetemail' => array(
		'email' => 'O campo do email parece não conter um endereço de email válido?',
		'invalid' => 'Desculpe, não temos o seu endereço de email.',
		'required' => 'O campo do email é obrigatório.',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Formato de função inválido.',
		'length' => 'O campo da função deve ter entre 5 a 30 caracteres.',
		'required' => 'Deve definir pelo menos um tipo de função.',
		'values' => 'Tem de seleccionar uma das funções ADMIN ou USER.',
	) ,
	'username' => array(
		'admin' => 'A função de utilizador admin não pode ser modificada.',
		'exists' => 'Desculpe, mas este nome de utilizador já está a ser utilizado.',
		'length' => 'O campo do nome de utilizador deve ter entre 3 a 16 caracteres.',
		'login error' => 'Por favor certifique que inseriu o nome de utilizador correcto.',
		'required' => 'O campo do nome de utilizador é obrigatório.',
		'superadmin' => 'A função de utilizador super admin não pode ser modificada.',
	) ,
);
