<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-27 06:19+0000
// PO revision date:  2013-06-26 16:55+0000
$lang = array(
	'captcha' => array(
		'default' => 'Por favor, insira um código de segurança válido.',
		'required' => 'Por favor, insira o código de segurança.',
	) ,
	'email' => array(
		'email' => 'O campo do e-mail parece não conter um endereço de e-mail inválido?',
		'length' => 'O campo do e-mail deve ter entre 4 a 64 carateres.',
		'required' => 'O campo do e-mail é obrigatório, se a opção for selecionada.',
	) ,
	'error' => array(
		'required' => 'O campo do erro é obrigatório.',
	) ,
	'subject' => array(
		'length' => 'O campo do assunto deve ter pelo menos 3 carateres.',
		'required' => 'O campo do assunto é obrigatório.',
	) ,
	'yourname' => array(
		'length' => 'O campo do nome deve ter pelos 3 carateres.',
		'required' => 'O campo do nome é obrigatório.',
	) ,
);
