<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:25+0000
$lang = array(
	'captcha' => array(
		'default' => 'Por favor insira um código de segurança válido',
		'required' => 'Por favor insira o código de segurança',
	) ,
	'email' => array(
		'email' => 'O campo do Email parece conter um endereço de email inválido?',
		'length' => 'O campo do Email deve ter entre 4 a 64 caracteres.',
		'required' => 'O campo do Email é obrigatório caso a opção seja seleccionada.',
	) ,
	'error' => array(
		'required' => 'O campo do erro é obrigatório.',
	) ,
	'subject' => array(
		'length' => 'O campo do assunto deve ter pelo menos 3 caracteres.',
		'required' => 'O campo do assunto é obrigatório.',
	) ,
	'yourname' => array(
		'length' => 'O campo do nome deve ter pelos 3 caracteres.',
		'required' => 'O campo do nome é obrigatório.',
	) ,
);
