<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-23 06:24+0000
// PO revision date:  2013-12-22 20:29+0000
$lang = array(
	'category_color' => array(
		'length' => 'O campo da cor deverá ter 6 carateres.',
		'required' => 'O campo da cor é obrigatório.',
	) ,
	'category_description' => array(
		'required' => 'O campo da descrição é obrigatório.',
	) ,
	'category_image' => array(
		'size' => 'Por favor, certifique-se que o tamanho da imagem a enviar seja limitada a 50KB.',
	) ,
	'category_title' => array(
		'required' => 'O campo do título é obrigatório.',
	) ,
);
