<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-01-26 17:48+0000
$lang = array(
	'captcha' => array(
		'default' => 'Please enter a valid security code',
		'valid' => 'Por favor introduza um código de segurança válido',
		'required' => 'Please enter the security code',
	) ,
	'contact_email' => array(
		'email' => 'The Email field does not appear to contain a valid email address?',
	) ,
	'email_send' => array(
		'failed' => 'Surgiu um erro a enviar a mensagem',
	) ,
);
