<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-03 00:02+0000
$lang = array(
	'field_default' => array(
		'length' => 'The Field Name must be at least 3 and no more 
				200 characters long.',
	) ,
	'field_height' => array(
		'between' => 'Please enter a value 0 to 50 for the Field Height',
	) ,
	'field_isdate' => array(
		'between' => 'You have entered an invalid value for Date Field',
		'required' => 'Please select Yes or No for the Date Field',
	) ,
	'field_name' => array(
		'length' => 'The Field Name must be at least 3 and no more 
				100 characters long.',
	) ,
	'field_required' => array(
		'between' => 'You have entered an invalid value for Field Required',
		'required' => 'Please select Yes or No for Field Required',
	) ,
	'field_width' => array(
		'between' => 'Please enter a value 0 to 300 for the Field Width',
	) ,
	'form_title' => array(
		'length' => 'The form name field must be at least 3 and no more 
				100 characters long.',
	) ,
);
