<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-04-23 17:41+0000
$lang = array(
	'field_default' => array(
		'length' => 'The Field Name must be at least 3 and no more 
				200 characters long.',
	) ,
	'field_height' => array(
		'between' => 'Please enter a value 0 to 50 for the Field Height',
	) ,
	'field_isdate' => array(
		'between' => 'You have entered an invalid value for Date Field',
		'required' => 'Please select Yes or No for the Date Field',
	) ,
	'field_name' => array(
		'length' => 'The Field Name must be at least 3 and no more 
				100 characters long.',
		'required' => 'Por favor introduza nome do campo',
	) ,
	'field_required' => array(
		'between' => 'Inseriu um valor inválido no Campo Necessário.',
		'required' => 'Por favor, selecione Sim ou Não no Campo Necessário.',
	) ,
	'field_type' => array(
		'required' => 'Por favor escolha o tipo de campo',
	) ,
	'field_width' => array(
		'between' => 'Please enter a value 0 to 300 for the Field Width',
	) ,
	'form_description' => array(
		'required' => 'Por favor introduza a descrição do formulário',
	) ,
	'form_title' => array(
		'length' => 'The form name field must be at least 3 and no more 
				100 characters long.',
	) ,
);
