<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-01-26 17:37+0000
$lang = array(
	'layer_color' => array(
		'length' => 'O campo de cor tem de ter 6 carateres',
		'required' => 'O campo de cor é obrigatório.',
	) ,
	'layer_file' => array(
		'type' => 'The file field does not appear to contain a valid file. The only accepted formats are .KMZ, .KML.',
		'valid' => 'O campo de ficheiro não contem um ficheiro válido',
	) ,
	'layer_name' => array(
		'length' => 'O campo de nome tem um mínimo de 3 e um máximo de 80 carateres',
		'required' => 'O campo de nome é obrigatório',
	) ,
	'layer_url' => array(
		'atleast' => 'Either a KML Url or File is required',
		'both' => 'You can\'t have both a KML file and a url',
		'url' => 'Please enter a valid URL. Eg. http://www.ushahidi.com/layerl.kml',
	) ,
);
