<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-04-23 17:31+0000
$lang = array(
	'captcha' => array(
		'default' => 'Please enter a valid security code',
		'required' => 'Please enter the security code',
	) ,
	'email' => array(
		'email' => 'The Email field does not appear to contain a valid email address?',
		'required' => 'O campo do e-mail é obrigatório, se a opção estiver selecionada.',
	) ,
	'message' => array(
		'required' => 'O campo dos comentários é obrigatório.',
	) ,
	'name' => array(
		'required' => 'O campo do nome é obrigatório.',
	) ,
	'phone' => array(
		'length' => 'O campo de telefone é obrigatório',
	) ,
);
