<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-01-26 17:30+0000
$lang = array(
	'latitude' => array(
		'between' => 'O campo de latitude não contem uma latitude válida.',
		'required' => 'O campo de latitude é obrigatório. Por favor marque no mapa a localização',
	) ,
	'location_name' => array(
		'required' => 'O campo do nome do local é obrigatório.',
	) ,
	'reporter_id' => array(
		'numeric' => 'Relator inválido',
		'required' => 'Relator inválido',
	) ,
);
