<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-01-26 16:23+0000
$lang = array(
	'description' => array(
		'required' => 'O campo de "descrição" é de preenchimento obrigatório',
	) ,
	'name' => array(
		'required' => 'O campo "nome" é de preenchimento obrigatório',
	) ,
);
