<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-27 06:19+0000
// PO revision date:  2013-06-26 16:52+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'O campo de autorização dos comentários não parece conter um valor válido.',
		'required' => 'É necessário o campo de autorização dos comentários.',
	) ,
	'allow_feed' => array(
		'between' => 'O campo de incluir o Feed não parece conter um valor válido.',
		'required' => 'É necessário o campo de incluir o Feed.',
	) ,
	'allow_reports' => array(
		'between' => 'The allow reports field does not appear to contain a valid value?',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'The stat sharing field does not appear to contain a valid value?',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'The Akismet field does not appear to contain a valid value?',
		'length' => 'The Akismet field does not appear to contain a valid value?',
	) ,
	'cache_pages' => array(
		'between' => 'É necessário o campo da cache das páginas.',
		'required' => 'O campo da cache das páginas parece não conter um valor válido.',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'It looks like your server is not configured to handle clean URLs. You will need to change the configuration of your server before you can enable clean URLs. See more info on how to enable clean URLs at this forum <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">post</a>',
		'clean_url_enabled' => 'This option makes Ushahidi to be accessed via "clean" URLs. Without "index.php" in the URL.',
		'enable_clean_url' => 'Ativar Limpar os URL\'s',
		'title' => ' Limpar URL\'s',
	) ,
	'configure_map' => 'Configurar Mapa',
	'default_location' => 'Localização Predefinida',
	'default_map_all' => array(
		'alpha_numeric' => 'The color feed field does not appear to contain a valid value?',
	) ,
	'default_map_view' => 'Visualização de Mapa Predefinida',
	'default_zoom_level' => 'Nível do Zoom Predefinido',
	'download_city_list' => 'Obter as Cidades a partir do Geonames',
	'email_host' => array(
		'length' => 'O campo da porta do servidor de Mail é muito longo.',
		'numeric' => 'O campo da porta do servidor de Mail só deverá conter números.',
	) ,
	'email_port' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'email_servertype' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'facebook' => array(
		'title' => 'Opções  de Configuração do Facebook',
		'app_id' => 'Id. da App do facebook',
	) ,
	'https' => array(
		'enable_https' => 'Ativar HTTPS',
		'title' => 'HTTPS',
	) ,
	'items_per_page' => array(
		'between' => 'The items per page (Frontend) field does not appear to contain a valid value?',
	) ,
	'items_per_page_admin' => array(
		'between' => 'The items per page (Admin) field does not appear to contain a valid value?',
	) ,
	'map' => array(
		'default_location' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
		'zoom' => 'Nível do Zoom',
	) ,
	'map_provider' => array(
		'get_api' => 'Obter um Código API',
		'info' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
	) ,
	'map_settings' => 'Definições do Mapa',
	'multiple_countries' => 'Does this Ushahidi Deployment Span Multiple Countries',
	'site' => array(
		'checkins' => 'Ativar Verificações',
		'copyright_statement' => 'Declaração dos direitos de Autor do Site',
		'default_category_colors' => 'Cor Predefinida para Todas as Categorias',
		'default_category_icons' => 'Ícone Predefinido para Todas as Categorias',
		'delete_default_map_all_icon' => 'Apagar Ícone Predefinido',
		'email_site' => 'Endereço de e-mail do Site',
		'google_analytics_example' => 'Web Property ID - Formato: UA-XXXXX-XX',
		'items_per_page_admin' => 'Itens por Página - Administrador',
		'language' => 'Idioam do Site',
		'manually_approve_users' => 'Aprovar Utilizadores Manualmente',
		'name' => 'Nome do Site',
		'share_site_stats' => 'Share Site Statistics in API',
		'title' => 'Definições do Site',
		'twitter_configuration' => 'Twitter Credentials',
	) ,
	'site_email' => array(
		'email' => 'The site email field does not appear to contain a valid email address?',
	) ,
	'sms_no1' => array(
		'length' => 'The phone 1 field does not appear to contain a valid value?',
	) ,
	'sms_no2' => array(
		'length' => 'The phone 2 field is too long',
	) ,
	'sms_no3' => array(
		'length' => 'The phone 3 field is too long',
	) ,
);
