<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-01-26 16:53+0000
$lang = array(
	'upgrade_automatic' => 'Atualização de versão automática',
	'upgrade_available' => 'Atualização automática',
	'upgrade_continue_btn_text' => 'Continuar',
	'upgrade_db_btn_text' => 'Atualizar versão',
	'upgrade_manual' => 'Atualização de versão manual',
	'upgrade_text_1' => 'The instructions below details how to manually upgrade your Ushahidi deployment',
	'upgrade_text_2' => 'Step 1: Download the most recent ushahidi build from <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
	'upgrade_text_3' => 'Step 2: Depending on the operating system running the webserver, use your preferred tool/mode (i.e: telnet, ftp, ssh) to login to the webserver and replace the contents of all the folders with the newest from the recent build. All EXCEPT:',
	'upgrade_text_4' => 'Step 3: Use your favorite Mysql client ( eg. phpMyAdmin ), and execute the <code>upgrade.sql</code>. The script shall update and alter the respective tables',
	'upgrade_text_5' => 'For automatic upgrade, click on the button below',
	'upgrading' => 'A atualizar',
	'upgrade_ftp_password' => 'Password do FTP:',
	'upgrade_ftp_username' => 'Nome de Utilizador do FTP',
	'upgrade_db_version' => 'Versão da base de dados: %d',
	'upgrade_database' => 'Base de dados:',
	'beta' => 'BETA!',
	'download' => 'Descarregar a última versão do ushahidi...',
	'failed_downloading' => 'O download falhou.',
);
