<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-28 06:24+0000
// PO revision date:  2013-12-27 13:50+0000
$lang = array(
	'upgrade' => array(
		'between' => 'Dados inseridos inválidos. Estes devem ser 0 para Não ou 1 para Sim.',
	) ,
	'upgrade_automatic' => 'Atualização Automática',
	'upgrade_available' => 'Atualizações Disponíveis',
	'upgrade_continue_btn_text' => 'Continuar',
	'upgrade_db_btn_text' => 'Atualizar',
	'upgrade_manual' => 'Atualização Manual',
	'upgrade_status' => 'Estado da atualização do Ushahidi',
	'upgrade_text_1' => 'The instructions below details how to manually upgrade your Ushahidi deployment',
	'upgrade_text_2' => 'Step 1: Download the most recent ushahidi build from <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
	'upgrade_text_3' => 'Step 2: Depending on the operating system running the webserver, use your preferred tool/mode (i.e: telnet, ftp, ssh) to login to the webserver and replace the contents of all the folders with the newest from the recent build. All EXCEPT:',
	'upgrade_text_4' => 'Step 3: Use your favorite Mysql client ( eg. phpMyAdmin ), and execute the <code>upgrade.sql</code>. The script shall update and alter the respective tables',
	'upgrade_text_5' => 'For automatic upgrade, click on the button below',
	'upgrading' => 'A atualizar',
	'upgrade_ftp_password' => 'Password do FTP:',
	'upgrade_ftp_username' => 'Nome de Utilizador do FTP',
	'upgrade_status_info' => 'Já possui a última versão do Ushahidi.',
	'upgrade_db_version' => 'Versão da base de dados: %d',
	'upgrade_database' => 'Base de dados:',
	'ushahidi_release_version' => 'Ushahidi %s',
	'beta' => 'BETA!',
	'download' => 'A transferiri a última versão do Ushahidi ...',
	'failed_downloading' => 'Não foi possível transferir.',
	'successfully_unpacked' => 'Descompactação bem sucedida. A copiar os ficheiros ...',
	'failed_unpacking' => 'Não foi possível descompactar.',
	'successfully_copied' => 'Cópia bem sucedida. A atualizar a base de dados ...',
	'failed_copying' => 'Não foi possível copiar os ficheiros.',
);
