<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-10 06:05+0000
// PO revision date:  2012-07-13 04:40+0000

$lang = array (
  'email' => 
  array (
    'email' => 'Adresse email invalide.',
    'exists' => 'Cette adress email existe déja.',
    'length' => 'L\'adresse email doit comporter entre 4 et 64 caractères.',
    'required' => 'Veuillez indiquer une adresse email.',
  ),
  'name' => 
  array (
    'length' => 'Le nom complet doit comporter entre 3 et 100 caractères.',
    'required' => 'Veuillez indiquer le nom complet.',
    'standard_text' => 'Le nom d\'utilisateur comporte des caractères invalides.',
  ),
  'password' => 
  array (
    'length' => 'Le mot de passe doit comporter entre 5 et 16 caractères.',
    'login error' => 'Veuillez vérifier le mot de passe.',
    'required' => 'Veuillez entrer un mot de passe.',
  ),
  'password_confirm' => 
  array (
    'matches' => 'Les deux mots de passe doivent être les mêmes.',
  ),
  'roles' => 
  array (
    'required' => 'Veuillez définier au moins un role.',
    'values' => 'Le rôle doit être ADMINISTRATEUR ou UTILISATEUR.',
  ),
  'username' => 
  array (
    'admin' => 'The role de l\'administrateur ne peut être modifié.',
    'exists' => 'Ce nom d\'utilisateur est déjà pris.',
    'length' => 'Le nom d\'utilisateur doit comporter entre 2 et 16 caractères.',
    'login error' => 'Veuillez vérifier que le nom d\'utilisateur est correct.',
    'required' => 'Veuillez indiquer un nom d\'utilisateur.',
  ),
);

