<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:27+0000
$lang = array(
	'category_color' => array(
		'length' => 'Le champ «couleur» doit comporter 6 caractères.',
		'required' => 'Veuillez spécifier une couleur.',
	) ,
	'category_description' => array(
		'required' => 'Veuillez indiquer une description.',
	) ,
	'category_title' => array(
		'length' => 'Le titre doit comporter entre 3 et 80 caractères.',
		'required' => 'Veuillez indiquer un titre.',
	) ,
);
