<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-14 12:04+0000
// PO revision date:  2012-07-12 21:28+0000
$lang = array(
	'captcha' => array(
		'default' => 'Indiquez un code de sécurité valide',
		'required' => 'Indiquez le code de sécurité',
	) ,
	'comment_author' => array(
		'length' => 'Le nom doit comporter au moins 3 caractères.',
		'required' => 'Veuillez indiquer un nom.',
	) ,
	'comment_description' => array(
		'required' => 'Veuillez remplir le champ «commentaire».',
	) ,
	'comment_email' => array(
		'email' => 'Adresse email invalide.',
		'length' => 'L\'adresse email doit comporter entre 4 et 64 caractères.',
		'required' => 'Une adresse email doit être spécifiée si la case est cochée.',
	) ,
);
