<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-14 15:29+0000
$lang = array(
	'config' => 'fichier config',
	'controller' => 'controleur',
	'driver' => 'driver',
	'driver_implements' => 'le %s driver de la librairie %s doit implémenter l’interface %s.',
	'driver_not_found' => 'le %s driver de la librairie %s n\'a pas pu être trouvé.',
	'errors_disabled' => 'vous pouvez aller à la <a href="%s">page d’accueil </a> ou <a href="%s"> réessayer</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'helper' => 'le aidee',
);
