<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-22 14:47+0000
$lang = array(
	'am' => 'am',
	'friday' => array(
		'abbv' => 'Ven',
		'full' => 'Vendredi',
	) ,
	'monday' => array(
		'abbv' => 'Lun',
		'full' => 'Lundi',
	) ,
	'pm' => 'pm',
	'saturday' => array(
		'abbv' => 'sam',
		'full' => 'samedi',
	) ,
	'sunday' => array(
		'abbv' => 'Dim',
		'full' => 'Dimanche',
	) ,
	'thursday' => array(
		'abbv' => 'Jeu',
		'full' => 'jeudi',
	) ,
	'tuesday' => array(
		'abbv' => 'Mar',
		'full' => 'Mardi',
	) ,
	'wednesday' => array(
		'abbv' => 'Mer',
		'full' => 'Mercredi',
	) ,
	'january' => array(
		'abbv' => 'Jan',
		'full' => 'Janvier',
	) ,
	'february' => array(
		'abbv' => 'Fev',
		'full' => 'Fevrier',
	) ,
	'march' => array(
		'abbv' => 'Mar',
		'full' => 'Mars',
	) ,
	'april' => array(
		'abbv' => 'Avr',
		'full' => 'Avril',
	) ,
	'may' => array(
		'abbv' => 'May',
		'full' => 'May',
	) ,
	'june' => array(
		'abbv' => 'Jun',
		'full' => 'Juin',
	) ,
	'july' => array(
		'abbv' => 'Jul',
		'full' => 'Juiller',
	) ,
	'august' => array(
		'abbv' => 'Aou',
		'full' => 'Août',
	) ,
	'september' => array(
		'abbv' => 'Sep',
		'full' => 'septembre',
	) ,
	'october' => array(
		'abbv' => 'Oct',
		'full' => 'octobre',
	) ,
	'november' => array(
		'abbv' => 'Nov',
		'full' => 'Novembre',
	) ,
	'december' => array(
		'abbv' => 'Dec',
		'full' => 'Décembre',
	) ,
);
