<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-21 12:05+0000
// PO revision date:  2012-07-12 21:45+0000
$lang = array(
	'admin_footer' => 'Ce message a été envoyé de votre site web',
	'admin_login_url' => 'Login Administrateur',
	'admin_new_comment' => array(
		'message' => 'Un nouveau commentaire vient d\'être envoyé sur votre site, en réponse à:',
		'subject' => 'Nouveau commentaire',
	) ,
	'admin_new_email' => array(
		'message' => 'Un nouvel email vient d\'être envoyé sur votre site.',
		'subject' => 'Nouvel email',
	) ,
	'admin_new_report' => array(
		'message' => 'Un nouveau rapport vient d\'être envoyé sur votre site.',
		'subject' => 'Nouveau rapport',
	) ,
	'admin_new_sms' => array(
		'message' => 'Un nouvel SMS vient d\'être envoyé sur votre site.',
		'subject' => 'Nouveau SMS',
	) ,
);
