<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-11-19 06:11+0000
// PO revision date:  2012-11-02 14:57+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Veuillez vérifier que vous avez coché un élément',
		'numeric' => 'Veuillez vérifier que vous avez coché un élément',
		'categories_required' => 'Les rapports doivent être classés avant d\\\'être approuvés',
	) ,
	'action' => array(
		'permission' => 'Vous n\\\'avez pas la permission d\\\'effectuer cette action',
	) ,
);
