<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-20 12:02+0000
$lang = array(
	'profile_email' => 'Votre adresse email',
	'profile_name' => 'Votre nom',
	'profile_notify' => 'Choisissez OUI pour recevoir une alerte par email quand un nouveau rapport ou un commentaire est envoyé sur votre site.',
	'profile_password' => 'Votre mot de passe. Laisser vide si vous ne désirez pas le changer.',
	'profile_username' => 'Vous ne pouvez pas changer votre nom d\'utilisateur.',
	'settings_alert_email' => 'Adresse à laquelle seront envoyées les alertes email.',
	'settings_display_contact' => 'Visibilité de l\'onglet Contact.',
	'settings_locale' => 'La langue utilisée sur votre site.',
	'settings_site_email' => 'Adresse email à laquelle les rapports et les messages seront envoyés.',
	'settings_site_name' => 'Nom de votre site (visite en haut de la page principale).',
	'settings_site_tagline' => 'Décrivez votre site en quelques mots.',
);
