<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-29 06:15+0000
// PO revision date:  2013-03-28 15:52+0000
$lang = array(
	'actions' => array(
		'email_body' => 'Corps de l\'e-mail qui sera envoyé.',
		'email_subject' => 'Sujet de l\'e-mail qui sera envoyé.',
		'report_title' => 'Ceci est le titre par défaut à ajouter au signalement.',
		'verify' => 'Indiquer si un signalement est vérifié ou non.',
	) ,
	'default_value' => 'Sépare chaque valeur avec une virgule, ex. valeur1, valeur2.',
	'dropdown_choices' => 'Sépare chaque choix avec une virgule, ex. Item 1, Item 2 etc.',
	'private_subject' => 'Sujet du message privé',
	'private_message' => 'Message privé',
	'profile_email' => 'Votre adresse email',
	'profile_name' => 'Votre nom',
	'profile_notify' => 'Choisissez OUI pour recevoir une alerte par email quand un nouveau rapport ou un commentaire est envoyé sur votre site.',
	'profile_password' => 'Votre mot de passe. Laisser vide si vous ne désirez pas le changer.',
	'profile_public_url' => 'Ceci est l\'adresse ou votre profil public peut être accessible.',
	'profile_username' => 'Vous ne pouvez pas changer votre nom d\'utilisateur.',
	'settings_alert_email' => 'Adresse à laquelle seront envoyées les alertes email.',
	'settings_allow_alerts' => 'Autoriser les utilisateurs de souscrire à des alertes via le web.',
	'settings_allow_comments' => 'Autoriser les utilisateurs a formuler des commentaires aux rapports sur le site web principal.',
	'settings_allow_feed' => 'Ceci autorise l\'affichage des flux de nouvelles RSS sur le site principal.',
	'settings_allow_reports' => 'Autorise les utilisateurs à envoyer des informations via le formulaire du site web.',
	'settings_api_default_record_limit' => 'Nombre par défaut d\\\'enregistrement à extraire par requête API',
	'settings_api_max_record_limit' => 'Nombre maximum d\\\'enregistrements à extraire par requête API',
	'settings_api_max_requests_per_ip' => 'Nombre maximum de requêtes de l\\\'API par dresse IP',
	'settings_cache_pages_lifetime' => 'Définir la durée de vie du cache.',
	'settings_default_category_icons' => 'Défini une icône pour toutes les catégories sur ce site.',
	'settings_default_location' => 'Ceci est le pays depuis lequel le site web a été déployé.',
	'settings_display_contact' => 'Visibilité de l\'onglet Contact.',
	'settings_display_items_per_page' => 'Ceci est le nombre de signalements affichés par page sur le site principal.',
	'settings_display_items_per_page_admin' => 'Ceci est le nombre de signalements affichés par page sur l\'interface d\'administration.',
	'settings_flsms_text_1' => 'Numéros de téléphones sur lesquels les messages sont reçus.',
	'settings_locale' => 'La langue utilisée sur votre site.',
	'settings_server_ssl_support' => 'Ceci est requis pour améliorer la sécurisation de la connexion.',
	'settings_server_username' => 'Ceci est l\'adresse e-mail qui recevra les signalements.',
	'settings_site_email' => 'Adresse email à laquelle les rapports et les messages seront envoyés.',
	'settings_site_name' => 'Nom de votre site (visite en haut de la page principale).',
	'settings_site_tagline' => 'Décrivez votre site en quelques mots.',
	'settings_twitter_configuration' => 'Défini le hashtag Twitter qui sera utilisé dans les tweets.',
);
