<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-15 04:42+0000
// PO revision date:  2012-08-15 04:40+0000
$lang = array(
	'captcha' => array(
		'default' => 'Fadlan geli security code sax ah',
		'required' => 'Fadlan geli security code-ka',
	) ,
	'comment_author' => array(
		'length' => 'Magacu waa inuusan ka yareyn saddex xaraf',
		'required' => 'Magac ayaa loo baahan yahay',
	) ,
	'comment_description' => array(
		'required' => 'Farriin ayaa loo baahan yahay',
	) ,
	'comment_email' => array(
		'email' => 'Emailkaad gelisay sax ma aha',
		'length' => 'Emailkaagu waa inuu ka kooban yahay ugu yaraan 4 xaraf, ugu badnaanna 64 xaraf',
		'required' => 'Email ayaa loo baahan yahay haddii sanduuqu saxan yahay',
	) ,
);
