<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-13 04:30+0000
// PO revision date:  2012-07-13 04:22+0000

$lang = array (
  'admin_footer' => 'Farriintaan waxaa laga soo diray boggaaga',
  'admin_login_url' => 'Ku-gelidda Administrator-ka',
  'admin_new_comment' => 
  array (
    'message' => 'Farriin cusub ayaa loo gudbiyay boggaaga taasoo jawaab u ah:',
    'subject' => 'Farriin cusub',
  ),
  'admin_new_email' => 
  array (
    'message' => 'Farriin cusub oo Email ah ayaa loo gudbiyay boggaaga',
    'subject' => 'Farriin cusub oo Email ah',
  ),
  'admin_new_report' => 
  array (
    'message' => 'Warbixin cusub ayaa loo gudbiyay boggaaga',
    'subject' => 'Warbixin cusub',
  ),
  'admin_new_sms' => 
  array (
    'message' => 'Farriin qoraaleed cusub ayaa loo gudbiyay boggaaga',
    'subject' => 'Farriin qoraaleed cusub',
  ),
);

