<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-11-22 06:11+0000
// PO revision date:  2012-11-15 00:46+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Παρακαλώ βεβαιωθείτε ότι έχετε ελέγξει ένα αντικείμενο',
		'numeric' => 'Παρακαλώ βεβαιωθείτε ότι έχετε ελέγξει ένα αντικείμενο',
		'categories_required' => 'Οι αναφορές θα πρέπει να ταξινομηθούν πριν μπορέσουν να εγκριθούν',
	) ,
	'action' => array(
		'permission' => 'Δεν έχετε δικαίωμα να εκτελέσετε αυτή την ενέργεια',
	) ,
);
