<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-11-19 14:17+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'Το πεδίο "επιτρέπω " δεν περιέχουν έγκυρη αξία.',
		'required' => 'Το πεδίο "επιτρέπω μηνύματα" είναι υποχρεωτικό.',
	) ,
	'allow_feed' => array(
		'between' => 'Το πεδίο "περιλαμβάνω" δεν περιέχει έγκυρη αξία.',
		'required' => 'Το πεδίο "περιλαμβάνω" είναι υποχρεωτικό.',
	) ,
);
