<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-03 06:11+0000
// PO revision date:  2012-11-22 17:48+0000
$lang = array(
	'about' => 'Περί',
	'access' => 'Πρόσβαση',
	'access_limits' => 'Περιορισμοί Πρόσβασης',
	'account_name' => 'Ονομα Λογαριασμού',
	'actions' => 'Ενέργειες',
	'action_confirm' => 'Αυτή η ενέργεια δεν μπορεί να αναιρεθεί. Είστε βέβαιοι ότι θέλετε να συνεχίσετε;',
	'activate' => 'Ενεργοποίηση',
	'active' => 'Ενεργό',
	'add' => 'Προσθήκη',
	'added_by' => 'Προσθήκη από',
	'additional_data' => 'Περισσότερα δεδομένα',
	'additional_reports' => 'Περισσότερες μαρτυρίες',
	'add_edit' => 'Προσθήκη / Επεξεργασία',
	'add_field' => 'Προσθήκη πεδίου',
);
