<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-15 06:11+0000
// PO revision date:  2012-12-14 19:11+0000
$lang = array(
	'captcha' => array(
		'default' => 'Introduce un código de seguridad válido.',
		'valid' => 'Introduce un código de seguridad válido.',
		'required' => 'Introduce el código de seguridad.',
	) ,
);
