<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-16 06:10+0000
// PO revision date:  2012-12-15 16:00+0000
$lang = array(
	'layer_color' => array(
		'length' => 'El campo Color debe contener al menos 6 caracteres.',
		'required' => 'El campo Color es obligatorio.',
	) ,
);
