<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:23+0000
// PO revision date:  2013-07-09 21:59+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Por favor, verificar que ha marcado un elemento',
		'numeric' => 'Por favor, verificar que ha marcado un elemento',
	) ,
);
