<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-26 06:20+0000
// PO revision date:  2013-06-25 21:00+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'El campo de permitir comentarios no parece que contenga un valor válido,',
		'required' => 'El campo de permitir comentarios es obligatorio.',
	) ,
	'allow_feed' => array(
		'between' => 'El campo de incluir feed no parece que contenga un valor válido.',
		'required' => 'El campo de incluir feed es obligatorio.',
	) ,
	'allow_alerts' => array(
		'between' => 'El campo de permitir alertas no contiene un valor válido.',
		'required' => 'El campo de permitir alertas es obligatorio.',
	) ,
);
