<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:23+0000
// PO revision date:  2013-07-09 19:54+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'El campo de permitir comentarios no parece que contenga un valor válido,',
		'required' => 'El campo de permitir comentarios es obligatorio.',
	) ,
	'allow_feed' => array(
		'between' => 'El campo de incluir feed no parece que contenga un valor válido.',
		'required' => 'El campo de incluir feed es obligatorio.',
	) ,
	'allow_alerts' => array(
		'between' => 'El campo de permitir alertas no contiene un valor válido.',
		'required' => 'El campo de permitir alertas es obligatorio.',
	) ,
	'allow_reports' => array(
		'between' => 'El campo Reportes Permitidos no contiene un valor correcto.',
		'required' => 'El campo Reportes Permitidos es requerido.',
	) ,
	'facebook' => array(
		'description_2' => 'Esta configuración permite a los usuarios entrar mediante Facebook, this <strong>no</strong> crea una aplicación de facebook para su despliegue',
	) ,
	'site' => array(
		'default_category_colors' => 'Color Por Defecto Para Todas las Categorías',
		'default_category_icons' => 'Icono Por Defecto Para Todas Las Categorías',
		'delete_default_map_all_icon' => 'Eliminar Icono Por Defecto',
		'display_contact_page' => 'Mostrar Página De Contacto',
		'email_alerts' => 'Dirección de Correo Electrónico de Alertas',
		'email_notice' => '<span>Para recibir reportes por correo electrónico, por favor configure los datos de su cuenta de correo electrónico</span>',
		'email_site' => 'Dirección de Correo Electrónico del Sitio',
		'google_analytics' => 'Google Analytics',
		'language' => 'Idioma del Sitio',
		'message' => 'Mensaje del Sitio',
		'name' => 'Nombre del Sitio',
		'private_deployment' => 'Despliegue Privado',
		'require_email_confirmation' => 'Requiere Confirmación por Correo Electrónico del Usuario',
		'share_site_stats' => 'Habilitar Estadísticas (Se almacenarán en el servidor de Ushahidi)',
		'twitter_configuration' => 'Términos de Búsqueda de Twitter',
	) ,
	'site_email' => array(
		'email' => 'El campo de correo electrónico del sitio no parece contenter una dirección de correo válida.',
		'length' => 'El campo de correo electrónico del sitio debe tener entre 4 y 100 caracteres de longitud.',
	) ,
	'site_name' => array(
		'length' => 'El campo del nombre del sitio debe tener entre 3 y 50 caracteres de longitud.',
		'required' => 'El campo de nombre del sitio es obligatorio',
	) ,
	'sms' => array(
		'flsms_download' => 'Descargar e Instalar FrontlineSMS',
	) ,
	'sms_no1' => array(
		'length' => 'El campo teléfono 1 no parece tener un valor válido.',
		'numeric' => 'El campo teléfono 1 debe contener sólo números.',
	) ,
	'sms_no2' => array(
		'length' => 'El campo teléfono 2 es demasiado largo',
		'numeric' => 'El campo teléfono 2 debe contener sólo números.',
	) ,
	'sms_no3' => array(
		'length' => 'El campo teléfono 3 es demasiado largo',
		'numeric' => 'El campo teléfono 3 debe contener sólo números.',
	) ,
	'test_settings' => 'Probar configuración',
);
