<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 11:20+0000
$lang = array(
	'approved' => 'Aprobado',
	'category_impact' => 'Impacto de la categoría',
	'category_impact_description' => 'Este gráfico ofrece una visión lineal de los informes por categoría en el tiempo. Desplazar de izquierda a derecha pata ver una vista comparativa de diferentes categorías. Pasar el puntero sobre el gráfico para más detalles.',
	'choose_date_range' => 'Elegir un rango de fechas',
	'countries' => 'Países',
	'country' => 'País',
	'error' => 'Error',
	'legend' => 'Leyenda',
	'time_range_1' => '1 mes',
	'time_range_2' => '3 meses',
	'time_range_3' => '6 meses',
	'time_range_all' => 'Todos',
	'unique_visitors' => 'Visitantes únicos',
	'unverified' => 'No comprobado',
	'verified' => 'Comprobado',
	'visitor_summary' => 'Resumen de visitantes',
	'visits' => 'Visitas',
);
