<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-22 12:04+0000
// PO revision date:  2012-08-19 22:56+0000
$lang = array(
	'category_color' => array(
		'length' => 'Бојата мора да е најмалку 6 карактери долга.',
		'required' => 'Полето за боја е задолжително.',
	) ,
	'category_description' => array(
		'required' => 'Описот е задолжителен.',
	) ,
	'category_title' => array(
		'length' => 'Насловот мора да биде најмалку 3 а најмногу 80 карактери долг.',
		'required' => 'Насловот е задолжителен.',
	) ,
);
