<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-03 18:04+0000
// PO revision date:  2012-07-12 21:31+0000

$lang = array (
  'error' => 'Database error: %s',
  'table_not_found' => 'Table "%s" cannot be found in the database. Please make sure you are using the latest version of the database for this version of Ushahidi.',
);

