<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-17 06:40+0000
// PO revision date:  2012-08-15 04:40+0000
$lang = array(
	'database' => 'База на податоци',
	'database_host' => 'Хост на база на податоци',
	'database_name' => 'Име на база на податоци',
	'disable' => 'Оневозможи',
	'enable' => 'Овозможи',
	'finished' => 'Завршено',
	'general' => 'Генерално',
	'go_back' => 'Вратете се назад',
	'index' => array(
		'advanced' => 'НАПРЕДНА ИНСТАЛАЦИЈА',
		'advanced_installation_description' => 'Комплетирајте ги си те основни подесувања низ овој процес од 5 чекори.  Ова вклучува сервер, мапа, име на страницата и контакт детали.',
		'basic_installation' => 'ОСНОВНА ИНСТАЛАЦИЈА',
		'basic_installation_description' => 'Едноставно и брзо. Се што ви треба е root папката на вашата страна и информациите околу вашата база на податоци. Одберете ја оваа опција ако сакате брзо да имате се спремно за работа, а се друго можете да подесите понатаму.',
		'proceed' => 'Продолжи',
	) ,
	'installation_successful' => 'Успешна инсталација',
	'map' => 'Мапа',
	'other_steps' => 'Други чекори...',
	'password' => 'Лозинка',
	'password_description' => 'Лозинка на базата на податоци',
	'previous' => 'Претходна',
	'select_mail_server_ssl' => 'Овозможи или оневозможи SSL',
	'site_name' => 'Име на страницата',
	'site_name_description' => 'Името на вашата страница',
	'site_tagline' => 'Слоганот на страницата',
	'site_tagline_description' => 'Вашиот слоган',
	'summary' => array(
		'text_2' => '<p>Инструкции за промена на пермисиите на документите:</p>
        <ul>
            <li><a href="http://www.washington.edu/computing/unix/permissions.html" target="_blank">Unix/Linux</a></li>
            <li><a href="http://support.microsoft.com/kb/308419" target="_blank">Windows</a></li>
        </ul>',
		'text_3' => 'Пред да почнете, мора да се осигурате дека следниве документи и папки имаат дозвола за пишување од напиот веб сервер. Ова вклучува промена на промена на пермисиите на фајловите.',
		'text_4' => 'За инсталациониот процес, ве молиме имајте ги следниве информации при рака.',
	) ,
	'table_prefix' => 'Префикс на табелата',
	'table_prefix_description' => 'Најчесто нема да сакате да го промените префиксот на табелата. Но, ако сакате да користите повеќе Ushahidi инсталации во една база на податоци, можете тоа да го направите со промена на префиксот овде.',
	'title' => 'Наслов',
	'to_login' => 'За да се логирате, одете до',
	'upload_data' => 'Качете податоци за пријавите',
	'username' => 'Корисничко име',
	'username_description' => 'Вашето корисничко има за базата на податоци',
	'use_credentials' => 'и ги корисите следниве информации за највување',
	'view_site' => 'Види ја твојата веб страна',
);
