<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-23 00:04+0000
// PO revision date:  2012-08-21 00:02+0000
$lang = array(
	'from' => 'Од',
	'from_date' => 'Од',
	'page_not_found' => 'Страницата не е пронајдена',
	'private_to' => 'До',
);
