<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-22 22:18+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Da li ste upisali ispravan email u polje za unos email adrese?',
	) ,
	'alert_lat' => array(
		'between' => 'Niste izabrali validnu lokaciju na mapi.',
		'required' => 'Niste izabrali validnu lokaciju na mapi.',
	) ,
	'alert_lon' => array(
		'between' => 'Niste izabrali validnu lokaciju na mapi.',
		'required' => 'Niste izabrali validnu lokaciju na mapi.',
	) ,
	'alert_mobile' => array(
		'one_required' => 'Morate unjeti broj vašeg mobitela ili vašu email adresu.',
	) ,
	'alert_recipient' => array(
		'required' => 'Niste naveli primaoca upozorenja.',
	) ,
);
