<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-30 12:11+0000
// PO revision date:  2012-10-28 12:35+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Da li ste upisali ispravan email u polje za unos email adrese?',
		'email_check' => 'Navedena email adresa je vec registrovana da prima obavjestenja o toj lokaciji.',
		'length' => 'Email polje mora imati najmanje 4 a najviše 64 znaka.',
		'required' => 'Email polje je obavezno ukoliko je oznaceno.',
	) ,
	'alert_lat' => array(
		'between' => 'Niste izabrali validnu lokaciju na mapi.',
		'required' => 'Niste izabrali validnu lokaciju na mapi.',
	) ,
	'alert_lon' => array(
		'between' => 'Niste izabrali validnu lokaciju na mapi.',
		'required' => 'Niste izabrali validnu lokaciju na mapi.',
	) ,
	'alert_mobile' => array(
		'length' => 'Čini se da polje za mobilni telefon ne sadrzi ispravan broj karaktera.',
		'mobile_check' => 'Navedeni broj je već registriran za primanje obavještenja o toj lokaciji.',
		'numeric' => 'Polje za mobitel ne sadrži ispravan broj karaktera. Molimo unesite samo brojeve uključujući i pozivni broj.',
		'one_required' => 'Morate unjeti broj vašeg mobitela ili vašu email adresu.',
		'required' => 'Polje za mobitel je obavezno ukoliko je označeno.',
	) ,
	'alert_radius' => array(
		'in_array' => 'Niste označili ispravan radius na mapi.',
		'required' => 'Niste podesili svoj radius na mapi.',
	) ,
	'alert_recipient' => array(
		'required' => 'Niste naveli primaoca upozorenja.',
	) ,
	'code_not_found' => 'Ovaj kod za verifikaciju nije pronađen! Molimo potvrdite da imate tačan URL.',
	'code_verified' => 'Vaš kod je uspješno verificiran. Od sada ćete primati upozorenja o incidentima kako se budu događali.',
	'unsubscribed' => 'Nećeš iše primati upozorenja od',
);
