<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-30 12:11+0000
// PO revision date:  2012-10-29 19:35+0000
$lang = array(
	'email' => array(
		'email' => 'Email adresa koja je unesena nije validna.',
		'exists' => 'Žao nam je, za Vaš email je već registrovan korisnički račun.',
		'length' => 'Polje email mora sadžavati najmanje 4, a najviše 64 karaktera.',
		'required' => 'Polje email je obavezno.',
	) ,
	'name' => array(
		'length' => 'Polje ime, mora sadržavati najmanje 3, a najviše 100 karaktera.',
		'required' => 'Polje ime je obavezno.',
		'standard_text' => 'Polje korisničko ime sadrži nedopuštene znakove.',
	) ,
	'current_password' => array(
		'length' => 'Vaša šifra mora sadržati najmanje 8 znakova.',
		'login error' => 'Provjerite da li ste unijeli tačan email i šifru.',
		'matches' => 'Unesite istu šifru u oba polja pod nazivom šifra.',
		'required' => 'Polje šifra je obavezna.',
		'alpha_dash' => 'Polje šifra mora da sadrži jedino alfabetske znakove, # i @simbole, brojeve i crtice',
		'incorrect' => 'Unijeli ste pogrešnu šifru. Molimo Vas pokušajte ponovo.',
	) ,
	'new_password' => array(
		'length' => 'Vaša šifra mora sadržati najmanje 8 znakova.',
		'login error' => 'Provjerite da li ste unijeli tačan email i šifru.',
		'matches' => 'Unesite istu šifru u oba polja pod nazivom šifra.',
		'required' => 'Polje šifra je obavezna.',
	) ,
	'password' => array(
		'length' => 'Vaša šifra mora sadržati najmanje 8 znakova.',
		'login error' => 'Molimo, provjerite da li ste unijeli ispravan email i šifru.',
		'matches' => 'Unesite istu šifru u oba polja pod nazivom šifra.',
		'required' => 'Polje šifra je obavezna.',
		'riverid' => '%s',
	) ,
	'password_confirm' => array(
		'matches' => 'Polje potvrdi šifru mora odgovarati polju šifra.',
	) ,
	'resetemail' => array(
		'email' => 'Email koji ste unijeli nije ispravna email adresa.',
		'invalid' => 'Žao nam je, unijeli ste nepostojeću email adresu.',
		'required' => 'Polje email je obavezno.',
	) ,
);
