<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-26 00:05+0000
// PO revision date:  2012-10-24 20:48+0000
$lang = array(
	'category_color' => array(
		'length' => 'Označeno polje mora imati 6 znakova',
		'required' => 'Označeno polje je obavezno',
	) ,
	'category_description' => array(
		'required' => 'Opis je obavezan',
	) ,
	'category_image' => array(
		'type' => 'Polje slika ne sadrži ispravnu sliku. Prihvaćeni formati slika su .JPG, .PNG i . GIF.',
	) ,
	'category_title' => array(
		'length' => 'Naslov mora imati najmanje 3, a najviše 80 znakova',
		'required' => 'Naslov je obavezan',
	) ,
	'parent_id' => array(
		'exists' => 'Odabarana kategorija ne postoji',
		'numeric' => 'Glavna kategorija mora biti numerička',
		'parent_trusted' => 'Glavna kategorija nemože biti specijalna kategorija',
		'required' => 'Odabir glavne kategorije je obavezan',
	) ,
);
