<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-11-07 12:10+0000
// PO revision date:  2012-11-05 12:07+0000
$lang = array(
	'field_default' => array(
		'default' => 'Postavljena vrijednost namjenjena za polje je nevažeća.',
		'length' => 'Polje Ime treba da sadrži najmanje 3 i ne više od 200 karaktera. ',
	) ,
	'field_height' => array(
		'between' => 'Unesite vrijednost od 0 do 50 u polje Visina',
	) ,
	'field_isdate' => array(
		'between' => 'Unesena je pogrešna vrijednost za polje Datum.',
		'required' => 'Molimo izaberi Da ili Ne za polje Datum.',
	) ,
	'field_name' => array(
		'length' => 'Polje Ime treba da sadrži najmanje 3 i ne više od 100 karaktera. ',
		'required' => 'Molimo unesite ime polja. ',
	) ,
	'field_required' => array(
		'between' => 'Unijeli ste nevažeću vrijednost za potrebno polje.',
		'required' => 'Molimo odaberite Da ili Ne za potrebno polje.',
	) ,
	'field_type' => array(
		'numeric' => 'Molimo odaberite valjanu vrstu polja.',
		'required' => 'Molimo odaberite vrstu polja.',
	) ,
	'field_width' => array(
		'between' => 'Unesite vrijednost od 0 do 300 za širinu polja.',
	) ,
	'form_description' => array(
		'required' => 'Molimo unesite opis obrasca.',
	) ,
	'form_id' => array(
		'default' => 'Zadani oblik se ne može izbrisati.',
		'numeric' => 'Molimo odaberite koju formu dodati ovom polju.',
		'required' => 'Molimo odaberite koju formu dodati ovom polju.',
	) ,
	'form_title' => array(
		'length' => 'Forma naziva polja mora da sadrži najmanje 3 i ne više od 100 karaktera.',
		'required' => 'Unesite naziv obrasca.',
	) ,
);
