<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-27 12:09+0000
// PO revision date:  2012-10-25 18:07+0000
$lang = array(
	'field_height' => array(
		'between' => 'Unesite vrijednost od 0 do 50 u polje Visina',
	) ,
);
