<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-29 00:10+0000
// PO revision date:  2012-10-28 17:46+0000
$lang = array(
	'database' => 'Baza podataka ',
	'database_name' => 'Naziv baze podataka ',
	'finished' => 'Završeno',
	'general' => 'Općenito',
	'go_back' => 'Idi nazad',
	'index' => array(
		'advanced' => 'Napredna instalacija',
		'basic_installation' => 'Osnovna instalacija',
	) ,
	'installation_successful' => 'Uspješna instalacija',
	'mail_server' => 'Mail Server',
	'map' => 'Mapa',
	'other_steps' => 'Drugi koraci',
	'password' => 'Lozinka',
	'password_description' => 'Lozinka veše baze podataka',
	'previous' => 'Predhodni',
	'title' => 'Naslov',
);
