<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-29 00:10+0000
// PO revision date:  2012-10-28 12:19+0000
$lang = array(
	'akismet_cannot_connect' => 'Nije uspjela konekcija na Aksimet server.',
	'akismet_cannot_retrieve' => 'Odgovor od Aksimet servera nije primljen.',
	'api_library_not_found' => 'API biblioteka: <strong>%s</strong> za <strong>%s</strong> kalsu nije nađena. Molimo provjerite API i njegovu tabelu smjerenja poslova. ',
	'askimet_invalid_apikey' => 'Vaš Aksimet API ključ nije validan.',
	'clickatell_message_too_long' => 'Vaša unicode poruka je previše duga! ( Trenutna dužina=',
	'clickatell_no_destination_address' => 'Molimo definišite destinacijsku adresu (ZA)!',
	'clickatell_no_sender_address' => 'Molimo definišite adresu izvora (OD)!',
	'clickatell_unicode_message_too_long' => 'Vaša unicode poruka je previše duga! ( Trenutna dužina=',
);
