<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-11-04 12:11+0000
// PO revision date:  2012-10-29 20:04+0000
$lang = array(
	'akismet_cannot_connect' => 'Nije uspjela konekcija na Aksimet server.',
	'akismet_cannot_retrieve' => 'Odgovor od Aksimet servera nije primljen.',
	'api_library_not_found' => 'API biblioteka: <strong>%s</strong> za <strong>%s</strong> kalsu nije nađena. Molimo provjerite API i njegovu tabelu smjerenja poslova. ',
	'askimet_invalid_apikey' => 'Vaš Aksimet API ključ nije validan.',
	'clickatell_message_too_long' => 'Vaša unicode poruka je previše duga! ( Trenutna dužina=',
	'clickatell_no_destination_address' => 'Molimo definišite destinacijsku adresu (ZA)!',
	'clickatell_no_sender_address' => 'Molimo definišite adresu izvora (OD)!',
	'clickatell_unicode_message_too_long' => 'Vaša unicode poruka je previše duga! ( Trenutna dužina=',
	'clickatell_unsupported_method' => 'Nepodržani metod slanja!',
	'upgrade_directory_not_deleted' => 'Directorij <code>%s</coded> ne može biti obrisan.',
	'upgrade_extracting_error' => 'Grška prilikom raspakivanja: <code>%s</code>',
	'upgrade_failed' => 'Preuzimanje poslljednjeg Ushahidi nije uspješno. HTTP statusni kod',
	'upgrade_file_not_copied' => 'Fajl <code>%s</coded> ne može biti kopiran.',
	'upgrade_file_not_deleted' => 'Fajl <code>%s</coded> ne može biti obrisan.',
	'upgrade_title' => 'Skripta za  Ushahidi nadogradnju',
	'upgrade_zip_error' => 'Preuzeti Ushahidi zip fajl <code>%s</code>, ne može biti zapisan.',
	'riverid_variable_not_available' => '%s nije dostupni u RiverID klasi.',
);
