<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-24 12:04+0000
// PO revision date:  2012-10-24 00:04+0000
$lang = array(
	'captcha' => array(
		'default' => 'Molimo unesite ispravan sigurnosni kod.',
		'required' => 'Molimo unesite sigurnosni kod.',
	) ,
	'email' => array(
		'email' => 'Molimo provjerite da li je unesena ispravna email adresa.',
	) ,
);
