<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-25 00:04+0000
// PO revision date:  2012-10-24 22:08+0000
$lang = array(
	'admin_footer' => 'Ova poruka je poslata sa vaše web stranice.',
	'admin_new_comment' => array(
		'subject' => 'Novi komentar',
	) ,
	'admin_new_email' => array(
		'subject' => 'Nova e-mail poruka',
	) ,
	'admin_new_report' => array(
		'subject' => 'Novi izvještaj',
	) ,
	'member_new_message' => array(
		'message' => 'Dobili ste privatnu poruku',
		'subject' => 'Nova privatna poruka',
	) ,
);
