<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-26 00:05+0000
// PO revision date:  2012-10-25 18:22+0000
$lang = array(
	'page_title' => array(
		'length' => 'Naslov stranice mora biti dug najmanje 3, a najviše 150 karaktera ',
	) ,
	'page_description' => array(
		'required' => 'Unesite opis stranice',
	) ,
);
