<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-26 00:05+0000
// PO revision date:  2012-10-25 21:10+0000
$lang = array(
	'reports_view' => 'Pogledaj izvjestaje',
	'reports_approve' => 'Odobri izvjestaj',
	'reports_verify' => 'Potvrdi izvjestaj',
);
