<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-28 00:10+0000
// PO revision date:  2012-10-27 10:34+0000
$lang = array(
	'private_to' => array(
		'exists' => 'Korisnik kome pokušavate poslati poruku ne postoji.',
	) ,
	'private_subject' => array(
		'required' => 'Obavezan unos predmeta poruke',
		'length' => 'Predmet mora sadržavati od 3 do 150 karaktera',
	) ,
	'private_message' => array(
		'required' => 'Polje za poruku je obavezno',
	) ,
);
