<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-27 12:09+0000
// PO revision date:  2012-10-26 19:28+0000
$lang = array(
	'comments_form_error' => 'graška!


detalji prijedlozi istorija',
	'data_include' => array(
		'between' => 'Molimo obilježite važeću stavku da je uključite u preuzimanje.',
		'numeric' => 'Molimo obilježite važeću stavku da je uključite u preuzimanje.',
	) ,
	'data_point' => array(
		'between' => 'Molimo odaberite važeći tip izvještaja za preuzimanje.',
		'numeric' => 'Molimo odaberite važeći tip oizvještaja za preuzimanje.',
		'required' => 'Molimo odaberite važeći tip izvještaja za preuzimanje.',
	) ,
);
