<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-11-24 06:10+0000
// PO revision date:  2012-10-29 22:32+0000
$lang = array(
	'comments_form_error' => 'graška!


detalji prijedlozi istorija',
	'country_name' => array(
		'single_country' => 'Ova implementacija proteže se unutar jedne zemlje samo. Molimo provjerite izvješće lokacija unutar države %s.',
	) ,
	'custom_field' => array(
		'values' => 'Unesite važeću vrijednost za jedan od svojih prilagođenih stavki obrasca.',
	) ,
	'data_include' => array(
		'between' => 'Molimo obilježite važeću stavku da je uključite u preuzimanje.',
		'numeric' => 'Molimo obilježite važeću stavku da je uključite u preuzimanje.',
	) ,
	'data_active' => array(
		'between' => 'Odaberite "Izvješća čekaju odobrenje" ili "Odobrena izvješća" ili oboje.',
		'numeric' => 'Odaberite "Izvješća čekaju odobrenje" ili "Odobrena izvješća" ili oboje.',
		'required' => 'Odaberite "Izvješća čekaju odobrenje" ili "Odobrena izvješća" ili oboje.',
	) ,
	'data_verified' => array(
		'between' => 'Odaberite "Izvješća čekaju potvrdu" ili "Potvrđena izvješća" ili oboje.',
		'numeric' => 'Odaberite "Izvješća čekaju potvrdu" ili "Potvrđena izvješća" ili oboje.',
		'required' => 'Odaberite "Izvješća čekaju potvrdu" ili "Potvrđena izvješća" ili oboje.',
	) ,
	'data_point' => array(
		'between' => 'Molimo odaberite važeći tip izvještaja za preuzimanje.',
		'numeric' => 'Molimo odaberite važeći tip oizvještaja za preuzimanje.',
		'required' => 'Molimo odaberite važeći tip izvještaja za preuzimanje.',
	) ,
	'incident_active' => array(
		'between' => 'Molimo unesite ispravnu vrijednost za odobri ovaj izvještaj',
		'required' => 'Molimo unesite ispravnu vrijednost za odobri ovaj izvještaj',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'Am/pm polje ne sadrži ispravnu vrijednost.',
	) ,
	'incident_category' => array(
		'numeric' => 'Polje "Kategorije" ne pokazuje da sadrži ispravnu kategoriju.',
		'required' => 'Polje "Kategorije" je obavezno.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'Polje datum ne pokazuje da sadrži ispravan datum. ',
		'date_mmddyyyy' => 'Polje datum ne pokazuje da sadrži ispravan datum.',
		'required' => 'Polje datum je obavezno.',
	) ,
	'incident_description' => array(
		'required' => 'Polje "Opis" je obavezno.',
	) ,
	'incident_hour' => array(
		'between' => 'Polje sat ne pokazuje da sadrži ispravan sat. ',
		'required' => 'Polje sati je obavezno.',
	) ,
	'incident_information' => array(
		'alpha' => 'Molimo unesite ispravnu vrijednost za informacijske vjerojatnosti.',
		'length' => 'Molimo unesite ispravnu vrijednost za informacijske vjerojatnosti.',
	) ,
	'incident_minute' => array(
		'between' => 'Polje minute ne pokazuje da sadrži ispravnu vrijednost.',
		'required' => 'Polje minuta je obavezno.',
	) ,
	'incident_news' => array(
		'url' => 'Polje izvori linkova vijesti ne sadrži ispravan URL. ',
	) ,
	'incident_photo' => array(
		'size' => 'Molimo osigurajte da je postavljena fotografija veličine do 2 MB.',
		'type' => 'Polje postavljanje fotografija ne sadrži ispravnu fotografiju. Jedini prihvaćeni formati su .JBG, .PNG i .GIF.',
		'valid' => 'Polje postavljanje fotografija ne sadrži ispravan dokument. ',
	) ,
	'incident_source' => array(
		'alpha' => 'Unesite važeću vrijednost za izvor pouzdanosti.',
		'length' => 'Unesite važeću vrijednost za izvor pouzdanosti.',
	) ,
	'incident_title' => array(
		'length' => 'Polje "Naslov izvješća" mora da sadrži najmanje 3 i ne više od 200 karaktera.',
		'required' => 'Polje "naslov prijave" je obavezno.',
		'csrf' => 'Mogući CSRF napad. Jeste li stvarno htjeli kreirati / urediti ​​izvješće?',
	) ,
	'incident_verified' => array(
		'between' => 'Molimo unesite ispravnu vrijednost za Provjeri ovaj izvještaj.',
		'required' => 'Molimo unesite ispravnu vrijednost za Provjeri ovaj izvještaj.',
	) ,
	'incident_video' => array(
		'url' => 'Polje Video poveznice ne sadrže ispravan URL.',
	) ,
	'locale' => array(
		'alpha_dash' => 'Polje regionalno ima neispravnu vrijednost.',
		'exists' => 'Ovo izvješće već ima prijevod za ovaj jezik.',
		'length' => 'Polje regionalno ima neispravnu vrijednost.',
		'locale' => 'Izvorni izvještaj i prijevod već imaju isti regionalni (jezik). ',
	) ,
	'location_name' => array(
		'length' => 'Polje "Naziv lokacije" mora da sadrži najmanje 3 i ne više od 200 karaktera. ',
		'required' => 'Polje "Lokacija" je obavezno.',
	) ,
	'person_email' => array(
		'email' => 'Polje e-mail  ne sadrži ispravne e-mail adrese. ',
		'length' => 'Polje e-mail mora da sadrži najmanje 4 i ne više od 64 karaktera. ',
	) ,
	'person_first' => array(
		'length' => 'Polje ime mora da sadrži najmanje 3 i ne više od 100 karaktera. ',
	) ,
	'person_last' => array(
		'length' => 'Polje prezime mora da sadrži najmanje 2 i ne više od 100 karaktera. ',
	) ,
);
