<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-28 00:10+0000
// PO revision date:  2012-10-25 21:05+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Molimo potvrdite da ste odabrali stavku',
		'numeric' => 'Molimo potvrdite da ste odabrali stavku',
		'categories_required' => 'Izvještaji moraju biti kategorizovani prije nego se odobre',
	) ,
	'action' => array(
		'permission' => 'Nemate odobrenje za ovu vrstu zahtjeva',
	) ,
);
