<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-28 12:10+0000
// PO revision date:  2012-10-27 21:33+0000
$lang = array(
	'cleanurl' => array(
		'title' => 'Očisti URLove',
	) ,
	'clickatell_username' => array(
		'required' => 'Clickatell korisničko ime je obavezno.',
	) ,
	'configure_map' => 'Konfigurirajte mapu.',
	'default_location' => 'Zadana lokacija',
	'default_zoom_level' => 'Zadani nivo zumiranja',
	'facebook' => array(
		'title' => 'Opcije za podešavanje Facebooka ',
		'description' => 'Kako bi ste dobili informaciju ispod potrebno je da kreirate novu Facebook aplikaciju za',
		'app_id' => 'Facebookov App ID',
		'app_secret' => 'Facebookob App Secret',
	) ,
	'map' => array(
		'zoom' => 'Nivo zumiranja',
	) ,
	'site' => array(
		'timezone' => 'Vremenska zona',
	) ,
	'sms' => array(
		'clickatell_password' => 'Vaša Clickatell lozinka',
		'clickatell_username' => 'Vaše Clickatell korisničko ime',
	) ,
);
