<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-29 00:10+0000
// PO revision date:  2012-10-28 21:27+0000
$lang = array(
	'api' => array(
		'maximum_record_limit' => 'Maksimalni broj zapisa za preuzimanje po API zahtjevu',
		'maximum_requests_per_ip_address' => 'Maksimalni broj API zahtjeva po IP adresi',
	) ,
	'banner_image' => array(
		'default' => 'Došlo je do greške u postavljanju baner slike.',
		'size' => 'Veličina banera prelazi dozvoljeni limit.',
	) ,
	'cleanurl' => array(
		'enable_clean_url' => 'Dozvolite čišćenje URL',
		'title' => 'Očisti URLove',
	) ,
	'clickatell_username' => array(
		'required' => 'Clickatell korisničko ime je obavezno.',
	) ,
	'configure_map' => 'Konfigurirajte mapu.',
	'default_location' => 'Zadana lokacija',
	'default_zoom_level' => 'Zadani nivo zumiranja',
	'facebook' => array(
		'title' => 'Opcije za podešavanje Facebooka ',
		'description' => 'Kako bi ste dobili informaciju ispod potrebno je da kreirate novu Facebook aplikaciju za',
		'app_id' => 'Facebookov App ID',
		'app_secret' => 'Facebookob App Secret',
	) ,
	'map' => array(
		'zoom' => 'Nivo zumiranja',
	) ,
	'site' => array(
		'timezone' => 'Vremenska zona',
	) ,
	'sms' => array(
		'clickatell_password' => 'Vaša Clickatell lozinka',
		'clickatell_username' => 'Vaše Clickatell korisničko ime',
	) ,
);
