<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-30 00:10+0000
// PO revision date:  2012-10-29 20:08+0000
$lang = array(
	'allow_comments' => array(
		'required' => 'Polje odobri komentare je obavezno.',
	) ,
	'allow_alerts' => array(
		'required' => 'Polje dopusti obavještenja je obavezno.',
	) ,
	'allow_reports' => array(
		'required' => 'Polje dopusti obavještenja je obavezno.',
	) ,
	'api' => array(
		'maximum_record_limit' => 'Maksimalni broj zapisa za preuzimanje po API zahtjevu',
		'maximum_requests_per_ip_address' => 'Maksimalni broj API zahtjeva po IP adresi',
	) ,
	'banner_image' => array(
		'default' => 'Došlo je do greške u postavljanju baner slike.',
		'size' => 'Veličina banera prelazi dozvoljeni limit.',
	) ,
	'cleanurl' => array(
		'enable_clean_url' => 'Dozvolite čišćenje URL',
		'title' => 'Očisti URLove',
	) ,
	'clickatell_username' => array(
		'required' => 'Clickatell korisničko ime je obavezno.',
	) ,
	'configure_map' => 'Konfigurirajte mapu.',
	'default_location' => 'Zadana lokacija',
	'default_map_all' => array(
		'required' => 'Polje boja je obavezno.',
	) ,
	'default_zoom_level' => 'Zadani nivo zumiranja',
	'facebook' => array(
		'title' => 'Opcije za podešavanje Facebooka ',
		'description' => 'Kako bi ste dobili informaciju ispod potrebno je da kreirate novu Facebook aplikaciju za',
		'app_id' => 'Facebookov App ID',
		'app_secret' => 'Facebookob App Secret',
	) ,
	'https' => array(
		'enable_https' => 'Omogući HTTPS',
		'title' => 'HTTPS',
	) ,
	'map' => array(
		'zoom' => 'Nivo zumiranja',
	) ,
	'select_default_location' => 'Odaberite državu.',
	'site' => array(
		'allow_comments' => 'Dozvoli korisnicima komentiranje prijava.',
		'google_analytics' => 'Google Analytics',
		'timezone' => 'Vremenska zona',
		'title' => 'Postavke stranice',
		'twitter_hashtags' => 'Hashtag - odvojeni zarezima',
	) ,
	'site_name' => array(
		'required' => 'Polje naziv stranice je obavezno.',
	) ,
	'sms' => array(
		'clickatell_password' => 'Vaša Clickatell lozinka',
		'clickatell_username' => 'Vaše Clickatell korisničko ime',
		'option_1' => 'Opcija 1: Koristi Frontline SMS',
	) ,
	'sms_no2' => array(
		'length' => 'Polje telefon 2 je predugačko.',
		'numeric' => 'Polje telefon 2 treba sadržati samo brojeve.',
	) ,
	'sms_no3' => array(
		'length' => 'Polje telefon 3 je predugačko.',
		'numeric' => 'Polje telefon 3 treba sadržati samo brojeve.',
	) ,
);
