<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-11-03 00:10+0000
// PO revision date:  2012-10-29 19:54+0000
$lang = array(
	'actions' => array(
		'add_to_category' => 'Ovo dodaje izvještaj u dodatne kategorije. Ako ste ovdje izabrali Kategoriju 1 a izvještaj je već unesen pod Kategoriju 2 onda će izvještaj biti i pod Kategorijom 1 i pod Kategorijom 2.',
		'approve' => 'Odobrava izvještaj ili ne. Odobreni izvještaj se prikazuje javno.',
		'email_body' => 'Tijelo e-mail poruke.',
		'email_subject' => 'Predmet e-mail poruke.',
		'verify' => 'Označava izvještaj kao potvrđen ili nepotvrđen',
	) ,
	'change_picture' => 'Profil stranica koristi Gravatar fotografiju. Klik na vašu fotografiju će vas odvesti na Gravatar stranicu gdje možete promjeniti fotografiju.',
	'default_value' => 'Razdvojite svaku vrijednost sa zarezom, npr. vrijednost1, vrijednost2',
	'dropdown_choices' => 'Odvojite svaku izabranu stavku zarezom. Npr. Stavka 1, Stavka 2 itd.',
	'private_to' => 'Započnite unos da izlistate članove.',
	'private_subject' => 'Naslov privatne poruke',
	'private_message' => 'Privatna poruka',
	'profile_email' => 'Vaša e-mail adresa',
	'profile_name' => 'Ovo je jedan od načina kako možete biti identifikovani na stranici. Imajte na umu da je ova informacija javna.',
	'profile_new_password' => 'Ako želite da promjenite šifru, unesite je u ovo polje. Ako ne želite da promjenite šifru, ostavite ovo polje prazno.',
	'profile_new_users_password' => 'Ova informacija je obavezna pri kreiranju novog korisnika i inicijalno će služiti kao korisnička šifra. Obavijestite novog korisnika da promjeni šifru nakon prve registracije.',
	'profile_notify' => 'Izbor opcije DA vam omogućava da dobijate obavijesti putem elektronske pošte kada se novi izvještaji ili komentari postave na vašu stranicu.',
	'profile_password' => 'Vaša šifra. Neophodno je unijeti šifru da bi spriječili neovlašten pristup vašem nalogu.',
	'profile_public_url' => 'Ovo je adresa gdje se može pronaći vaš javni profil.',
	'profile_username' => 'Vaše korisničko ime nije promjenjivo',
	'settings_alert_email' => 'Ovo je e-mail adresa koja će biti korištena za e-mail obavještenja',
	'settings_allow_alerts' => 'Dozvolite korisnicima da se pretplate na obavještenja putem web-a',
	'settings_allow_clustering' => 'Ovo omogućuje grupisanje sličnih izvještaja u jednu tačku na karti.',
	'settings_allow_comments' => 'Dozvolite korisnicima da komentarišu izvještaj na glavnoj stranici',
	'settings_allow_feed' => 'Ovo omogućuje RSS Novosti da budu prikazane na glavnoj stranici.',
	'settings_allow_reports' => 'Dozvoljava korisnicima da postave informaciju preko web forme',
	'settings_configure_map' => 'Podesite mapu da pokriva specifičnu lokaciju.',
	'settings_default_category_colors' => 'Podesite jednu boju za sve kategorije na stranici.',
	'settings_default_category_icons' => 'Podesite jednu ikonu za sve kategorije na stranici.',
	'settings_flsms_text_1' => 'Broj telefona za primanje SMS poruka.',
	'settings_google_analytics' => 'Pratite posjetioce Vaše stranice. Dobijte detaljne statističke podatke posjetioca.',
	'settings_locale' => 'Postavite jezik koji će se koristiti na stranici.',
	'settings_map_provider' => 'Ovo odredžuje koja mapa će koristiti za stranicu.',
	'settings_server_password' => 'Ovo je lozinka za email adresu koja prima izvještaje.',
	'settings_server_username' => 'Ovo je email adresa koja prima izvještaje.',
	'settings_site_name' => 'Ovo je ime stranice koje se pojavljuje na vrhu glavne stranice.',
	'settings_site_tagline' => 'Opišite stranicu u nekoliko riječi.',
	'settings_twitter_configuration' => 'Odredite twitter hashtag koji će biti korišten u tweetu.',
);
