<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-26 00:05+0000
// PO revision date:  2012-10-25 18:15+0000
$lang = array(
	'actions' => array(
		'verify' => 'Označava izvještaj kao potvrđen ili nepotvrđen',
	) ,
	'default_value' => 'Razdvojite svaku vrijednost sa zarezom, npr. vrijednost1, vrijednost2',
	'private_subject' => 'Naslov privatne poruke',
	'private_message' => 'Privatna poruka',
	'profile_email' => 'Vaša e-mail adresa',
	'profile_public_url' => 'Ovo je adresa gdje se može pronaći vaš javni profil.',
	'profile_username' => 'Vaše korisničko ime nije promjenjivo',
	'settings_alert_email' => 'Ovo je e-mail adresa koja će biti korištena za e-mail obavještenja',
	'settings_allow_alerts' => 'Dozvolite korisnicima da se pretplate na obavještenja putem web-a',
	'settings_allow_comments' => 'Dozvolite korisnicima da komentarišu izvještaj na glavnoj stranici',
	'settings_allow_reports' => 'Dozvoljava korisnicima da postave informaciju preko web forme',
);
