<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-26 12:00+0000
// PO revision date:  2012-10-25 21:12+0000
$lang = array(
	'add_to_category' => 'Dodaj u kategoriju',
	'approved' => 'odobreno',
	'approve_manual' => 'Odobri manuelnim putem',
	'are_you_sure_you_want_to_delete_this_item' => 'Da li ste sigurni da zelite da obrisete ovu stavku?',
	'are_you_sure_you_want_to_delete_this_photo' => 'Da li ste sigurni da zelite da obrisete ovu fotografiju?',
	'color' => 'Boja',
);
