<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-01 06:10+0000
// PO revision date:  2012-10-30 13:24+0000
$lang = array(
	'upgrade_automatic' => 'Automatska nadogradnja',
	'upgrade_available' => 'Raspoložive nadogradnje',
	'upgrade_continue_btn_text' => 'Nastavi',
	'upgrade_db_btn_text' => 'Nadogradi',
	'upgrade_db_text_1' => 'Spremam se nadograditi vašu bazu podataka sa verzije',
	'upgrade_db_text_2' => 'na novu verziju baze podataka',
	'upgrade_db_text_3' => 'Klik na dugme "Nadogradi" i opusti te se dok se magija dešava',
	'upgrade_db_title' => 'Ushahidi baza podataka nadograđena',
	'upgrade_db_up_to_date' => 'Vaša verzija baze podataka je svježa.',
	'upgrade_failed' => 'Nadogradnja nije uspjela',
	'upgrade_manual' => 'Ručna nadogradnja',
	'upgrade_text_6' => 'Za automatsku nadogradnju kliknite ispod',
	'upgrading' => 'Nadograđujem',
	'upgrade_ftp_password' => 'FTP lozinka:',
	'upgrade_ftp_username' => 'FTP korisničko ime:',
	'upgrade_status_info' => 'Imate najnoviju verziju Ushahidija.',
	'upgrade_status_info_2' => 'Nemate potrebe za nadogradnjom.',
	'upgrade_db_version' => 'Verzija baze podataka: %d',
	'upgrade_database' => 'Baza podataka',
	'ushahidi_release_version' => 'Ushahidi %s',
	'beta' => 'BETA!',
	'download' => 'Preuzimanje najnovije verzije Ushahidi-a',
	'log_file' => 'Log fajl',
	'successfully_downloaded' => 'Uspješno preuzeto. Raspakivanje...',
	'failed_downloading' => 'Neuspješno preuzimanje',
	'successfully_unpacked' => 'Uspješno raspakivanje. Kopiram datoteke...',
	'failed_unpacking' => 'Neuspješno raspakivanje.',
	'successfully_copied' => 'Uspješno kopirane datoteke. Nadograđujem bazu podataka...',
	'failed_copying' => 'Neuspješno kopiranje datoteka.',
	'backup_success' => 'Uspješno pohranjivanje i nadogradnja baze podataka',
	'backup_failed' => 'Neuspješno pohranjivanje baze podataka',
	'dbupgrade_success' => 'Uspješna nadogradnja baze podataka.',
	'deleting_files' => 'Brisanje preuzetih datoteka',
);
