<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-22 22:12+0000
$lang = array(
	'upgrade_continue_btn_text' => 'Nastavi',
	'upgrade_ftp_password' => 'FTP lozinka:',
	'upgrade_ftp_username' => 'FTP korisničko ime:',
	'upgrade_status_info' => 'Imate najnoviju verziju Ushahidija.',
	'ushahidi_release_version' => 'Ushahidi %s',
	'beta' => 'BETA!',
);
