<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-15 12:00+0000
$lang = array(
	'email' => array(
		'email' => '請確認email為正確資料',
		'exists' => '抱歉，這個email帳號已經註冊了',
		'length' => 'email資料需為4～64個字元',
		'required' => 'email為必填',
	) ,
	'name' => array(
		'length' => '姓名欄位必須填入3~100個字元',
		'required' => '姓名為必填',
		'standard_text' => '使用者名稱出現不能使用的字元',
	) ,
	'new_password' => array(
		'length' => '密碼必須為5~16個字元',
		'login error' => '請確認你已輸入正確的密碼.',
		'matches' => '請在兩個密碼欄位中輸入一樣的密碼.',
		'required' => '密碼為必填欄位.',
		'alpha_dash' => '密碼只能由字母，數字和符號#，@，_以及-組成',
	) ,
	'password' => array(
		'length' => '密碼必須為5~16個字元',
		'login error' => '請確認你已輸入正確的密碼',
		'matches' => '請在兩個密碼欄位中輸入一樣的密碼',
		'required' => '密碼為必填欄位',
		'alpha_dash' => '密碼只能由字母，數字和符號#，@，_以及-組成',
	) ,
	'password_confirm' => array(
		'matches' => '密碼確認欄位資料需與密碼欄位資料一致',
	) ,
	'resetemail' => array(
		'email' => '請確認輸入的email是正確的',
		'invalid' => '抱歉，系統內沒有你的email資料',
		'required' => 'email欄位為必填',
	) ,
	'role' => array(
		'superadmin_modify' => '只有超級管理員可以修改超級管理員或升級用戶到管理員.',
	) ,
	'roles' => array(
		'alpha_numeric' => '無效的角色.',
		'length' => '角色地欄位字元長度需於5~30之間.',
		'required' => '請至少選擇一種角色',
		'values' => '必須選擇是管理者或使用者',
	) ,
	'username' => array(
		'admin' => '管理者權限無法被修改',
		'alpha_numeric' => '公告頁面的URL網址地址只能包含數字和字母.',
		'exists' => '抱歉，這個使用者名稱已經被註冊',
		'length' => '使用者帳號必須為2~16個字元',
		'login error' => '請確認你已輸入正確的使用者名稱',
		'required' => '使用者帳號為必填',
		'superadmin' => '超級管理者權限無法被修改',
		'csrf' => '可能的的CSRF（跨站請求偽造）攻擊。你真的要建立/編輯用戶?',
	) ,
);
