<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:28+0000
$lang = array(
	'captcha' => array(
		'default' => '請輸入正確的安全碼',
		'required' => '請輸入安全碼',
	) ,
	'contact_email' => array(
		'email' => '請確認已輸入有效的Email',
		'length' => 'Email資料需為4~64字元',
		'required' => '如果已經選擇Email，則Email欄位為必填',
	) ,
	'contact_message' => array(
		'required' => '訊息欄位為必填',
	) ,
	'contact_name' => array(
		'length' => '姓名欄位至少為1個字元',
		'required' => '姓名欄位為必填',
	) ,
	'contact_subject' => array(
		'length' => '主題欄位置少為3個字元',
		'required' => '主題欄位為必填',
	) ,
);
