<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-14 18:56+0000
$lang = array(
	'friday' => array(
		'abbv' => '週五',
		'full' => '週五',
	) ,
	'monday' => array(
		'abbv' => '週一',
		'full' => '週一',
	) ,
	'saturday' => array(
		'abbv' => '週六',
		'full' => '週六',
	) ,
	'sunday' => array(
		'abbv' => '週日',
		'full' => '週日',
	) ,
	'thursday' => array(
		'abbv' => '週四',
		'full' => '週四',
	) ,
	'tuesday' => array(
		'abbv' => '週二',
		'full' => '週二',
	) ,
	'wednesday' => array(
		'abbv' => '週三',
		'full' => '週三',
	) ,
);
