<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-20 02:57+0000
$lang = array(
	'feed_name' => array(
		'length' => 'RSS名稱的長度應在3至70個字符之間',
		'required' => '請輸入RSS的名稱.',
	) ,
	'feed_url' => array(
		'required' => '請輸入RSS的源地址(URL).',
		'url' => '請輸入一個正確的URL。比如. http://www.ushahidi.com',
	) ,
);
