<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-31 06:04+0000
// PO revision date:  2012-07-12 21:48+0000

$lang = array (
  'latitude' => 
  array (
    'between' => '緯度欄位資料顯示為無效',
    'required' => '緯度欄位為必填，請在地圖上點選一個位置.',
  ),
  'level_id' => 
  array (
    'numeric' => 'The Reporter Level field does not appear to contain a valid Level?',
    'required' => 'The Reporter Level field does not appear to contain a valid Level?',
  ),
  'location_name' => 
  array (
    'length' => '地點名稱長度為2~200個字元.',
    'required' => '地點名稱欄位為必填.',
  ),
  'longitude' => 
  array (
    'between' => '經度欄位資料顯示為無效',
    'required' => '經度欄位為必填，請在地圖上點選一個位置.',
  ),
  'reporter_id' => 
  array (
    'numeric' => 'Invalid Reporter',
    'required' => 'Invalid Reporter',
  ),
);

