<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 23:14+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'The allow comments field does not appear to contain a valid value?',
	) ,
	'allow_feed' => array(
		'between' => 'The include feed field does not appear to contain a valid value?',
	) ,
	'allow_reports' => array(
		'between' => 'The allow reports field does not appear to contain a valid value?',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'The stat sharing field does not appear to contain a valid value?',
	) ,
	'api' => array(
		'default_record_limit' => 'Default no. of records to be fetched per API request',
		'maximum_record_limit' => 'Maximum no. of records to be fetched per API request',
		'maximum_requests_per_ip_address' => 'Maximum no. of API requests per IP address',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'The Akismet field does not appear to contain a valid value?',
		'length' => 'The Akismet field does not appear to contain a valid value?',
	) ,
	'cache_pages' => array(
		'required' => 'The cache pages field does not appear to contain a valid value?',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'The cache pages lifetime field does not appear to contain a valid value?',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'It looks like your server is not configured to handle clean URLs. You will need to change the configuration of your server before you can enable clean URLs. See more info on how to enable clean URLs at this forum <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">post</a>',
		'clean_url_enabled' => 'This option makes Ushahidi to be accessed via "clean" URLs. Without "index.php" in the URL.',
	) ,
	'default_map_all' => array(
		'alpha_numeric' => 'The color feed field does not appear to contain a valid value?',
	) ,
	'email_host' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'email_port' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'email_servertype' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'items_per_page' => array(
		'between' => 'The items per page (Frontend) field does not appear to contain a valid value?',
	) ,
	'items_per_page_admin' => array(
		'between' => 'The items per page (Admin) field does not appear to contain a valid value?',
	) ,
	'map' => array(
		'default_location' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
	) ,
	'map_provider' => array(
		'info' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
	) ,
	'multiple_countries' => 'Does this Ushahidi Deployment Span Multiple Countries',
	'site' => array(
		'google_analytics_example' => 'Web Property ID - Formato: UA-XXXXX-XX',
	) ,
	'site_email' => array(
		'email' => 'The site email field does not appear to contain a valid email address?',
	) ,
	'sms' => array(
		'flsms_instructions' => 'Messages received into a FrontlineSMS hub can be synched with Ushahidi. Detailed instructions on how to sync can be found <strong><a href="http://wiki.ushahididev.com/doku.php?id=how_to_use_ushahidi_alpha#how_to_setup_frontlinesms_to_sync_with_ushahidi" target="_blank">here</a></strong>. You will require the key and link below to set up the sync with FrontlineSMS',
	) ,
	'sms_no1' => array(
		'length' => 'The phone 1 field does not appear to contain a valid value?',
	) ,
	'sms_no2' => array(
		'length' => 'The phone 2 field is too long',
	) ,
	'sms_no3' => array(
		'length' => 'The phone 3 field is too long',
	) ,
);
