<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-17 21:59+0000
$lang = array(
	'date_added' => '日期已新增',
	'last_access' => '上一次連線',
	'sharing_color' => array(
		'length' => '顏色欄位至少需六瑪.',
		'required' => '顏色欄位為必填.',
	) ,
	'sharing_name' => array(
		'length' => '分享名稱顯示為無效',
		'required' => '分享名稱為必填.',
	) ,
	'sharing_url' => array(
		'exists' => '這個網址已經存在',
		'length' => '這個網址顯示為無效?',
		'required' => '網址欄位為必填.',
		'url' => '網址欄位顯示包含無效資料?',
	) ,
);
