<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-09 06:23+0000
// PO revision date:  2013-07-08 16:38+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Phần thông tin email dường như chứa địa chỉ email không hợp lệ?',
		'email_check' => 'Phần địa chỉ email đã được đăng ký và nhận cảnh báo từ địa điểm đó.',
		'length' => 'Phần thông tin email phải chứa ít nhất 4 và không được nhiều hơn 64 ký tự.',
		'required' => 'Phần thông tin email được yêu cầu nếu phần lựa chọn được chọn.',
	) ,
	'alert_country' => array(
		'single_country' => 'Việc thi hành này chỉ gói gọn trong một quốc gia. Hãy chắc rằng địa điểm cảnh báo nằm trong quốc gia %s.',
	) ,
	'alert_lat' => array(
		'between' => 'Bạn vẫn chưa chọn một địa điểm hợp lệ trên bản đồ',
		'required' => 'Bạn vẫn chưa chọn một địa điểm hợp lệ trên bản đồ',
	) ,
	'alert_lon' => array(
		'between' => 'Bạn vẫn chưa chọn một địa điểm hợp lệ trên bản đồ',
		'required' => 'Bạn vẫn chưa chọn một địa điểm hợp lệ trên bản đồ',
	) ,
	'alert_mobile' => array(
		'length' => 'Phần thông tin di động dường như không chứa các chữ số hợp với yêu cầu.',
		'mobile_check' => 'Số di động này đã được đăng ký và nhận thông tin từ địa điểm đó.',
		'numeric' => 'Phần thông tin về điện thoại di động chứa dữ liệu không hợp lệ. Xin vui lòng nhập vào số liệu kèm theo mã quốc gia.',
		'one_required' => 'Bạn phải điền vào hoặc phần số di động của bạn hoặc địa chỉ email',
		'required' => 'Khung thông tin điện thoại di động cần được đánh dấu chọn.',
	) ,
	'alert_radius' => array(
		'in_array' => 'Bạn vẫn chưa thiết lập bán kính hợp lệ trên bản đồ.',
		'required' => 'Bạn vẫn chưa chọn bán kính trên bản đồ.',
	) ,
	'alert_recipient' => array(
		'required' => 'Bạn vẫn chưa chỉnh cảnh báo về người gửi.',
	) ,
	'alerts_subscribed' => 'Bạn đã đăng ký phần cảnh báo cho các phần mục sau',
	'code_already_verified' => 'Mã đã được xác nhận trước đó!',
	'code_not_found' => 'Không tìm thấy mã xác nhận! Xin vui lòng xác nhận rằng bạn đã điền vào đúng đường dẫn liên kết.',
);
