<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:24+0000
// PO revision date:  2013-07-09 15:29+0000
$lang = array(
	'base_path' => 'Đường dẫn gốc',
	'database' => 'Cơ sở dữ liệu',
	'database_host' => 'Host của cơ sở dữ liệu',
	'database_host_description' => 'Nếu bạn thực thi Ushahidi từ chính máy tính của bạn, điều này có nghĩa rằng đây là một "localhost". Nếu bạn thực thi Ushahidi từ web server, bạn sẽ nhận được thông tin về host của bạn từ nhà cung cấp dịch vụ web hosting.',
	'database_name' => 'Tên cơ sở dữ liệu',
	'database_name_description' => 'Tên của cơ sở dữ liệu mà bạn muốn Ushahidi được thực thi trong đó',
	'db_information_link' => 'Để biết thêm thông tin, vui lòng truy cập <a href="http://wiki.ushahidi.com/doku.php?id=a_brief_word_on_databases" target="_blank">phần đề mục này</a> trên hệ thống wiki có bàn về cơ sở dữ liệu với đầy đủ thông tin chi tiết.',
	'default_language' => 'Ngôn ngữ mặc định (địa phương)',
	'default_language_description' => 'Mỗi phần phát triển của Ushahidi đi kèm theo đó là các gói ngôn ngữ ứng với từng quốc gia sở tại. Bạn cũng có thể <a href="http://wiki.ushahidi.com/doku.php?id=localisation_l10n_internationlisation_i18n&s[]=language#enabling_new_languages" target="_blank">thêm vào phần dịch của riêng bạn</a>.',
	'disable' => 'Vô hiệu hóa',
	'enable' => 'Bật',
	'error_summary' => 'Được hiển thị dưới đây là thông tin tóm tắt về các lỗi mà hệ thống gặp phải',
);
