<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:24+0000
// PO revision date:  2013-07-10 05:44+0000
$lang = array(
	'approved' => 'Đã chấp thuận',
	'categories' => 'Phân Loại',
	'category_impact' => 'Tác động phân loại',
	'category_impact_description' => 'Biểu đồ này cho bạn cách nhìn theo dạng tuyến tính của các báo cáo theo từng dạng phân loại theo từng thời điểm thời gian. Kéo chuột từ trái sang phải để xem phần so sánh giữa các loại. Di chuyển chuột đến vùng biểu đồ để biết thêm chi tiết.',
	'choose_date_range' => 'Chọn một khoảng ngày tháng.',
	'countries' => 'Quốc gia',
	'country' => 'Quốc gia',
);
