<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-03 06:22+0000
// PO revision date:  2013-07-02 21:43+0000
$lang = array(
	'base_path' => 'Base Path',
	'database' => 'Database',
	'database_host' => 'Database Host',
	'database_host_description' => 'If you are running Ushahidi on your own computer, this will more than likely be "localhost". If you are running Ushahidi from a web server, you will get your host information from your web hosting provider.',
	'database_name' => 'Database Name',
);
