<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-03 06:22+0000
// PO revision date:  2013-07-02 21:35+0000
$lang = array(
	'actions' => array(
		'add_to_category' => 'This adds the report to additional categories. If you select Category 1 here and the report already has Category 2 attached to it, the report will then have both Category 1 and Category 2.',
		'approve' => 'Approves a report or not. If approved, it will show up publicly.',
		'assign_badge' => 'You will be able to assign a badge to the triggering user. Pick the badge that gets assigned here.',
		'between_times' => 'This is a range of hours and/or minutes between two times in 24 hour format. If you input an earlier time in the second field, it will be flipped with the first. These times must be within a single day. Also, this time is checked against the time you have configured on your site in site settings and <strong>not</strong> necessarily the timezone of the user interacting with your deployment. Leave this at 00:00 to 00:00 to ignore this qualifier.',
		'category' => 'If you would like to activate triggers only when a certain category is being used, you can set that here. This will allow a trigger to be activated if only one of the categories is used. For instance, if you select Category 1 and Category 2 here and a report is submitted using Category 2 and Category 3, it will pass the test.',
		'days_of_the_week' => 'If these actions happen on certain days of the week, set that here. Keep in mind the day is determined by the timezone configured on your deployment. Hold shift, command, or control for multiple day selection.',
		'email_body' => 'Body of the email that will be sent.',
		'email_subject' => 'Subject of email that will be sent.',
		'keywords' => 'You can choose to leave this blank if you do not want to check against keywords. If you add words here, you will need to separate them with a comma (,). For example, if you want to activate a trigger when someone mentions "love" or "peace" in their message, you will want to add "love, peace" in the keywords box.',
	) ,
);
