<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-20 01:28+0000
// PO revision date:  2012-08-20 01:15+0000
$lang = array(
	'upgrade' => array(
		'between' => 'Dada introduida no vàlida. Pot ser 0 per No i 1 per Si.',
	) ,
	'upgrade_automatic' => 'Actualització automàtica',
	'upgrade_available' => 'Actualització disponible',
	'upgrade_continue_btn_text' => 'Continuar',
	'upgrade_db_btn_text' => 'Actualitzar',
	'upgrade_db_text_1' => 'Procedeixo a actualitzar la base de dades des de la versió',
	'upgrade_db_text_2' => 'a la nova versió de la base de dades',
	'upgrade_db_text_3' => 'Cliqueu sobre el botó "Actualitzar" i relaxeu-vos mentre faig la màgia.',
	'upgrade_db_text_4' => 'Oh, i si també voleu fer un backup de la vostra base de dades, marqueu el checkbox de sota i ho faré en un instant.',
	'upgrade_db_text_5' => 'Faig un backup de la base de dades abans d`actualitzar? (<strong style="color:#FF0000;">Altament Recomanable</strong>)',
	'upgrade_db_title' => 'Actualització de la base de dades de l`Ushahidi',
	'upgrade_failed' => 'L`actualització ha fallat en algun punt',
	'upgrade_manual' => 'Actualització Manual',
	'upgrade_status' => 'Estat de l`actualització de l`Ushahidi',
	'upgrade_text_1' => 'Les següents instruccions us guiaran per a actualitzar manualment l`Ushahidi',
	'upgrade_text_2' => '<strong>Pas 1:</strong> Descarregueu la versió més recent d`Ushahidi des de <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
	'upgrade_text_3' => '<strong>Pas 2:</strong> Depenent del sistema operatiu del servidor web, feu servir el vostre métode preferit (p.ex.: telnet, ftp, ssh) per entrar al servidor web i reemplaçar els continguts de totes les carpetes amb els de la darrera versió. <strong>TOTS EXCEPTE:</strong>',
	'upgrade_text_4' => '<strong>Pas 3:</strong> Cliqueu el botó <strong>"Continuar"</strong> per a actualitzar les taules necessàries.',
	'upgrade_text_5' => 'Per a una actualització automàtica, cliqueu al botó de sota.',
	'upgrading' => 'Actualitzant',
);
