<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-14 00:05+0000
// PO revision date:  2012-07-12 21:27+0000

$lang = array (
  'captcha' => 
  array (
    'default' => 'Vložte platný ověřovací kód',
    'required' => 'Opište ověřovací kód',
  ),
  'comment_author' => 
  array (
    'length' => 'Jméno má mít alespoň tři znaky.',
    'required' => 'Vyplňte jméno.',
  ),
  'comment_description' => 
  array (
    'required' => 'Vyplňte komentář.',
  ),
  'comment_email' => 
  array (
    'email' => 'Emailová adresa není ve správném formátu',
    'length' => 'Emailová adresa má mít minimálně 4 a maximálně 64 znaků.',
    'required' => 'Vyplňte Váš email.',
  ),
);

