<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-31 00:04+0000
// PO revision date:  2012-08-19 22:43+0000
$lang = array(
	'friday' => array(
		'abbv' => 'Pá',
		'full' => 'Pátek',
	) ,
	'monday' => array(
		'abbv' => 'Po',
		'full' => 'Pondělí',
	) ,
	'saturday' => array(
		'abbv' => 'So',
		'full' => 'Sobota',
	) ,
	'sunday' => array(
		'abbv' => 'Ne',
		'full' => 'Neděle',
	) ,
	'thursday' => array(
		'abbv' => 'Čt',
		'full' => 'Čtvrtek',
	) ,
	'tuesday' => array(
		'abbv' => 'Út',
		'full' => 'Úterý',
	) ,
	'wednesday' => array(
		'abbv' => 'Stř',
		'full' => 'Středa',
	) ,
	'october' => array(
		'abbv' => 'Říj',
		'full' => 'Říjen',
	) ,
);
