<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-07 12:05+0000
// PO revision date:  2012-07-12 21:45+0000

$lang = array (
  'admin_footer' => 'Z vašeho webu byla zaslána tato zpráva',
  'admin_login_url' => 'Login admina',
  'admin_new_comment' => 
  array (
    'message' => 'Na webu byl zadán nový komentář v odpověď na:',
    'subject' => 'Nový komentář',
  ),
  'admin_new_email' => 
  array (
    'message' => 'Na web byla zaslána nová emailová zpráva',
    'subject' => 'Nová emailová zpráva',
  ),
  'admin_new_report' => 
  array (
    'message' => 'Nová zpráva byla zadána přes webové rozhraní',
    'subject' => 'Nová zpráva',
  ),
  'admin_new_sms' => 
  array (
    'message' => 'Na web byla zaslána nová sms zpráva.',
    'subject' => 'Nová sms zpráva',
  ),
  'member_new_alert' => 
  array (
    'message' => 'You Have Received a New Alert',
    'subject' => 'New Alert!',
  ),
  'member_new_message' => 
  array (
    'message' => 'You Have Received a Private Message',
    'subject' => 'New Private Message',
    'footer' => 'To Reply Please Go To: ',
  ),
);

