<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-05 10:13+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Ověřte prosím, že jste položku zkontrolovali',
		'numeric' => 'Ověřte prosím, že jste položku zkontrolovali',
		'categories_required' => 'Hlášení musí být ketegorizovány před tím, než mohou být schváleny',
	) ,
	'action' => array(
		'permission' => 'Nemáte oprávnění k provedení této akce',
	) ,
);
