<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-21 00:04+0000
// PO revision date:  2012-08-19 22:44+0000
$lang = array(
	'custom_field' => array(
		'values' => 'Please enter a valid value for one of your custom form items',
	) ,
	'data_include' => array(
		'between' => 'Please select a valid item to include in the download',
		'numeric' => 'Please select a valid item to include in the download',
	) ,
	'data_point' => array(
		'between' => 'Please select a valid type of report to download',
		'numeric' => 'Please select a valid type of report to download',
		'required' => 'Please select a valid type of report to download',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'The FROM date field does not appear to contain a valid date?',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'The am/pm field does not appear to contain a valid value?',
	) ,
	'incident_category' => array(
		'numeric' => 'The category field does not appear to contain a valid category?',
		'required' => 'Je třeba zaškrtnout jednu nebo více kategorií.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'The date field does not appear to contain a valid date?',
		'date_mmddyyyy' => 'The date field does not appear to contain a valid date?',
	) ,
	'incident_description' => array(
		'required' => 'Chybí popis události.',
	) ,
	'incident_hour' => array(
		'between' => 'The hour field does not appear to contain a valid hour?',
	) ,
	'incident_information' => array(
		'alpha' => 'Please enter a valid value for Information Probability',
		'length' => 'Please enter a valid value for Information Probability',
	) ,
	'incident_minute' => array(
		'between' => 'The minute field does not appear to contain a valid value?',
	) ,
	'incident_news' => array(
		'url' => 'Odkaz není ve správném formátu?',
	) ,
	'incident_photo' => array(
		'size' => 'Prosím, zkontrolujte, že soubory s fotografiemi nemají více než 2MB.',
		'type' => 'Soubor s fotkou/obrázkem musí být ve formátu .JPG, .PNG a .GIF.',
		'valid' => 'Soubor s fotkou/obrázkem není platným souborem',
	) ,
	'incident_source' => array(
		'alpha' => 'Please enter a valid value for Source Reliability',
		'length' => 'Please enter a valid value for Source Reliability',
	) ,
	'incident_title' => array(
		'length' => 'Název má mít minimálně 3 a maximálně 100 znaků.',
		'required' => 'Chybí název události.',
	) ,
	'incident_verified' => array(
		'between' => 'Please enter a valid value for Verify This Report',
		'required' => 'Please enter a valid value for Verify This Report',
	) ,
	'incident_video' => array(
		'url' => 'Odkaz není ve správném formátu?',
	) ,
	'latitude' => array(
		'between' => 'Je zempisná šířka ve správném formátu?',
		'required' => 'Je třeba vyplnit zeměpisnou šířku. Klikněte na správné místo na mapě pro určení polohy.',
	) ,
	'locale' => array(
		'exists' => 'This report already has a translation for this language',
		'locale' => 'The Original Report and the Translation have the same locale (language)',
		'required' => 'Chybí specifikace místa.',
	) ,
	'location_name' => array(
		'length' => 'Položka "upřesnění místa" má mít minimálně 3 a maximálně 200 znaků.',
		'required' => 'Je třeba vyplnit položku "upřesnění místa".',
	) ,
	'longitude' => array(
		'between' => 'Je zeměpisná délka ve správném formátu?',
		'required' => 'Je třeba vyplnit zeměpisnou délku. Klikněte na správné místo na mapě pro určení polohy.',
	) ,
	'person_email' => array(
		'email' => 'Email není ve správném formátu',
		'length' => 'Email má mít minimálně 4 a maximálně 64 znaků.',
	) ,
	'person_first' => array(
		'length' => 'Jméno má mít minimálně 3 a maximálně 100 znaků.',
	) ,
	'person_last' => array(
		'length' => 'Příjmení má mít minimálně 3 a maximálně 100 znaků.',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'The TO date field does not appear to contain a valid date?',
	) ,
);
