<?php
	$lang = array(
	'upgrade_automatic' => 'Automatická aktualizace',
	'upgrade_available' => 'Dostupné aktualizace',
	'upgrade_continue_btn_text' => 'Pokračovat',
	'upgrade_db_btn_text' => 'Aktualizovat',
	'upgrade_db_text_1' => 'Chystáte se aktualizovat databázi z verze',
	'upgrade_db_text_2' => 'na nejnovější verzi',
	'upgrade_db_text_3' => 'Klikněte na tlačítko Aktualizovat a počkejte až se aktualizace provede.',
	'upgrade_db_text_4' => 'Přejete-li si zálohovat databázi, zaškrtněte příslušné políčko.',
	'upgrade_db_text_5' => 'Zálohovat databázi před aktualizací? (<strong style="color:#FF0000;">Silně doporučujeme!</strong>)',
	'upgrade_db_title' => 'Databáze aktualizována',
	'upgrade_failed' => 'Aktualizace selhala',
	'upgrade_manual' => 'Manuální aktualizace',
	'upgrade_status' => 'Průběh aktualizace',
	'upgrade_text_1' => 'Následující instrukce popisují, jak manuálně aktualizovat Váš systém Ushahidi',
	'upgrade_text_2' => 'en_US: <strong>Krok 1:</strong> Stáhněte si poslední sestavení Ushahidi na stránkách <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
	'upgrade_text_3' => '<strong>Krok 2:</strong> Vyberte si mód, v jakém se připojíte k Vašemu webovému serveru (telnet, ftp, ssh) a nahraďte obsah složek soubory z nejnovějšího sestavení. <strong>Všechny KROMĚ:</strong>',
	'upgrade_text_4' => '<strong>Krok 4:</strong> Klikněte na tlačítko <strong>"Pokračovat"</strong> pro aktualizaci nezbytných tabulek.',
	'upgrade_text_5' => 'Pro automatickou aktualizaci klikněte na tlačítko níže',
	'upgrade_title_text_1' => 'Používáte Ushahidi verze v',
	'upgrade_title_text_2' => 'běžící na',
	'upgrading' => 'Aktualizuji',
	);
?>
