<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-31 00:04+0000
// PO revision date:  2012-07-12 21:58+0000

$lang = array (
  'upgrade' => 
  array (
    'between' => 'Invalid input data. It can either be 0 for No and 1 for Yes.',
  ),
  'upgrade_automatic' => 'Automatická aktualizace',
  'upgrade_available' => 'Dostupné aktualizace',
  'upgrade_continue_btn_text' => 'Pokračovat',
  'upgrade_db_btn_text' => 'Aktualizovat',
  'upgrade_db_text_1' => 'Chystáte se aktualizovat databázi z verze',
  'upgrade_db_text_2' => 'na nejnovější verzi',
  'upgrade_db_text_3' => 'Klikněte na tlačítko Aktualizovat a počkejte až se aktualizace provede.',
  'upgrade_db_text_4' => 'Přejete-li si zálohovat databázi, zaškrtněte příslušné políčko.',
  'upgrade_db_text_5' => 'Zálohovat databázi před aktualizací? (<strong style="color:#FF0000;">Silně doporučujeme!</strong>)',
  'upgrade_db_title' => 'Databáze aktualizována',
  'upgrade_failed' => 'Aktualizace selhala',
  'upgrade_manual' => 'Manuální aktualizace',
  'upgrade_status' => 'Průběh aktualizace',
  'upgrade_text_1' => 'Následující instrukce popisují, jak manuálně aktualizovat Váš systém Ushahidi',
  'upgrade_text_2' => 'en_US: <strong>Krok 1:</strong> Stáhněte si poslední sestavení Ushahidi na stránkách <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
  'upgrade_text_3' => '<strong>Krok 2:</strong> Vyberte si mód, v jakém se připojíte k Vašemu webovému serveru (telnet, ftp, ssh) a nahraďte obsah složek soubory z nejnovějšího sestavení. <strong>Všechny KROMĚ:</strong>',
  'upgrade_text_4' => '<strong>Krok 4:</strong> Klikněte na tlačítko <strong>"Pokračovat"</strong> pro aktualizaci nezbytných tabulek.',
  'upgrade_text_5' => 'Pro automatickou aktualizaci klikněte na tlačítko níže',
  'upgrading' => 'Aktualizuji',
);

