<?php
	$lang = array(
	'approved' => 'מאושר',
	'categories' => 'קטגויות',
	'category_impact' => 'Category Impact',
	'category_impact_description' => 'בתרשים זה מוצגת כמות הדיווחים לכל קטגוריה לאורך הזמן. יש לגלול משמאל לימין כדי לראות תצוגה השוואתית של הקטגוריות השונות. יש להעביר את הסמן מעל הגרף לפרטים נוספים.',
	'choose_date_range' => 'בחירת טווח תאריכים',
	'countries' => 'מדינות',
	'country' => 'מדינה',
	'country_breakdown' => 'Country Breakdown',
	'description' => 'זהו אזור הסטטיסטיקה. ניתן להתרשם באמצעות הקישורים לתתי הקטגוריות למעלה',
	'error' => 'שגיאה',
	'glossary' => 'מילון מונחים',
	'hit_summary' => 'Hit Summary',
	'legend' => 'מקרא',
	'pageviews' => 'צפיות',
	'pageviews_description' => 'המספר הכולל של דפים שנצפו על ידי המבקרים באתר',
	'reports' => 'דיווחים',
	'reports_categories' => 'קטגוריות הדיווחים',
	'reports_statistics' => 'סטטיסטיקת הדיווחים',
	'reports_status' => 'מצב הדיווחים',
	'report_punchcard' => 'Report Punchcard',
	'report_stats' => 'Report Stats',
	'stats_not_setup' => 'Stats Not Set Up',
	'time_range_1' => 'חודש אחד',
	'time_range_2' => 'שלושה חודשים',
	'time_range_3' => 'חצי שנה',
	'time_range_all' => 'הכל',
	'unapproved' => 'לא מאושר',
	'unique_visitors' => 'מבקרים ייחודיים',
	'unique_visitors_description' => 'The number of individuals coming to your deployment; Unique Visitors are determined using cookies. In the case that a visitor does not have cookies enabled, they will be identified using a simple heuristic taking into account IP address, resolution, browser, plugins, OS, etc',
	'unverified' => 'לא מאומת',
	'verified' => 'מאומת',
	'visitor_summary' => 'Visitor Summary',
	'visits' => 'ביקורים',
	'visits_description' => 'ביקור מתאר מבקר ייחודי שנכנס לאתר לאחר יותר מ30 דקות מאז הפעם האחרונה בה צפה בדף',
	);
?>
