<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-19 23:22+0000
// PO revision date:  2012-08-19 23:01+0000
$lang = array(
	'friday' => array(
		'abbv' => 'Sex',
		'full' => 'Sexta',
	) ,
	'monday' => array(
		'abbv' => 'Seg',
		'full' => 'Segunda',
	) ,
	'saturday' => array(
		'abbv' => 'Sáb',
		'full' => 'Sábado',
	) ,
	'sunday' => array(
		'abbv' => 'Dom',
		'full' => 'Domingo',
	) ,
	'thursday' => array(
		'abbv' => 'Qui',
		'full' => 'Quinta',
	) ,
	'tuesday' => array(
		'abbv' => 'Ter',
		'full' => 'Terça',
	) ,
	'wednesday' => array(
		'abbv' => 'Qua',
		'full' => 'Quarta',
	) ,
);
