<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-21 20:53+0000
$lang = array(
	'reports_view' => 'Ver Relatórios.',
	'reports_edit' => 'Criar/Editar/Excluir Relatórios',
	'reports_approve' => 'Aprovar Relatórios',
	'reports_verify' => 'Verificar Relatórios',
	'reports_comments' => 'Gerenciar Relatório de Comentários',
	'reports_download' => 'Download Relatórios',
	'reports_upload' => 'Upload Relatórios',
	'messages' => 'Gerenciar Mensagens',
	'messages_reporters' => 'Gerenciar Relatórios de Mensagens',
	'stats' => 'Ver estatísticas',
	'settings' => 'Modificar configurações',
	'manage' => 'Gerenciar Painel',
	'users' => 'Gerenciar Usuários',
	'manage_roles' => 'Gerenciar Funções',
	'checkin' => 'Permitir checkin',
	'checkin_admin' => 'Gerenciar checkins',
	'admin_ui' => 'Acesse UI de administração',
	'member_ui' => 'Acesse UI de membros',
);
