<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-01-17 00:38+0000
$lang = array(
	'reports_view' => 'Ver Relatos',
	'reports_edit' => 'Criar/Editar/Excluir Relatos',
	'reports_approve' => 'Aprovar Relatos',
	'reports_verify' => 'Verificar Relatos',
	'reports_comments' => 'Gerenciar Comentários dos Relatos',
	'reports_download' => 'Descarregar Relatos',
	'reports_upload' => 'Carregar Relatos',
	'messages' => 'Gerenciar Mensagens',
	'messages_reporters' => 'Gerenciar Relatores de Mensagens',
	'stats' => 'Ver estatísticas',
	'settings' => 'Modificar configurações',
	'manage' => 'Gerenciar Painel',
	'users' => 'Gerenciar Usuários',
	'manage_roles' => 'Gerenciar Funções',
	'checkin' => 'Permitir checkin',
	'checkin_admin' => 'Gerenciar checkins',
	'admin_ui' => 'Acesse UI de administração',
	'member_ui' => 'Acesse UI de membros',
);
