<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-21 20:20+0000
$lang = array(
	'comments_form_error' => 'erro!',
	'country_name' => array(
		'single_country' => 'Essa implantação se estende dentro de um único país. Por favor, verifique se o local está dentro do referido país %s.',
	) ,
	'custom_field' => array(
		'values' => 'Digite dados válidos para um dos items de seu formulário personalizado.',
	) ,
	'data_include' => array(
		'between' => 'Selecione um item válido para incluir no download.',
		'numeric' => 'Selecione um item válido para incluir no download.',
	) ,
	'data_active' => array(
		'between' => 'Por favor, selecione "Relatórios Aguardando Aprovação" ou "Relatórios aprovados" ou ambos.',
		'numeric' => 'Por favor, selecione "Relatórios Aguardando Aprovação" ou "Relatórios aprovados" ou ambos.',
		'required' => 'Por favor, selecione "Relatórios Aguardando Aprovação" ou "Relatórios aprovados" ou ambos.',
	) ,
	'data_verified' => array(
		'between' => 'Por favor, selecione "Relatórios Aguardando Verificação" ou "Relatórios verificados" ou ambos.',
		'numeric' => 'Por favor, selecione "Relatórios Aguardando Verificação" ou "Relatórios verificados" ou ambos.',
		'required' => 'Por favor, selecione "Relatórios Aguardando Verificação" ou "Relatórios verificados" ou ambos.',
	) ,
	'data_point' => array(
		'between' => 'Selecione um tipo válido de relato para baixar.',
		'numeric' => 'Selecione um tipo válido de relato para baixar.',
		'required' => 'Selecione um tipo válido de relato para baixar.',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'O campo da data inicial parece não conter uma data válida.',
		'range' => 'Digite uma data inicial válida, não pode ser posterior a data de hoje.',
	) ,
	'incident_active' => array(
		'between' => 'Forneça dados válidos para o campo aprove esse relato.',
		'required' => 'Forneça dados válidos para o campo aprove esse relato.',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'O campo am/pm parece não conter dados válidos.',
	) ,
	'incident_category' => array(
		'numeric' => 'O campo categoria parece não conter uma categoria válida.',
		'required' => 'É necessário preencher o campo categoria.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'O campo data parece não conter uma data válida.',
		'date_mmddyyyy' => 'O campo data parece não conter uma data válida.',
		'required' => 'É necessário preencher o campo data.',
	) ,
	'incident_description' => array(
		'required' => 'É necessário preencher o campo descrição.',
	) ,
	'incident_hour' => array(
		'between' => 'O campo horário parece não conter uma hora válida.',
		'required' => 'É necessário preencher o campo horário.',
	) ,
	'incident_information' => array(
		'alpha' => 'Forneça dados válidos para o campo probabilidade da informação.',
		'length' => 'Forneça dados válidos para o campo probabilidade da informação.',
	) ,
	'incident_minute' => array(
		'between' => 'O campo horário parece não conter uma hora válida.',
		'required' => 'É necessário preencher o campo horário.',
	) ,
	'incident_news' => array(
		'url' => 'O link da fonte de notícias parece não conter uma URL válida.',
	) ,
	'incident_photo' => array(
		'size' => 'Certifique-se de que o tamanho das fotos enviadas está limitado a 2MB.',
		'type' => 'O campo de envio de fotos parece não conter uma imagem válida. Os únicos formatos aceitos são .JPG, .PNG e .GIF.',
		'valid' => 'O campo de envio de fotos parece não conter um arquivo válido.',
	) ,
	'incident_source' => array(
		'alpha' => 'Forneça dados válidos para o campo confiabilidade da fonte.',
		'length' => 'Forneça dados válidos para o campo confiabilidade da fonte.',
	) ,
	'incident_title' => array(
		'length' => 'O campo título deve ter pelo menos 3 e no máximo 200 caracteres.',
		'required' => 'É necessário preencher o campo título.',
		'csrf' => 'Possível ataque CSRF. Será que você realmente quer criar/editar um relatório?',
	) ,
	'incident_verified' => array(
		'between' => 'Forneça dados válidos para o campo verificar esse relato.',
		'required' => 'Forneça dados válidos para o campo verificar esse relato.',
	) ,
	'incident_video' => array(
		'url' => 'O link do vídeo parece não conter uma URL válida.',
	) ,
	'latitude' => array(
		'between' => 'O campo latitude parece não conter uma latitude válida.',
		'required' => 'É necessário preencher o campo latitude. Clique no mapa para apontar um local.',
	) ,
	'locale' => array(
		'alpha_dash' => 'O campo locale apresenta um valor incorreto. ',
		'exists' => 'Esse relato já tem uma tradução nesse idioma.',
		'length' => 'O campo locale apresenta um valor incorreto. ',
		'locale' => 'O relato original e a tradução apresentam o mesmo locale (idioma).',
		'required' => 'É necessário fornecer o locale.',
	) ,
	'location_name' => array(
		'length' => 'O nome do local deve ter pelo menos 3 e no máximo 200 caracteres.',
		'required' => 'É necessário preencher o campo local.',
	) ,
	'longitude' => array(
		'between' => 'O campo longitude parece não conter uma longitude válida.',
		'required' => 'É necessário preencher o campo longitude. Clique no mapa para apontar um local.',
	) ,
	'person_email' => array(
		'email' => 'O campo do email parece não conter um endereço de email válido.',
		'length' => 'O campo de email deve ter pelo menos 4 e no máximo 64 caracteres.',
	) ,
	'person_first' => array(
		'length' => 'O nome deve ter pelo menos 3 e no máximo 100 caracteres.',
	) ,
	'person_last' => array(
		'length' => 'O sobrenome deve ter pelo menos 3 e no máximo 100 caracteres.',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'O campo da data final parece não conter uma data válida.',
		'range' => 'Digite uma data inicial válida, não pode ser posterior a data de hoje.',
		'range_greater' => 'A data inicial não pode ter posterior à data final.',
	) ,
);
