<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-21 20:42+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Por favor, verifique se checou um item',
		'numeric' => 'Por favor, verifique se checou um item',
		'categories_required' => 'Relatórios devem ser categorizadas, antes de poderem ser aprovados',
	) ,
	'action' => array(
		'permission' => 'Você não tem permissão para executar esta ação',
	) ,
);
