<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-13 12:05+0000
// PO revision date:  2012-07-12 21:49+0000

$lang = array (
  'description' => 
  array (
    'length' => 'O campo descrição deve ter pelo menos 3 e no máximo 100 caracteres.',
    'required' => 'É necessário preencher o campo descrição.',
  ),
  'name' => 
  array (
    'alpha_numeric' => 'O campo nome deve conter apenas letras e números.',
    'length' => 'O campo nome deve ter pelo menos 2 e no máximo 30 caracteres.',
    'nomodify' => 'O perfil de SuperAdmin não pode ser modificado.',
    'required' => 'O campo nome precisa ser preenchido.',
  ),
);

