<?php
	$lang = array(
	'profile_email' => 'Seu e-mail',
	'profile_name' => 'Seu nome completo',
	'profile_notify' => 'Ao clicar em SIM, você receberá alertas via email sempre que um novo relato ou comentário for enviado ao seu site.',
	'profile_password' => 'Sua senha. Deixe esse campo vazio se quiser manter a sua senha atual.',
	'profile_username' => 'Não é possível mudar o nome de usuário.',
	'settings_alert_email' => 'É o endereço de email que será usado para o envio de alertas.',
	'settings_allow_clustering' => 'Permite que relatos parecidos sejam agrupados em um único ponto no site.',
	'settings_allow_comments' => 'Permite que usuários deixem comentários em relatos no site principal.',
	'settings_allow_feed' => 'Permite que feeds de RSS sejam exibidos no site principal.',
	'settings_allow_reports' => 'Permite que usuários enviem informações por meio de um formulário online.',
	'settings_api_default_record_limit' => 'Quantidade padrão de dados a serem buscados por solicitação API.',
	'settings_api_max_record_limit' => 'Quantidade máxima de dados a serem buscados por solicitação API.',
	'settings_api_max_requests_per_ip' => 'Quantidade máxima de dados a serem solicitados da API por endereço de IP.',
	'settings_default_location' => 'Esse é o país onde o site está sendo usado.',
	'settings_display_contact' => 'Liga ou desliga a seção de contato no site principal.',
	'settings_display_howtohelp' => 'Liga ou desliga a seção como ajudar no site principal.',
	'settings_display_items_per_page' => 'Quantidade de relatos exibidos por página no site principal.',
	'settings_display_items_per_page_admin' => 'Quantidade de relatos exibidos por página no painel de controle.',
	'settings_flsms_text_1' => 'Números de telefones por meio dos quais as mensagens são recebidas.',
	'settings_locale' => 'Define o idioma que será usado no site.',
	'settings_map_provider' => 'Define qual mapa será usado no site.',
	'settings_server_ssl_support' => 'É necessário para aumentar a segurança da conexão.',
	'settings_server_type' => 'É necessário para receber emails do servidor.',
	'settings_server_username' => 'É o email que recebe relatos.',
	'settings_site_copyright_statement' => 'É uma boa ideia definir o copyright do seu trabalho. Para obter ajudar para determinar a melhor licença para o seuc caso, acesse http://creativecommons.org/choose/.',
	'settings_site_email' => 'É o email que receberá relatos e mensagens enviadas por meio do formulário de contato.',
	'settings_site_message' => 'Esse texto aparecerá acima do mapa, na homepage. É útil para prover informações importantes a visitantes do site.',
	'settings_site_name' => 'Trata-se do nome do site, e aparecerá no topo do site principal.',
	'settings_site_tagline' => 'Em poucas palavras, explique o que o site é.',
	'settings_twitter_configuration' => 'Defina a hashtag que será usada no twitter',
	);
?>
