<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-02-23 06:25+0000
// PO revision date:  2014-02-22 22:18+0000
$lang = array(
	'allow_stat_sharing' => array(
		'required' => 'El campo compartir estadísticas es obligatorio',
	) ,
	'cleanurl' => array(
		'enable_clean_url' => 'Permitir URLs limpias',
		'title' => 'URLs limpias',
	) ,
	'configure_map' => 'Configurar mapa',
	'default_map_all' => array(
		'required' => 'El campo color es obligatorio.',
	) ,
	'facebook' => array(
		'app_id' => 'Facebook App ID',
	) ,
	'https' => array(
		'enable_https' => 'Habilitar HTTPS',
		'title' => 'HTTPS',
	) ,
	'map_provider' => array(
		'choose' => 'Seleccionar proveedor de mapas',
		'name' => 'Proveedor de Mapas',
	) ,
	'map_settings' => 'Configuración del Mapa',
	'site' => array(
		'email_alerts' => 'Dirección de correo para alertas',
		'email_site' => 'Dirección de correo electrónico del sitio',
		'language' => 'Idioma del sitio',
		'message' => 'Mensaje del sitio',
		'name' => 'Nombre del Sitio',
	) ,
);
