<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-02-23 06:25+0000
// PO revision date:  2014-02-22 22:29+0000
$lang = array(
	'approved' => 'aprobado',
	'categories' => 'Categorias',
	'countries' => 'Países',
	'country' => 'País ',
	'error' => 'Error',
	'glossary' => 'Glosario',
	'reports' => 'Reportes',
	'reports_categories' => 'Categorías de reportes',
	'reports_statistics' => 'Estadísticas de reportes',
	'reports_status' => 'Estatus de reportes',
	'report_stats' => 'Estadística del reporte',
	'time_range_1' => '1 mes',
	'time_range_2' => '3 meses',
	'time_range_3' => '6 meses',
	'time_range_all' => 'Todo',
	'unapproved' => 'No aprobado',
	'unverified' => 'No verificado',
	'verified' => 'Verificado',
	'visits' => 'Visitas',
);
