<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-02-23 06:25+0000
// PO revision date:  2014-02-22 22:33+0000
$lang = array(
	'upgrade_available' => 'Actualizaciones disponibles',
);
