<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-05 00:04+0000
// PO revision date:  2012-07-12 21:23+0000

$lang = array (
  'alert_email' => 
  array (
    'email' => 'The Email field does not appear to contain a valid email address?',
    'email_check' => 'That Email address has already been registered to receive alerts for that location',
    'length' => 'The Email field must be at least 4 and no more 64 characters long.',
    'required' => 'The Email field is required if the checkbox is checked.',
  ),
  'alert_lat' => 
  array (
    'between' => 'You have not selected a valid location on the map.',
    'required' => 'You have not selected a valid location on the map.',
  ),
  'alert_lon' => 
  array (
    'between' => 'You have not selected a valid location on the map.',
    'required' => 'You have not selected a valid location on the map.',
  ),
  'alert_mobile' => 
  array (
    'length' => 'The Mobile Phone field does not seem to contain the right amount of digits.',
    'mobile_check' => 'That Mobile Phone Number has already been registered to receive alerts for that location',
    'numeric' => 'The Mobile Phone field does not appear to contain a valid phone. Please input numbers only including Country Code.',
    'one_required' => 'You must enter either your Mobile Phone Number or your Email Address.',
    'required' => 'The Mobile Phone field is required if the checkbox is checked.',
  ),
);

