<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-30 12:04+0000
// PO revision date:  2012-07-12 21:26+0000

$lang = array (
  'category_color' => 
  array (
    'length' => 'The color field must be 6 characters long.',
    'required' => 'The color field is required.',
  ),
  'category_description' => 
  array (
    'required' => 'The description field is required.',
  ),
  'category_title' => 
  array (
    'length' => 'The title field must be at least 3 and no more 80 characters long.',
    'required' => 'The title field is required.',
  ),
);

