<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-15 04:42+0000
// PO revision date:  2012-08-15 04:39+0000
$lang = array(
	'feed_name' => array(
		'length' => 'The feed name field must be at least 3 and no more 
				70 characters long.',
	) ,
	'feed_url' => array(
		'url' => 'Please enter a valid URL. Eg. http://www.ushahidi.com',
	) ,
);
