<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-09 18:05+0000
// PO revision date:  2012-07-12 21:35+0000

$lang = array (
  'feed_name' => 
  array (
    'length' => 'The feed name field must be at least 3 and no more 
				70 characters long.',
    'required' => 'Please enter the name of the feed.',
  ),
  'feed_url' => 
  array (
    'required' => 'Please enter feed\'s URL.',
    'url' => 'Please enter a valid URL. Eg. http://www.ushahidi.com',
  ),
);

