<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-14 04:09+0000
// PO revision date:  2012-07-12 21:55+0000

$lang = array (
  'admin_role' => 'Admin',
  'comments' => 'Comments',
  'confirm_msg' => 'The User Has Been',
  'dashboard' => 'Dashboard',
  'delete_action' => 'Delete',
  'edit_action' => 'Edit',
  'error_msg' => 'Error',
  'faqs' => 'FAQ\'s',
  'feedback' => 'Feedback',
  'forum' => 'Forum',
  'get_help' => 'Get Help',
  'header_actions' => 'Actions',
  'header_add_edit' => 'Add/Edit',
  'header_email' => 'Email',
  'header_manage_users' => 'Manage Users',
  'header_role' => 'Role',
  'header_user' => 'User',
  'label_email' => 'Email Address:',
  'label_full_name' => 'Full Name:',
  'label_password' => 'Password:',
  'label_role' => 'Role:',
  'label_username' => 'Username:',
  'login_role' => 'Moderator',
  'logout' => 'Logout',
  'manage' => 'Manage',
  'messages' => 'Messages',
  'my_profile' => 'My Profile',
  'notification' => 'Notification',
  'no_result_display_msg' => 'No Results To Display!',
  'reports' => 'Reports',
  'settings' => 'Settings',
  'stats' => 'Stats',
  'superadmin_role' => 'Super Admin',
  'title' => 'Manage Users',
  'update_link' => ' Click here to upgrade now',
  'users' => 'Users',
  'ushahidi' => 'Ushahidi',
  'version' => 'Moderator',
  'version_available' => ' is available for upgrade.',
  'view_site' => 'View Site',
  'welcome' => 'Welcome, ',
  'wiki' => 'Wiki',
);

