<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-14 18:05+0000
// PO revision date:  2012-07-12 21:24+0000

$lang = array (
  'email' => 
  array (
    'email' => 'Il campo email non contiene un indirizzo email valido.',
    'exists' => 'Siamo spiacenti, esiste uno user account con questo indirizzo email.',
    'length' => 'Il campo email deve essere lungo almeno 3 caratteri e non più di 64.',
    'required' => 'Il campo email è richiesto.',
  ),
  'name' => 
  array (
    'length' => 'Il campo nome deve essere lungo almeno 3 caratteri e non più di 100.',
    'required' => 'Il campo nome ',
    'standard_text' => 'Il campo username contiene carattere non permessi.',
  ),
  'password' => 
  array (
    'length' => 'Il campo password deve essere lungo alemno 5 caratteri e non più di 16.',
    'login error' => 'Per favore controlla che la password inserita sia corretta.',
    'matches' => 'Per favore inserisci la stessa password nei due campi password.',
    'required' => 'Il campo password è richiesto.',
  ),
  'password_confirm' => 
  array (
    'matches' => 'Il campo password di conferma deve essere uguale al campo password.',
  ),
  'resetemail' => 
  array (
    'email' => 'Il campo email non contiene un indirizzo email valido.',
    'invalid' => 'Spiacenti, non abbiamo il tuo indirizzo email.',
    'required' => 'Il campo email è richiesto.',
  ),
  'roles' => 
  array (
    'alpha_numeric' => 'Formato del ruolo non valido.',
    'length' => 'Il campo ruolo deve essere lungo almeno 5 caratteri e non più di 30.',
    'required' => 'Devi definire almeno un ruolo.',
    'values' => 'Seleziona il ruolo ADMIN or USER.',
  ),
  'username' => 
  array (
    'admin' => 'Il ruolo admin dell\'utente non può essere modificato.',
    'exists' => 'Spiacenti, questo username è già in uso.',
    'length' => 'Il campo username deve essere lungo almeno 2 caratteri e non più di 30.',
    'login error' => 'Per favore controlla che lo username inserito sia corretto.',
    'required' => 'Il campo username è richiesto.',
    'superadmin' => 'Il ruolo super admin non può essere modificato.',
  ),
);

