<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-11 15:42+0000
$lang = array(
	'category_color' => array(
		'length' => 'Il campo colore deve contenere 6 caratteri.',
		'required' => 'Il campo colore ',
	) ,
	'category_description' => array(
		'required' => 'Il campo descrizione ',
	) ,
	'category_image' => array(
		'size' => 'Assicurati che il peso delle immagini caricate non sia superiore a 50KB.',
		'type' => 'Il campo immagine non contiene un\'immagine valida. I soli formati accettati sono .JPG, .PNG e .GIF.',
		'valid' => 'Il campo immagine non contiene un file valido',
	) ,
	'category_title' => array(
		'length' => 'Il campo titolo deve essere lungo almeno 3 caratteri non pi',
		'required' => 'Il campo titolo ',
	) ,
	'parent_id' => array(
		'already_parent' => 'Non puoi far diventare una sottocategoria una categoria che già contiene delle sottocategorie',
		'exists' => 'La categoria madre non esiste.',
		'numeric' => 'Il campo categoria madre deve essere numerico.',
		'parent_trusted' => 'La categoria padre non può essere una categoria speciale',
		'required' => 'Il campo categoria madre ',
		'same' => 'La categoria e la categoria madre non possono essere uguali.',
		'special' => 'Le categorie speciali non posso diventare sottocategorie',
	) ,
);
