<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-11 15:40+0000
$lang = array(
	'captcha' => array(
		'default' => 'Inserisci un codice di sicurezza valido',
		'valid' => 'Inserire un codice di sicurezza valido',
		'required' => 'Inserisci il codice di sicurezza',
	) ,
	'contact_email' => array(
		'email' => 'Il campo Email non contiene un indirizzo email valido?',
		'length' => 'Il campo Email deve essere lungo almeno 4 caratteri e non pi',
		'required' => 'Il campo Email ',
	) ,
	'contact_message' => array(
		'required' => 'Il campo Messaggio ',
	) ,
	'contact_name' => array(
		'length' => 'Il campo Nome deve essere lungo almeno 3 caratteri.',
		'required' => 'Il campo Nome ',
	) ,
	'contact_subject' => array(
		'length' => 'Il campo Oggetto deve essere lungo almeno 3 caratteri.',
		'required' => 'Il campo Oggetto ',
	) ,
	'email_send' => array(
		'failed' => 'Si è verificato un errore durante l\'invio del messaggio.',
	) ,
);
