<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 22:52+0000
$lang = array(
	'driver_implements' => 'Il %s driver per la %s library deve sviluppare la %s interface',
	'driver_not_found' => 'Il %s driver per la %s library non ',
	'errors_disabled' => 'Vai alla <a href="%s">home page</a> o <a href="%s">per riprovare</a>.',
	'generic_error' => 'Non ',
	'invalid_filetype' => 'Il tipo di file richiesto, .%s, non ',
	'invalid_method' => 'Metodo non valido %s called in %s',
	'invalid_property' => 'La %s propriet',
	'log_dir_unwritable' => 'La log directory non ',
	'model' => 'modello',
	'no_controller' => 'Ushahidi non ha potuto determinare un controller per elaborare questa richiesta: %s',
	'no_default_route' => 'Definisci una route di default in config/routes.php',
	'page_not_found' => 'La pagina richiesta, %s, non ',
	'report_bug' => '<a href="%s" id="show_bugs">Segnala questo problema a Ushahidi</a>',
	'resource_not_found' => 'La risorsa %s richiesta, %s, non ',
	'stats_footer' => 'Loaded in {execution_time} secondi, usando {memory_usage} della memoria. Generato da Ushahidi v%s.',
	'there_can_be_only_one' => 'E\' consentita solo un\'istanza di Ushahidi per pagina richiesta',
	'view' => 'vista',
	'view_set_filename' => 'Definisci il nome file della vista prima del calling render',
);
