<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-16 00:04+0000
// PO revision date:  2012-08-19 22:52+0000
$lang = array(
	'friday' => array(
		'abbv' => 'Ven',
		'full' => 'Venerdì',
	) ,
	'monday' => array(
		'abbv' => 'Lun',
		'full' => 'Lunedì',
	) ,
	'saturday' => array(
		'abbv' => 'Sab',
		'full' => 'Sabato',
	) ,
	'sunday' => array(
		'abbv' => 'Dom',
		'full' => 'Domenica',
	) ,
	'thursday' => array(
		'abbv' => 'Gio',
		'full' => 'Giovedì',
	) ,
	'tuesday' => array(
		'abbv' => 'Mar',
		'full' => 'Martedì',
	) ,
	'wednesday' => array(
		'abbv' => 'Mer',
		'full' => 'Mercoledì',
	) ,
);
