<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-17 06:40+0000
// PO revision date:  2012-08-15 04:39+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'Per favore inserisci un codice di controllo valido.',
		'required' => 'Per favore inserisci il codice ci controllo.',
	) ,
	'contact_email' => array(
		'email' => 'Il campo email contiene un valore che non è un indirizzo email valido.',
		'required' => 'Per favore inserisci un indirizzo email valido.',
	) ,
	'contact_message' => array(
		'required' => 'Il campo messaggio è obbligatorio.',
	) ,
	'contact_subject' => array(
		'length' => 'Il subject deve contenere almeno 3 caratteri.',
		'required' => 'Il campo subject è obbligatorio.',
	) ,
);
