<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-04 12:05+0000
// PO revision date:  2012-08-19 22:53+0000
$lang = array(
	'admin_footer' => 'Questo messaggio ',
	'admin_new_comment' => array(
		'message' => 'Un nuovo Commento ',
		'subject' => 'Nuovo Commento',
	) ,
	'admin_new_email' => array(
		'message' => 'Un Nuovo Messaggio Email ',
		'subject' => 'Nuovo Messaggio Email',
	) ,
	'admin_new_report' => array(
		'message' => 'Una nuova segnalazione ',
		'subject' => 'Nuova segnalazione',
	) ,
	'admin_new_sms' => array(
		'message' => 'Un nuovo Messaggio di Testo ',
		'subject' => 'Nuovo Messaggio di Testo',
	) ,
);
