<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-03 17:33+0000
$lang = array(
	'comments_form_error' => 'errore!',
	'custom_field' => array(
		'values' => 'Inserisci un valore valido per uno degli item del tuo custom form',
	) ,
	'data_include' => array(
		'between' => 'Seleziona un item valido da includere nel download',
		'numeric' => 'Seleziona un item valido da includere nel download',
	) ,
	'data_point' => array(
		'between' => 'Seleziona un tipo di segnalazione valido da scaricare',
		'numeric' => 'Seleziona un tipo di segnalazione valido da scaricare',
		'required' => 'Seleziona un tipo di segnalazione valido da scaricare',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'Il campo data DA contiene una data valida?',
		'range' => 'Inserisci una data DA valida. Non può essere successiva a oggi.',
	) ,
	'incident_active' => array(
		'between' => 'Inserisci un valore valido per Approva questa segnalazione',
		'required' => 'Inserisci un valore valido per Approva questa segnalazione',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'Il campo am/pm contiene un valore valido?',
	) ,
	'incident_category' => array(
		'numeric' => 'Il campo categoria contiene una categoria valida?',
		'required' => 'Il campo categoria è richiesto.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'Il campo data contiene una data valida?',
		'date_mmddyyyy' => 'Il campo data contiene una data valida?',
		'required' => 'Il campo data è richiesto.',
	) ,
	'incident_description' => array(
		'required' => 'Il campo descrizione è richiesto.',
	) ,
	'incident_hour' => array(
		'between' => 'Il campo ora contiene un\'ora valida?',
		'required' => 'Il campo ora è richiesto.',
	) ,
	'incident_information' => array(
		'alpha' => 'Inserisci un valore valido per Grado di Probabilità',
		'length' => 'Inserisci un valore valido per Grado di Probabilità',
	) ,
	'incident_minute' => array(
		'between' => 'Il campo minuto contiene un valore valido?',
		'required' => 'Il campo minuto è richiesto.',
	) ,
	'incident_news' => array(
		'url' => 'Il campo link della fonte news contiene una URL valida?',
	) ,
	'incident_photo' => array(
		'size' => 'I file di immagini non devono superare i 2MB.',
		'type' => 'Il campo Upload Photos non contiene un\'immagine valida. I formati consentiti sono .JPG, .PNG e .GIF.',
		'valid' => 'Il campo Upload Photos non contiene un file valido',
	) ,
	'incident_source' => array(
		'alpha' => 'Inserisci un valore valido per l\'Affidabilità della Fonte',
		'length' => 'Inserisci un valore valido per Affidabilità della Fonte',
	) ,
	'incident_title' => array(
		'length' => 'Il campo titolo deve essere lungo almeno 3 caratteri e non più di 200.',
		'required' => 'Il campo titolo è richiesto.',
	) ,
	'incident_verified' => array(
		'between' => 'Inserisci un valore valido per Verifica Questa Segnalazione',
		'required' => 'Inserisci un valore valido per Verifica Questa Segnalazione',
	) ,
	'incident_video' => array(
		'url' => 'Il campo video link contiene una URL valida?',
	) ,
	'latitude' => array(
		'between' => 'Il campo latitudine contiene una latitudine valida?',
		'required' => 'Il campo latitudine è richiesto. Clicca sulla mappa per indicare un luogo.',
	) ,
	'locale' => array(
		'alpha_dash' => 'Il campo luogo ha un valore non corretto. ',
		'exists' => 'Questa segnalazione ha già una traduzione per questa lingua.',
		'length' => 'Il campo luogo ha un valore non corretto. ',
		'locale' => 'La segnalazione originale e la traduzione sono nella stessa lingua',
		'required' => 'Il luogo è richiesto.',
	) ,
	'location_name' => array(
		'length' => 'Il campo Nome Luogo deve essere lungo almeno 3 caratteri e non più di 200.',
		'required' => 'Il campo Nome Luogo è richiesto.',
	) ,
	'longitude' => array(
		'between' => 'Il campo longitudine contiene una longitudine valida?',
		'required' => 'Il campo longitudine è richiesto. Clicca sulla mappa per indicare un luogo.',
	) ,
	'person_email' => array(
		'email' => 'Il campo email field contiene un indirizzo email valido?',
		'length' => 'Il campo email deve essere lungo almeno 4 caratteri e non pi',
	) ,
	'person_first' => array(
		'length' => 'Il campo Nome deve essere lungo almeno 3 caratteri e non più di 100.',
	) ,
	'person_last' => array(
		'length' => 'Il campo Cognome deve essere lungo almeno 3 caratteri e non più di 100.',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'Il campo data A contiene una data valida?',
		'range' => 'Inserisci una data A valida. Non può essere successivo a oggi.',
		'range_greater' => 'La data DA non può essere successivo alla data indicata nel campo A.',
	) ,
);
