<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-11 15:34+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Verifica di aver selezionato un elemento',
		'numeric' => 'Verifica di aver selezionato un elemento',
		'categories_required' => 'I report devono appartenere ad una categoria prima di essere approvati',
	) ,
	'action' => array(
		'permission' => 'Non hai i permessi per eseguire questa operazione',
	) ,
);
