<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-11-16 06:10+0000
// PO revision date:  2012-11-10 17:00+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'Il campo autorizza commenti non sembra contenere un valore valido?',
		'required' => 'Il campo autorizza commenti è richiesto.',
	) ,
	'allow_feed' => array(
		'between' => 'The include feed field does not appear to contain a valid value?',
	) ,
	'allow_reports' => array(
		'between' => 'The allow reports field does not appear to contain a valid value?',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'The stat sharing field does not appear to contain a valid value?',
	) ,
	'api' => array(
		'default_record_limit' => 'Default no. of records to be fetched per API request',
		'maximum_record_limit' => 'Numero massimo di elementi da scaricare per ogni richiesta API',
		'maximum_requests_per_ip_address' => 'Numero massimo di richieste API per indirizzo IP',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'The Akismet field does not appear to contain a valid value?',
		'length' => 'The Akismet field does not appear to contain a valid value?',
	) ,
	'banner_image' => array(
		'default' => 'Si è verificato un errore durante l\'upload della tua immagine per la testata',
		'size' => 'Le dimensioni del tuo banner superano il limite massimo per l\'upload',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'Sembra che il tuo server non sia configurato per gestire le clean URLs. Dovrai modificare la configurazione del tuo server prima di abilitare le clean URL. Maggiori informazioni su come abilitare le clean URLs in questo forum <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">post</a>',
		'clean_url_enabled' => 'Questa opzione consente di accedere a Ushahidi con "clean" URLs. Senza "index.php" nella URL.',
		'enable_clean_url' => 'Abilita Clean URLs',
		'title' => 'Pulisci URL',
	) ,
	'configure_map' => 'Configura la Mappa',
	'default_location' => 'Luogo di default',
	'default_map_all' => array(
		'alpha_numeric' => 'The color feed field does not appear to contain a valid value?',
	) ,
	'default_map_view' => 'Vista Mappa di Default',
	'default_zoom_level' => 'Livello di default dello zoom',
	'download_city_list' => 'Recupera la citt',
	'email_host' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'email_port' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'email_servertype' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'facebook' => array(
		'app_id' => 'Facebook App ID',
		'app_secret' => 'Facebook App Secret',
	) ,
	'https' => array(
		'enable_https' => 'Abilita HTTPS',
		'https_disabled' => 'Questa opzione permette di accedere a Ushahidi di accedere in modalità non sicura; <strong>senza</strong> "https://" nel prefisso dell\'URL',
		'https_enabled' => 'Questa opzione permette di accedere a Ushahidi di accedere in modalità sicura; <strong>con</strong> "https://" nel prefisso dell\'URL',
		'title' => 'HTTPS',
	) ,
	'items_per_page' => array(
		'between' => 'The items per page (Frontend) field does not appear to contain a valid value?',
		'required' => 'Il campo elementi per pagina (Frontend) è obbligatorio',
	) ,
	'items_per_page_admin' => array(
		'between' => 'The items per page (Admin) field does not appear to contain a valid value?',
		'required' => 'Il campo elementi per pagina (Admin) è obbligatorio',
	) ,
	'map' => array(
		'default_location' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
		'zoom' => 'Livello di zoom',
	) ,
	'map_provider' => array(
		'choose' => 'Seleziona un Provider della mappa',
		'enter_api' => 'Digita la nuova API Key',
		'get_api' => 'Ottieni una API Key',
		'info' => 'Definire il fornitore della mappa - provider -  ',
		'name' => 'Provider Mappa',
	) ,
	'map_timeline' => 'Timeline mappa',
	'map_settings' => 'Setting Mappa',
	'multiple_countries' => 'Questa installazione di Ushahidi ',
	'select_default_location' => 'Seleziona un paese di default',
	'set_location' => 'Clicca e trascina la mappa per definire la tua esatta localizzazione',
	'site' => array(
		'allow_clustering' => 'Cluster delle segnalazioni sulla Mappa',
		'allow_comments' => 'Consenti agli Utenti di commentare le segnalazioni',
		'allow_feed' => 'Includere RSS News Feed sul Website',
		'allow_reports' => 'Consenti agli utenti di inviare Segnalazioni',
		'api_akismet' => 'Chiave Akismet',
		'cache_pages' => 'Pagine Cache',
		'cache_pages_lifetime' => 'Durata temporale delle Pagine Cache',
		'checkins' => 'Abilita Checkins',
		'copyright_statement' => 'Copyright del sito',
		'default_category_colors' => 'Colore di default per tutte le categorie',
		'default_category_icons' => 'Icona di default per tutte le categorie',
		'delete_banner_image' => 'Elimina immagine di testata',
		'delete_default_map_all_icon' => 'Elimina icona di default',
		'display_contact_page' => 'Mostra la Pagina Contatti',
		'display_howtohelp_page' => 'Mostra la pagina "Come aiutare"',
		'email_alerts' => 'Indirizzo Email per gli alert',
		'email_notice' => '<span>Per ricevere report via email, ti preghiamo di configurare le impostazioni del tuo account email.</span>',
		'email_site' => 'Indirizzo email del sito',
		'google_analytics_example' => 'Web Property ID - Formato: UA-XXXXX-XX',
		'items_per_page' => 'Items per Pagina - Front End',
		'items_per_page_admin' => 'Items Per Pagina  - Admin',
		'kismet_notice' => 'Prevenire spam nei commenti utilizzando <a href="http://akismet.com/" target="_blank">Akismet</a> da Automattic. <BR />Puoi ricevere una API key gratuita registrandoti un <a href="http://en.wordpress.com/api-keys/" target="_blank">account come utente WordPress.com</a>',
		'laconica_configuration' => 'Credenziali Laconica',
		'laconica_site' => 'Sito Laconica ',
		'language' => 'Lingua del Sito',
		'name' => 'Nome Sito',
		'share_site_stats' => 'Condividi le statistiche del Sito in API',
		'tagline' => 'Tagline Sito',
		'title' => 'Impostazioni Sito',
		'twitter_configuration' => 'Credenziali Twitter',
		'twitter_hashtags' => 'Hashtags - Separati da virgola ',
	) ,
	'site_email' => array(
		'email' => 'The site email field does not appear to contain a valid email address?',
	) ,
	'sms' => array(
		'clickatell_api' => 'Il tuo Clickatell API Number',
		'clickatell_check_balance' => 'Controlla il tuo credito Your Clickatell Credit Balance',
		'clickatell_password' => 'La tua Clickatell Password',
		'clickatell_text_1' => 'Iscriviti al servizio Clickatells <a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">cliccando qui</a>',
		'clickatell_text_2' => 'Inserisci le credenziali del tuo accesso Clickatell qui sotto',
		'clickatell_username' => 'Il tuo Clickatell User Name',
		'flsms_description' => 'FrontlineSMS ',
		'flsms_download' => 'Download Frontline SMS e installalo sul tuo computer',
		'flsms_instructions' => 'I Messaggi ricevuti con FrontlineSMS hub possono essere sincronizzati con Ushahidi. Istruzioni dettagliate sulla sincronizzazione si trovano <strong><a href="http://wiki.ushahididev.com/doku.php?id=how_to_use_ushahidi_alpha#how_to_setup_frontlinesms_to_sync_with_ushahidi" target="_blank">qui</a></strong>. Avrai bisogno della key e del link che trovi pi',
		'flsms_key' => 'La tua Ushahidi Sync Key',
		'flsms_synchronize' => 'Sync con Ushahidi',
		'flsms_text_1' => 'Inserisci il numero di telefono collegato a Frontline SMS nel campo',
		'flsms_text_2' => 'Inserisci nel campo qui sotto il numero senza nessun + o trattino',
		'option_1' => 'Optione 1: Usa Frontline SMS',
		'option_2' => 'Option 2: Usa un Global SMS Gateway',
		'title' => 'SMS Setup - Opzioni',
	) ,
	'sms_no1' => array(
		'length' => 'The phone 1 field does not appear to contain a valid value?',
	) ,
	'sms_no2' => array(
		'length' => 'The phone 2 field is too long',
	) ,
	'sms_no3' => array(
		'length' => 'The phone 3 field is too long',
	) ,
);
