<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-17 12:04+0000
// PO revision date:  2012-08-17 07:01+0000
$lang = array(
	'date' => 'Data di entrata',
	'date_added' => 'Data di creazione',
	'last_access' => 'Ultimo accesso',
	'sharing_color' => array(
		'length' => 'Il campo colore deve avere lunghezza di 6 caratteri.',
		'required' => 'Il campo colore è obbligatorio.',
	) ,
);
