<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-13 00:05+0000
// PO revision date:  2012-07-12 21:58+0000

$lang = array (
  'upgrade' => 
  array (
    'between' => 'Dati inseriti non validi. I valori ammessi sono solo 0 per NO e 1 per SI\'',
  ),
  'upgrade_continue_btn_text' => 'Continua',
  'upgrade_db_btn_text' => 'Aggiorna',
  'upgrade_db_title' => 'Aggiornamento del database di Ushahidi',
  'upgrade_failed' => 'La procedura di upgrade è stata interrotta.',
  'upgrade_status' => 'Stato dell\'aggiornamento di Ushahidi',
  'upgrade_text_1' => 'Le istruzioni qui sotto illustrano nel dettaglio come eseguire un aggiornamento manuale della tua istallazione di Ushahidi',
  'upgrade_text_2' => '<strong>Step 1:</strong> Scarica la versione più recente di Ushahidi da <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
  'upgrade_text_3' => '<strong>Step 2:</strong> A seconda del sistema operativo del tuo web server scegli la modalità e lo strumento più adatti (es.telnet, ftp, ssh) per effettuare login sul webserver e sostituisci i contenuti di tutte le cartelle con quelli della nuova versione. <strong>Tutti TRANNE:</strong>',
  'upgrade_text_4' => '<strong>Step 4:</strong> Clicca sul tasto<strong>"Continua"</strong> per aggiornare le tabelle necessarie.',
  'upgrade_text_5' => 'Per eseguire l\'aggiornamento automatico clicca il bottone qui sotto.',
  'upgrading' => 'Aggiornamento in corso',
);

