<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-22 06:17+0000
// PO revision date:  2013-05-21 08:50+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Email eremuak ez du baliozko email helbiderik',
		'email_check' => 'Email hori dagoeneko kokaleku horretako alertak jasotzeko erregistratua izan da.',
		'length' => 'Email eremuak ezin du 4 hizki baino gutxiago eta 64 baino gehiago eduki',
		'required' => 'email eremua beharrezkoa da kontrol-laukia hautatuta badago',
	) ,
	'alert_lat' => array(
		'between' => 'Ez duzu baliodun kokalekurik hautatu mapan',
		'required' => 'Ez duzu mapan baliozko kokalekurik aukeratu.',
	) ,
	'alert_lon' => array(
		'between' => 'Ez duzu mapan baliozko kokalekurik aukeratu.',
		'required' => 'Ez duzu mapan baliozko kokalekurik aukeratu.',
	) ,
	'alert_mobile' => array(
		'length' => 'Badirudi Sakelako telefonoa eremuak ez duela behar besteko digitu kopurua',
		'mobile_check' => 'Sakelako telefono zenbaki hori dagoeneko erregistratuta dago kokaleku horretako alertak jasotzeko',
		'numeric' => 'Sakelako telefonoa eremuak ez du baliozko telefonoa. Mesedez, idatzi Herrialdeko Kodea baino ez duten zenbakiak',
		'one_required' => 'Mugikor zenbakia edo Email helbidea sartzea beharrezkoa da.',
		'required' => 'Sakelako Telefonoa eremua beharrezkoa da kontrol-laukia hautatuta badago',
	) ,
	'alerts_subscribed' => 'Honako kategorietako alertetan harpidetu zara',
	'code_already_verified' => 'Kode hori aldez aurretik egiaztatu dute!',
	'confirm_request' => 'Alerta eskaera berresteko, mesedez, joan hona',
);
