<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-21 06:17+0000
// PO revision date:  2013-05-20 23:30+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Email eremuak ez du baliozko email helbiderik',
		'length' => 'Email eremuak ezin du 4 hizki baino gutxiago eta 64 baino gehiago eduki',
		'required' => 'email eremua beharrezkoa da kontrol-laukia hautatuta badago',
	) ,
	'alert_lat' => array(
		'between' => 'Ez duzu baliodun kokalekurik hautatu mapan',
		'required' => 'Ez duzu mapan baliozko kokalekurik aukeratu.',
	) ,
	'alert_lon' => array(
		'between' => 'Ez duzu mapan baliozko kokalekurik aukeratu.',
		'required' => 'Ez duzu mapan baliozko kokalekurik aukeratu.',
	) ,
);
