<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-21 06:17+0000
// PO revision date:  2013-05-20 22:08+0000
$lang = array(
	'captcha' => array(
		'required' => 'Sartu baliozko segurtasun kodea, mesedez',
	) ,
	'contact_email' => array(
		'email' => 'Email eremuak ez du baliozko email helbiderik',
		'length' => 'Email eremuak ezin du 4 hizki baino gutxiago eta 64 baino gehiago eduki',
		'required' => 'email eremua beharrezkoa da kontrol-laukia hautatuta badago',
	) ,
	'contact_message' => array(
		'required' => 'Mezu eremua beharrezkoa da',
	) ,
	'contact_name' => array(
		'required' => 'Izena eremua beharrezkoa da',
	) ,
	'email_send' => array(
		'failed' => 'Errore bat egon da zure mezua bidaltzean.',
	) ,
);
