<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-22 06:17+0000
// PO revision date:  2013-05-21 23:59+0000
$lang = array(
	'config' => 'konfigurazio fitxategia',
	'controller' => 'kontrolatzailea',
	'driver' => 'kontrolatzailea',
	'driver_implements' => '%s liburutegiarentzako %s kontrolatzaileak %s interfazea ezarri beharko luke.',
	'driver_not_found' => '%s liburutegiarentzako %s kontrolatzailea ezin izan da aurkitu.',
	'errors_disabled' => '<a href="%s">hasiera orrira</a> joan zintezke edo <a href="%s">berriz saiatu</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'Ezin da eskaera bete',
	'helper' => 'laguntzailea',
	'invalid_filetype' => 'Zure ikusteko konfigurazioak ez du %s, eskatutako fitxategi mota onartzen',
	'invalid_method' => '%s baliogabeko methodoak %s-ra deitu du',
	'invalid_property' => '%s propietatea ez da existitzen %s klasean',
	'library' => 'liburutegi',
	'log_dir_unwritable' => '"log" direktorioa ez da idazgarria. %s',
	'model' => 'eredua',
	'no_default_route' => 'Mesedez zehaztu berezko ruta config/routes.php fitxategian',
	'view' => 'ikusi',
);
