<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-22 06:17+0000
// PO revision date:  2013-05-21 13:33+0000
$lang = array(
	'base_path' => 'Basearen bidea',
	'database' => 'Datu basea',
	'database_host' => 'Datu Basearen ostalaria',
	'database_host_description' => 'Ushahidi zure ordenagailuan erabiltzen ari bazara, "localhost" bezala agertuko da. Web-zerbitzari batetik ari bazara, zure ostalariaren informazioa lortuko duzu zure web hornitzailearengandik.',
	'database_name' => 'Datu Basearen izena',
	'database_name_description' => 'Ushaidik erabiliko duen Datu Basearen izena',
	'db_information_link' => 'Info gehiagorako, mesedez ikustatu ezazu <a href="http://wiki.ushahidi.com/doku.php?id=a_brief_word_on_databases" target="_blank">artikulu hau</a> datu baseak zehaztasun handiagorekin jorratzen dituen wikian.',
	'default_language' => 'Lehenetsitako hizkuntza(Lokala)',
	'disable' => 'Desgaitua',
	'enable' => 'Gaitua',
	'finished' => 'Amaiturik',
	'general' => 'Orokorra',
	'go_back' => 'Atzera joan',
	'index' => array(
		'advanced' => 'INSTALAZIO AURRERATUA',
		'basic_installation' => 'OINARRIZKO INSTALAZIOA',
	) ,
	'mail_server' => 'Postaren zerbitzaria',
	'mail_server_host_description' => 'Adibideak: mail.yourwebsite.com, imap.gmail.com, pop.gmail.com',
	'mail_server_password' => 'Postaren zerbitzariaren pasahitza',
	'mail_server_password_description' => 'Zure postan normalean sartzeko erabilitako pasahitza',
);
