<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-22 06:17+0000
// PO revision date:  2013-05-21 21:08+0000
$lang = array(
	'comments_form_error' => 'Akatsa!',
	'country_name' => array(
		'single_country' => 'Hedaketa hau herrialde baterako bakarrik balio du. Ziurtatu berri emandako lekua herrialde %s barnean dagoela.',
	) ,
	'custom_field' => array(
		'values' => 'Sartu baliozkoa den balorea zure ohiturazkoa diren gaiei mesedez.',
		'required' => '"%s" eremua betetzea beharrezkoa da.',
	) ,
	'data_include' => array(
		'between' => 'Aukeratu ezazu baliozkoa den gai bat deskargan biltzeko.',
		'numeric' => 'Aukeratu ezazu baliozkoa den gai bat deskargan biltzeko.',
	) ,
	'incident_date' => array(
		'required' => 'Dataren eremua betetzea beharrezkoa da.',
	) ,
	'incident_hour' => array(
		'required' => 'Orduaren eremua betetzea beharrezkoa da.',
	) ,
	'incident_minute' => array(
		'required' => 'Minutuaren eremua betetzea beharrezkoa da.',
	) ,
	'incident_title' => array(
		'required' => '\'\'Iruzkinaren izenburua\'\'  eremua betetzea beharrezkoa da.',
	) ,
);
