<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-22 06:17+0000
// PO revision date:  2013-05-22 00:02+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'Email eremuak ez du baliozko helbiderik.',
		'required' => 'Mezu eremua beharrezkoa da.',
	) ,
	'allow_feed' => array(
		'between' => 'Badirudi feed-a sartu eremuan balio egokirik ez duela.',
		'required' => 'Feed-a sartu eremua beharrezkoa da.',
	) ,
	'allow_alerts' => array(
		'between' => 'Badirudi abisuak baimendu eremuak ez duela balio egokirik.',
		'required' => 'Abisuak baimendu eremua beharrezkoa da.',
	) ,
	'allow_reports' => array(
		'between' => 'Badirudi txostenak baimendu eremuak balio egokirik ez duela',
		'required' => 'Txostenak baimendu eremua beharrezkoa da.',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'Badirudi \'estatistikak elkarbanatu\' eremuak ez du balio egokirik.',
		'required' => 'Estatistitak elkarbanatu eremua nahitaezkoa da.',
	) ,
	'cache_pages' => array(
		'between' => 'Cache orrialdeen eremua',
	) ,
	'cleanurl' => array(
		'title' => 'Garbitu URLak',
	) ,
	'configure_map' => 'Mapa konfiguratu',
	'default_location' => 'Berezko kokapena',
	'default_map_all' => array(
		'alpha_numeric' => 'Badirudi feed-a sartu eremuan balio egokirik ez duela',
		'length' => 'Koloredun eremuak 6 karaktere izan behar ditu.',
		'required' => 'Kolore eremua beharrezkoa da',
	) ,
	'default_map_view' => 'Berezko mapa ikuskera',
	'default_zoom_level' => 'Berezko zoom maila',
	'download_city_list' => 'Eskuratu hiriak Geonames-etik',
	'email_host' => array(
		'length' => 'Mail serbitzariaren portuaren eremua luzeegia da.',
	) ,
	'facebook' => array(
		'app_id' => 'Facebook erabiltzailea',
	) ,
	'map' => array(
		'zoom' => 'Zoom maila',
	) ,
	'site' => array(
		'google_analytics' => 'Google Analytics',
	) ,
);
