<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-21 06:17+0000
// PO revision date:  2013-05-20 22:15+0000
$lang = array(
	'approved' => 'Onartua',
	'categories' => 'Kategoriak',
	'category_impact' => 'Kategoria arrakasta',
	'category_impact_description' => 'Estatistika honetan txostenen lerro ikuspegia duzu denboran zehar. Mugi sagua ezkerretik eskubira ikuspegi konparatiboa eskuratzeko kategoria ezberdinetan. Sagua grafikoaren gainean detaile gehiago lortzeko.',
	'choose_date_range' => 'Aukeratu datu tarte bat.',
	'countries' => 'Herrialdeak',
	'country' => 'Herrialdea',
	'country_breakdown' => 'Herrialde zatiketa',
	'description' => 'Hau estatistiken sekzioa da eta deskribapen orokorra izango du laster. Momentuz nabigatzen has zaitezke gainean dauden azpi kategoriak erabiltzen.',
	'error' => 'Akatsa',
	'glossary' => 'Hiztegia',
	'hit_summary' => 'Ikustaldi laburpena',
	'legend' => 'Legenda',
	'pageviews' => 'Bisitaldiak',
	'pageviews_description' => 'Zure orrialdeko bisitariek ikusi dituzten orrialdeen kopurua',
	'reports' => 'Txostenak',
	'reports_categories' => 'Kategoria txostenak',
	'reports_statistics' => 'Txostenen estatistikak',
	'reports_status' => 'Txostenen egoera',
	'report_punchcard' => 'Orri zulatu txostena',
	'report_stats' => 'Estatistiken txostena',
	'stats_not_setup' => 'Estatistikak ez dira ezarri',
	'time_range_1' => 'Hilabete 1',
	'time_range_2' => '3 hilabete',
	'time_range_3' => '6 hilabete',
	'time_range_all' => 'Denak',
	'unapproved' => 'Aprobatu gabeak',
	'unique_visitors' => 'Bisitari bakarrak',
	'unverified' => 'Ziurtatu gabeak',
	'verified' => 'Ziurtatua',
	'visitor_summary' => 'Bisitarien laburpena',
	'visits' => 'Bisitak',
	'visits_description' => 'Bisitaldi bat bisitari batek azken orrialde ikusitik gutxienez 30 minutu pasa direnean gordetzen da.',
);
