<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-22 06:17+0000
// PO revision date:  2013-05-21 15:19+0000
$lang = array(
	'actions' => array(
		'email_body' => 'Bialduko den emailaren gorputza',
		'email_subject' => 'Bialduko den emailaren gaia',
	) ,
	'default_value' => 'Bereiztu balio bakoitza komaz, adib. 1 balioa, 2 balioa, eta abar.',
	'dropdown_choices' => 'Bereiztu aukerautako elementu bakoitza komaz, adib. 1 elementua, 2 elementua, eta abar.',
	'private_to' => 'Hasi zerrendako bazkideei idazten.',
	'private_subject' => 'Mezu pribatuaren subjektua',
	'private_message' => 'Mezu pribatua',
	'profile_email' => 'Zure posta helbidea',
	'profile_public_url' => 'Helbide honetan zure profil publikoa aurkitu daiteke.',
	'profile_username' => 'Zure erabiltzailearen izena ezin izan da aldatu.',
	'settings_alert_email' => 'Helbide posta hau mezu alertak bidaltzeko erabiliko da.',
);
