<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-21 06:17+0000
// PO revision date:  2013-05-20 23:49+0000
$lang = array(
	'actions' => 'Ekintzak',
	'add_to_category' => 'Kategoriara gehitu',
	'alerts' => 'Alertak',
	'alerts_received' => 'Jasotako alertak',
	'all' => 'Guztia',
	'database' => 'Datu basea',
	'field_toggle_no' => 'Ez',
	'get_more_themes' => 'Gai gehiago eskuratu',
	'get_more_plugins' => 'Plugin gehiago eskuratu',
	'page_not_found' => 'Orria ez da aurkitu',
	'page_not_found_message' => 'Barkatu, ikusi nahi duzun orrialdia ez da hemen aurkitzen',
	'password' => 'Pasahitza',
	'password_reset_message_line_1' => 'Adiskide',
	'password_reset_message_line_3' => 'Pasahitza aldatzeko, mesedez klik egin azpiko estekan (bestenaz kopiatu eta zure nabigatzailean itsasi).',
	'phone' => 'Telefonoa',
	'please_select' => 'Mesedez aukeratu',
	'pm' => 'PM',
	'private_message' => 'Mezua',
);
