<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-06 00:05+0000
// PO revision date:  2012-07-12 21:24+0000
$lang = array(
	'email' => array(
		'email' => 'Pole adresu email nie zawiera ważnego adresu emailowego',
		'exists' => 'Przepraszamy, dla tego adresu emailowego już istnieje konto  użytkownika.',
		'length' => 'Adres emailowy musi mieć co najmniej  4 i nie więcej niż 64 znaki.',
		'required' => 'Pole adresu emailowego musi być wypełnione.',
	) ,
	'name' => array(
		'length' => 'Pełna nazwa pola musi mieć co najmniej 3 i nie więcej niż 100 znaków.',
		'required' => 'Wymagane jest wypełnienie pełnej nazwa pola.',
		'standard_text' => 'Pole nazwy użytkownika zawiera niedozwolone znaki.',
	) ,
	'password' => array(
		'length' => 'Pole hasła musi mieć co najmniej 5 i nie więcej niż 16 znaków.',
		'login error' => 'Sprawdź, czy wprowadziłeś właściwe hasło.',
		'matches' => 'Wprowadź to samo hasło w obydwu polach hasła.',
		'required' => 'Pole hasła musi być wypełnione.',
	) ,
	'password_confirm' => array(
		'matches' => 'Pole potwierdzenia hasła musi odpowiadać polu hasła.',
	) ,
	'resetemail' => array(
		'email' => 'Pole adresu emailowego prawdopodobnie nie zawiera ważnego adresu emailowego',
		'invalid' => 'Przepraszamy, nie mamy twojego adresu emailowego',
		'required' => 'Pole adresu emailowego musi być wypełnione.',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Niewłaściwe pole formatu.',
		'length' => 'Pole Roli musi składać się z minimum 5 znaków i maksymalnie z 30.',
		'required' => 'Musisz zdefiniować co najmniej jedną funkcję.',
		'values' => 'Musisz wybrać funkcję albo ADMINISTRATORA, albo UŻYTKOWNIKA.',
	) ,
	'username' => array(
		'admin' => 'Funkcja administratora/użytkownika nie może być zmodyfikowana.',
		'exists' => 'Przepraszamy, ta nazwa użytkownika jest już używana.',
		'length' => 'Pole nazwy użytkownika musi mieć co najmniej 2 i nie więcej niż 16 znaków.',
		'login error' => 'Sprawdź, czy wprowadziłeś właściwą nazwę użytkownika.',
		'required' => 'Pole nazwy użytkownika musi być wypełnione.',
		'superadmin' => 'Rola superadministratora nie może być zmodyfikowana.',
	) ,
);
