<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-17 06:40+0000
// PO revision date:  2012-08-15 04:40+0000
$lang = array(
	'error' => 'Błąd bazy danych: %s',
	'table_not_found' => 'Tabela "%s" nie może być znaleziona w bazie danych. Upewnij się, czy używasz najnowszej wersji bazy danych dla tej wersji Ushahidi',
);
