<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-17 06:40+0000
// PO revision date:  2012-08-15 04:40+0000
$lang = array(
	'am' => 'przed południem',
	'friday' => array(
		'abbv' => 'Pia',
		'full' => 'Piątek',
	) ,
	'monday' => array(
		'abbv' => 'Pon',
		'full' => 'Poniedziałek',
	) ,
	'pm' => 'po południu',
	'saturday' => array(
		'abbv' => 'Sob',
		'full' => 'Sobota',
	) ,
	'sunday' => array(
		'abbv' => 'Nie',
		'full' => 'Niedziela',
	) ,
	'thursday' => array(
		'abbv' => 'Czw',
		'full' => 'Czwartek',
	) ,
	'tuesday' => array(
		'abbv' => 'Wto',
		'full' => 'Wtorek',
	) ,
	'wednesday' => array(
		'abbv' => 'Śro',
		'full' => 'Środa',
	) ,
);
