<?php
	$lang = array(
	'database' => 'Baza danych',
	'database_host' => 'Host bazy danych',
	'database_name' => 'Nazwa bazy danych',
	'default_language' => 'Domyślny język',
	'default_language_description' => 'Each instance of Ushahidi comes with a set of built in language translations. You can also <a href="http://wiki.ushahidi.com/doku.php?id=localisation_l10n_internationlisation_i18n&s[]=language#enabling_new_languages" target="_blank">add your own</a>',
	'disable' => 'Wyłącz',
	'enable' => 'Włącz',
	'error' => 'Błąd',
	'google_key' => 'Klucz API <span>Google</span>',
	'go_back' => 'Powrót',
	'index' => array(
		'advanced' => 'ZAAWANSOWANA INSTALACJA',
		'basic_installation' => 'PODSTAWOWA INSTALACJA',
		'proceed' => 'Kontynuuj',
	),
	'installation_successful' => 'Instalacja zakończyła się pomyślnie.',
	'mail_server' => 'Serwer poczty',
	'mail_server_host' => 'Host serwera poczty',
	'mail_server_host_description' => 'Przykłady: mail.yourwebsite.com, imap.gmail.com, pop.gmail.com',
	'mail_server_password' => 'Hasło serwera poczty',
	'mail_server_port' => 'Port serwera poczty',
	'mail_server_port_description' => 'Popularne poty: 25, 110, 995 (Gmail POP3 SSL), 993 (Gmail IMAP SSL)',
	'mail_server_type' => 'Typ serwera poczty',
	'map' => 'Mapa',
	'map_provider' => 'Dostawca mapy',
	'other_steps' => 'Inne kroki',
	'password' => 'Hasło',
	'password_description' => 'Hasło bazy danych',
	'previous' => 'Poprzedni',
	'restart_apache' => 'Zrestartuj Serwer Apache',
	'select_mail_server_ssl' => 'Włącz lub wyłącz SSL',
	'setup_sms' => 'Skonfiguruj serwers SMS',
	'site_email' => 'Adres email strony',
	'site_email_alerts' => 'Adres email raportów',
	'site_name' => 'Nazwa strony',
	'site_name_description' => 'Nazwa Twojej strony',
	'site_tagline' => 'Hasło strony',
	'site_tagline_description' => 'Hasło Twojej strony',
	'upload_data' => 'Wgraj dane raportów',
	'username' => 'Nazwa użytkownika',
	'username_description' => 'Nazwa użytkwb bazy danych',
	'view_site' => 'Zobacz swoją stronę',
	);
?>
