<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-24 12:05+0000
// PO revision date:  2012-07-12 21:45+0000
$lang = array(
	'admin_footer' => 'Ta wiadomość została wysłana z serwisu',
	'admin_login_url' => 'Logowanie do panelu administracyjnego',
	'admin_new_comment' => array(
		'message' => 'Do systemu został dodany nowy komentarz, jako odpowiedź do:',
		'subject' => 'Nowy komentarz',
	) ,
	'admin_new_email' => array(
		'message' => 'Do systemu została dodana nowa wiadomość email.',
		'subject' => 'Nowa wiadomość email',
	) ,
	'admin_new_report' => array(
		'message' => 'Do systemu został dodany nowy raport.',
		'subject' => 'Nowy Raport',
	) ,
	'admin_new_sms' => array(
		'message' => 'Do systemu została dodana nowa wiadomość tekstowa SMS.',
		'subject' => 'Nowa wiadomość tekstowa',
	) ,
);
