<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-12 18:09+0000
$lang = array(
	'comments_form_error' => 'błąd!',
	'country_name' => array(
		'single_country' => 'Ta mapa jest ograniczona do obszaru jednego kraju. Proszę się upewnić, że raport znajduje się na terytorium kraju %s.',
	) ,
	'custom_field' => array(
		'values' => 'Proszę wypełnij wszystkie wymagane pola.',
	) ,
	'data_include' => array(
		'between' => 'Proszę wybrać właściwy obiekt do pobrania.',
		'numeric' => 'Wybierz właściwe elementy do pobrania',
	) ,
	'data_active' => array(
		'between' => 'Proszę wybrać "Oczekujące akceptacji", "Zaakceptowane" lub wszystkie. ',
		'numeric' => 'Proszę wybrać "Oczekujące akceptacji", "Zaakceptowane" lub wszystkie. ',
		'required' => 'Proszę wybrać "Oczekujące akceptacji", "Zaakceptowane" lub wszystkie. ',
	) ,
	'data_verified' => array(
		'between' => 'Proszę wybrać "Oczekujące weryfikacji", "Zweryfikowane" lub wszystkie. ',
		'numeric' => 'Proszę wybrać "Oczekujące weryfikacji", "Zweryfikowane" lub wszystkie. ',
		'required' => 'Proszę wybrać "Oczekujące weryfikacji", "Zweryfikowane" lub wszystkie. ',
	) ,
	'data_point' => array(
		'between' => 'Podaj właściwy typ raportu do pobrania',
		'numeric' => 'Podaj właściwy typ raportu do pobrania',
		'required' => 'Podaj właściwy typ raportu do pobrania',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'Pole DATA OD zawiera nieprawidłowe dane.',
		'range' => 'Pole DATA OD zawiera nieprawidłowe dane (nie może być większe od dzisiejszej daty).',
	) ,
	'incident_active' => array(
		'between' => 'Proszę podaj właściwe dane przy akceptacji alertu.',
		'required' => 'Proszę podaj właściwe dane przy akceptacji alertu.',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'Pole AM/PM zawiera nieprawidłową wartość',
	) ,
	'incident_category' => array(
		'numeric' => 'Pole kategoria zawiera nieprawidłowe dane.',
		'required' => 'Kategoria jest wymagana.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'Format daty jest nieprawidłowy.',
		'date_mmddyyyy' => 'Format daty jest nieprawidłowy.',
		'required' => 'Data jest wymagana.',
	) ,
	'incident_description' => array(
		'required' => 'Opis jest wymagany.',
	) ,
	'incident_hour' => array(
		'between' => 'Format albo zakres godzinowy jest nieprawidłowy.',
		'required' => 'Podaj godzinę!',
	) ,
	'incident_information' => array(
		'alpha' => 'Określ stopień Prawdopodobieństwa Informacji',
		'length' => 'Określ stopień Prawdopodobieństwa Informacji',
	) ,
	'incident_minute' => array(
		'between' => 'Format albo zakres pola minutowego jest nieprawidłowy.',
		'required' => 'Pole z minutą jest wymagane.',
	) ,
	'incident_news' => array(
		'url' => 'Źródło alertu zawiera nieprawidłowy adres URL.',
	) ,
	'incident_photo' => array(
		'size' => 'Limit wielkości zdjęcia to 2MB.',
		'type' => 'Wgrywane zdjęcie nie wydaje się być w prawidłowym formacie. Akceptowalne formaty to: .JPG, .PNG and .GIF.',
		'valid' => 'Wgrywane zdjęcie nie wydaje się być w prawidłowym formacie.',
	) ,
	'incident_source' => array(
		'alpha' => 'Proszę podaj właście dane źródła alertu.',
		'length' => 'Proszę podaj właście dane źródła alertu.',
	) ,
	'incident_title' => array(
		'length' => 'Tutuł raportu musi mieć min. 3 znaki (max. 200).',
		'required' => 'Tutuł raportu jest wymagany.',
		'csrf' => 'Podejrzenie ataku CSRF! Czy rzeczywiście chcesz utworzyć/edytować raport?',
	) ,
	'incident_verified' => array(
		'between' => 'Proszę podaj właście dane przy weryfikacji raportu',
		'required' => 'Proszę podaj właście dane przy weryfikacji raportu.',
	) ,
	'incident_video' => array(
		'url' => 'Video zwiera nieprawidłowy adres URL.',
	) ,
	'latitude' => array(
		'between' => 'Pole szerokości geograficznej zawiera nieprawidłową wartość.',
		'required' => 'Wartość szerokości geograficznej musi zostać podana. Proszę zaznacz ja na mapie.',
	) ,
	'locale' => array(
		'alpha_dash' => 'Pole locale zawiera nieprawidłowe dane. ',
		'exists' => 'Ten raport już posiada tłumaczenie w tym języku.',
		'length' => 'Pole locale posiada nieprawidłową długość. ',
		'locale' => 'Orginaly raport oraz tłumaczenie zawierają tą samą wartość locale.',
		'required' => 'Pole locale jest wymagane.',
	) ,
	'location_name' => array(
		'length' => 'Nazwa lokalizacji musi zawierać min. 3 znaki (max. 200)',
		'required' => 'Nazwa lokalizacji jest wymagana.',
	) ,
	'longitude' => array(
		'between' => 'Pole długości geograficznej zawiera nieprawidłową wartość.',
		'required' => 'Wartość długości geograficznej musi zostać podana. Proszę zaznacz ja na mapie.',
	) ,
	'person_email' => array(
		'email' => 'Proszę podaj prawidłowy adres email.',
		'length' => 'Adres email musi posiadać min 4 znaki (max 64).',
	) ,
	'person_first' => array(
		'length' => 'Imię musi zawierać min 3 znaki (max 100).',
	) ,
	'person_last' => array(
		'length' => 'Nazwisko musi zawierać min 3 znaki (max 100).',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'Pole DATA DO zawiera nieprawidłowe dane.',
		'range' => 'Pole DATA DO zawiera nieprawidłowe dane (nie może być większe od dzisiejszej daty).',
		'range_greater' => 'Pole DATA DO zawiera nieprawidłowe dane (nie może być większe od dzisiejszej daty).',
	) ,
);
