<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-28 00:05+0000
// PO revision date:  2012-07-12 21:52+0000
$lang = array(
	'approved' => 'Zaakceptowane',
	'categories' => 'Kategorie',
	'category_impact' => 'Siła Kategorii',
	'choose_date_range' => 'Wybierz zasięg czasowy',
	'countries' => 'Państwa',
	'country' => 'Kraj',
	'country_breakdown' => 'Rozłóż na kraje',
	'error' => 'Błąd',
	'legend' => 'Legenda',
	'pageviews' => 'Odsłony',
	'reports' => 'Raporty',
	'reports_categories' => 'Kategorie Raportów',
	'reports_statistics' => 'Statystyki Raportów',
	'reports_status' => 'Status Raportów',
	'report_stats' => 'Statystyki Raportów',
	'time_range_1' => '1 miesiąc',
	'time_range_2' => '3 miesiące',
	'time_range_3' => '6 miesięcy',
	'time_range_all' => 'Wszystkie',
	'unapproved' => 'Niezaakceptowane',
	'unique_visitors' => 'UU',
	'unique_visitors_description' => 'The number of individuals coming to your instance; Unique Visitors are determined using cookies. In the case that a visitor does not have cookies enabled, they will be identified using a simple heuristic taking into account IP address, resolution, browser, plugins, OS, etc',
	'unverified' => 'Niepotwierdzone',
	'verified' => 'Potwierdzone',
	'visitor_summary' => 'Podsumowanie wizyt',
	'visits' => 'Wizyty',
);
