<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-12 12:05+0000
// PO revision date:  2012-07-12 21:53+0000
$lang = array(
	'profile_email' => 'Twój adres email',
	'profile_name' => 'Twoja pełna nazwa (imie i nazwisko)',
	'profile_notify' => 'Wybież TAK, jeżeli pragniesz uzyskiwać notyfikacje.',
	'profile_password' => 'Twoje hasło (pozostaw to pole puste, jeżeli pragniesz aby pozostało niezmienione)',
	'profile_username' => 'Twoja nazwa użytkownika nie może być zmieniona',
);
