<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-03 12:04+0000
// PO revision date:  2012-07-12 21:58+0000

$lang = array (
  'upgrade' => 
  array (
    'between' => 'Nieprawidłowe dane. 0 to Nie a 1 to Tak.',
  ),
  'upgrade_automatic' => 'Automatyczna Aktualizacja',
  'upgrade_available' => 'Dostępne uaktualnienia',
  'upgrade_continue_btn_text' => 'Kontynuuj',
  'upgrade_db_btn_text' => 'Aktulizacja',
  'upgrade_db_text_1' => 'Aktualizacja bazy danych z wersji',
  'upgrade_db_text_2' => 'do najnowszej wersji bazy danych',
  'upgrade_db_text_3' => 'Kliknij przycisk "Aktualizacja" i zrelaksuj się :) ',
  'upgrade_db_text_4' => 'Jeśli chcesz wykonać kopię bazy danych, zaznacz poniższe pole wyboru.',
  'upgrade_db_text_5' => 'Wykonać kopię zapasową bazdy danych przed aktyalizacją? ',
  'upgrade_db_title' => 'Aktualizacj bazy danych Ushahidi',
  'upgrade_failed' => 'Aktualizacja nie powiodła się',
  'upgrade_manual' => 'Manualna Aktualizacja',
  'upgrade_status' => 'Postęp aktualizacji Ushahidi',
  'upgrade_text_1' => 'The instructions below details how to manually upgrade your Ushahidi instance',
  'upgrade_text_2' => 'Krok 1: Pobierz najnowszą wersję Ushahidi z <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
  'upgrade_text_3' => 'Krok 2: Depending on the operating system running the webserver, use your preferred tool/mode (i.e: telnet, ftp, ssh) to login to the webserver and replace the contents of all the folders with the newest from the recent build. All EXCEPT:',
  'upgrade_text_4' => 'Step 3: Use your favorite Mysql client ( eg. phpMyAdmin ), and execute the <code>upgrade.sql</code>. The script shall update and alter the respective tables',
  'upgrade_text_5' => 'Aby uruchomić automatyczną aktualizację kliknij poniższy przycisk.',
  'upgrading' => 'Aktualizaja',
);

