<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-15 06:20+0000
$lang = array(
	'description' => array(
		'length' => 'Hap&euml;sira e p&euml;rshkrimit duhet t&euml; p&euml;rmbaj&euml; 3 deri n&euml; 100 karaktere.',
		'required' => ' Informacioni n&euml; hap&euml;sir&euml;n e p&euml;rshkrimit &euml;sht&euml; i detyruesh&euml;m p&euml;r tu plot&euml;suar.',
	) ,
	'name' => array(
		'alpha_numeric' => 'Emri duhet t&euml; p&euml;rmbaj&euml; vet&euml;m shkronja dhe numra .',
		'length' => 'Emri duhet t&euml; p&euml;rmbaj&euml;  2 deri n&euml; 30 karaktere.',
		'nomodify' => ' Roli i Krye Administratorit nuk mund t&euml; modifikohet.',
		'required' => 'Informacioni p&euml;r emrin &euml;sht&euml; i detyruesh&euml;m p&euml;r tu plot&euml;suar.',
	) ,
	'access_level' => array(
		'numeric' => 'Niveli i aksesit duhet t&euml; jet&euml; nj&euml; num&euml;r nga 0 deri n&euml; 100.',
		'required' => 'Niveli i aksesit duhet t&euml; jet&euml; nj&euml; num&euml;r nga 0 deri n&euml; 100.',
	) ,
);
