<?php
	$lang = array(
	'alert_email' => array(
		'email' => 'Emailkaad gelisay sax ma aha.',
		'email_check' => 'Emailkaad gelisay horay ayuu u diiwaangashanaa suu u helo farriimo ku saabsan goobtaas.',
		'length' => 'Emailkaagu waa inuu ka kooban yahay ugu yaraan afar xaraf, ugu badnaana 64 xaraf.',
		'one_required' => 'so_SO:',
		'required' => 'Email ayaa loo baahan yahay haddii sanduuqu saxan yahay.',
	),
	'alert_lat' => array(
		'between' => 'Ma aadan ka dooran khariidada goob jirta.',
		'required' => 'Ma aadan ka dooran khariidada goob jirta.',
	),
	'alert_lon' => array(
		'between' => 'Ma aadan ka dooran khariidada goob jirta.',
		'required' => 'Ma aadan ka dooran khariidada goob jirta.',
	),
	'alert_mobile' => array(
		'length' => 'Tirada nambarrada telefonka aad gelisay sax ma aha.',
		'mobile_check' => 'Telefon nambarka aad gelisay horay ayuu u diiwaangashanaa suu u helo farriimo ku saabsan goobtaas.',
		'numeric' => 'Ma jiro telefonka aad gelisay. Fadlan geli telefon nambar sax ah, adigoo ku bilaabaya furaha wadanka.',
		'one_required' => 'Waa inaad gelisaa telefoon nambarkaaga ama Emailkaaga.',
		'required' => 'Telefon nambar ayaa loo baahan yahay hadii sanduuqu saxan yahay.',
	),
	'alert_radius' => array(
		'in_array' => 'Gacan (radius) sax ah uma aadan hagaajin khariidada.',
		'required' => 'Gacan (radius)uma aadan hagaajin khariidada.',
	),
	'code_already_verified' => 'Furahan horey ayaa loo xaqiijiyay!',
	'code_not_found' => 'furaha xaqiijinta lama helin! Fadlan hubi in URL-ku sax yahay.',
	'code_verified' => 'Furahaaga waa la xaqiijiyay. Waxaad heli doontaa fariimaha islamarka ay dhacaan.',
	'confirm_request' => 'Si aad u xaqiijiso dalabkaaga farriimaha, fadlan booqo',
	'create_more_alerts' => 'Dib ugu noqo bogga farriimaha si aad u samayso farriimo kaloo badan.',
	'email_alert_request_created' => 'Dalabka farriimaha ee Emailkaaga waa la sameeyay, waxaana farrin xaqiijin ah laguugu soo diray',
	'email_code' => 'Fadlan geli furaha xaqiijinta Emailka ee aad hoos ku heshay.',
	'email_error_head' => 'Dalabka farrimaha Emailkaaga lama keydin!',
	'email_ok_head' => 'Dalabka farriimaha Emailkaaga waa la keydiyay!',
	'error' => 'Mashiinku wuu awoodi waayay inuu soo saaro dalabkaaga xajiinta!',
	'mobile_alert_request_created' => 'Dalabkaaga farrimaha mobile-ka waa la sameeyay, waxaana farriin xaqiijin ah laguugu soo diray',
	'mobile_code' => 'Fadlan hoos geli furaha xaqiijinta ee laguugu soo diray mobile-kaaga.',
	'mobile_error_head' => 'Dalabka farrimaha Mobile-kaaga lama keydin!',
	'mobile_ok_head' => 'Dalabka farrimaha Mobile-kaaga waa la keydiyay!',
	'settings_error' => 'Qaabkaad wax u hagaajisay, si sax ah uma soo saari karo farriimaha.',
	'unsubscribe' => 'Waad heshay Emailkaan, maxaayeelay adiga codsaday inaad hesho farriimo joogta ah. Haddii aadan doonayn inaad hesho farriimaha, booqo',
	'unsubscribed' => 'Farriimo dambe ma heli doontid, laga bilaabo',
	'unsubscribe_failed' => 'Waan awoodi weynay inaan kaa xirno farrimaheena. Fadlan hubi in URL-ku saxan yahay.',
	'verification_email_subject' => 'Xaqiijinta farriimaha',
	'verify_code' => 'Ma heli kartid farrimo ku saabsan goobtan adigoon xaqiijin dalabkaaga.',
	);
?>
