<?php
	$lang = array(
	'base_path' => 'Waddada aasaaska ah.',
	'database' => 'Keydka xogta',
	'database_host' => 'Martigeliyaha keydka xogta',
	'database_host_description' => 'Haddii Ushahidi aad ka maamulayso computer-kaaga, computer-kaaga waxa uu noqonayaa "Localhost". Haddiise Ushahidi aad ka maamulayso computer-ka nooca web serverka, waxaad warbixinadda ka heleysaa shirkadda hosti gareyneyso boggiina.',
	'database_name' => 'Magaca keydka xogta',
	'database_name_description' => 'Magaca keydka xogta ee aad doonayso inaad ku maamusho Ushahidi',
	'db_information_link' => 'Wixii faahfaahin ah, fadlan ku raadi link-gaan <a href="http://wiki.ushahidi.com/doku.php?id=a_brief_word_on_databases" target="_blank">this article</a> website sida faahfaahsan uga hadlayo keydadka xogta.',
	'default_language' => 'Luuqada asalka ah',
	'default_language_description' => 'Version kasta oo Ushahidi waxa uu la yimaadaa luqado ku dhisan gudihiisa oo diyaar u ah in la turjumo. Waxaad <a href="http://wiki.ushahidi.com/doku.php?id=localisation_l10n_internationlisation_i18n&s[]=language#enabling_new_languages" target="_blank"> ku dari kartaa luuqadaada hooyo </a>',
	'disable' => 'Awooda ka xir',
	'enable' => 'Awood sii',
	'error_summary' => 'Waxaa hoos ku xusan warbixin kooban oo ku saabsan cilladaha aanu la kulannay',
	'files_location_text' => 'Halka aad Faylasha Ushahidi ka dhigtay Computerka Serverka. <strong> Waxaa inoo soo baxay qiimahan, fadlan hubi inuu sax yahay. </strong> Haddii goobtu ay maran tahay, ha welwelin, Ushahidi waxay ku rakiban tahay khaanadda kore.',
	'finished' => 'Dhammaystiran',
	'general' => 'Guud ahaan',
	'google_key' => '<span>Google</span> API Key',
	'google_key_description' => 'Qof kasta waa uu heli karaa furaha api. <a id="api-link" href="http://code.google.com/apis/maps/signup.html" target="_blank">Get yours now</a>',
	'go_back' => 'Dib u noqo',
	'index' => array(
		'advanced' => 'Rakibaad horumarsan',
		'advanced_installation_description' => 'Waxaad qaabka loo hagaajiyo ka heli kartaa adigoo raacaya hannaanka 5-ta tallaabo. Waxaa 5-ta hannaan ka mid ah computerka Server-ka, khariirada, magaca bogga iyo halka lagala xiriirayo.',
		'basic_installation' => 'Rakibaadda aasaaska ah',
		'basic_installation_description' => 'Rakibaaddu waa ay fududahay, waana deg-deg. Keliya waxaad u baahan tahay root directory-ga bogga iyo warbixinta keydka xogtaada.',
		'proceed' => 'Wad',
		'welcome' => 'Ku soo dhowow hannaanka rakibaadda Ushahidi ee serverada. Hoos ka dooro nooca rakibaadda aad jeclaan lahayd inaad computerkaaga ku rakibto.',
	),
	'installation_successful' => 'Rakibaaddu si fiican ayay u dhamaatay.',
	'mail_server' => 'Mail Server',
	'mail_server_host' => 'Martigeliyaha mail Serverka',
	'mail_server_host_description' => 'Tusaale ahaan: mail.yourwebsite.com, imap.gmail.com, pop.gmail.com',
	'mail_server_password' => 'Password-ka Mail Server-ka',
	'mail_server_password_description' => 'Passwordka waxa aad u addeegsataa inaad ku gasho email-kaaga.',
	'mail_server_port' => 'Mail Server Port',
	'mail_server_port_description' => 'Common Ports: 25, 110, 995 (Gmail POP3 SSL), 993 (Gmail IMAP SSL)',
	'mail_server_type' => 'Mail Server Type',
	'mail_server_type_description' => 'en_US: Internet Message Access Protocol (IMAP) or Post Office Protocol (POP). <a href="http://saturn.med.nyu.edu/it/help/email/imap/index.html" target="_blank">What is the difference?</a>
',
	'mail_server_username' => 'Username-ka lagu galo Mail Server-ka',
	'mail_server_username_description' => 'Haddii aad isticmaalayso Gmail, Hotmail, ama Yahoo Mail, u isticmaal Emailkaaga oo dhamaystiran magaca aad ku galayso',
	'map_provider' => 'Khariirad bixiye',
	'map_provider_description' => 'Ushahidi si siman ayay ula shaqeysaa afarta khariirad bixiyayaal: Google, Bing, Yahoo ama Open Street Map. Dooro midda ay ku jirto faahfaahin ku saabsan meesha aad ku sugan tahay.',
	'other_steps' => 'Waddiiqooyin kale...',
	'password' => 'Password',
	'password_description' => 'Password-ka keydka xogtaada',
	'previous' => 'Hore',
	'restart_apache' => 'Fadlan dib u soo kici Server-kaaga Apache',
	'select_mail_server_ssl' => 'Awood sii ama awoodda ka xir SSL',
	'select_mail_server_ssl_description' => 'Qaar ka mid ah Mail Servers-yada waxay ku siinayaan dookha ah inaad isticmaasho <abbr title="Secure Sockets Layer">SSL</abbr> marka aad sameyneyso xiriirin. Addeegsiga SSL waa uu fiican yahay maadama uu ku siinayo amni dheeraad ah.',
	'setup_sms' => 'Rakib Serverkaaga SMS-yada.',
	'site_email' => 'Cinwaanka Emailka ee bogga.',
	);
?>
