<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-13 04:30+0000
// PO revision date:  2012-07-13 04:22+0000

$lang = array (
  'am' => 'сутрин',
  'friday' => 
  array (
    'abbv' => 'пет',
    'full' => 'петък',
  ),
  'monday' => 
  array (
    'abbv' => 'пон',
    'full' => 'понеделник',
  ),
  'pm' => 'следобед',
  'saturday' => 
  array (
    'abbv' => 'съб',
    'full' => 'събота',
  ),
  'sunday' => 
  array (
    'abbv' => 'нед',
    'full' => 'неделя',
  ),
  'thursday' => 
  array (
    'abbv' => 'чет',
    'full' => 'четвъртък',
  ),
  'tuesday' => 
  array (
    'abbv' => 'втр',
    'full' => 'вторник',
  ),
  'wednesday' => 
  array (
    'abbv' => 'сря',
    'full' => 'сряда',
  ),
);

