<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-23 18:04+0000
// PO revision date:  2012-07-12 21:34+0000

$lang = array (
  'date' => 'DATE',
  'feed_name' => 
  array (
    'length' => 'Името на абонамента трябва да е между 3 и 70 символа.',
    'required' => 'Моля въведете име на абонамента.',
  ),
  'feed_url' => 
  array (
    'required' => 'Моля въведете адрес на абонамента.',
    'url' => 'Моля въведете валиден адрес. Например: http://www.ushahidi.com',
  ),
  'source' => 'ИЗТОЧНИК',
  'title' => 'Заглавие',
);

