<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-12-27 06:21+0000
// PO revision date:  2014-12-26 07:20+0000
$lang = array(
	'phone' => 'फाेन',
	'private_message' => 'सन्देश',
	'private_messages' => 'गाेप्य सन्देश',
	'private_subject' => 'विषय',
	'required' => 'अावश्यक',
	'results' => 'नतिजाहरू',
	'search' => 'खाेज',
	'sender' => 'प्रेषक',
	'subject' => 'विषय',
	'theme_name' => 'नाम',
	'view_private' => 'गाेप्य सन्देशहरू',
	'view_site' => 'साइट हेर्नुहाेस्',
	'view_report' => 'रिपाेर्ट हेर्नुहाेस्',
	'welcome' => 'स्वागतम्,',
	'xml' => 'एक्स एफ एल',
	'yes' => 'हाे',
);
