<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-26 00:04+0000
// PO revision date:  2012-09-25 23:14+0000
$lang = array(
	'about' => 'हाम्रो बारेमा',
	'add' => 'जोड्नु',
	'alerts' => 'अधिसूचनाहरु प्राप्त गर्नु',
	'alerts_get' => 'अधिसूचनाहरु प्राप्त गर्नु',
	'contact' => 'सम्पर्क',
	'home' => 'गृहपृष्ठ',
	'how_to_report' => 'रिपोर्ट कसरी गर्ने',
	'official_news' => 'अधिकारिक र मूलधारका समाचारहरु',
	'reports_listed' => 'प्रतिवेदनहरु  <span>(नक्शाबाटा, तिथिक्रमानुसार)</span>',
	'reports' => 'प्रतिवेदनहरु',
	'report_option_1' => 'sms बाटा "report"+ गा.वि.सा./ नगरपालिका / वाडा न./ नाम/पता टाईप गरेर 18771555 मा पठाउन सकिन्छ',
	'report_option_2' => 'ईमेल बाटा',
	'report_option_4' => 'हाम्रो वेबसाईटमा भएको फारम भरेर',
	'report_option_external_apps' => 'app को प्रयोगबाटा',
	'submit' => 'प्रतिवेदन बुझाउनु',
);
