<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-04-30 05:29+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Format alamat surel yang tercantum pada kolom surel tidak valid ?',
		'email_check' => 'Alamat surel yang tercantum sudah terdaftar sebagai penerima berita untuk lokasi tersebut',
		'length' => 'Panjang isian alamat surel harus minimal 4 dan tidak lebih dari 64 karakter.',
		'required' => 'Jika checkbox dicentang, isian surel tidak boleh kosong',
	) ,
	'alert_country' => array(
		'single_country' => 'Cakupan penyebaran platform ini hanya dalam satu negara, pastikan lokasi pemberitahuan berada dalam negara %s',
	) ,
	'alert_lat' => array(
		'between' => 'Anda belum memilih lokasi yang benar pada peta',
		'required' => 'Anda belum memilih lokasi yang benar pada peta',
	) ,
	'alert_lon' => array(
		'between' => 'Anda belum memilih lokasi yang benar pada peta',
		'required' => 'Anda belum memilih lokasi yang benar pada peta',
	) ,
	'alert_mobile' => array(
		'length' => 'Jumlah karakter pada isian Telepon Seluler salah.',
		'mobile_check' => 'Nomor telpon seluler yang dicantumkan sudah terdaftar untuk menerima berita dari lokasi itu.',
		'numeric' => 'Nomor telepon seluler pada kolom telepon seluler salah. Mohon isi hanya dengan angka termasuk kode negara.',
		'one_required' => 'Anda harus mencantumkan nomor telepon seluler anda atau alamat surel anda',
		'required' => 'Jika kotak centang dicentang, isian telepon seluler tidak boleh kosong',
	) ,
	'alert_radius' => array(
		'in_array' => 'Anda belum menentukan radius yang benar pada peta',
		'required' => 'Anda belum menentukan radius anda pada peta',
	) ,
	'alert_recipient' => array(
		'required' => 'anda belum menentukan penerima peringatan.',
	) ,
	'alerts_subscribed' => 'Anda telah berlangganan peringatan dengan kategori berikut ini',
	'code_already_verified' => 'Kode ini sudah pernah diverifikasi !',
	'code_not_found' => 'Kode verifikasi ini tidak ditemukan ! Mohon periksa kembali URL yang digunakan.',
	'code_verified' => 'Kode anda telah diverifikasi dengan benar. Anda akan menerima pesan begitu ada kejadian.',
	'confirm_request' => 'Untuk mengkonfirmasikan permintaan pesan anda, mohon lanjut ke',
	'create_more_alerts' => 'Kembali ke laman pesan untuk membuat pesan baru',
	'email_alert_request_created' => 'Permintaan notifikasi surel anda telah dibuat dan pesan untuk memverifikasi ini telah di kirim ke',
	'email_code' => 'Silakan masukan kode konfirmasi surel yang anda terima di bawah ini :',
	'email_error_head' => 'Permintaan notifikasi surel anda belum tersimpan !',
	'email_ok_head' => 'Permintaan notifikasi surel anda telah tersimpan!',
	'error' => 'Sistem tidak bisa memroses permintaan konfirmasi anda!',
	'mobile_alert_request_created' => 'Permintaan notifikasi mobile anda telah dibuat dan pesan untuk memverifikasi ini telah dikirim ke',
	'mobile_code' => 'Silakan masukan kode konfirmasi sms yang anda terima di telpon seluler anda di bawah ini :',
	'mobile_error_head' => 'Permintaan notifikasi mobile anda belum tersimpan !',
	'mobile_ok_head' => 'Permintaan notifikasi mobile anda telah tersimpan !',
	'settings_error' => 'Instalasi ini tidak terkonfigurasi untuk memroses notifikasi dengan benar',
	'unsubscribe' => 'Anda menerima surel ini karena anda minta untuk dinotifikasi. Jika anda mau menghentikan pengiriman surel ini silakan ke',
	'unsubscribed' => 'Anda tidak lagi akan dikirimi notifikasi dari',
	'unsubscribe_failed' => 'Kami gagal membatalkan permintaan penghentian berlangganan anda. Mohon pastikan anda URL yg anda gunakan sudah benar.',
	'verification_email_subject' => 'pesan - verifikasi',
	'verify_code' => 'Anda tidak akan menerima pesan dari lokasi ini sebelum anda konfirmasikan permintaan anda.',
);
