<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-15 12:00+0000
$lang = array(
	'email' => array(
		'email' => 'Format alamat e-mail yang tercantum pada isian e-mail tidak valid ?',
		'exists' => 'Maaf, alamat e-mail ini sudah digunakan pengguna lain.',
		'length' => 'Panjang isian alamat e-mail harus minimal 4 dan tidak lebih dari 64 karakter.',
		'required' => 'Isian e-mail harus diisi',
	) ,
	'name' => array(
		'length' => 'Panjang isian nama lengkap harus minimal 3 dan tidak lebih dari 100 karakter.',
		'required' => 'Isian nama lengkap harus diisi',
		'standard_text' => 'Isian nama pengguna mengandung karakter yang terlarang.',
	) ,
	'password' => array(
		'length' => 'Panjang isian password harus minimal 5 dan tidak lebih dari 16 karakter.',
		'matches' => 'Mohon masukkan password yang sama ke isian password kedua',
		'required' => 'Isian password harus diisi',
	) ,
	'password_confirm' => array(
		'matches' => 'password yang anda masukkan pada isian konfirmasi password harus sama dengan yg anda masukkan pada isian password',
	) ,
	'resetemail' => array(
		'email' => 'format alamat e-mail yang anda masukkan, salah ?',
		'invalid' => 'Maaf, alamat e-mail anda tidak terdaftar',
		'required' => 'Isian alamat e-mail harus diisi',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Format peran tidak valid',
		'length' => 'Panjang isian peran harus minimal 5 dan tidak lebih dari 30 karakter.',
		'required' => 'Anda harus tetapkan minimal satu peran',
		'values' => 'Anda harus memilih peran admin ATAU pengguna',
	) ,
	'username' => array(
		'admin' => 'Peran admin tidak boleh disunting',
		'exists' => 'Maaf, nama pengguna ini sudah terpakai',
		'length' => 'Panjang isian nama pengguna harus minimal 2 dan tidak lebih dari 16 karakter.',
		'required' => 'Isian nama pengguna harus diisi',
		'superadmin' => 'Peran admin super tidak boleh disunting',
	) ,
);
