<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-22 06:23+0000
// PO revision date:  2013-10-21 10:49+0000
$lang = array(
	'email' => array(
		'email' => 'Alamat surel yang Anda masukkan tidak benar.',
		'exists' => 'Maaf, alamat surel ini sudah digunakan pengguna lain.',
		'length' => 'Panjang isian alamat surel setidaknya terdiri dari 4 karakter dan tidak lebih dari 64 karakter.',
		'required' => 'Kolom isian surel wajib diisi.',
	) ,
	'name' => array(
		'length' => 'Kolom nama lengkap setidaknya 3 dan tidak lebih dari 100 karakter.',
		'required' => 'Isian nama lengkap harus diisi',
		'standard_text' => 'Isian nama pengguna mengandung karakter yang terlarang.',
	) ,
	'current_password' => array(
		'length' => 'Kolom password setidaknya harus terdiri atas 8 karakter.',
		'login error' => 'Pastikan bahwa alamat surel dan password yang Anda masukkan sudah benar.',
		'matches' => 'Masukkan password yang sama ke kedua kolom password.',
		'required' => 'Kolom password wajib diisi.',
		'alpha_dash' => 'Kolom password setidaknya harus berisi karakter huruf, simbiol # dan @, angka, garis bawah dan dash',
		'incorrect' => 'Password yang Anda masukkan salah. Silahkan coba lagi.',
	) ,
	'new_password' => array(
		'length' => 'Kolom password setidaknya harus terdiri atas 8 karakter.',
		'login error' => 'Pastikan bahwa alamat surel dan password yang Anda masukkan sudah benar.',
		'matches' => 'Masukkan password yang sama ke kedua kolom password.',
		'required' => 'Kolom password wajib diisi.',
		'alpha_dash' => 'Kolom password setidaknya harus berisi karakter huruf, simbiol # dan @, angka, garis bawah dan dash',
	) ,
	'password' => array(
		'default' => 'Ada kesalahan saat mencoba login.',
		'length' => 'Kolom password setidaknya harus berisi 8 karakter.',
		'login error' => 'Pastikan Anda sudah mengisi alamat surel dan password dengan benar.',
		'matches' => 'Masukkan password yang sama dalam ekdua kolom password.',
		'required' => 'Kolom password wajib diisi.',
		'riverid server down' => 'Server otentifikasi sedang mati. Coba beberapa saat lagi.',
		'alpha_dash' => 'Kolom password setidaknya harus berisi karakter huruf, simbiol # dan @, angka, garis bawah dan dash',
	) ,
	'password_confirm' => array(
		'matches' => 'password yang anda masukkan pada isian konfirmasi password harus sama dengan yg anda masukkan pada isian password',
	) ,
	'resetemail' => array(
		'email' => 'format alamat e-mail yang anda masukkan, salah ?',
		'invalid' => 'Maaf, alamat e-mail anda tidak terdaftar',
		'required' => 'Kolom password wajib diisi.',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Format peran tidak valid',
		'length' => 'Panjang isian peran harus minimal 5 dan tidak lebih dari 30 karakter.',
		'required' => 'Anda harus tetapkan minimal satu peran',
		'values' => 'Anda harus memilih peran admin ATAU pengguna',
	) ,
	'username' => array(
		'admin' => 'Peran admin tidak boleh disunting',
		'exists' => 'Maaf, nama pengguna ini sudah terpakai',
		'length' => 'Panjang isian nama pengguna harus minimal 2 dan tidak lebih dari 16 karakter.',
		'required' => 'Isian nama pengguna harus diisi',
		'superadmin' => 'Peran admin super tidak boleh disunting',
	) ,
);
