<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:25+0000
$lang = array(
	'captcha' => array(
		'default' => 'Mohon pastikan kode keamanan yang anda masukan sudah benar',
		'required' => 'Masukan kode keamanan anda',
	) ,
	'email' => array(
		'email' => 'Alamat e-mail yang anda masukan tidak dalam format yang benar?',
		'length' => 'Panjang alamat e-mail minimal 4 karakter tapi boleh tidak lebih dr 64 karakter',
		'required' => 'Kalau cek box tercentang isian alamat e-mail tidak boleh kosong',
	) ,
	'error' => array(
		'required' => 'Isian yang salah harus diisi dengan benar',
	) ,
	'subject' => array(
		'length' => 'Panjang subjek minimal 3 karakter',
		'required' => 'Isian subjek tidak boleh dikosongkan',
	) ,
	'yourname' => array(
		'length' => 'Panjang nama harus minimal 3 karakter',
		'required' => 'Isian nama tidak boleh dikosongkan',
	) ,
);
