<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-28 06:23+0000
// PO revision date:  2013-10-27 10:50+0000
$lang = array(
	'captcha' => array(
		'default' => 'Pastikan kode keamanan yang Anda masukkan sudah benar.',
		'required' => 'Masukkan kode keamanan Anda.',
	) ,
	'email' => array(
		'email' => 'Apakah Anda yakin kolom Surel sudah terisi dengan benar?',
		'length' => 'Panjang alamat surel minimal 4 dan tidak lebih dari 64 karakter.',
		'required' => 'Kolom Surel diminta, jika kotak cek Anda centang.',
	) ,
	'error' => array(
		'required' => 'Mohon kolom yang belum terisi dengan benar dikoreksi terlebih dahulu.',
	) ,
	'subject' => array(
		'length' => 'Isi kolom judul setidaknya 3 karakter.',
		'required' => 'Kolom judul tidak boleh dikosongkan.',
	) ,
	'yourname' => array(
		'length' => 'Panjang nama setidaknya 3 karakter.',
		'required' => 'Kolom nama tidak boleh dikosongkan.',
	) ,
);
