<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:28+0000
$lang = array(
	'captcha' => array(
		'default' => 'Mohon masukan kode keamanan yang benar',
		'required' => 'Masukan kode keamanan anda',
	) ,
	'comment_author' => array(
		'length' => 'Panjang nama harus minimal 3 karakter',
		'required' => 'Nama tidak boleh dikosongkan',
	) ,
	'comment_description' => array(
		'required' => 'Isian komentar tidak boleh dikosongkan',
	) ,
	'comment_email' => array(
		'email' => 'Format alamat e-mail yg dimasukan salah ?',
		'length' => 'Alamat e-mail harus minmal 4 karakter tapi tidak lebih panjang dr 64 karakter',
		'required' => 'Kalau cek box tercentang alamat e-mail tidak boleh dikosongkan',
	) ,
);
