<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-17 06:23+0000
// PO revision date:  2013-10-16 18:05+0000
$lang = array(
	'captcha' => array(
		'default' => 'Masukkan kode keamanan Anda.',
		'valid' => 'Masukkan kode keamanan Anda.',
		'required' => 'Masukkan kode keamanan Anda.',
	) ,
	'contact_email' => array(
		'email' => 'Kolom Surel tidak benar.',
		'length' => 'Panjang alamat surel minimal 4 karakter tapi tidak lebih dari 64 karakter.',
		'required' => 'Jika tanda cek tercentang, maka Surel tidak boleh dikosongkan.',
	) ,
	'contact_message' => array(
		'required' => 'Kolom pesan tidak boleh kosong.',
	) ,
	'contact_name' => array(
		'length' => 'Panjang nama minimal 3 karakter.',
		'required' => 'Nama tidak boleh dikosongkan.',
	) ,
	'contact_subject' => array(
		'length' => 'Panjang subjek harus minimal 3 karakter.',
		'required' => 'Subjek tidak boleh dikosongkan.',
	) ,
	'email_send' => array(
		'failed' => 'Ada kesalahan dalam proses pengiriman pesan Anda.',
	) ,
);
