<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-03 00:02+0000
$lang = array(
	'field_default' => array(
		'length' => 'Panjang nama minimal 3 karakter tapi tidak boleh lebih dr 200 karakter',
	) ,
	'field_height' => array(
		'between' => 'Isian tinggi hanya boleh diisi angka antara 0 - 50',
	) ,
	'field_isdate' => array(
		'between' => 'Format tanggal yang anda masukkan salah',
		'required' => 'Mohon hanya pilih Yes atau No pada isian tanggal',
	) ,
	'field_name' => array(
		'length' => 'Panjang nama minimal 3 karakter tapi tidak boleh lebih dr 100 karakter',
		'required' => 'Masukan nama anda',
	) ,
	'field_required' => array(
		'between' => 'Salah satu masukan anda pada isian wajib yang ada, salah',
		'required' => 'Mohon hanya pilih Yes atau No pada isian yang diwajibkan',
	) ,
	'field_type' => array(
		'numeric' => 'Mohon pastikan tipe isian yang anda pilih sudah benar',
		'required' => 'Pilih tipe isian',
	) ,
	'field_width' => array(
		'between' => 'Isian lebar hanya boleh diisi angka antara 0 - 300',
	) ,
	'form_description' => array(
		'required' => 'Masukan sertakan keterangan pada formulirnya',
	) ,
	'form_id' => array(
		'default' => 'Formulir default tidak bisa dihapus',
		'numeric' => 'Silakan pilih ke formulir yang mana isian ini akan ditambahkan',
		'required' => 'Silakan pilih ke formulir yang mana isian ini akan ditambahkan',
	) ,
	'form_title' => array(
		'length' => 'Panjang nama formulis minimal 3 karakter dan tidak boleh lebih dari 100 karakter',
		'required' => 'Masukan nama formulir',
	) ,
);
