<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:42+0000
$lang = array(
	'akismet_cannot_connect' => 'Tidak bisa konek dengan peladen Akismet',
	'akismet_cannot_retrieve' => 'Respon dr Akismet tidak bisa didapat',
	'api_library_not_found' => 'Pustaka API: <strong>%s</strong>, Kalau class <strong>%s</strong> tidak ditemukan. Mohon periksa tabel routing API task anda.',
	'askimet_invalid_apikey' => 'Kunci API Akismet anda tidak valid.',
	'clickatell_fopen_error' => 'Galat terjadi pada saat melakukan metode pengiriman fopen!<br>Mohon pastikan PHP punya layanan OpenAAL dan pastikan versi PHP-nya lebih tinggi dr 5.2',
	'clickatell_message_too_long' => 'Pesan Unicode anda terlalu panjang! (Panjang sekarang=',
	'clickatell_no_destination_address' => 'Mohon sertakan alamat tujuan (TO)!',
	'clickatell_no_sender_address' => 'Mohon sertakan alamat pengirim (FROM)!',
	'clickatell_unicode_message_too_long' => 'Pesan Unicode anda terlalu panjang! (Panjang sekarang=',
	'clickatell_unsupported_method' => 'Metode pengiriman tidak dikenal!',
	'invalid_api_library' => 'Pustaka API %s tidak berlaku. Semua pustaka API harus merupakan subclass dr %s',
	'upgrade_directory_not_deleted' => 'Directory <code>%s</code> tidak bisa dihapus.',
	'upgrade_extracting_error' => 'Galat pada saat ekstraksi: <code>%s</code>',
	'upgrade_failed' => 'Pengunduhan versi terbaru Ushahidi gagal. Status kode HTTP',
	'upgrade_file_not_copied' => 'Berkas <code>%s</code> tidak bisa disalin',
	'upgrade_file_not_deleted' => 'Berkas <code>%s</code> tidak bisa dihapus',
	'upgrade_title' => 'Skrip upgrade Ushahidi',
	'upgrade_zip_error' => 'Berkas zip Ushahidi yang diunduh <code>%s</code>, tidak bisa ditulis',
);
