<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:43+0000
$lang = array(
	'captcha' => array(
		'default' => 'Masukan kode keamanan yang valid',
		'required' => 'Masukan kode keamanan',
	) ,
	'email' => array(
		'email' => 'Isi kolom alamat e-mail, salah ?',
		'length' => 'Panjang alamat e-mail minimal 4 karakter dan tidak boleh lebih dari 64 karakter',
		'required' => 'Kalau cek box dicentang kolom alamat e-mail tidak boleh dikosongkan',
	) ,
	'message' => array(
		'required' => 'Kolom komentar tidak boleh dikosongkan',
	) ,
	'name' => array(
		'length' => 'Panjang kolom nama minimal 3 karakter',
		'required' => 'Kolom nama tidak boleh dikosongkan',
	) ,
	'phone' => array(
		'length' => 'Isi kolom telpon salah.',
	) ,
);
