<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:44+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'Masukan kode keamanan yang valid',
		'required' => 'Masukan kode keamanan',
	) ,
	'contact_email' => array(
		'email' => 'Isi kolom alamat e-mail salah ?',
		'required' => 'Mohon pastikan alamat e-mail diisikan sudah benar.',
	) ,
	'contact_message' => array(
		'required' => 'Kolom pesan tidak boleh dikosongkan',
	) ,
	'contact_subject' => array(
		'length' => 'Panjang isi kolom subjek minimal 3 karakter',
		'required' => 'Kolom subjek tidak boleh dikosongkan',
	) ,
);
