<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:45+0000
$lang = array(
	'admin_footer' => 'Pesan ini dikirmkan dr situs',
	'admin_login_url' => 'Login administrator',
	'admin_new_comment' => array(
		'message' => 'Sebuah komentar baru dikirimkan ke situs untuk menanggapi :',
		'subject' => 'Komentas baru',
	) ,
	'admin_new_email' => array(
		'message' => 'Sebuah e-mail baru telah dikirim ke situs anda',
		'subject' => 'Pesan e-mail baru',
	) ,
	'admin_new_report' => array(
		'message' => 'Sebuah laporan baru telah dikirimkan ke situs anda',
		'subject' => 'Laporan baru',
	) ,
	'admin_new_sms' => array(
		'message' => 'Sebuah pesan teks telah dikirim ke situs anda',
		'subject' => 'Pesan teks baru',
	) ,
);
