<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-22 06:23+0000
// PO revision date:  2013-10-21 10:41+0000
$lang = array(
	'reports_view' => 'Menampilkan Laporan',
	'reports_edit' => 'Buat/Sunting/Hapus Laporan',
	'reports_approve' => 'Menyetujui Laporan',
	'reports_verify' => 'Verifikasi Laporan',
	'reports_comments' => 'Atur Komentar dalam Laporan',
	'reports_download' => 'Unduh Laporan',
	'reports_upload' => 'Unggah Laporan',
	'messages' => 'Pengaturan Pesan',
	'messages_reporters' => 'Pengaturan Pesan Pelapor',
	'stats' => 'Lihat Status',
	'settings' => 'Ubah Pengaturan',
	'manage' => 'Pengaturan Panel',
	'users' => 'Pengaturan Pengguna',
	'manage_roles' => 'Pengaturan Hak Akses',
	'checkin' => 'Bisa checkin',
	'checkin_admin' => 'Pengaturan checkin',
	'admin_ui' => 'Akses UI Admin',
	'member_ui' => 'Akses UI Anggota',
	'delete_all_reports' => 'Hapus semua laporan',
);
