<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-28 06:23+0000
// PO revision date:  2013-10-27 10:46+0000
$lang = array(
	'latitude' => array(
		'between' => 'Isi pada kolom Lintang tidak benar. ',
		'required' => 'Kolom Lintang tidak boleh dikosongkan. Anda bisa klik lokasi di peta untuk lokasi yang diinginkan.',
	) ,
	'level_id' => array(
		'numeric' => 'Isi pada kolom Level Reporter tidak benar.',
		'required' => 'Isi pada kolom Level Reporter tidak benar.',
	) ,
	'location_name' => array(
		'length' => 'Nama lokasi setidaknya terdiri atas 3 dan tidak lebih dari 200 karakter.',
		'required' => 'Kolom nama lokasi tidak boleh dikosongkan.',
	) ,
	'longitude' => array(
		'between' => 'Isi pada kolom Bujur tidak benar. ',
		'required' => 'Kolom Bujur tidak boleh dikosongkan. Anda bisa klik lokasi di peta untuk lokasi yang diinginkan.',
	) ,
	'reporter_id' => array(
		'numeric' => 'Pelapor Tidak Dikenal',
		'required' => 'Pelapor Tidak Dikenal',
	) ,
);
