<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-17 06:23+0000
// PO revision date:  2013-10-16 17:28+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Pastikan Anda telah memilih satu pilihan.',
		'numeric' => 'Pastikan Anda telah memilih satu pilihan.',
		'categories_required' => 'Laporan harus dikategorisasikan sebelum disetujui.',
	) ,
	'action' => array(
		'permission' => 'Anda tidak memiliki ijin untuk menajlankan perintah ini.',
	) ,
	'uploadfile' => array(
		'required' => 'Anda harus memilih satu buah file untuk diunggah.',
		'type' => 'File yang diunggah harus dalam bentuk .csv atau .xml.',
		'valid' => 'File yang Anda unggah sepertinya tidak benar.',
	) ,
);
