<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:48+0000
$lang = array(
	'comments_form_error' => 'Galat !',
	'custom_field' => array(
		'values' => 'Mohon masukan nilai yang valid untuk salah satu kolom formulir buatan anda',
	) ,
	'data_include' => array(
		'between' => 'Mohon pilih item yang valid untuk di unduh',
		'numeric' => 'Mohon pilih item yang valid untuk di unduh',
	) ,
	'data_point' => array(
		'between' => 'Mohon pilih laporan yang valid untuk di unduh',
		'numeric' => 'Mohon pilih laporan yang valid untuk di unduh',
		'required' => 'Mohon pilih laporan yang valid untuk di unduh',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'Isi kolom tanggal dari, salah ?',
		'range' => 'Mohon masukan tanggal dari yang benar. Tanggal tidak boleh lebih besar dr hari ini',
	) ,
	'incident_active' => array(
		'between' => 'Mohon isi kolom Approve This Report dengan benar.',
		'required' => 'Mohon isi kolom Approve This Report dengan benar.',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'Isi kolom am/pm, salah ?',
	) ,
	'incident_category' => array(
		'numeric' => 'Isi kolom kategori, salah ?',
		'required' => 'Kolom kategori tidak boleh dikosongkan',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'Isi kolom tanggal, salah ?',
		'date_mmddyyyy' => 'Isi kolom tanggal, salah ?',
		'required' => 'Kolom tanggal tidak boleh dikosongkan',
	) ,
	'incident_description' => array(
		'required' => 'Kolom keterengan tidak boleh dikosongkan',
	) ,
	'incident_hour' => array(
		'between' => 'Isi kolom jam, salah ?',
		'required' => 'Kolom jam tidak boleh dikosongkan',
	) ,
	'incident_information' => array(
		'alpha' => 'Masukan nilai yang valid untuk peluang informasi',
		'length' => 'Masukan nilai yang valid untuk peluang informasi',
	) ,
	'incident_minute' => array(
		'between' => 'Isi kolom menit, salah ?',
		'required' => 'Kolom menit tidak boleh dikosongkan',
	) ,
	'incident_news' => array(
		'url' => 'URL pada kolom tautan sumber berita, salah ?',
	) ,
	'incident_photo' => array(
		'size' => 'Mohon pastikan besar foto yang diunggah tidak lebih dr 2Mb',
		'type' => 'Isi kolom Upload Photo, salah. Format yang berlaku hanya .JPG, .PNG dan .GIF',
		'valid' => 'Isi kolom Upload Photo, salah.',
	) ,
	'incident_source' => array(
		'alpha' => 'Mohon sertakan kehandalan sumber berita yang valid',
		'length' => 'Mohon sertakan kehandalan sumber berita yang valid',
	) ,
	'incident_title' => array(
		'length' => 'Panjang judul minimal 3 karakter dan tidak boleh lebih dr 200 karakter',
		'required' => 'Judul tidak boleh dikosongkan',
	) ,
	'incident_verified' => array(
		'between' => 'Mohon isi kolom Verify this report dengan benar',
		'required' => 'Mohon isi kolom Verify this report dengan benar',
	) ,
	'incident_video' => array(
		'url' => 'URL pada isi kolom tautan video, salah.',
	) ,
	'latitude' => array(
		'between' => 'Isi kolom latitude, salah ?',
		'required' => 'Kolom latitude tidak boleh dikosongkan. Mohon klik pada peta untuk mendefiniskan lokasinya',
	) ,
	'locale' => array(
		'alpha_dash' => 'Isi kolom pengaturan lokal, salah',
		'exists' => 'Laporan ini sudah diterjemahkan ke bahasa ini',
		'length' => 'Isi kolom pengaturan lokal, salah',
		'locale' => 'Bahasa pada laporan aslinya dan Laporan hasil terjemahannya sama. ',
		'required' => 'Kolom pengaturan lokal tidak boleh dikosongkan',
	) ,
	'location_name' => array(
		'length' => 'Panjang isi pengaturan lokal minmal 3 karakter dan tidak boleh lebih dr 200 karakter',
		'required' => 'Kolom nama lokasi tidak boleh dikosongkan',
	) ,
	'longitude' => array(
		'between' => 'Isi kolom longitude, salah?',
		'required' => 'Kolom longitude tidak boleh dikosongkan. Mohon klik pada peta untuk mendefinisikan lokasinya',
	) ,
	'person_email' => array(
		'email' => 'Isi kolome alamat e-mail, salah?',
		'length' => 'Panjang isi kolom alamat e-mail minimal 4 karakter dan tidak boleh lebih dr 64 karakter',
	) ,
	'person_first' => array(
		'length' => 'Kolom nama panggilan minimal 3 karakter dan tidak boleh lebih dr 100 karakter',
	) ,
	'person_last' => array(
		'length' => 'Kolom nama keluarga minimal 3 karakter dan tidak boleh lebih dr 100 karakter',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'Isi pada kolom tanggal sampai, salah ?',
		'range' => 'Mohon pastikan kolom SAMPAI terisi dengan tanggal yg benar. Tanggal tidak boleh lebih besar dr hari ini.',
		'range_greater' => 'Isi tanggal pada kolom DARI tidak boleh lebih besar dr isi tanggal pada kolom SAMPAI',
	) ,
);
