<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-17 06:23+0000
// PO revision date:  2013-10-16 18:07+0000
$lang = array(
	'description' => array(
		'length' => 'Isi kolom Keterangan minimal 3 karakter dan tidak boleh lebih dari 100 karakter.',
		'required' => 'Kolom Keteranga tidak boleh dikosongkan.',
	) ,
	'name' => array(
		'alpha_numeric' => 'Kolom Nama hanya boleh diisi huruf atau angka.',
		'length' => 'Isi kolom Nama minimal 2 dan tidak boleh lebih dari 30 karakter.',
		'nomodify' => 'Hak Akses SuperAdmin Tidak Bisa Diubah.',
		'required' => 'Kolom Nama tidak boleh dikosongkan.',
	) ,
	'access_level' => array(
		'numeric' => 'Kolom Level Akses harus berisi angka antara 0-100.',
		'required' => 'Kolom Level Akses harus berisi angka antara 0-100.',
	) ,
	'permissions' => array(
		'numeric' => 'Kolom Ijin harus berisi angka antara 0-100.',
	) ,
);
