<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:50+0000
$lang = array(
	'description' => array(
		'length' => 'Panjang isi kolom KETERANGAN minimal 3 karakter dan tidak boleh lebih dr 100 karakter.',
		'required' => 'Kolom KETERANGAN tidak boleh dikosongkan',
	) ,
	'name' => array(
		'alpha_numeric' => 'Kolom NAMA hanya boleh diisi huruf atau angka',
		'length' => 'Panjang isi kolom NAMA minimal 2 dan tidak boleh lebih panjang dr 30 karakter',
		'nomodify' => 'Akun SuperAdmin tidak boleh diubah',
		'required' => 'Kolom NAMA tidak boleh dikosongkan',
	) ,
);
