<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-28 06:23+0000
// PO revision date:  2013-10-28 01:50+0000
$lang = array(
	'actions' => array(
		'add_to_category' => 'Hal ini akan menambahkan laporan ke kategori. Jika Anda memilih Kategori 1 di sini dan laporan sudah dimasukkan dalam Kategori 2, maka laporan akan masuk dalam Kategori 1 dan Kategori 2.',
		'approve' => 'Setujui laporan atau tidak. Jika disetujui maka akan dipublikasikan.',
		'assign_badge' => 'Anda bisa menetapkan sebuah lencana untuk memicu pengguna memasukkan laporan. Pilih lencana yang anda tetapkan di sini.',
		'between_times' => 'Ini adalah rentang waktu dalam jam dan/atau menit antara dua batas waktu dalam format 24 jam. Jika Anda memasukkan waktu yang lebih dulu di kolom kedua, maka yang Anda masukkan akan diubah menjadi awal. Juga bila waktu dicentang berlawanan dengan konfigurasi situs dan <strong>tidak</strong> memerlukan zona waktu yang berbeda antara pengguna dengan situs ini. Masukkan rentang waktu 00:00 hingga 00:00 untuk mengabaikan aturan ini.',
		'category' => 'Jika Anda ingin mengaktifkan pemicu untuk satu kategori saja, Anda bisa mengaturnya di sini. Sebagai contoh, jika Anda memilih Kategori 1 dan Kategori 2 di sini, sedangkan laporan dimasukkan Kategori 2 dan 3 maka aturan Anda akan diabaikan.',
		'days_of_the_week' => 'Jika kejadian berlangsung selama beberapa hari dalam seminggu, atur di sini. Ingat bahwa ada aturan mengenai zona waktu. Gunakan tombol Shift, Command atau Control untuk memilih hari yang berbeda-beda.',
		'email_body' => 'Isi surel yang hendak dikirim.',
		'email_subject' => 'Judul surel yang hendak dikirim.',
		'keywords' => 'Anda bisa mengosongkannya bila tidak ingin memeriksa kata kunci. Jika Anda memasukkan beberapa kata, pisahkan dengan tanda koma (,). Misalnya Anda ingin mengaktifkan pemicu jika ada yang menyebutkan "cinta" atau "sayang" dalam pesannya, Anda harus menuliskannya dengan "cinta, sayang" dalam kotak kata kunci.',
		'location' => 'Anda dapat memilih di mana saja atau lokasi tertentu. Jika Anda memilih lokasi tertentu, Anda akan diminta untuk menggambar kotak sekitar area sesuai kejadian. Misalnya, jika Anda ingin pemicu ini diaktifkan ketika seseorang menyampaikan laporan di Brazil, Anda akan memilih "area spesifik" dan kemudian menggambar kotak di sekitar Brazil. Anda dapat membuat kotak-kotak ini kecil atau besar sesuai keinginan. Anda juga dapat menggambar beberapa kotak sekaligus.',
		'on_specific_count' => 'Kualifikasi ini akan mengaktifkan pemicu pada bilangan ke-N, baik untuk seleuruh pengguna atau untuk satu pengguna saja. Jika Anda ingin mengabaikan, kosongkan saja.',
		'report_title' => 'Ini adalah judul standar untuk menambahkan laporan.',
		'response' => 'Jika semua kualifikasi di atas dilalui, maka pemicu akan memberi tanggapan. Hal ini dapat berupa menyetujui laporan ke surel pengguna. Pilih tanggapan di sini untuk mengaktifkan pilihan tambahan untuk tanggapan khusus.',
	) ,
	'dropdown_choices' => 'Pisahkan setiap pilihan dengan sebuah tanda koma, misalnya Bagian 1, Bagian 2 dan seterusnya.',
	'private_to' => 'Silahkan mulai menulis untuk para anggota dalam daftar. ',
	'private_subject' => 'Judul pesan pribadi',
	'private_message' => 'Pesan pribadi',
	'profile_color' => 'Anda bisa memilih warna yang muncul di bawah gambar profil dalam halaman profil Anda. Warna ini juga akan menjadi warna pada setiap titik di mana Anda checkin.',
	'profile_email' => 'Alamat surel Anda',
	'profile_public_url' => 'Ini adalah alamat profil publik Anda.',
	'profile_username' => 'Nama pengguna tidak bisa diubah.',
	'settings_allow_alerts' => 'Ijinkan pengguna untuk mendaftarkan peringatan melalui situs.',
);
