<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:26+0000
$lang = array(
	'category_color' => array(
		'length' => 'Sehemu ya rangi lazma iwe herufi 6.',
		'required' => 'Sehemu ya rangi inahitajika.',
	) ,
	'category_description' => array(
		'required' => 'Sehemu ya elezo inahitajika.',
	) ,
	'category_image' => array(
		'size' => 'Tafadhali hakikisha faili ya picha haipiti 50KB.',
		'type' => 'Sehemu ya picha inaonekana haina faili ilio sawa. Picha zinazokubalika ni za .JPG, .PNG na .GIF.',
		'valid' => 'Sehemu ya picha inaonekana haina faili ilio sawa',
	) ,
	'category_title' => array(
		'length' => 'Jina la jamii lazima liwe baina ya herifi 3 na 80.',
		'required' => 'Jina la jamii linahitajika.',
	) ,
	'parent_id' => array(
		'exists' => 'Jamii mzazi uliotupatia haipo.',
		'numeric' => 'Jamii mzazi lazma iwe nambari.',
		'required' => 'Jamii mzazi inatakikana.',
		'same' => 'Jamii pamoja na jamii mzazi haziezi kuwa sawa.',
	) ,
);
