<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-03 00:02+0000
$lang = array(
	'field_default' => array(
		'length' => 'Jina la uga lazima liwe baina ya heufi 3 na 100.',
	) ,
	'field_height' => array(
		'between' => 'Tafadhali andika baina ya 0 na 50 kwenye sehemu ya urefu wa uga',
	) ,
	'field_isdate' => array(
		'between' => 'Umeandika kimakosa kwenye sehemu ya tarehe ya uga ya tarehe',
		'required' => 'Tafadhali chagua Ndio au La kwa sehemu ya uga ya tarehe',
	) ,
	'field_name' => array(
		'length' => 'Jina la uga lazima liwe baina ya hefuri 3 na 100.',
		'required' => 'Tafadhali andika jina la uga.',
	) ,
	'field_required' => array(
		'between' => 'Tafadhali chagua neno la sahihi kwa sehemu ya kuhitajika kwa uga',
		'required' => 'Tafadhali chagua Ndio au La kwa sehemu ya kuhitajika kwa uga',
	) ,
	'field_type' => array(
		'numeric' => 'Tafadhali chagua aina ya uga.',
		'required' => 'Tafadhali chagua aina ya uga.',
	) ,
	'field_width' => array(
		'between' => 'Tafadhali andika baina ya 0 na 300 kwenye sehemu ya upana wa uga',
	) ,
	'form_description' => array(
		'required' => 'Tafadhali andika elezo la fomu.',
	) ,
	'form_id' => array(
		'default' => 'Fomu ya awali haiezi kufutwa.',
		'numeric' => 'Tafadhali chagua fomu ambayo itaongezewa uga.',
		'required' => 'Tafadhali chagua fomu ambayo itaongezewa uga.',
	) ,
	'form_title' => array(
		'length' => 'Jina la fomu lazima liwa baina ya herufi 3 na 100.',
		'required' => 'Tafadhali andika jina la fomu.',
	) ,
);
