<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:41+0000
$lang = array(
	'layer_color' => array(
		'length' => 'Sehemu ya rangi lazma iwe na herufi 6.',
		'required' => 'Sehemu ya rangi inahitajika.',
	) ,
	'layer_file' => array(
		'type' => 'Sehemu ya faili inaonekana kutokuwa na faili iliyo hitajika. Faili zinazokubalika ni za .KMZ, .KML.',
		'valid' => 'Sehemu ya faili inaonekana kutokuwa na faili iliyo hitajika',
	) ,
	'layer_name' => array(
		'length' => 'Sehemu ya jina lazima iwe baina ya herufi 3 na 80.',
		'required' => 'Sehemu ya jina inahitajika.',
	) ,
	'layer_url' => array(
		'atleast' => 'Anwani ya KML au faili inahitajika',
		'both' => 'Huwezi kuwa na KML na faili pamoja',
		'url' => 'Tafadhali andika anwani iliyo sahihu. kwa mfano: http://www.ushahidi.com/layerl.kml',
	) ,
);
