<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:43+0000
$lang = array(
	'captcha' => array(
		'default' => 'Tafadhali andika ishara ya ulinzi iliyo sahihi',
		'required' => 'Tafadhali andika ishara ya ulinzi',
	) ,
	'email' => array(
		'email' => 'Anwani ya barua pepe inaonekana si sahihi',
		'length' => 'Anwani ya barua pepe lazima iwe baina ya herufi 4 na 64.',
		'required' => 'Anwani ya barua pepe inahitajika kama kisanduku tiki chake kimewekwa tiki.',
	) ,
	'message' => array(
		'required' => 'Sehemu ya fikira inahitajika.',
	) ,
	'name' => array(
		'length' => 'Sehemu ya jina lazima iwe herufi 3 au zaidi.',
		'required' => 'Sehemu ya jina inahitajika.',
	) ,
	'phone' => array(
		'length' => 'Sehemu ya nambari ya simu si sahihi.',
	) ,
);
