<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-03 18:57+0000
$lang = array(
	'admin_footer' => 'Ujumbe huu ulitumwa kutoka kwa tovuti yako',
	'admin_login_url' => 'Kiingilizi cha meneja',
	'admin_new_comment' => array(
		'message' => 'Fikira mpya zimeletwa kwa tovuti yako kutokana na:',
		'subject' => 'Maoni mapya',
	) ,
	'admin_new_email' => array(
		'message' => 'Ujumbe mpya kutoka kwa simu ya rununu umeletwa kwa tovuti yako.',
		'subject' => 'Ujumbe mpya kutoka kwa barua pepe',
	) ,
	'admin_new_report' => array(
		'message' => 'Repoti mpya imetumwa kwa tovuti yako.',
		'subject' => 'Repoti mpya',
	) ,
	'admin_new_sms' => array(
		'message' => 'Ujumbe mpya kutoka kwa simu ya rununu umeletwa kwa tovuti yako.',
		'subject' => 'Ujumbe mpya kutoka kwa simu ya rununu',
	) ,
	'member_new_alert' => array(
		'message' => 'Umepokea tahadhari mpya',
		'subject' => 'Tahadhari mpya!',
	) ,
	'member_new_message' => array(
		'message' => 'Umepokea ujumbe wa kibinafsi',
		'subject' => 'Ujumbe mpya wa kibinafsi',
		'footer' => 'Ili kujibu tafadhali nenda',
	) ,
);
