<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-17 07:01+0000
$lang = array(
	'date' => 'Tarehe ingress',
	'date_added' => 'Tarehe iliengezwa',
	'last_access' => 'Tarehe ya mwisho kushikwa',
	'sharing_color' => array(
		'length' => 'Sehemu ya rangi lazima iwe na herufi 6.',
		'required' => 'Sehemu ya rangi inahitajika.',
	) ,
	'sharing_url' => array(
		'exists' => 'Anwani ya tovuti ilishasajilishwa',
		'required' => 'Sehemu ya anwani ya tovuti inahitajika.',
		'url' => 'Sehemu ya anwani ya tovuti inaonekana si sahihi',
	) ,
);
