<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-07-12 21:52+0000
$lang = array(
	'approved' => 'Imepitishwa',
	'categories' => 'Jamii',
	'category_impact' => 'Athari ya jamii',
	'category_impact_description' => 'Chati hii inakupa inakuonyesha repoti ya jamii kwa muda maalum. Buruta kutoka kishoto mpaka kulia kuona jamii tofauti. Elekeza puku juu ya chati kupata maarifa zaidi',
	'choose_date_range' => 'Chagua muda wa tarehe',
	'countries' => 'Nchi',
	'country' => 'Nchi',
	'country_breakdown' => 'Mvunjo kwa nchi',
	'description' => 'Karibu, hii ni sehemu ya takwimu. Maelezo kwa ujumla itakuja hapa. Kwa sasa jivinjari kwa kuangalia jamii tofauti',
	'error' => 'Kosa',
	'glossary' => 'Kamusi',
	'hit_summary' => 'Muhtasari wa hits',
	'legend' => 'Ngano',
	'pageviews' => 'Mara kurasa imefunguliwa',
	'pageviews_description' => 'Kurasa zilofunguliwa na wageni kwa tovuti',
	'reports' => 'Ripoti',
	'reports_categories' => 'Jamii za ripoti',
	'reports_statistics' => 'Takwimu za ripoti',
	'reports_status' => 'Msimamo wa ripoti',
	'report_stats' => 'Msimamo wa ripoti',
	'stats_not_setup' => 'Takwimu hazijaezeshwa',
	'time_range_1' => 'Mwezi 1',
	'time_range_2' => 'Miezi 3',
	'time_range_3' => 'Miezi 6',
	'time_range_all' => 'Zote',
	'unapproved' => 'Haijapitishwa',
	'unique_visitors' => 'Wageni wa kipekee',
	'unique_visitors_description' => 'Watu waliokuja kwa Ushahidi hii; Wageni wa kipekee wanajulikana kwa kutumia cookies. Kama mgeni hajawezesha cookies, watajulikana kwa anwani ya njia zenginezo',
	'unverified' => 'Haijathabitishwa',
	'verified' => 'Imethibitishwa',
	'visitor_summary' => 'Muhtasari wa wageni',
	'visits' => 'Ziara',
	'visits_description' => 'Ziara ni rekodi ya wageni wa kipekee wanaokuja kwa tovuti kwa dekika 30 baada ziara yake ya mwisho',
);
