<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-20 12:02+0000
$lang = array(
	'profile_email' => 'Anwani yako ya barua pepe',
	'profile_name' => 'Jina lako kwa kamili',
	'profile_notify' => 'Kuchagua NDIO itakutanabahisha kwa barua pepe iwapo ripoti mpya au fikira mpya zimewekwa kwa tovuti',
	'profile_password' => 'Nywila yako. Usjiaze kama huna nia ya kuibadilisha',
	'profile_username' => 'Jina lako la mtumizi haiezi badilishwa',
	'settings_alert_email' => 'Hii ndio anwani ya barua pepe ambayo itatumiwa kutanabahisha kwa barua pepe.',
	'settings_display_contact' => 'Washa au zima fomu ya mawasiliano.',
	'settings_locale' => 'Inaweka lugha itakayotumika kwa tovuti.',
	'settings_site_email' => 'Hii ndio anwani ya barua pepe itakayopata repoti na ujumbe kutoka kwa fomu ya mawasiliano.',
	'settings_site_name' => 'Hili ni jina la tovuti linalotokea juu ya tovuti.',
	'settings_site_tagline' => 'Kwa maneno machache, Eleza hii tovuti ina malengo gani.',
);
