<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-03 06:23+0000
// PO revision date:  2013-10-03 02:29+0000
$lang = array(
	'action' => array(
		'permission' => 'ఈ పని చేయడానికి మీకు అనుమతి లేదు',
	) ,
	'uploadfile' => array(
		'required' => 'మీరు ఎక్కించడానికి ఏదో ఒక దస్త్రాన్ని ఎంచుకోవాలి',
		'type' => 'ఎక్కించే దస్త్రం .csv లేదా .xml అయి ఉండాలి',
		'valid' => 'దస్త్రం ఎక్కింపు స్థానంలో సరైన దస్త్రం ఉన్నట్టు కనిపించడం లేదు',
	) ,
);
