<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 14:19+0000
$lang = array(
	'categories' => 'వర్గాలు',
	'countries' => 'దేశాలు',
	'country' => 'దేశం',
	'time_range_1' => '1 నెల',
	'time_range_2' => '3 నెలలు',
	'time_range_3' => '6 నెలలు',
);
