<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-18 12:03+0000
// PO revision date:  2012-07-12 21:24+0000

$lang = array (
  'email' => 
  array (
    'email' => 'het opgegeven e-mail adres lijkt ongeldig.',
    'exists' => 'Er bestaat al een gebruiker met het opgegeven e-mail adres',
    'length' => 'Het e-mail adres dient uit tenminste 4 en maximaal 64 tekens te bestaan',
    'required' => 'Een geldig e-mail adres is verplicht.',
  ),
  'name' => 
  array (
    'length' => 'Een volledige naam moet tenminste 3 en niet meer dan 100 tekens bevatten.',
    'required' => 'Volledige naam is verplicht.',
    'standard_text' => 'De gebruikersnaam bevat ongeldige tekens',
  ),
  'password' => 
  array (
    'length' => 'Een wachtwoord moet tenminste 5 en maximaal 16 tekens bevatten.',
    'login error' => 'Controleer het wachtwoord.',
    'matches' => 'Herhaal het wachtwoord.',
    'required' => 'Wachtwoord is verplicht.',
  ),
  'password_confirm' => 
  array (
    'matches' => 'De wachtwoord bevestiging moet hetzelfde zijn als het wachtwoord.',
  ),
  'resetemail' => 
  array (
    'email' => 'Er is geen geldig e-mail adres ingevuld',
    'invalid' => 'Het e-mail adres is niet bekend',
    'required' => 'E-mail is verplicht.',
  ),
  'roles' => 
  array (
    'alpha_numeric' => 'Ongeldige rol.',
    'length' => 'Een rol moet tenminste 5 en maximaal 30 tekens bevatten.',
    'required' => 'Er dient tenminste een rol te worden gedefinieerd.',
    'values' => 'Selecteer ADMIN of USER als rol.',
  ),
  'username' => 
  array (
    'admin' => 'De ADMIN rol kan niet worden gewijzigd.',
    'exists' => 'De opgegeven gebruikersnaam is al in gebruik.',
    'length' => 'Een gebruikersnaam moet tenminste 2 en maxiimaal 16 tekens bevatten',
    'login error' => 'Controleer of de gebruikersnaam juist is.',
    'required' => 'Gebruikersnaam is verplicht',
    'superadmin' => 'De SUPER ADMIN rol kan niet worden gewijzigd.',
  ),
);

