<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 22:58+0000
$lang = array(
	'friday' => array(
		'abbv' => 'Vr',
		'full' => 'Vrijdag',
	) ,
	'monday' => array(
		'abbv' => 'Ma',
		'full' => 'Maandag',
	) ,
	'saturday' => array(
		'abbv' => 'Za',
		'full' => 'Zaterdag',
	) ,
	'sunday' => array(
		'abbv' => 'Zo',
		'full' => 'Zondag',
	) ,
	'thursday' => array(
		'abbv' => 'Do',
		'full' => 'Donderdag',
	) ,
	'tuesday' => array(
		'abbv' => 'Di',
		'full' => 'Dinsdag',
	) ,
	'wednesday' => array(
		'abbv' => 'Wo',
		'full' => 'Woensdag',
	) ,
	'january' => array(
		'full' => 'Januari',
	) ,
	'february' => array(
		'full' => 'Februari',
	) ,
	'march' => array(
		'abbv' => 'Maa',
		'full' => 'Maart',
	) ,
	'may' => array(
		'abbv' => 'Mei',
		'full' => 'Mei',
	) ,
	'june' => array(
		'full' => 'Juni',
	) ,
	'july' => array(
		'full' => 'Juli',
	) ,
	'august' => array(
		'full' => 'Augustus',
	) ,
	'october' => array(
		'abbv' => 'Okt',
		'full' => 'Oktober',
	) ,
);
