<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-27 18:04+0000
// PO revision date:  2012-07-12 21:32+0000

$lang = array (
  'am' => 'am',
  'friday' => 
  array (
    'abbv' => 'Vr',
    'full' => 'Vrijdag',
  ),
  'monday' => 
  array (
    'abbv' => 'Ma',
    'full' => 'Maandag',
  ),
  'pm' => 'pm',
  'saturday' => 
  array (
    'abbv' => 'Za',
    'full' => 'Zaterdag',
  ),
  'sunday' => 
  array (
    'abbv' => 'Zo',
    'full' => 'Zondag',
  ),
  'thursday' => 
  array (
    'abbv' => 'Do',
    'full' => 'Donderdag',
  ),
  'tuesday' => 
  array (
    'abbv' => 'Di',
    'full' => 'Dinsdag',
  ),
  'wednesday' => 
  array (
    'abbv' => 'Wo',
    'full' => 'Woensdag',
  ),
);

