<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-16 12:03+0000
// PO revision date:  2012-07-12 21:39+0000

$lang = array (
  'base_path' => 'Systeempad',
  'database' => 'Database',
  'database_host' => 'Database server',
  'database_host_description' => 'Wanneer je Ushahidi uitvoert op je eigen computer, dan is dit waarschijnlijk "localhost". Wanneer je Ushahidi uitvoert op een web server, controleer dan de server naam en informatie van de provider',
  'database_name' => 'Databasenaam',
  'database_name_description' => 'De naam van de database waarin de gegevens van Ushahidi worden opgeslagen',
  'default_language' => 'Standaard taal (Landinstelling)',
  'disable' => 'Uitschakelen',
  'enable' => 'Inschakelen',
  'finished' => 'Gereed',
  'general' => 'Algemeen',
  'google_key' => '<span>Google</span> API sleutel',
  'google_key_description' => 'API sleutels voor Google Maps zijn <a id="api-link" href="http://code.google.com/apis/maps/signup.html" target="_blank">hier</a> aan te vragen',
  'go_back' => 'Terug',
  'index' => 
  array (
    'advanced' => 'Geavanceerde installatie',
    'basic_installation' => 'Standaard installatie',
    'proceed' => 'Doorgaan',
  ),
  'installation_successful' => 'Installatie gelukt',
  'mail_server' => 'Mail server',
  'mail_server_host' => 'Mail server adres',
  'map' => 'Kaart',
  'map_provider' => 'Kaartaanbieder',
  'password' => 'Wachtwoord',
  'previous' => 'Vorige',
  'select_mail_server_ssl' => 'SSL in- of uitschakelen',
  'setup_sms' => 'SMS server instellen',
  'site_email' => 'E-mail adres van deze website',
  'site_name' => 'Website Naam',
  'site_name_description' => 'Naam van de website',
  'table_prefix' => 'Tabel Prefix',
  'title' => 'Titel',
  'to_login' => 'Om aan te melden, ga naar',
  'username' => 'Gebruikersnaam',
  'username_description' => 'Database gebruikersnaam',
  'view_site' => 'Website bekijken',
);

