<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 22:58+0000
$lang = array(
	'captcha' => array(
		'default' => 'Please enter a valid security code',
		'required' => 'Please enter the security code',
	) ,
	'email' => array(
		'email' => 'The Email field does not appear to contain a valid email address?',
	) ,
);
