<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 22:58+0000
$lang = array(
	'admin_footer' => 'This message was sent from your website',
	'member_new_alert' => array(
		'message' => 'Je hebt een nieuw alarm ontvangen',
		'subject' => 'Nieuw alarm!',
	) ,
	'member_new_message' => array(
		'message' => 'Je hebt een nieuw privébericht ontvangen',
		'subject' => 'Nieuw privébericht',
		'footer' => 'Om te antwoorden ga naar:',
	) ,
);
