<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 22:59+0000
$lang = array(
	'category_impact_description' => 'This chart gives you a linear view of the reports by category over time.  Scroll from left to right to see a comparative view of the different categories. Mouse over the graph for more details',
	'choose_date_range' => 'Choose a date range',
	'description' => 'Hello, this is the statistics section. General description going here soon. For now, browse around using the sub category links above',
	'reports' => 'Berichten',
	'reports_categories' => 'Berichtcategorie&euml;n',
	'reports_statistics' => 'Berichtstatistiek',
	'reports_status' => 'Berichtstatus',
	'unique_visitors_description' => 'The number of individuals coming to your deployment; Unique Visitors are determined using cookies. In the case that a visitor does not have cookies enabled, they will be identified using a simple heuristic taking into account IP address, resolution, browser, plugins, OS, etc',
	'visits_description' => 'A visit is a record of a unique visitor coming to the site more than 30 minutes past his/her last pageview',
);
