<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 23:00+0000
$lang = array(
	'upgrade' => array(
		'between' => 'Ongeldige invoer. De geaccepteerde waarden zijn 0 voor Nee en 1 voor Ja.',
	) ,
	'upgrade_automatic' => 'Automatisch upgraden',
	'upgrade_available' => 'Beschikbare updates',
	'upgrade_continue_btn_text' => 'Doorgaan',
	'upgrade_db_text_1' => 'Ik zal dus je database upgraden van versie',
	'upgrade_db_text_2' => 'naar de nieuwste databaseversie',
	'upgrade_failed' => 'De upgrade is niet gelukt',
	'upgrade_manual' => 'Handmatige upgrade',
	'upgrade_text_2' => '<strong>Stap 1:</strong> Download de meest recente ushahidi versie op <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
	'upgrade_text_6' => 'Klik de knop hieronder voor automatisch upgraden',
	'upgrading' => 'Bezig met het uitvoeren van de upgrade',
	'upgrade_ftp_password' => 'FTP paswoord:',
	'upgrade_ftp_username' => 'FTP gebruikersnaam:',
	'upgrade_status_info' => 'Je hebt de meest recente versie van Ushahidi.',
	'upgrade_db_version' => 'Databaseversie: %d',
	'log_file' => 'Logbestand',
	'failed_downloading' => 'Het downloaden is mislukt.',
	'failed_unpacking' => 'Het uitpakken is mislukt.',
);
