<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-13 18:05+0000
// PO revision date:  2012-08-13 08:24+0000

$lang = array (
  'upgrade' => 
  array (
    'between' => 'Ongeldige invoer. De geaccepteerde waarden zijn 0 voor Nee en 1 voor Ja.',
  ),
  'upgrade_automatic' => 'Automatisch upgraden',
  'upgrade_available' => 'Beschikbare updates',
  'upgrade_continue_btn_text' => 'Doorgaan',
  'upgrade_db_btn_text' => 'Upgrade',
  'upgrade_db_text_1' => 'Ik zal dus je database upgraden van versie',
  'upgrade_db_text_2' => 'naar de nieuwste databaseversie',
  'upgrade_db_title' => 'Ushahidi database upgrade',
  'upgrade_failed' => 'De upgrade is niet gelukt',
  'upgrade_manual' => 'Handmatige upgrade',
  'upgrade_status' => 'Ushahidi upgrade status',
  'upgrade_text_2' => '<strong>Stap 1:</strong> Download de meest recente ushahidi versie op <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
  'upgrade_text_6' => 'Klik de knop hieronder voor automatisch upgraden',
  'upgrading' => 'Bezig met het uitvoeren van de upgrade',
  'upgrade_ftp_password' => 'FTP paswoord:',
  'upgrade_ftp_username' => 'FTP gebruikersnaam:',
  'upgrade_status_info' => 'Je hebt de meest recente versie van Ushahidi.',
  'upgrade_db_version' => 'Databaseversie: %d',
  'upgrade_database' => 'Database:',
  'ushahidi_release_version' => 'Ushahidi %s',
  'beta' => 'BETA!',
  'log_file' => 'Logbestand',
  'failed_downloading' => 'Het downloaden is mislukt.',
  'failed_unpacking' => 'Het uitpakken is mislukt.',
);

