<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-25 00:04+0000
// PO revision date:  2012-07-12 21:24+0000

$lang = array (
  'email' => 
  array (
    'email' => 'Câmpul de e-mail nu pare să conţină o adresă de e-mail validă.',
    'exists' => 'Există deja un cont pentru această adresă e-mail.',
    'length' => 'Câmpul de e-mail trebuie să conţină cel puţin 4 şi nu mai mult de 64 caractere.',
    'required' => 'Câmpul de e-mail este necesar.',
  ),
  'name' => 
  array (
    'length' => 'Câmpul pentru nume trebuie să fie de cel puţin 3 şi nu mai mult de 100 de caractere.',
    'required' => 'Câmpul Numele Complet este necesar.',
    'standard_text' => 'Câmpul Nume de utilizator conţine caractere nepermise.',
  ),
  'password' => 
  array (
    'length' => 'Câmpul Parolă trebuie să fie de cel puţin 5 şi nu mai mult 16 caractere.',
    'matches' => 'Vă rugăm să introduceţi aceeaşi parolă în ambele câmpuri pentru parolă.',
    'required' => 'Câmpul Parolă este necesar.',
  ),
  'password_confirm' => 
  array (
    'matches' => 'Câmpul de Confirmare Parolă trebuie să se potrivească câmpului Parolă.',
  ),
  'resetemail' => 
  array (
    'email' => 'Câmpul de e-mail nu pare să conţină o adresă de e-mail validă.',
    'invalid' => 'Ne pare rău, nu avem adresa dumneavoastră de e-mail.',
    'required' => 'Câmpul de E-mail este necesar.',
  ),
  'roles' => 
  array (
    'alpha_numeric' => 'Format Rol nevalid.',
    'length' => 'Câmpul Rolul trebuie să fie de cel puţin 5 şi nu mai mult de 30 caractere lungime.',
    'required' => 'Trebuie să definiţi cel puţin un rol.',
    'values' => 'Trebuie să selectaţi fie rol de ADMIN, fie rol de UTILIZATOR.',
  ),
  'username' => 
  array (
    'admin' => 'Rolul ADMIN nu pot fi modificat.',
    'exists' => 'Ne pare rău, acest nume de utilizator este deja în uz.',
    'length' => 'Campul Numelui de utilizator trebuie să fie de cel puţin 2 şi nu mai mult 16 caractere.',
    'required' => 'Campul Numelui de utilizator este necesar.',
    'superadmin' => 'Rolul de super admin nu poate fi modificat.',
  ),
);

