<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-15 12:04+0000
// PO revision date:  2012-09-13 00:09+0000
$lang = array(
	'captcha' => array(
		'default' => 'Vă rugăm introduceți un cod de securitate valid.',
		'required' => 'Vă rugăm introduceți un cod de securitate.',
	) ,
	'subject' => array(
		'required' => 'Câmpul subiect este necesar.',
	) ,
);
