<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-09 00:05+0000
// PO revision date:  2012-09-08 19:44+0000
$lang = array(
	'category_color' => array(
		'length' => 'Câmpul culoare trebuie să aibă 6 caractere lungime.',
		'required' => 'Câmpul culoare este necesar.',
	) ,
	'category_description' => array(
		'required' => 'Câmpul descriere este necesar.',
	) ,
	'category_image' => array(
		'valid' => 'Câmpul imagine nu pare să conțină un fișier valid',
	) ,
	'parent_id' => array(
		'exists' => 'Categoria părinte nu există.',
		'numeric' => 'Câmpul pentru categoria părinte trebuie să fie numeric.',
	) ,
);
