<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-03 06:10+0000
// PO revision date:  2013-01-02 21:31+0000
$lang = array(
	'config' => 'fișerul de configurare',
	'controller' => 'controlor',
	'driver' => 'driver',
	'driver_implements' => 'Driver-ul %s pentru biblioteca %s trebuie să implementeze interfața %s.',
	'driver_not_found' => 'Driver-ul %s pentru biblioteca %s nu a putut fi găsit.',
	'errors_disabled' => 'Poți merge la <a href="%s">Acasă</a> sau <a href="%s">Încearcă iar</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'Imposibil de a finaliza solicitarea',
	'helper' => 'ajutor',
	'invalid_filetype' => 'Tipul de fișier solicitat, .%s, nu este permis în fișierul dvs. de configurare.',
	'invalid_method' => 'Metoda invalidă %s este apelată în %s',
	'invalid_property' => 'Proprietatea %s nu există în clasa %s.',
	'library' => 'bibliotecă',
	'log_dir_unwritable' => 'Directorul de log nu este writable: %s',
	'model' => 'model',
	'no_default_route' => 'Vă rugăm să setați o rută implicită în config/routes.php',
	'page_not_found' => 'Pagina solicitată, %s, nu a putut fi găsită.',
	'resource_not_found' => '%s, %s, solicitată nu a putut fi găsită',
	'stack_trace' => 'Stack Trace',
	'text_direction' => 'ltr',
	'view' => 'vezi',
);
