<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-18 12:04+0000
// PO revision date:  2012-09-16 17:55+0000
$lang = array(
	'config' => 'fișerul de configurare',
	'driver' => 'driver',
	'driver_implements' => 'Driver-ul %s pentru biblioteca %s trebuie să implementeze interfața %s.',
	'driver_not_found' => 'Driver-ul %s pentru biblioteca %s nu a putut fi găsit.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'library' => 'bibliotecă',
	'model' => 'model',
);
