<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-10-01 10:28+0000
$lang = array(
	'config' => 'fișerul de configurare',
	'controller' => 'controlor',
	'driver' => 'driver',
	'driver_implements' => 'Driver-ul %s pentru biblioteca %s trebuie să implementeze interfața %s.',
	'driver_not_found' => 'Driver-ul %s pentru biblioteca %s nu a putut fi găsit.',
	'errors_disabled' => 'Poți merge la <a href="%s">Acasă</a> sau <a href="%s">Încearcă iar</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'helper' => 'ajutor',
	'library' => 'bibliotecă',
	'model' => 'model',
	'view' => 'vezi',
);
