<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-13 04:30+0000
// PO revision date:  2012-07-13 04:22+0000

$lang = array (
  'error' => 'Eroare bază de date: %s',
  'table_not_found' => 'Tabelul "% s" nu pot fi găsit în baza de date. Vă rugăm să vă asiguraţi că utilizaţi cea mai recentă versiune a bazei de date pentru această versiune de Ushahidi',
);

