<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-05 06:10+0000
// PO revision date:  2013-01-04 16:45+0000
$lang = array(
	'field_name' => array(
		'required' => 'Vă rugăm introduceți câmpul nume.',
	) ,
);
