<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-04 06:10+0000
// PO revision date:  2013-01-03 21:27+0000
$lang = array(
	'akismet_cannot_connect' => 'Nu s-a putut conecta la serverul Akismet.',
	'akismet_cannot_retrieve' => 'Răspunsul de la Akismet nu a putut fi recuperat.',
	'api_library_not_found' => 'Biblioteca API: <strong>%s</ strong> pentru clasa <strong>%s</ strong> nu a putut fi găsită. Vă rugăm să verificați activitățile API din tabelul de rutare.',
	'askimet_invalid_apikey' => 'Cheia dvs. Akismet API nu este validă.',
	'clickatell_fopen_error' => 'Eroare în timpul execuției metodei de trimitere fopen!<br>Vă rugăm să verificați dacă PHP are suport OpenSSL și dacă versiunea PHP este mai mare de 5.2.',
	'clickatell_message_too_long' => 'Mesajul dvs. unicode este prea lung! (Lungimea curentă=',
	'clickatell_no_destination_address' => 'Vă rugăm specificați o adresă de destinație (TO)!',
	'clickatell_no_sender_address' => 'Vă rugăm specificați o adresă de expediție (FROM)!',
	'clickatell_unicode_message_too_long' => 'Mesajul dvs. unicode este prea lung! (Lungimea curentă=',
	'clickatell_unsupported_method' => 'Metodă de trimitere neacceptată!',
	'upgrade_directory_not_deleted' => 'Directorul <code>%s</coded> nu poate fi șters.',
	'upgrade_file_not_copied' => 'Fișierul <code>%s</coded> nu poate fi copiat.',
	'upgrade_file_not_deleted' => 'Fișierul <code>%s</coded> nu poate fi șters.',
	'upgrade_title' => 'Script pentru upgrade Ushahidi',
);
