<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-05 06:10+0000
// PO revision date:  2013-01-04 18:19+0000
$lang = array(
	'comments_form_error' => 'eroare!',
	'data_active' => array(
		'between' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
		'numeric' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
		'required' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
	) ,
	'data_verified' => array(
		'between' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
		'numeric' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
		'required' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
	) ,
	'data_point' => array(
		'between' => 'Vă rugăm să selectați un tip valid de raport pentru descărcare.',
		'numeric' => 'Vă rugăm să selectați un tip valid de raport pentru descărcare.',
		'required' => 'Vă rugăm să selectați un tip valid de raport pentru descărcare.',
	) ,
);
