<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-24 20:44+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Vă rugăm să contolați dacă ați verificat elementul',
		'numeric' => 'Vă rugăm să contolați dacă ați verificat elementul',
		'categories_required' => 'Semnalările trebuiesc categorizate înainte de a fi aprobate',
	) ,
	'action' => array(
		'permission' => 'Nu aveți permisiunea de a executa această acțiune',
	) ,
);
