<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-11-29 06:10+0000
// PO revision date:  2012-11-23 21:36+0000
$lang = array(
	'description' => array(
		'length' => 'Câmpul descriere trebuie să aibă cel puțin 3 dar nu mai mult de 100 de caractere lungime.',
		'required' => 'Este necesar câmpul descriere.',
	) ,
	'name' => array(
		'required' => 'Este necesar câmpul nume.',
	) ,
);
