<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-15 06:12+0000
// PO revision date:  2013-03-14 08:04+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'Cîmpul de permitere a comentariilor nu pare să conțină o valoare validă.',
		'required' => 'Cîmpul de permitere a comentariilor este obligatoriu.',
	) ,
	'allow_feed' => array(
		'between' => 'Câmpul include feed nu pare să conțină o valoare validă.',
		'required' => 'Câmpul include feed este necesar.',
	) ,
	'allow_alerts' => array(
		'between' => 'Câmpul permite alerte nu pare să conțină o valoare validă.',
		'required' => 'Câmpul permite alerte este necesar.',
	) ,
	'allow_reports' => array(
		'between' => 'Câmpul permite rapoarte nu pare să conțină o valoare validă.',
		'required' => 'Câmpul permite rapoarte este necesar.',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'Câmpul de sharing statistici  nu pare să conțină o valoare validă.',
		'required' => 'Câmpul de sharing statistici este necesar.',
	) ,
	'api' => array(
		'default_record_limit' => 'Numărul implicit de înregistrări care urmează să fie aduse de o cerere API',
		'maximum_record_limit' => 'Numărul maxim de înregistrări care urmează să fie aduse de o cerere API',
		'maximum_requests_per_ip_address' => 'Numărul maxim de cereri API per addresă IP',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'Câmpul Akismet nu pare a conține o valoare validă.',
		'length' => 'Câmpul Akismet nu pare a conține o valoare validă.',
	) ,
	'banner_image' => array(
		'default' => 'Ceva nu a mers bine la încărcarea imaginii banner.',
		'size' => 'Dimensiunea banner-ul dvs. depășește limita de dimensiune pentru această încărcare.',
	) ,
	'cache_pages' => array(
		'between' => 'Câmpul ce conține paginile cache este necesar.',
		'required' => 'Câmpul ce conține paginile cache nu pare a conține o valoare validă.',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'Câmpul ce conține timpul de viață al paginilor cache nu pare a conține o valoare validă.',
		'required' => 'Câmpul ce conține timpul de viață al paginilor cache este necesar.',
	) ,
	'cleanurl' => array(
		'enable_clean_url' => 'Activează curățarea URL-urilor',
		'title' => 'Curăță URL-uri',
	) ,
	'clickatell_api' => array(
		'length' => 'Câmpul numeric Clickatell API nu trebuie să aiba mai mult de 20 de caractere lungime.',
		'required' => 'Câmpul numeric Clickatell API este necesar.',
	) ,
	'clickatell_password' => array(
		'length' => 'Câmpul Clickatell trebuie să aiba cel putin 5 dar nu mai mult de 50 de caractere lungime.',
		'required' => 'Câmpul Clickatell este necesar.',
	) ,
	'clickatell_username' => array(
		'length' => 'Câmpul Clickatell Username nu trebuie să aiba mai mult de 50 de caractere lungime.',
		'required' => 'Câmpul Clickatell Username este necesar.',
	) ,
	'configure_map' => 'Configurare harta',
	'default_location' => 'Locația implicită ',
	'default_map_all' => array(
		'length' => 'Campul culoare nu trebuie sa aiba mai mult de 6 caractere lungime.',
		'required' => 'Câmpul culoare este necesar.',
	) ,
	'default_map_view' => 'Vizualizare harta implicita',
	'default_zoom_level' => 'Nivel harta implicita',
	'facebook' => array(
		'title' => 'Opținuni Facebook Setup',
		'app_id' => 'ID Facebook App',
		'app_secret' => 'Secret Facebook App ',
	) ,
	'https' => array(
		'enable_https' => 'Activează HTTPS',
	) ,
	'map' => array(
		'zoom' => 'Nivel zoom',
	) ,
	'map_provider' => array(
		'enter_api' => 'Introduce noua cheie API',
		'get_api' => 'Obtine o cheie API ',
		'name' => 'Furnizor harta',
	) ,
	'map_settings' => 'Setari harta',
	'select_default_location' => 'Selecteaza o tara default',
	'site' => array(
		'api_akismet' => 'Cheie Akismet ',
		'banner' => 'Site Banner',
		'blocks_per_row' => 'Blocuri pe rand',
		'cache_pages' => 'Pagini cache',
		'cache_pages_lifetime' => 'Timpul de viata al paginilor cache',
		'delete_banner_image' => 'Sterge imaginea banner',
		'delete_default_map_all_icon' => 'Sterge icoana default',
		'email_site' => 'Adresa de email a site-ului',
		'google_analytics' => 'Google Analytics',
		'language' => 'Limba site',
		'message' => 'Mesaj site',
		'name' => 'Nume site',
		'private_deployment' => 'Implementare privată',
		'timezone' => 'Fus orar',
		'title' => 'Setari site',
	) ,
	'sms' => array(
		'flsms_synchronize' => 'Sincronizare cu Ushahidi',
		'title' => 'Optiuni setare SMS',
	) ,
);
