<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-07 06:10+0000
// PO revision date:  2013-01-06 19:41+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'Cîmpul de permitere a comentariilor nu pare să conțină o valoare validă.',
		'required' => 'Cîmpul de permitere a comentariilor este obligatoriu.',
	) ,
	'allow_feed' => array(
		'between' => 'Câmpul include feed nu pare să conțină o valoare validă.',
		'required' => 'Câmpul include feed este necesar.',
	) ,
	'allow_alerts' => array(
		'between' => 'Câmpul permite alerte nu pare să conțină o valoare validă.',
		'required' => 'Câmpul permite alerte este necesar.',
	) ,
	'allow_reports' => array(
		'between' => 'Câmpul permite rapoarte nu pare să conțină o valoare validă.',
		'required' => 'Câmpul permite rapoarte este necesar.',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'Câmpul de sharing statistici  nu pare să conțină o valoare validă.',
		'required' => 'Câmpul de sharing statistici este necesar.',
	) ,
	'api' => array(
		'default_record_limit' => 'Numărul implicit de înregistrări care urmează să fie aduse de o cerere API',
		'maximum_record_limit' => 'Numărul maxim de înregistrări care urmează să fie aduse de o cerere API',
		'maximum_requests_per_ip_address' => 'Numărul maxim de cereri API per addresă IP',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'Câmpul Akismet nu pare a conține o valoare validă.',
		'length' => 'Câmpul Akismet nu pare a conține o valoare validă.',
	) ,
	'banner_image' => array(
		'default' => 'Ceva nu a mers bine la încărcarea imaginii banner.',
		'size' => 'Dimensiunea banner-ul dvs. depășește limita de dimensiune pentru această încărcare.',
	) ,
	'cache_pages' => array(
		'between' => 'Câmpul ce conține paginile cache este necesar.',
		'required' => 'Câmpul ce conține paginile cache nu pare a conține o valoare validă.',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'Câmpul ce conține timpul de viață al paginilor cache nu pare a conține o valoare validă.',
		'required' => 'Câmpul ce conține timpul de viață al paginilor cache este necesar.',
	) ,
	'cleanurl' => array(
		'enable_clean_url' => 'Activează curățarea URL-urilor',
		'title' => 'Curăță URL-uri',
	) ,
	'default_location' => 'Locația implicită ',
	'default_map_all' => array(
		'required' => 'Câmpul culoare este necesar.',
	) ,
	'facebook' => array(
		'title' => 'Opținuni Facebook Setup',
		'app_id' => 'ID Facebook App',
		'app_secret' => 'Secret Facebook App ',
	) ,
	'https' => array(
		'enable_https' => 'Activează HTTPS',
	) ,
);
