<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-03 06:10+0000
// PO revision date:  2013-01-02 21:32+0000
$lang = array(
	'cleanurl' => array(
		'enable_clean_url' => 'Activează curățarea URL-urilor',
		'title' => 'Curăță URL-uri',
	) ,
);
