<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-06 06:10+0000
// PO revision date:  2013-01-05 15:53+0000
$lang = array(
	'actions' => array(
		'approve' => 'Aprobă un raport sau nu. Dacă va fi aprobat, aceasta va apărea în mod public.',
	) ,
	'private_message' => 'Mesaj privat',
	'profile_email' => 'Adresa dvs. de email',
);
