<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-07 06:10+0000
// PO revision date:  2013-01-06 19:54+0000
$lang = array(
	'actions' => array(
		'add_to_category' => 'Aceasta se adaugă raportul la categorii adiționale. Dacă selectați categoria 1 și raportul are deja categoria 2, raportul va avea atunci atât categoria 1 și categoria 2.',
		'approve' => 'Aprobă un raport sau nu. Dacă va fi aprobat, aceasta va apărea în mod public.',
		'assign_badge' => 'Veți fi capabil să atribuiți o insignă utilizatorului ce face declanșarea. Alege insigna pe care i-o repartizați aici.',
		'email_body' => 'Corpul mesajului pentru emailul ce va fi trimis.',
		'email_subject' => 'Subiectul emailului ce va fi trimis.',
		'report_title' => 'Acesta este titlul implicit ce va fi adăugat la raport.',
		'verify' => 'Marchează un raport ca verificat sau nu.',
	) ,
	'private_subject' => 'Subiectul mesajului privat',
	'private_message' => 'Mesaj privat',
	'profile_email' => 'Adresa dvs. de email',
	'profile_username' => 'Numele utilizatorului nu poate fi schimbat.',
);
