<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-25 00:04+0000
// PO revision date:  2012-08-24 20:50+0000
$lang = array(
	'access_level' => 'Nivel de acces',
	'actions' => 'Acțiuni',
	'add_to_category' => 'Adaugă la categorii',
	'added' => 'adăugat',
	'added_edited' => 'adăugat/editat',
	'admin_role' => 'Administrator',
	'alerts' => 'Alerte',
	'alerts_received' => 'Alerte Primite',
	'am' => 'AM',
	'anonymous' => 'Anonim',
	'anyone_role' => 'Oricine',
	'anywhere' => 'Oriunde',
);
