<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-28 12:04+0000
// PO revision date:  2012-08-28 05:52+0000
$lang = array(
	'access_level' => 'Nivel de acces',
	'actions' => 'Acțiuni',
	'add_to_category' => 'Adaugă la categorii',
	'added' => 'adăugat',
	'added_edited' => 'adăugat/editat',
	'admin_role' => 'Administrator',
	'alerts' => 'Alerte',
	'alerts_received' => 'Alerte Primite',
	'am' => 'AM',
	'anonymous' => 'Anonim',
	'anyone_role' => 'Oricine',
	'anywhere' => 'Oriunde',
	'api_settings' => 'Setări API',
	'approved' => 'aprobat',
	'approve_auto' => 'Aprobă automat',
	'approve_manual' => 'Aprobă manual',
	'archived' => 'Arhivat',
	'are_you_sure_you_want_to' => 'Ești sigur că vrei să',
	'are_you_sure_you_want_to_delete_this_item' => 'Ești sigur că vrei să ștergi acest element?',
	'are_you_sure_you_want_to_delete_this_photo' => 'Ești sigur că vrei să ștergi această poză?',
	'are_you_sure_you_want_to_switch_forms' => 'Ești sigur că vrei să schimbi formularele?',
	'author' => 'Autor',
	'author_email' => 'Email autor',
	'back' => 'Înapoi',
	'body' => 'Corp',
	'cancel' => 'Anulează',
	'categories' => 'Categorii',
	'check_message_valid' => 'Vă rugăm verificați dacă mesajul este valid.',
);
