<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-24 00:04+0000
// PO revision date:  2012-08-21 21:06+0000
$lang = array(
	'upgrade' => array(
		'between' => 'Datele introduse sunt invalide. Poate fi fie 0 pentru Nu, fie 1 pentru Da.',
	) ,
	'upgrade_automatic' => 'Upgrade automat',
	'upgrade_available' => 'Actualizări disponibile',
	'upgrade_continue_btn_text' => 'Continuă',
	'upgrade_db_btn_text' => 'Upgrade',
	'upgrade_db_text_1' => 'Deci, voi face upgrade la baza de date de la versiunea',
	'upgrade_db_text_2' => 'la ultima versiune a bazei de date',
	'upgrade_manual' => 'Upgrade manual',
	'upgrade_text_2' => '<dl><dt><strong>Descarcă</strong></dt>',
	'upgrade_status_info_2' => 'Nu este necesar să faci upgrade',
);
