<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-14 06:13+0000
// PO revision date:  2013-03-13 09:39+0000
$lang = array(
	'alert_email' => array(
		'email' => 'វាល​អ៊ីមែល​មិន​មាន​បង្ហាញ​អាសយដ្ឋាន​អ៊ីមែល​ត្រឹមត្រូវ​ឡើយ?',
		'email_check' => 'បាន​ចុះ​ឈ្មោះ​អាសយដ្ឋាន​អ៊ីមែល​នោះ​​រួច​ហើយ ដើម្បី​ទទួល​បាន​ការ​ជូនដំណឹង​សម្រាប់​ទីតាំង​នោះ។',
		'length' => 'វាល​អ៊ីមែល​ត្រូវ​តែ​មាន​យ៉ាងហោចណាស់​ ៤ តួអក្សរ និង​មិន​ច្រើន​ជាង ៦៤ តួ​អក្សរ​ឡើយ។',
		'required' => 'វាល​អ៊ីមែល​ត្រូវ​​ទាមទារ ប្រសិនបើ​បាន​​គូស​ធីក​ប្រអប់​ធីក។',
	) ,
	'alert_lat' => array(
		'between' => 'អ្នក​មិន​បាន​ជ្រើស​ទីតាំង​ត្រឹមត្រូវ​នៅ​លើ​ផែនទី​ឡើយ។',
	) ,
);
