<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:12+0000
// PO revision date:  2013-03-11 07:52+0000
$lang = array(
	'category_color' => array(
		'length' => 'វាល​ពណ៌​ត្រូវតែ​មាន​៦​តួអក្សរ​។',
		'required' => 'បាន​ទាមទារ​វាល​ពណ៌។',
	) ,
	'category_description' => array(
		'required' => 'បាន​ទាមទារ​វាល​ពណ៌នា។',
	) ,
	'category_image' => array(
		'size' => 'សូម​ប្រាកដ​ថា​ទំហំ​រូបភាព​ផ្ទុក​ឡើង​ត្រូវ​បាន​កំណត់​ត្រឹម​៥០​គីឡូបៃ។',
		'type' => 'វាល​រូបភាព​មិន​បង្ហាញ​ថា​មាន​រូបភាព​ត្រឹមត្រូវ​ទេ។ ទ្រង់ទ្រាយ​ដែល​ព្រម​ទទួល​គឺ .JPG .PNG និង .GIF។',
		'valid' => 'វាល​រូបភាព​មិន​បង្ហាញ​ថា​មាន​ឯកសារ​ត្រឹមត្រូវ​ទេ',
	) ,
	'category_title' => array(
		'length' => 'វាល​ចំណងជើង​ត្រូវតែ​មាន​អក្សរ​យ៉ាងតិច៣ ប៉ុន្តែ​មិន​លើស​ពី​៨០​តួ​ឡើយ។',
		'required' => 'បាន​ទាមទារ​វាល​ចំណងជើង។',
	) ,
	'parent_id' => array(
		'already_parent' => 'អ្នក​មិន​អាច​ចាត់​ប្រភេទ​រង​ប្រភេទ​ជាមួយ​ប្រភេទ​រង​បាន​ទេ។',
		'exists' => 'ប្រភេទមេមិនមាន',
		'numeric' => 'ប្រភេទមេត្រូវតែជាលេខ',
		'parent_trusted' => 'ប្រភេទ​មេ​មិន​អាច​ជា​ប្រភេទ​ពិសេស​បាន​ទេ',
		'required' => 'ប្រភេទមេតម្រូវឲ្យមាន',
		'same' => 'ប្រភេទនិងប្រភេទមេមិនអាចដូចគ្នា',
		'special' => 'ប្រភេទពិសេសមិនអាចជាកូនប្រភេទ',
	) ,
);
