<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:12+0000
// PO revision date:  2013-03-07 08:15+0000
$lang = array(
	'config' => 'កំណត់​រចនា​សម្ព័ន្ធ​ឯកសារ',
	'controller' => 'ឧបករណ៍​បញ្ជា',
	'helper' => 'ជំនួយការ',
	'library' => 'បណ្ណាល័យ',
	'model' => 'គំរូ',
	'view' => 'បង្ហាញ',
	'view_set_filename' => 'អ្នកត្រូវតែដាក់បង្ហាញឈ្មោះឯកសារមុននឹងធ្វើវា',
);
