<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-12 06:12+0000
// PO revision date:  2013-03-11 10:02+0000
$lang = array(
	'base_path' => 'ផ្លូវ​មូលដ្ឋាន',
	'database' => 'មូលដ្ឋាន​ទិន្នន័យ',
	'database_host' => 'ម៉ាស៊ីន​មូលដ្ឋាន​ទិន្នន័យ',
	'database_host_description' => 'ប្រសិនបើ​អ្នក​កំពុង​ប្រើ​យូសាហ៊ីឌី​នៅ​លើ​កុំព្យូទ័រ​របស់​អ្នក នេះ​ទំនងជា "localhost"។ ប្រសិនបើ​អ្នក​កំពុង​ដំណើរការ​យូសាហ៊ីឌី​ពី​ម៉ាស៊ីន​មេ​បណ្ដាញ អ្នក​នឹង​ទទួល​បាន​ព័ត៌មាន​ម៉ាស៊ីន​ពី​ក្រុមហ៊ុន​ផ្ដល់​ការ​បង្ហោះ​បណ្ដាញ​របស់​អ្នក។ ',
	'database_name' => 'ឈ្មោះ​មូលដ្ឋាន​ទិន្នន័យ',
	'database_name_description' => 'ឈ្មោះ​មូលដ្ឋាន​ទិន្នន័យ​ដែល​អ្នក​ត្រូវ​ដំណើរការ​យូសាហ៊ីឌី',
	'db_information_link' => 'សម្រាប់​ព័ត៌មាន​បន្ថែម​សូម​មើល​នៅ <a href="http://wiki.ushahidi.com/doku.php?id=a_brief_word_on_databases" target="_blank">អត្ថបទ​នេះ</a> នៅ​លើ​វីគី​ដែល​និយាយ​អំពី​មូលដ្ឋាន​ទិន្នន័យ​លម្អិត។',
	'default_language' => 'ភាសា​លំនាំដើម (Locale)',
	'default_language_description' => 'ការ​ប្រើប្រាស់​នីមួយៗ​របស់​យូសាហ៊ីឌី​គឺ​មក​ជាមួយ​សំណុំ​ការ​បកប្រែ​ភាសា​ដែល​ជាប់។ អ្នក​បន្ថែម​ភាសា​របស់​អ្នក​បាន <a href="http://wiki.ushahidi.com/doku.php?id=localisation_l10n_internationlisation_i18n&s[]=language#enabling_new_languages" target="_blank"></a>.',
	'disable' => 'បិទ',
	'enable' => 'បើក',
	'error_summary' => 'បញ្ជី​ខាងក្រោម​គឺ​សេចក្ដី​សង្ខេប​អំពី​កំហុស​ដែល​យើង​បាន​ជួប។',
	'files_location_text' => 'ទីតាំង​នៅ​លើ​ម៉ាស៊ីន​មេ​សម្រាប់​ដាក់​ឯកសារ​យូសាហ៊ីឌី​របស់​អ្នក។ <strong>យើ​បាន​រក​ឃើញ​តម្លៃ​នេះ​ដោយ​ស្វ័យប្រវត្តិ សូម​ប្រាកដ​ថា​វា​ត្រឹមត្រូវ។</strong> ប្រសិនបើ​វាល​ទទេ សូម​កុំ​បារម្ភ​អី វា​មានន័យថា​យូសាហ៊ីឌី​ត្រូវ​បាន​ដំឡើង​នៅ​ថត​កំពូល។',
	'finished' => 'បាន​បញ្ចប់',
	'general' => 'ទូទៅ',
	'google_key' => '<span>Google</span> API Key',
	'google_key_description' => 'អ្នក​ណា​ក៏​អាច​យក​គ្រាប់ចុច api បាន​ដែរ។ <a id="api-link" href="http://code.google.com/apis/maps/signup.html" target="_blank">យក​របស់​អ្នក​ឥឡូវ</a>',
	'go_back' => 'ត្រឡប់​ក្រោយ',
	'map' => 'ផែនទី',
	'other_steps' => 'ជំហានដទៃ',
	'password' => 'ពាក្យសំងាត់',
	'password_description' => 'ពាក្យសំងាត់ Database របស់អ្នក',
	'previous' => 'ក្រោយ',
	'site_email' => 'អាស័យដ្ឋានអ៊ីម៉ែលគេហទំព័រ',
	'site_name' => 'នាមគេហទំព័រ',
	'site_name_description' => 'ឈ្មោះគេហទំព័រអ្នក',
);
