<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:12+0000
// PO revision date:  2013-02-28 07:51+0000
$lang = array(
	'message' => 'សូម​ទោស តំបន់​បណ្ដាញ​របស់​យើង​បច្ចុប្បន្ន​ផ្អាក​ដើម្បី​ថែទាំ។ សូម​ព្យាយាម​ម្ដងទៀត​ក្នុង​រយៈ​ពេល​​ពីរ ឬ​បី​នាទី​ទៀត។',
);
