<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-21 06:14+0000
// PO revision date:  2013-03-20 09:52+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'វាល​អនុញ្ញាត​សេចក្ដី​អធិប្បាយ​មិន​បង្ហាញ​ថា​មាន​តម្លៃ​ត្រឹមត្រូវ​ទេ។',
		'required' => 'បាន​ទាមទារ​វាល​អនុញ្ញាត​សេចក្ដី​អធិប្បាយ។',
	) ,
	'allow_feed' => array(
		'required' => 'បាន​ទាមទារ​វាល​មតិ​ព័ត៌មាន​រួមបញ្ចូល។',
	) ,
	'allow_alerts' => array(
		'between' => 'វាល​អនុញ្ញាត​ការ​ជូនដំណឹង​មិន​បង្ហាញ​ថា​មាន​តម្លៃ​ត្រឹមត្រូវ​ទេ។',
		'required' => 'បាន​ទាមទារ​វាល​អនុញ្ញាត​ការ​ជូនដំណឹង។',
	) ,
	'allow_reports' => array(
		'between' => 'វាល​អនុញ្ញាត​របាយការណ៍​មិន​បង្ហាញ​ថា​មាន​តម្លៃ​ត្រឹមត្រូវ​ទេ។',
		'required' => 'បាន​ទាមទារ​វាល​អនុញ្ញាត​របាយការណ៍។',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'វាល​អនុញ្ញាត​សភាព​ចែករំលែក​មិន​បង្ហាញ​ថា​មាន​តម្លៃ​ត្រឹមត្រូវ​ទេ។',
		'required' => 'បាន​ទាមទារ​វាល​សភាព​ចែករំលែក។',
	) ,
	'api' => array(
		'default_record_limit' => 'លេខ​លំនាំដើម​នៃ​កំណត់ត្រា​ដែល​បាន​ទៅ​ប្រមូល​យក​ក្នុង​មួយ​សំណើ API',
		'maximum_record_limit' => 'ចំនួន​អតិបរមា​នៃ​កំណត់ត្រា​ដែល​បាន​ទៅ​ប្រមូល​យក​ក្នុង​មួយ​សំណើ API',
		'maximum_requests_per_ip_address' => 'ចំនួន​អតិបរមា​នៃ​សំណើ API ក្នុង​មួយ​អាសយដ្ឋាន IP',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'វាល Akismet មិន​បង្ហាញ​ថា​មាន​តម្លៃ​ត្រឹមត្រូវ​ទេ។',
		'length' => 'វាល Akismet មិន​បង្ហាញ​ថា​មាន​តម្លៃ​ត្រឹមត្រូវ​ទេ។',
	) ,
	'banner_image' => array(
		'default' => 'មាន​បញ្ហា​ជាមួយ​ការ​ផ្ទុក​ឡើង​នៃ​រូបភាព​បដា​របស់​អ្នក។',
		'size' => 'ទំហំ​បដា​របស់​អ្នក​លើសពី​ទំហំ​កំណត់​សម្រាប់​ការ​ផ្ទុក​ឡើង​នេះ។',
	) ,
	'cache_pages' => array(
		'between' => 'បាន​ទាមទារ​វាល​ទំព័រ​ឃ្លាំង​សម្ងាត់។',
		'required' => 'វាល​ទំព័រឃ្លាំង​សម្ងាត់​មិន​បង្ហាញ​ថា​មាន​តម្លៃ​ត្រឹមត្រូវ​ទេ។',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'វាល​ជំនាន់​ទំព័រ​ឃ្លាំង​សម្ងាត់​មិន​បង្ហាញ​ថា​មាន​តម្លៃ​ត្រឹមត្រូវ​ទេ។',
		'required' => 'បាន​ទាមទារ​វាល​ជំនាន់​ទំព័រ​ឃ្លាំង​សម្ងាត់។',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'ម៉ាស៊ីន​មេ​របស់​អ្នក​ហាក់​ដូចជា​មិន​បាន​កំណត់​រចនាសម្ព័ន្ធ​ដើម្បី​ប្រើ URLs ត្រឹមត្រូវ។ អ្នក​ចាំបាច់​ត្រូវ​ប្ដូរ​ការ​កំណត់​រចនាសម្ព័ន្ធ​ម៉ាស៊ីន​មេ​របស់​អ្នក​ជាមុន ទើប​អាច​បើក URLs ត្រឹមត្រូវ​បាន។ មើល​ព័ត៌មាន​បន្ថែម​អំពី​របៀប​បើក URLs ត្រឹមត្រូវ​នៅ <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">សម្រាប់​វេទិកា​ប្រកាស​នេះ</a>',
		'clean_url_enabled' => 'ជម្រើស​នេះ​ធ្វើឲ្យ​យូសាហ៊ីឌី​អាច​ចូល​ដំណើរការ​បាន​តាមរយៈ URLs "ត្រឹមត្រូវ"  (ដោយ​គ្មាន "index.php" នៅ​ក្នុង URL)។',
		'enable_clean_url' => 'បើក URLs ត្រឹមត្រូវ',
		'title' => 'URLs ត្រឹមត្រូវ',
	) ,
	'clickatell_api' => array(
		'length' => 'វាល​លេខ Clickatell API ត្រូវតែ​មាន​ប្រវែង​តិច​ជាង​២០​តួអក្សរ។',
		'required' => 'បាន​ទាមទារ​វាល​លេខ Clickatell API។',
	) ,
	'clickatell_password' => array(
		'length' => 'វាល​ពាក្យសម្ងាត់ Clickatell ត្រូវតែ​មាន​តួអក្សរ​យ៉ាងតិច​៥ និង​យ៉ាង​ច្រើន៥០។',
		'required' => 'បាន​ទាមទារ​វាល​ពាក្យសម្ងាត់ Clickatell ។',
	) ,
);
