<?php
	$lang = array(
	'config' => '設定ファイル',
	'controller' => 'コントローラ',
	'driver' => 'ドライバ',
	'driver_implements' => '',
	'driver_not_found' => '%s　ドライバ（ %s　ライブラリ用）が見つかりませんでした。',
	'errors_disabled' => '<a href="%s">ホームページ</a> or <a href="%s">再トライ</a>へアクセス出来ます。',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'リクエストを完了出来ません。',
	'helper' => 'ヘルパー',
	'invalid_filetype' => 'リクエストされた %s ファイルタイプは、ビュー設定ファイルでは許可されていません。',
	'invalid_method' => '',
	'invalid_property' => '',
	'library' => '',
	'log_dir_unwritable' => '',
	'model' => '',
	'no_controller' => '',
	'no_default_route' => '',
	'page_not_found' => '',
	'report_bug' => '',
	'resource_not_found' => '',
	'stack_trace' => '',
	'stats_footer' => '',
	'there_can_be_only_one' => '',
	'uncaught_exception' => '',
	'view' => '',
	'view_set_filename' => '',
	);
?>
