<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-17 06:40+0000
// PO revision date:  2012-08-15 04:39+0000
$lang = array(
	'date' => '日時',
	'feed_name' => array(
		'length' => 'フィード名は最低3文字以上、70文字以下にする必要があります。',
		'required' => 'フィード名を入力してください。',
	) ,
	'feed_url' => array(
		'required' => 'フィードのURLを入力してください。',
		'url' => '有効なURLを入力してください。例 http://www.ushahidi.com',
	) ,
	'source' => 'ソース',
	'title' => 'タイトル',
);
