<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-07 06:22+0000
// PO revision date:  2013-07-06 17:43+0000
$lang = array(
	'incident_id' => array(
		'required' => 'アイテムをチェックしたか、確認して下さい。',
		'numeric' => 'アイテムをチェックしたか、確認して下さい。',
		'categories_required' => '報告書を承認してもらうには、それを分類しなければなりません。',
	) ,
	'action' => array(
		'permission' => 'あなたには、この操作をする権限がありません。',
	) ,
	'uploadfile' => array(
		'required' => 'アップロードするファイルを選択して下さい。',
		'type' => 'アップロードするファイルは、csv形式またはxml形式でなければなりません。',
		'valid' => 'アップロードするファイルとして、アップロードできないファイルが指定されているようです。',
	) ,
);
