<?php
	$lang = array(
	'approved' => '承認済み',
	'categories' => 'カテゴリー',
	'category_impact' => 'カテゴリーの影響力',
	'choose_date_range' => '期間を選択する',
	'countries' => '国々',
	'country' => '国',
	'country_breakdown' => '国内の細分化',
	'description' => 'こんにちは。ここは統計セクションです。一般的な説明は後ほどこの場所に表示されます。コンテンツが作成されるまで、今しばらく上記されているサブカテゴリーのリンクを閲覧するなどしてください。',
	'error' => 'エラー',
	'glossary' => '単語',
	'hit_summary' => '要約',
	'legend' => '凡例',
	'pageviews' => 'ページビュー',
	'pageviews_description' => 'あなたのサイトを、訪問者がページを閲覧したトータル数',
	'reports' => 'レポート',
	'reports_categories' => 'レポートカテゴリー',
	'reports_statistics' => 'レポート統計',
	'reports_status' => 'レポート状況',
	'report_punchcard' => 'レポートパンチカード',
	'report_stats' => 'レポート統計',
	'stats_not_setup' => '統計は設定されていません。',
	'time_range_1' => '1ヶ月',
	'time_range_2' => '3ヶ月',
	'time_range_3' => '6ヶ月',
	'time_range_all' => 'すべて',
	'unapproved' => '未承認',
	'unique_visitors' => 'ユニーク訪問者',
	'unverified' => '未確認',
	'verified' => '確認済み',
	'visitor_summary' => '訪問者の要約',
	'visits' => '訪問',
	'visits_description' => 'このサイトを訪問するユニークユーザーは、再度にページを見てから30分以上経ってから登録しています。',
	);
?>
