<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 22:26+0000
$lang = array(
	'upgrade' => array(
		'between' => '入力したデータが不正です。0（いいえ）か1(はい)のみです。',
	) ,
	'upgrade_automatic' => '自動アップグレード',
	'upgrade_available' => '可能なアップグレード',
	'upgrade_continue_btn_text' => '続ける',
	'upgrade_db_btn_text' => 'アップグレード',
	'upgrade_db_text_1' => '今のバージョンからデータベースをアップグレードします。',
	'upgrade_db_text_2' => '新しいデータベースのバージョンへ',
	'upgrade_db_text_3' => '魔法を呼び起こす"アップグレード"ボタンをクリックしてください。',
	'upgrade_db_text_4' => 'それとデータベースバックアップをしておいてください。以下にあるボタンを押すだけでバックアップを行います。',
	'upgrade_db_text_5' => 'アップグレードを行う前にデータベースをバックアップしますか？(<strong style="color:#FF0000;">推奨</strong>)',
	'upgrade_db_title' => 'Ushahidiデータベースアップグレード',
	'upgrade_failed' => 'どこかのポイントでアップグレードが失敗したようです。',
	'upgrade_manual' => '手動アップグレード',
	'upgrade_status' => 'Ushahidiアップグレードステイタス',
	'upgrade_text_1' => '以下の説明はUshahidiサイトの手動アップグレード方法についてです。',
	'upgrade_text_2' => '<strong>ステップ 1:</strong>一番新しいushahidiを<a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>こちらからダウンロードしてください。',
	'upgrade_text_3' => '<strong>ステップ 2:</strong>ウェブサーバーで動いているOSにもよりますが、使いやすいツールやモード (例: telnet, ftp, ssh) を使ってウェブサイトにログインし、すべてのファイルを新しいファイルに上書きしてください。 <strong>例外:</strong>',
	'upgrade_text_4' => '<strong>ステップ 4:</strong>  <strong>"続ける"</strong>ボタンをクリックして必要なテーブルのアップグレードを行います。',
	'upgrade_text_5' => '自動アップグレードは、以下のボタンをクリックしてください。',
	'upgrading' => 'アップグレード中',
);
