<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-01 06:04+0000
// PO revision date:  2012-07-13 04:22+0000

$lang = array (
  'alert_email' => 
  array (
    'email' => 'This is a test',
    'email_check' => 'Harrr!',
  ),
  'alert_radius' => 
  array (
    'in_array' => 'Yarr! Ye can\'t make a circle that big!',
  ),
);

