<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-04 06:04+0000
// PO revision date:  2012-07-13 04:22+0000

$lang = array (
  'captcha' => 
  array (
    'default' => 'captcherrr*default',
    'required' => 'Captcharrr+required',
  ),
  'email' => 
  array (
    'email' => 'This is a test I\'ll test this I will - test this with Some $ funky Character * ddsad * # $ % ^ fjdskfdsl few ferw f \\ \\ \\ \\ \' \' \' \' ',
    'length' => '\' \' \' \' \' ',
  ),
);

