<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-01 18:04+0000
// PO revision date:  2012-07-13 04:22+0000

$lang = array (
  'am' => 'in the morn\'',
  'friday' => 
  array (
    'abbv' => 'Fri',
    'full' => 'Friday',
  ),
  'monday' => 
  array (
    'abbv' => 'Mon',
    'full' => 'Monday',
  ),
  'pm' => 'in the evenin\'',
  'saturday' => 
  array (
    'abbv' => 'Sat',
    'full' => 'Saturday',
  ),
  'sunday' => 
  array (
    'abbv' => 'Sun',
    'full' => 'Sunday',
  ),
  'thursday' => 
  array (
    'abbv' => 'Thu',
    'full' => 'Thursday',
  ),
  'tuesday' => 
  array (
    'abbv' => 'Tue',
    'full' => 'Tuesday',
  ),
  'wednesday' => 
  array (
    'abbv' => 'Wed',
    'full' => 'Wednesday',
  ),
);

