<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-07 00:05+0000
// PO revision date:  2012-07-12 21:32+0000

$lang = array (
  'friday' => 
  array (
    'abbv' => 'Пт',
    'full' => 'П\'ятниця',
  ),
  'monday' => 
  array (
    'abbv' => 'Пн',
    'full' => 'Понеділок',
  ),
  'saturday' => 
  array (
    'abbv' => 'Сб',
    'full' => 'Субота',
  ),
  'sunday' => 
  array (
    'abbv' => 'Нд',
    'full' => 'Неділя',
  ),
  'thursday' => 
  array (
    'abbv' => 'Чт',
    'full' => 'Четвер',
  ),
  'tuesday' => 
  array (
    'abbv' => 'Вт',
    'full' => 'Вівторок',
  ),
  'wednesday' => 
  array (
    'abbv' => 'Ср',
    'full' => 'Середа',
  ),
);

