<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-17 06:40+0000
// PO revision date:  2012-08-15 04:40+0000
$lang = array(
	'latitude' => array(
		'between' => 'Координати широти місцевості введені неправильно',
		'required' => 'Введіть координати широти місцевості. Будь ласка, натисніть на карту, щоб визначити місце розташування.',
	) ,
	'level_id' => array(
		'numeric' => 'Рівень повідомника неправильний',
		'required' => 'Рівень повідомника неправильний',
	) ,
	'location_name' => array(
		'length' => 'Довжина назви місця не може бути менше 3х і більше 200 символів.',
		'required' => 'Введіть назву місця.',
	) ,
	'longitude' => array(
		'between' => 'Координати довготи місцевості введені неправильно',
		'required' => 'Введіть координати довготи місцевості. Будь ласка, натисніть на карту, щоб визначити місце розташування.',
	) ,
	'reporter_id' => array(
		'numeric' => 'Неправильна особа',
		'required' => 'Неправильна особа',
	) ,
);
