<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 23:10+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'Поле про дозвіл коментувати заповнене невірно',
		'required' => 'Поле про дозвіл коментувати має бути заповнене.',
	) ,
	'allow_feed' => array(
		'between' => 'Поле про RSS-стрічку заповнене невірно',
		'required' => 'Поле про RSS-стрічку має бути заповнене.',
	) ,
	'allow_reports' => array(
		'between' => 'Поле про можливість відправляти звіти заповнене невірно',
		'required' => 'Поле про можливість відправляти звіти має бути заповнене.',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'Поле про відправку статистики заповнене невірно',
		'required' => 'Поле про відправку статистики має бути заповнене.',
	) ,
	'api' => array(
		'default_record_limit' => 'Кількість записів, за замовчуванням отримуваних за запитом API',
		'maximum_record_limit' => 'Максимальна кількість записів, отримуваних за запитом API',
		'maximum_requests_per_ip_address' => 'Максимальна кількість запитів API на одну IP-адресу',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'Поле Akismet заповнене невірно',
		'length' => 'Поле Akismet заповнене невірно',
	) ,
	'cache_pages' => array(
		'between' => 'Поле кешування сторінок повинно бути заповнене',
		'required' => 'Заповніть поле кешування сторінок',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'Час кешування сторінок заповнений невірно',
		'required' => 'Введіть час кешування сторінок',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'Ваш сервер не налаштований для чистих URL. Налаштуйте Ваш сервер до увімкнення даної послуги. Для більш детальної інформації зайдите <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">post</a>',
		'clean_url_enabled' => 'Це дозволить Ushahidi заходити на "чисті" сайти без входу на "index.php".',
		'enable_clean_url' => 'Дозволити чисті URL',
		'title' => 'Чисті URL',
	) ,
	'clickatell_api' => array(
		'length' => 'Довжина номера Clickatell API не повинна перевищувати 20 символів.',
		'required' => 'Введіть Clickatell API номер.',
	) ,
	'clickatell_password' => array(
		'length' => 'Довжина паролю Clickatell не повинна перевищувати 50 символів.',
		'required' => 'Введіть пароль Clickatell.',
	) ,
	'clickatell_username' => array(
		'length' => 'Довжина імені користувача Clickatell не повинна перевищувати 50 символів.',
		'required' => 'Введіть ім\'я користувача Clickatell.',
	) ,
	'configure_map' => 'Налаштувати карту',
	'default_location' => 'Місцезнаходження за замовчуванням',
	'default_map_all' => array(
		'alpha_numeric' => 'Поле кольору містить неправильні дані',
		'length' => 'Поле кольору повинно бути 6-значним',
		'required' => 'Введіть колір.',
	) ,
	'default_map_view' => 'Бачити карту за замовчуванням',
	'default_zoom_level' => 'Рівень масштабу за замовчуванням',
	'download_city_list' => 'Отримати назви з ГЕОназв',
	'email_host' => array(
		'length' => 'Поле хоста Сервера пошти надто довге',
		'numeric' => 'Хост сервера пошти повинен містити лише цифри.',
	) ,
	'email_password' => array(
		'length' => 'Довжина паролю сервера пошти не повинна перевищувати 50 символів.',
		'required' => 'Введіть пароль сервера пошти.',
	) ,
	'email_port' => array(
		'length' => 'Поле порта Сервера пошти надто довге',
		'numeric' => 'Порт сервера пошти повинен містити лише цифри.',
	) ,
	'email_servertype' => array(
		'length' => 'Поле типу сервера пошти надто довге',
		'required' => 'Введіть тип сервера пошти.',
	) ,
	'email_username' => array(
		'length' => 'Довжина імені користувача сервера пошти не повинна перевищувати 50 символів.',
		'required' => 'Введіть ім\'я користувача сервера пошти.',
	) ,
	'google_analytics' => array(
		'length' => 'Поле Google Analytics повинне містити діючий Web Property ID у форматі UA-XXXXX-XX.',
	) ,
	'items_per_page' => array(
		'between' => 'Поле кількості звітів на сторінці (Головній) заповнене неправильно',
		'required' => 'Введіть кількість звітів на сторінці для (Головна).',
	) ,
	'items_per_page_admin' => array(
		'between' => 'Поле кількості звітів на сторінці (Admin) заповнене неправильно',
		'required' => 'Введіть кількість звітів на сторінці для (Admin).',
	) ,
	'map' => array(
		'default_location' => 'Вибір провайдера карти відбувається напряму з провайдером. Виберіть провайдера, отримайте API ключ, Введіть ключ на сайті',
		'zoom' => 'Масштаб',
	) ,
	'map_provider' => array(
		'choose' => 'Виберіть провайдера карти',
		'enter_api' => 'Виберіть новий API ключ',
		'get_api' => 'Отримати ключ API ',
		'info' => 'Вибір провайдера карти відбувається напряму з провайдером. Виберіть провайдера, отримайте API ключ, Введіть ключ на сайті',
		'name' => 'Провайдер карти',
	) ,
	'map_settings' => 'Властивості карти',
	'multiple_countries' => 'Чи об\'єднує Ushahidi декілька країн',
	'select_default_location' => 'Виберіть країну за замовчанням',
	'set_location' => 'Клікніть на карту щоб вказати точне місцезнаходження',
	'site' => array(
		'allow_clustering' => 'Кластеризувати звіти по Карті',
		'allow_comments' => 'Дозволити користувачам відправляти коментарі до звітів',
		'allow_feed' => 'Включити стрічку новин RSS на головній сторінці сайта',
		'allow_reports' => 'Дозволити користувачам відправляти звіти про події',
		'api_akismet' => 'Akismet ключ',
		'cache_pages' => 'Кешування сторінок',
		'cache_pages_lifetime' => 'Час кешування сторінок',
		'copyright_statement' => 'Заява авторського права сайту',
		'default_category_colors' => 'Колір за замовчуванням для всіх категорій',
		'display_contact_page' => 'Відображати страницу контактів',
		'display_howtohelp_page' => 'Відображати сторінку "Як допомогти"',
		'email_alerts' => 'Email для сповіщення',
		'email_notice' => '<span> Щоб отримати звіти по пошті, будь ласка, налаштуйте параметри Вашого email.</span>',
		'email_site' => 'Email Веб сайта',
		'google_analytics_example' => 'Ідентифікатор Google Analytics - формат: UA-XXXXX-XX',
		'items_per_page' => 'Кількість елементів на сторінці - Головна',
		'items_per_page_admin' => 'Кількість елементів на сторінці - Admin',
		'kismet_notice' => 'Захистіться від спаму, використовуючи <a href="http://akismet.com/" target="_blank">Akismet</a> от Automattic.<BR />Ви можете отримати безкоштовний API ключ в <a href="http://en.wordpress.com/api-keys/" target="_blank">WordPress.com user account</a>',
		'laconica_configuration' => 'Laconica акаунт',
		'laconica_site' => 'Laconica Сайт',
		'language' => 'Мова сайта',
		'message' => 'Повідомлення сайту',
		'name' => 'Назва сайту',
		'private_deployment' => 'Окреме розгортання',
		'share_site_stats' => 'Відправляти статистику в API',
		'tagline' => 'Заголовок сайту',
		'title' => 'Параметри сайта',
		'twitter_configuration' => 'Twitter аккаунт',
		'twitter_hashtags' => 'Хэштеги - відокремте комами',
	) ,
	'site_email' => array(
		'email' => 'Email веб сайта введений неправильно',
		'length' => 'Довжина Email веб сайта не повинна містити менше 4х і більше 100 символів.',
	) ,
	'site_name' => array(
		'length' => 'Довжина назви сайта не повинна містити менше 3х символів і більше 50 символів.',
		'required' => 'Введіть назву сайта.',
	) ,
	'site_tagline' => array(
		'length' => 'Довжина поля заголовку має бути не менше 3х і більше 100 символів.',
		'required' => 'Введіть поле заголовку.',
	) ,
	'sms' => array(
		'clickatell_api' => 'Введіть ваш Clickatell API Номер',
		'clickatell_check_balance' => 'Перевірте Ваш баланс на Clickatell',
		'clickatell_load_balance' => 'Завантажте баланс на Clickatell',
		'clickatell_password' => 'Введіть Ваш Clickatell Пароль',
		'clickatell_text_1' => 'Підключіться до послуги Clickatell в <a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">clicking here</a>',
		'clickatell_text_2' => 'Введіть Вашу інформацію Clickatell внизу',
		'clickatell_username' => 'Введіть ваш Clickatell логін',
		'flsms_description' => 'FrontlineSMS - вільна програма з відкритим вихідним кодом, яка перетворює ноутбук та мобільний телефон у центральний вузол зв\'язку. Після установки, програма дозволяє користувачам відправляти і отримувати текстові повідомлення з великими групами людей за допомогою мобільних телефонів. Клацніть на кнопку, щоб завантажити FrontlineSMS.com',
		'flsms_download' => 'Завантажте Frontline SMS та встановіть на Ваш комп\'ютер',
		'flsms_instructions' => 'Повідомлення, отримані у FrontlineSMS можуть бути синхронізовані з Ushahidi. Інформацію про те, як синхронізувати з Ushahidi, можна знайти в <strong><a href="http://wiki.ushahididev.com/doku.php?id=how_to_use_ushahidi_alpha#how_to_setup_frontlinesms_to_sync_with_ushahidi" target="_blank">here</a></strong>. Вы повинні отримати ключ за посиланням щоб синхронізувати з FrontlineSMS',
		'flsms_key' => 'Це ключ синхронізації Ushahidi',
		'flsms_link' => 'FrontlineSMS HTTP Post посилання',
		'flsms_synchronize' => 'Синхронізувати з Ushahidi',
		'flsms_text_1' => 'Введіть номер телефона, підключений до Frontline SMS в поле внизу',
		'flsms_text_2' => 'Введіть номер без символів + чи скобок',
		'option_1' => 'Option 1: Використовуйте Frontline SMS',
		'option_2' => 'Option 2: Використовуйте Global SMS Gateway',
		'title' => 'Налаштування SMS',
	) ,
	'sms_no1' => array(
		'length' => 'Телефон 1 занадто довгий',
		'numeric' => 'Телефон 1 має включати лише цифри.',
	) ,
	'sms_no2' => array(
		'length' => 'Телефон 2 занадто довгий',
		'numeric' => 'Телефон 2 має включати лише цифри.',
	) ,
	'sms_no3' => array(
		'length' => 'Телефон 3 занадто довгий',
		'numeric' => 'Телефон 3 має включати лише цифри.',
	) ,
);
