<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-17 07:01+0000
$lang = array(
	'date' => 'Дата реєстрації',
	'date_added' => 'Дата додана',
	'last_access' => 'Останній доступ',
	'sharing_color' => array(
		'length' => 'Довжина кольору має бути 6-значною',
		'required' => 'Введіть колір.',
	) ,
	'sharing_url' => array(
		'exists' => 'URL сайта вже існує',
		'length' => 'Адреса сайта введена невірно',
		'required' => 'Введіть url сайта',
		'url' => 'Адреса сайта введена невірно',
	) ,
);
