<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-19 22:26+0000
$lang = array(
	'upgrade' => array(
		'between' => 'Неправильні дані. Введіть 0 як Ні або 1 як Так',
	) ,
	'upgrade_automatic' => 'Автоматичне оновлення',
	'upgrade_available' => 'Доступні оновлення',
	'upgrade_continue_btn_text' => 'Продовжити',
	'upgrade_db_btn_text' => 'Оновити',
	'upgrade_db_text_1' => 'Зараз відбудеться оновлення бази даних з версії',
	'upgrade_db_text_2' => 'до найновішої версії бази даних',
	'upgrade_db_text_3' => 'Натисніть на кнопку "Оновити" і зачекайте',
	'upgrade_db_text_4' => 'Якщо ви хочете зробити резервну копію бази даних перед оновленням, відзначте галочкою прапорець нижче',
	'upgrade_db_text_5' => 'Зробити резервну копію бази даних перед оновленням (<strong style="color:#FF0000;">Рекомендується</strong>)',
	'upgrade_db_title' => 'Оновлення бази даних Ushahidi ',
	'upgrade_failed' => 'Оновлення перервалося',
	'upgrade_manual' => 'Ручне оновлення',
	'upgrade_status' => 'Стан оновлення Ushahidi',
	'upgrade_text_1' => 'Як оновити Ushahidi вручну',
	'upgrade_text_2' => '<strong>Крок 1::</strong> Завантажте останню версію ushahidi з  <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a>',
	'upgrade_text_3' => '<strong>Крок 2::</strong> В залежності від ОС вебсервера, виберіть потрібний канал передачі (i.e: telnet, ftp, ssh) для входа на веб сервер и повністю замініть вміст останньою версією Ushahidi. <strong>Крім:</strong>',
	'upgrade_text_4' => '<strong>Крок 4::</strong> Натисніть на кнопку <strong>""Продовжити":</strong> щоб оновити таблиці',
	'upgrade_text_5' => 'Для автоматичного оновлення натисніть нижче',
	'upgrading' => 'Оновлюється',
);
