<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-18 08:16+0000
$lang = array(
	'alert_email' => array(
		'email' => 'ईमेल क्षेत्र में मान्य ईमेल पता नहीं है?',
		'email_check' => 'यह ईमेल पता पहले से ही उस स्थान के लिए अलर्ट प्राप्त करने के लिए पंजीकृत किया जा चुका है|',
		'length' => 'ईमेल क्षेत्र की लम्बाई कम से कम 4 और अधिकतम 64 वर्ण लंबा होनी चाहिए।',
		'required' => ' चेकबॉक्स अंकित होने पर ईमेल क्षेत्र की आवश्यकता है।',
	) ,
	'alert_country' => array(
		'single_country' => 'यह प्रणाली एक देश तक ही सीमित है। कृपया सुनिश्चित करें कि अलर्ट स्थान %s देश के भीतर है।',
	) ,
);
