<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-27 06:19+0000
// PO revision date:  2013-06-27 05:56+0000
$lang = array(
	'alert_email' => array(
		'email' => ' क्या यह ईमेल क्षेत्र एक मान्य ईमेल पता नहीं रखता ?',
		'email_check' => 'यह ईमेल पता पहले से ही उस स्थान के लिए अलर्ट प्राप्त करने के लिए पंजीकृत किया जा चुका है|',
		'length' => 'ईमेल क्षेत्र की लम्बाई कम से कम 4 और अधिकतम 64 वर्ण लंबा होनी चाहिए।',
		'required' => ' चेकबॉक्स अंकित होने पर ईमेल क्षेत्र की आवश्यकता है।',
	) ,
	'alert_country' => array(
		'single_country' => 'यह प्रणाली एक देश तक ही सीमित है। कृपया सुनिश्चित करें कि अलर्ट स्थान %s देश के भीतर है।',
	) ,
	'alert_lat' => array(
		'between' => 'आपने मानचित्र पर एक मान्य स्थान का चयन नही किया है|',
		'required' => 'आपने मानचित्र पर एक सही स्थान का चयन नही किया है| ',
	) ,
	'alert_lon' => array(
		'between' => 'आपने मानचित्र पर एक सही स्थान का चयन नही किया है| ',
		'required' => 'आपने मानचित्र पर एक सही स्थान का चयन नही किया है| ',
	) ,
	'alert_mobile' => array(
		'length' => 'यह चल दूरभाष का क्षेत्र सही मात्रा मे अक्षर से युक्त नही है|',
	) ,
);
