<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-08-20 03:00+0000
$lang = array(
	'captcha' => array(
		'default' => '验证码输入不正确',
		'required' => '请输入验证码',
	) ,
	'contact_email' => array(
		'email' => '电子邮箱地址格式不正确',
		'length' => '电子邮箱地址长度应为4至64个字符',
		'required' => '打钩则电子邮箱地址为必填项',
	) ,
	'contact_message' => array(
		'required' => '消息内容是必填项',
	) ,
	'contact_name' => array(
		'length' => '用户名长度须不少于3个字母',
		'required' => '用户名是必填项',
	) ,
	'contact_subject' => array(
		'length' => '主题长度必须超过3个字符',
		'required' => '主题是必填项',
	) ,
);
