<?php
	$lang = array(
	'config' => '设置文件',
	'controller' => '控制器',
	'driver' => '驱动',
	'driver_implements' => '%s库的%s驱动必须采用%s界面',
	'driver_not_found' => '无法找到%s库的%s驱动',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => '无法完成请求',
	'helper' => '帮助',
	'invalid_filetype' => '您的显示设置文件不允许显示您所要求的文件类型， .%s',
	'invalid_method' => '无效的方法%s访问%s',
	'invalid_property' => '%s类型中并不存在%s财产。',
	'library' => '类',
	'log_dir_unwritable' => '日志记录无法写入：%s',
	'model' => '类型',
	'no_controller' => 'Ushahidi无法确定执行此请求的控制者: %s',
	'no_default_route' => '请在config/routes.php中设置默认路径',
	'page_not_found' => '无法找到您所要求的界面%s',
	'report_bug' => '<a href="%s" id="show_bugs">将此情况报告给Ushahidi</a>","<a href="%s">将此情况报告给Ushahidi</a>',
	'resource_not_found' => '无法找到所请求的%s, %s',
	'stack_trace' => '栈跟踪',
	'stats_footer' => '载入用时{execution_time}秒，使用内存{memory_usage}. 由Ushahidi v%s生成。',
	'uncaught_exception' => '无法捕捉 %s：%s 位于文件%s第%s行',
	'view' => '查看',
	'view_set_filename' => '您必须在调用前设置查看的文件名。',
	);
?>
