<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-27 00:04+0000
// PO revision date:  2012-07-12 21:33+0000

$lang = array (
  'am' => '上午',
  'friday' => 
  array (
    'abbv' => '五',
    'full' => '星期五',
  ),
  'monday' => 
  array (
    'abbv' => '一',
    'full' => '星期一',
  ),
  'pm' => '下午',
  'saturday' => 
  array (
    'abbv' => '六',
    'full' => '星期六',
  ),
  'sunday' => 
  array (
    'abbv' => '日',
    'full' => '星期日',
  ),
  'thursday' => 
  array (
    'abbv' => '四',
    'full' => '星期四',
  ),
  'tuesday' => 
  array (
    'abbv' => '二',
    'full' => '星期二',
  ),
  'wednesday' => 
  array (
    'abbv' => '三',
    'full' => '星期三',
  ),
);

