<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-26 12:04+0000
// PO revision date:  2012-07-12 21:36+0000

$lang = array (
  'cURL_not_installed' => '系统没有安装 php5-curl',
);

