<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-19 06:03+0000
// PO revision date:  2012-07-13 04:56+0000

$lang = array (
  'layer_color' => 
  array (
    'length' => '颜色值长度应是6个字符',
    'required' => '颜色值是必填项',
  ),
  'layer_file' => 
  array (
    'type' => '文件地址不包含有效的文件。只接受.KMZ，.KML类型的文件',
    'valid' => '文件地址不包含有效的文件',
  ),
  'layer_name' => 
  array (
    'length' => '姓名的长度应在3到80个字符之间',
    'required' => '姓名是必填项',
  ),
  'layer_url' => 
  array (
    'atleast' => '需要填入KML，链接或文件',
    'both' => '你无法同时使用一个KML文件和Url链接',
    'url' => '请输入一个正确的 URL。比如：http://www.ushahidi.com/layerl.kml',
  ),
);

