<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-19 23:22+0000
// PO revision date:  2012-07-12 21:43+0000
$lang = array(
	'captcha' => array(
		'default' => '请输入一个有效的验证码',
		'required' => '请输入安全码',
	) ,
	'email' => array(
		'email' => '邮件地址格式不正确',
		'length' => '邮件地址长度须在4至64个字符之间',
		'required' => '打钩将邮件地址设为必填项',
	) ,
	'message' => array(
		'required' => '评论栏为必填项',
	) ,
	'name' => array(
		'length' => '姓名长度须不少于3个字母',
		'required' => '姓名栏为必填项',
	) ,
	'phone' => array(
		'length' => '电话号码不可用',
	) ,
);
