<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-30 12:04+0000
// PO revision date:  2012-07-12 21:50+0000

$lang = array (
  'description' => 
  array (
    'length' => '描述的长度须在3到100个字符之间',
    'required' => '描述为必填项',
  ),
  'name' => 
  array (
    'alpha_numeric' => '姓名中只能包含字母和数字',
    'length' => '姓名的长度应在3到80个字符之间',
    'nomodify' => '超级管理员角色不能被更改',
    'required' => '姓名为必填项',
  ),
);

