<?php
	$lang = array(
	'allow_comments' => array(
		'between' => '允许评论栏格式错误',
		'required' => '允许评论为必选项',
	),
	'allow_feed' => array(
		'between' => '包括反馈栏格式错误',
		'required' => '包括反馈为必选项',
	),
	'allow_reports' => array(
		'between' => '允许报告栏格式错误',
		'required' => '允许报告为必选项',
	),
	'allow_stat_sharing' => array(
		'between' => '数据分享栏格式错误',
		'required' => '数据分享为必选项',
	),
	'api' => array(
		'default_record_limit' => '默认记录数量为每个API请求所获得的数量',
		'maximum_record_limit' => '最大记录数量为每个API请求所获得的数量',
		'maximum_requests_per_ip_address' => '每个IP地址最大的API请求数量',
	),
	'api_akismet' => array(
		'alpha_numeric' => 'Akismet栏格式错误',
		'length' => 'Akismet栏格式错误',
	),
	'cache_pages' => array(
		'between' => '缓存网页为必选项',
		'required' => '缓存网页格式错误',
	),
	'cache_pages_lifetime' => array(
		'in_array' => '缓存网页时间格式错误',
		'required' => '缓存网页时间为必填项',
	),
	'checkins' => '登入',
	'cleanurl' => array(
		'enable_clean_url' => '允许清除链接',
		'title' => '清除链接',
	),
	'clickatell_api' => array(
		'length' => 'Clickatell API号码不得长于20个字符',
		'required' => 'Clickatell API号码为必填项',
	),
	'clickatell_password' => array(
		'length' => 'Clickatell密码长度须在5到50个字符之间',
		'required' => 'Clickatell密码为必填项',
	),
	'clickatell_username' => array(
		'length' => 'Clickatell用户名不得长于50个字符',
		'required' => 'Clickatell用户名为必填项',
	),
	'configure_map' => '地图设置',
	'default_location' => '默认地址',
	'default_map_all' => array(
		'alpha_numeric' => '颜色值格式错误',
		'length' => '颜色值长度应是6个字符',
		'required' => '颜色值为必填项',
	),
	'default_map_view' => '查看默认地图',
	'default_zoom_level' => '默认缩放度',
	'download_city_list' => '从城市地名检索',
	'email_host' => array(
		'length' => '邮件服务器端口过长',
		'numeric' => '邮件服务器端口只能包含数字',
	),
	'email_password' => array(
		'length' => '邮件服务器密码必须在5到50个字符之间',
		'required' => '邮件服务器密码为必填项',
	),
	'email_port' => array(
		'length' => '邮件服务器端口过长',
		'numeric' => '邮件服务器端口只能包含数字',
	),
	'email_servertype' => array(
		'length' => '邮件服务器端口过长',
		'required' => '邮件服务器类型为必填项',
	),
	'email_username' => array(
		'length' => '邮件服务器用户名不得长于50个字符',
		'required' => '邮件服务器用户名为必填项',
	),
	'google_analytics' => array(
		'length' => 'Google Analytics中必须包含有效的网站内容ID，格式为UA-XXXXX-XX',
	),
	'items_per_page' => array(
		'between' => '每页项目数（前端）格式错误',
		'required' => '每页项目数（前端）为必填项',
	),
	'items_per_page_admin' => array(
		'between' => '每页项目数（管理员）格式错误',
		'required' => '每页项目数（管理员）格式错误',
	),
	'map' => array(
		'default_location' => '设置地图提供商的过程非常简单。选择提供商，从提供商的网站获得API密匙，然后输入该密匙即可。',
		'zoom' => '缩放',
	),
	'map_provider' => array(
		'choose' => '选择地图提供商',
		'enter_api' => '输入新的API密匙',
		'get_api' => '获得API密匙',
		'info' => '设置地图提供商的过程非常简单。选择提供商，从提供商的网站获得API密匙，然后输入该密匙即可。',
		'name' => '地图提供商',
	),
	'map_settings' => '地图设置',
	'multiple_countries' => '该Ushahidi布署是否跨越多个国家',
	'select_default_location' => '请选择默认的国家',
	'set_location' => '点击并拖动地图选择确切的位置',
	'site' => array(
		'allow_clustering' => '在地图上生成群报告',
		'allow_comments' => '允许所有用户对报告进行评论',
		'allow_feed' => '包括网站上的RSS新闻源',
		'allow_reports' => '允许用户提交报告',
		'api_akismet' => 'Akismet密匙',
		'cache_pages' => '缓存页',
		'cache_pages_lifetime' => '缓存页保存时间',
		'copyright_statement' => '网站版权描述',
		'default_category_colors' => '为所有分类采用默认颜色',
		'display_contact_page' => '显示联系页面',
		'email_alerts' => '提醒邮件地址',
		'email_notice' => '<span>如果想通过电子邮件接收报告，请在此设置您的电子邮件账号。</span>',
		'email_site' => '网站电子邮件地址',
		'google_analytics' => 'Google Analytics',
		'google_analytics_example' => '网页内容ID - 格式：UA-XXXXX-XX',
		'items_per_page' => '每页项目数量（前端）',
		'items_per_page_admin' => '每页项目数量（管理员）',
		'laconica_configuration' => 'Laconica证书',
		'laconica_site' => 'Laconica网站',
		'language' => '网站语言',
		'message' => '网站信息',
		'name' => '网站名称',
		'private_deployment' => '隐私设置',
		'share_site_stats' => '允许数据存储在Ushahidi的服务器',
		'tagline' => '网站标签',
		'title' => '网站设置',
		'twitter_configuration' => '推特搜索关键词',
		'twitter_hashtags' => '标签，以逗号分隔',
	),
	'site_email' => array(
		'email' => '网站电子邮箱格式无效',
		'length' => '网站电子邮箱地址长度须在4到100个字符之间',
	),
	'site_name' => array(
		'length' => '网站名称长度须在3到50个字符之间',
		'required' => '网站名称为必填项',
	),
	'site_tagline' => array(
		'length' => '标签栏长度须在3到100个字符之间',
		'required' => '标签栏为必选项',
	),
	'sms' => array(
		'clickatell_api' => '您的Clickatell API号码',
		'clickatell_check_balance' => '查看您的Clickatell帐户余额',
		'clickatell_load_balance' => '读取帐户余额',
		'clickatell_password' => '您的Clickatell密码',
		'clickatell_text_1' => '<a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">点击这里</a>注册Clickatell服务',
		'clickatell_text_2' => '在此输入您的Clickatell登录信息',
		'clickatell_username' => '您的Clickatell用户名',
		'flsms_description' => 'Frontline SMS是一款免费开源软件，可以将笔记本或移动电话变成中央通讯枢纽。安装该软件之后，便可以通过手机向大量用户发送短信。点击灰色按钮开始从FrontlineSMS.com下载软件。',
		'flsms_download' => '下载Frontline SMS并在您的计算机上安装',
		'flsms_key' => '您的Ushahidi同部密匙',
		'flsms_link' => 'Frontline SMS HTTP Post LINK',
		'flsms_synchronize' => '与Ushahidi同步',
		'flsms_text_1' => '在下方输入连入Frontline SMS的电话号码',
		'flsms_text_2' => '请输入电话号码，不包含“+”和“-”',
		'option_1' => '选项1：使用Frontline SMS',
		'option_2' => '选项2：使用Global SMS接口',
		'title' => 'SMS设置选项',
	),
	'sms_no1' => array(
		'length' => '电话号码1格式错误',
		'numeric' => '电话号码1只能包括数字',
	),
	'sms_no2' => array(
		'length' => '电话号码2过长',
		'numeric' => '电话号码2只能包括数字',
	),
	'sms_no3' => array(
		'length' => '电话号码3过长',
		'numeric' => '电话号码3只能包括数字',
	),
	'ssl' => array(
		'enable_ssl' => '允许SSL',
		'title' => 'SSL支持',
	),
	'timezone' => '时区',
	);
?>
