<?php
	$lang = array(
	'approved' => '已准许',
	'categories' => '分类',
	'category_impact' => '分类影响',
	'category_impact_description' => '您可以在该表格中看到各类别的报告量随时间变化的情况。从左到右拖动滚动条可以看到不同分类的情况。将鼠标移到图片上可以查看详情。',
	'choose_date_range' => '选择日期范围',
	'countries' => '国家',
	'country' => '国家',
	'country_breakdown' => '国家分布',
	'description' => '您好，这是数据部分。总体描述将随后放出。现在，您可以在上面的分类链接中访问其他页面。',
	'error' => '错误',
	'glossary' => '术语表',
	'hit_summary' => '点击统计',
	'legend' => '图例',
	'pageviews' => '页面访问',
	'pageviews_description' => '访问者在您的网站上访问页面的总数量',
	'reports' => '报道',
	'reports_categories' => '报道类型',
	'reports_statistics' => '报道数据',
	'reports_status' => '报道状态',
	'report_punchcard' => '报道穿孔卡',
	'report_stats' => '报道数据',
	'stats_not_setup' => '数据未确定',
	'time_range_1' => '1个月',
	'time_range_2' => '3个月',
	'time_range_3' => '6个月',
	'time_range_all' => '全部',
	'unapproved' => '未批准的',
	'unique_visitors' => '独立访问者',
	'unique_visitors_description' => '访问您的页面的人数；独立访问者的身份标识为其浏览器cookie。如果来访者没有使用cookie，将通过IP地址、协议、浏览器、插件、操作系统等方式来验证其身份。',
	'unverified' => '未验证的',
	'verified' => '已验证的',
	'visitor_summary' => '访客总数',
	'visits' => '访问',
	'visits_description' => '在最后一次页面访问以后30分钟后重新登录的独立访问者将被视为一次新的访问。',
	);
?>
