<?php
	$lang = array(
	'upgrade' => array(
		'between' => '无效的输入数据。0表示否，1表示是。',
	),
	'upgrade_automatic' => '自动升级',
	'upgrade_available' => '可用的更新',
	'upgrade_continue_btn_text' => '继续',
	'upgrade_db_btn_text' => '升级',
	'upgrade_db_text_1' => '我们将把您的数据库自',
	'upgrade_db_text_2' => '版本升级至新的版本',
	'upgrade_db_text_3' => '点击“升级”按钮，在我们升级的过程中您可以放松一下。',
	'upgrade_db_text_4' => '如果您希望我们为您备份数据库，只需要点击下面的按钮，就可以轻松备份了',
	'upgrade_db_text_5' => '在升级时是否备份数据库？（强烈推荐您如此做）',
	'upgrade_db_title' => 'Ushahidi数据库升级',
	'upgrade_failed' => '升级失败',
	'upgrade_manual' => '手动升级',
	'upgrade_status' => 'Ushahidi升级情况',
    'upgrade_text_1' => 'The instructions below detail how to manually upgrade your Ushahidi deploymentl',
    'upgrade_text_2' => '<dl><dt><strong>Download</strong></dt>',
	'upgrade_text_3' => '<dd>- Download the most recent Ushahidi build from',
	'upgrade_text_4' => '<dt><strong>Backup</strong></dt><dd>- .htaccess, ./applications/config/config.php, ./applications/config/database.php and ./applications/config/auth.php files. </dd><dd>- Just in case something goes wrong, it\'s recommended you make an entire backup of your Ushahidi deployment.</dd><dt><strong>Copy files</strong></dt><dd>- Extract the downloaded zip file</dd><dd>- Depending on the operating system running the web server, use your preferred tool/mode (e.g. Telnet, FTP, SSH) to login to the webserver and replace the contents of all the folders with the newest from the recent build.</dd><dt><strong>Upgrde database</strong></dt><dd>- First determine your database schema version by looking at the <strong>db_version</strong> value in the settings table or look at the Ushahidi upgrade information at the top of this page. </dd><dd>- If you are at version 25, you need to upgrade from 25-26, 26-27, 27-28 and so on up to the latest SQL file in your <strong>/sql</strong> directory.</dd><dd>- With your database client, upgrade the database by executing the appropriate upgradex-x.sql file.</dd></dl>',
    'upgrade_tables' => '<strong>Step 3:</strong> Look inside the <strong>sql</strong> folder. Manuall run the upgrade<xx>-<xx>.sql file starting from the current db version of your install through to the final sql upgrade file.',
    'upgrade_text_5' => '<strong>Step 4:</strong> Click on the <strong>"Continue"</strong> button to upgrade the necessary tables.',
	'upgrade_text_6' => 'For automatic upgrade, click on the button below.',
    'upgrade_title_text_1' => 'You are currently using Ushahidi v',
    'upgrade_title_text_2' => 'with database version ',
	'upgrade_title_text_3' => 'running on',
	'upgrading' => '正在升级',
    'upgrade_ftp_text' => 'To continue with the easy upgrade, the following information is required for the FTP server that your website is hosted on.',
    'upgrade_ftp_hostname' => 'FTP Hostname: <span>Example: "localhost"</span>',
    'upgrade_ftp_password' => 'FTP Password:',
    'upgrade_ftp_username' => 'FTP User Name:',
    'upgrade_status_info' => 'You have the latest version of Ushahidi.',
    'upgrade_db_version' => 'Database version: ',
    'upgrade_warning_software_version' => 'Warning: Software version in version.php and database do not match.',
    'upgrade_warning_db_version' => 'Warning: Database version in version.php and database do not match.',
    'upgrade_database' => 'Database:'
);
?>
