<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-02 01:56+0000
$lang = array(
	'incident_id' => array(
		'required' => '체크한 아이템을 다시 한 번 확인해주세요.',
		'numeric' => '체크한 아이템을 다시 한 번 확인해주세요.',
		'categories_required' => '리포트는 승인 전 반드시 카테고리에 속해 있어야 합니다.',
	) ,
	'action' => array(
		'permission' => '이것을 실행하기 위해 허락이 필요없습니다.',
	) ,
);
