<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-25 12:04+0000
// PO revision date:  2012-08-19 22:56+0000
$lang = array(
	'site' => array(
		'allow_clustering' => '리포트 그룹표시 활성화',
		'allow_comments' => '사용자 코멘트 활성화',
		'allow_feed' => 'RSS 뉴스피드 표시 활성화',
		'allow_alerts' => '사용자 알람받기 활성화',
		'allow_reports' => '사용자 리포트 활성화',
		'banner' => '사이트 배너',
		'blocks_per_row' => '한 줄당 칸',
		'cache_pages' => '캐쉬페이지',
		'cache_pages_lifetime' => '캐쉬페이지 시간',
		'checkins' => '체크인 기능 활성화',
		'copyright_statement' => '사이트 저작권',
		'default_category_colors' => '대표 컬러',
		'default_category_icons' => '대표 아이콘',
		'delete_banner_image' => '배너 사진 삭제',
		'delete_default_map_all_icon' => '기본 아이콘 삭제',
		'display_contact_page' => '연락처 표시',
		'display_howtohelp_page' => '도움말 표시',
		'email_alerts' => '알림 이메일 주소',
		'email_notice' => '<span>정확한 이메일 주소를 입력해주세요. 리포트와 연락처에 노출됩니다.</span>',
		'email_site' => '사이트 이메일 주소',
		'items_per_page' => '한 페이지당 리포트 수 - 홈페이지 메인화면',
		'items_per_page_admin' => '한 페이지당 리포트 수 - 운영자',
		'kismet_notice' => '자동 스팸 방지 <a href="http://akismet.com/" target="_blank">Akismet</a><BR />무료 API KEY는 <a href="http://en.wordpress.com/api-keys/" target="_blank">WordPress.com user account</a>에 등록하시면 받을 수 있습니다.',
		'laconica_site' => 'Laconica Site',
		'language' => '사이트 언어',
		'manually_approve_users' => '사용자 수동 승인',
		'message' => '공지사항-HOME에 나타납니다.',
		'name' => '사이트 이름',
		'require_email_confirmation' => '이메일 확인이 필요합니다.',
		'submit_report_message' => '리포트 신고 페이지 공지사항',
		'share_site_stats' => '사이트 통계 설정(유샤히디 서버에 저장)',
		'tagline' => '간단하게 사이트 설명을 입력해주세요.',
		'timezone' => '타임존',
		'title' => '사이트 설정',
		'twitter_configuration' => '트위터 해쉬태그 입력',
		'twitter_hashtags' => '해쉬태그는 콤마로 구분해주세요.',
	) ,
);
