<?php
	$lang = array(
	'allow_comments' => array(
		'between' => 'The allow comments field does not appear to contain a valid value.',
		'required' => 'The allow comments field is required.',
	),
	'allow_feed' => array(
		'between' => 'The include feed field does not appear to contain a valid value.',
		'required' => 'The include feed field is required.',
	),
	'allow_alerts' => array(
		'between' => 'The allow alerts field does not appear to contain a valid value.',
		'required' => 'The allow alerts field is required.',
	),
	'allow_reports' => array(
		'between' => 'The allow reports field does not appear to contain a valid value.',
		'required' => 'The allow reports field is required.',
	),
	'allow_stat_sharing' => array(
		'between' => 'The stat sharing field does not appear to contain a valid value.',
		'required' => 'The stat sharing field is required.',
	),
	'api' => array(
		'default_record_limit' => 'Default number of records to be fetched per API request',
		'maximum_record_limit' => 'Maximum number of records to be fetched per API request',
		'maximum_requests_per_ip_address' => 'Maximum number of API requests per IP address',
	),
	'api_akismet' => array(
		'alpha_numeric' => 'The Akismet field does not appear to contain a valid value.',
		'length' => 'The Akismet field does not appear to contain a valid value.',
	),
	'banner_image' => array(
		'default' => 'Something went wrong with your banner image upload.',
		'size' => 'The size of your banner exceeds the size limit for this upload.'
	),
	'cache_pages' => array(
		'between' => 'The cache pages field is required.',
		'required' => 'The cache pages field does not appear to contain a valid value.',
	),
	'cache_pages_lifetime' => array(
		'in_array' => 'The cache pages lifetime field does not appear to contain a valid value.',
		'required' => 'The cache pages lifetime field is required.',
	),
	'cleanurl' => array(
		'clean_url_disabled' => 'It looks like your server is not configured to handle clean URLs. You will need to change the configuration of your server before you can enable clean URLs. See more info on how to enable clean URLs at <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">this forum post</a>',
		'clean_url_enabled' => 'This option makes Ushahidi to be accessed via "clean" URLs (without "index.php" in the URL).',
		'enable_clean_url' => 'Enable Clean URLs',
		'title' => 'Clean URLs',
	),
	'clickatell_api' => array(
		'length' => 'The Clickatell API number field must be no more 20 characters long.',
		'required' => 'The Clickatell API number field is required.',
	),
	'clickatell_password' => array(
		'length' => 'The Clickatell Password field must be at least 5 and no more 50 characters long.',
		'required' => 'The Clickatell Password field is required.',
	),
	'clickatell_username' => array(
		'length' => 'The Clickatell Username field must be no more 50 characters long.',
		'required' => 'The Clickatell Username field is required.',
	),
	'configure_map' => 'Configure Map',
	'default_location' => 'Default Location',
	'default_map_all' => array(
		'alpha_numeric' => 'The color feed field does not appear to contain a valid value.',
		'length' => 'The color field must be no more 6 characters long.',
		'required' => 'The color field is required.',
	),
	'default_map_view' => 'Default Map View',
	'default_zoom_level' => 'Default Zoom Level',
	'download_city_list' => 'Retrieve Cities From Geonames',
	'email_host' => array(
		'length' => 'The Mail server port field is too long.',
		'numeric' => 'The Mail server port field should contain numbers only.',
	),
	'email_password' => array(
		'length' => 'The Mail Server Password field must be at least 5 and no more 50 characters long.',
		'required' => 'The Mail Server Password field is required.',
	),
	'email_port' => array(
		'length' => 'The Mail server port field is too long.',
		'numeric' => 'The Mail server port field should contain numbers only.',
	),
	'email_servertype' => array(
		'length' => 'The Mail server port field is too long.',
		'required' => 'The Mail Server Type field is required.',
	),
	'email_username' => array(
		'length' => 'The Mail Server Username field must be no more 50 characters long.',
		'required' => 'The Mail Server Username field is required.',
	),
	'facebook' => array(
		'title' => 'Facebook Setup Options',
		'description' => 'To get the information below you will need to create a new Facebook application at',
		'app_id' => 'Facebook App ID',
		'app_secret' => 'Facebook App Secret'
	),
	'google_analytics' => array(
		'length' => 'The Google Analytics field must contain a valid Web Property ID in the format UA-XXXXX-XX.',
	),
	'https' => array(
	   'enable_https' => 'Enable HTTPS',
	   'https_disabled' => 'This option makes Ushahidi be accessed in unsecure mode; <strong>without</strong> "https://" in the URL prefix',
	   'https_enabled' => 'This option makes Ushahidi be accessed in secure mode; with <strong>https</strong> in the URL prefix',
	   'title' => 'HTTPS'
	),
	'items_per_page' => array(
		'between' => 'The items per page (Frontend) field does not appear to contain a valid value.',
		'required' => 'The items per page (Frontend) field is required.',
	),
	'items_per_page_admin' => array(
		'between' => 'The items per page (Admin) field does not appear to contain a valid value.',
		'required' => 'The items per page (Admin) field is required.',
	),
	'map' => array(
		'default_location' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key.',
		'zoom' => 'Zoom Level',
	),
	'map_provider' => array(
		'choose' => 'Select a Map Provider',
		'enter_api' => 'Enter the new API Key',
		'get_api' => 'Get an API Key',
		'info' => 'Setting up your map provider is a straight-forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key.',
		'name' => 'Map provider',
	),
	'map_settings' => 'Map Settings',
	'multiple_countries' => 'Does this Ushahidi Deployment span multiple countries?',
	'select_default_location' => 'Please select a default country',
	'set_location' => 'Click and drag the map to set your exact location',
	'site' => array(
		'allow_clustering' => '리포트 그룹표시 활성화',
		'allow_comments' => '사용자 코멘트 활성화',
		'allow_feed' => 'RSS 뉴스피드 표시 활성화',
		'allow_alerts' => '사용자 알람받기 활성화',
		'allow_reports' => '사용자 리포트 활성화',
		'api_akismet' => 'Akismet Key',
		'banner' => '사이트 배너',
		'blocks_per_row' => '한 줄당 칸',
		'cache_pages' => '캐쉬페이지',
		'cache_pages_lifetime' => '캐쉬페이지 시간',
		'checkins' => '체크인 기능 활성화',
		'copyright_statement' => '사이트 저작권',
		'default_category_colors' => '대표 컬러',
		'default_category_icons' => '대표 아이콘',
		'delete_banner_image' => '배너 사진 삭제',
		'delete_default_map_all_icon' => '기본 아이콘 삭제',
		'display_contact_page' => '연락처 표시',
		'display_howtohelp_page' => '도움말 표시',
		'email_alerts' => '알림 이메일 주소',
		'email_notice' => '<span>정확한 이메일 주소를 입력해주세요. 리포트와 연락처에 노출됩니다.</span>',
		'email_site' => '사이트 이메일 주소',
		'google_analytics' => 'Google Analytics',
		'google_analytics_example' => 'Web Property ID - Format: UA-XXXXX-XX',
		'items_per_page' => '한 페이지당 리포트 수 - 홈페이지 메인화면',
		'items_per_page_admin' => '한 페이지당 리포트 수 - 운영자',
		'kismet_notice' => '자동 스팸 방지 <a href="http://akismet.com/" target="_blank">Akismet</a><BR />무료 API KEY는 <a href="http://en.wordpress.com/api-keys/" target="_blank">WordPress.com user account</a>에 등록하시면 받을 수 있습니다.',
		'laconica_configuration' => 'Laconica Credentials',
		'laconica_site' => 'Laconica Site',
		'language' => '사이트 언어',
		'manually_approve_users' => '사용자 수동 승인',
		'map_point_reports' => 'Reports are points',
		'message' => '공지사항-HOME에 나타납니다.',
		'name' => '사이트 이름',
		'private_deployment' => 'Private Deployment',
		'require_email_confirmation' => '이메일 확인이 필요합니다.',
		'submit_report_message' => '리포트 신고 페이지 공지사항',
		'share_site_stats' => '사이트 통계 설정(유샤히디 서버에 저장)',
		'tagline' => '간단하게 사이트 설명을 입력해주세요.',
		'timezone' => '타임존',
		'title' => '사이트 설정',
		'twitter_configuration' => '트위터 해쉬태그 입력',
		'twitter_hashtags' => '해쉬태그는 콤마로 구분해주세요.',
	),
	'site_email' => array(
		'email' => 'The site email field does not appear to contain a valid email address.',
		'length' => 'The site email field must be at least 4 and no more 100 characters long.',
	),
	'site_name' => array(
		'length' => 'The site name field must be at least 3 and no more 50 characters long.',
		'required' => 'The site name field is required.',
	),
	'site_tagline' => array(
		'length' => 'The tagline field must be at least 3 and no more 100 characters long.',
		'required' => 'The tagline field is required.',
	),
	'sms' => array(
		'clickatell_api' => 'Your Clickatell API Number',
		'clickatell_check_balance' => 'Check Your Clickatell Credit Balance',
		'clickatell_load_balance' => 'Load Credit Balance',
		'clickatell_password' => 'Your Clickatell Password',
		'clickatell_text_1' => 'Sign up for Clickatells service by <a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">clicking here</a>',
		'clickatell_text_2' => 'Enter your Clickatell access information below',
		'clickatell_username' => 'Your Clickatell User Name',
		'flsms_description' => 'FrontlineSMS is free open source software that turns a laptop and a mobile phone into a central communications hub. Once installed, the program enables users to send and receive text messages with large groups of people through mobile phones. Click on the grey box to request a download from FrontlineSMS.com',
		'flsms_download' => 'Download Frontline SMS and install it on your computer',
		'flsms_instructions' => 'Messages received into a FrontlineSMS hub can be synched with Ushahidi. Detailed instructions on how to sync can be found <strong><a href="http://wiki.ushahidi.com/display/WIKI/How+to+Set-up+FrontlineSMS+and+Ushahidi" target="_blank">here</a></strong>. You will require the key and link below to set up the sync with FrontlineSMS',
		'flsms_key' => 'Your Ushahidi Sync Key',
		'flsms_link' => 'FrontlineSMS HTTP Post LINK',
		'flsms_synchronize' => 'Sync with Ushahidi',
		'flsms_text_1' => 'Enter phone number(s) connected to Frontline SMS in the field(s) below',
		'flsms_text_2' => 'Enter the number without any + or dashes below',
		'option_1' => 'Option 1: Use Frontline SMS',
		'option_2' => 'Option 2: Use a Global SMS Gateway',
		'title' => 'SMS Setup Options',
	),
	'sms_no1' => array(
		'length' => 'The phone 1 field does not appear to contain a valid value.',
		'numeric' => 'The phone 1 field should contain numbers only.',
	),
	'sms_no2' => array(
		'length' => 'The phone 2 field is too long.',
		'numeric' => 'The phone 2 field should contain numbers only.',
	),
	'sms_no3' => array(
		'length' => 'The phone 3 field is too long.',
		'numeric' => 'The phone 3 field should contain numbers only.',
	));
?>
