<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-06 00:04+0000
// PO revision date:  2012-09-02 04:09+0000
$lang = array(
	'actions' => array(
		'add_to_category' => '이 기능은 하나의 리포트에 추가 카테고리를 설정할 수 있게 합니다. 예를 들면 카테고리 1을 선택하고 카테고리 2를 추가로 선택하면, 해당 리포트는 2개의 카테고리에 속하게 됩니다.',
		'approve' => '리포트를 승인 또는 하지 않음. 만약 승인하면 리포트는 공개됩니다.',
		'between_times' => '24시간 형식으로 시간 범위를 지정할 수 있습니다. 나중의 시간이 앞에 설정한 시간보다 빠르면 오류가 발생합니다. 또한, 시간은 하루 내 이어야 합니다. 그리고 설정한 시간은 사이트 설정에서 설정한 사이트 시간을 기준으로 하며, 사용자의 타임존을 필요로 하지는 않습니다. 시간을 입력하지 않으려면 00:00에서 00:00의 형식으로 놔두면 됩니다.',
		'days_of_the_week' => '여기서 설정을 통해 특정 요일에 이것들을 실행되게 할 수 있습니다. 당신의 배치상의 타임존을 반드시 고려해야 합니다. shift키와 command 또는 control키를 동시에 누르면 중복 요일 선택이 가능합니다.',
		'email_body' => '이메일의 본문이 전송됩니다.',
		'email_subject' => '이메일의 제목이 전송됩니다.',
		'keywords' => '키워드를 입력하길 원하지 않으면 빈칸으로 두어도 됩니다. 만약, 단어를 입력하고자 하면, 콤마(,)로 구분하면 됩니다. 예를 들어 "love"또는"peace"를 메시지에 넣고자 하면, "love,peace"의 형태로 구분 입력하면 됩니다.',
		'location' => '다양한 지역 선택이 가능합니다. 만약, 특정 지역을 선택하고 해당 지역에서만 리포트를 받을 수 있습니다. 예를 들어 누군가로부터 브라질에 관련한 리포트를 받길 원하면, "특정지역"을 선택하고, 브라질 주위에 박스를 그려 이를 설정할 수 있습니다. 이 박스의 크기는 자유롭게 설정할 수 있으며, 1개 이상의 박스를 그릴 수 있습니다.',
		'on_specific_count' => '이것은 전체 유저 베이스 또는 개별 유저 중 하나에서 특정번째에서 작동되게 할 수 있습니다. 사용하지 않으려면 빈칸으로 두면 됩니다.',
		'report_title' => '리포트의 기본 제목입니다.',
		'send_to' => '"',
	) ,
	'settings_site_tagline' => '몇 개 안 되는 단어로 이 웹페이지를 설명할 수 있습니다',
	'settings_site_timezone' => '이 곳이 당신의 사이트를 만들  수 있는 곳입니다. ',
	'settings_twitter_configuration' => '트위터 해쉬태그를 설정해주세요.(예시: #Ushahidi)',
);
