<?php
	$lang = array(
	'alert_email' => array(
		'email' => 'Ist Ihre angegebene eMail-Adresse korrekt?',
		'email_check' => 'Diese eMail-Adresse ist bereits für Benachrichtigungen von diesem Ort registriert.',
		'length' => 'Die eMail-Adresse darf nicht weniger als 4 und mehr als 64 Zeichen lang sein.',
		'one_required' => 'Email Adresse erforderlich',
		'required' => 'Das eMail-Feld muss ausgefüllt sein, wenn das Kästchen angehakt wurde.',
	),
	'alert_lat' => array(
		'between' => 'Sie haben einen ungültigen Ort ausgewählt.',
		'required' => 'Sie haben einen ungültigen Ort ausgewählt.',
	),
	'alert_lon' => array(
		'between' => 'Sie haben einen ungültigen Ort ausgewählt.',
		'required' => 'Sie haben einen ungültigen Ort ausgewählt.',
	),
	'alert_mobile' => array(
		'length' => 'Das Feld für die Handynummer scheint eine falsche Anzahl von Nummern zu beinhalten.',
		'mobile_check' => 'Diese Handynummer wurde bereits für Benachrichtigungen zu diesem Ort registriert.',
		'numeric' => 'Die Handynummer scheint nicht gültig zu sein. Bitte fügen Sie der Nummer nur das Länderpräfix an.',
		'one_required' => 'Sie müssen entweder Ihre Handynummer oder Ihre eMail-Adresse eingeben.',
		'required' => 'Sie müssen Ihre Handynummer angeben, wenn das Kästchen angehakt wurde.',
	),
	'alert_radius' => array(
		'in_array' => 'Sie haben einen ungültigen Radius gewählt.',
		'required' => 'Sie haben keinen Radius auf der Karte gewählt.',
	),
	'code_already_verified' => 'Dieser Schlüssel wurde schon einmal verwendet!',
	'code_not_found' => 'Dieser Verifizierungsschlüssel wurde nicht gefunden! Bitte überprüfen Sie, ob Sie die richtige URL angegeben haben.',
	'code_verified' => 'Ihr Schlüssel wurde erfolgreich verifiziert. Sie erhalten nun aktuelle Meldungen.',
	'confirm_request' => 'Um Ihre Anfrage zu bestätigen, gehen Sie bitte zu',
	'create_more_alerts' => 'Zurück zur Benachrichtigungsseite gehen, um weitere Meldungen zu abonnieren ',
	'email_alert_request_created' => 'Ihre Anfrage wurde erstellt. Eine Verifizierungs-eMail wurde geschickt an ',
	'email_code' => 'Bitte geben Sie unten den eMail-Bestätigungscode ein',
	'email_error_head' => 'Ihre Anfrage wurde NICHT gespeichert!',
	'email_ok_head' => 'Ihre Anfrage wurde erfolgreich gespeichert!',
	'error' => 'Das System konnte Ihren Bestätigungsvorgang nicht vollenden.',
	'mobile_alert_request_created' => 'Ihre Alarmanforderung via Mobiltelefon wurde bearbeitet und wurde gesendet an:',
	'mobile_code' => 'Bitte geben Sie den SMS-Bestätigungscode ein, den Sie per SMS empfangen haben.',
	'mobile_error_head' => 'Ihre Alarmanforderung via Mobiltelefon wurde NICHT gespeichert.',
	'mobile_ok_head' => 'Ihre Anforderung für mobilen Alarm wurde gespeichert!',
	'settings_error' => 'Fehler in den Einstellungen. Alarme können nicht korrekt ausgeführt werden.',
	'unsubscribe' => 'Sie erhalten diese eMail aufgrund Ihrer Anmeldung zum Erhalt aktueller Meldungen. Wenn Sie keine weiteren Meldungen mehr erhalten möchten, gehen Sie bitte zu',
	'unsubscribed' => 'Sie werden keine weiteren Meldungen erhalten von',
	'unsubscribe_failed' => 'Wir konnten Sie nicht abmelden. Bitte überprüfen Sie, ob Sie die korrekte URL angegeben haben.',
	'verification_email_subject' => 'Erhalte Meldungen - Bestätigung',
	'verify_code' => 'Sie müssen Ihre Anfrage bestätigen, um Meldungen für diesen Ort zu erhalten.',
	);
?>
