<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-24 18:04+0000
// PO revision date:  2012-07-12 21:24+0000

$lang = array (
  'email' => 
  array (
    'email' => 'Das eMail-Feld enthält eine ungültige Mailadresse.',
    'exists' => 'Sorry, diese eMailadresse ist bereits einem Account zugeordnet.',
    'length' => 'Die eMail-Adresse muss zwischen 4 und 64 Zeichen lang sein.',
    'required' => 'Die eMail-Adresse ist ein Pflichtfeld',
  ),
  'name' => 
  array (
    'length' => 'Die eMail-Adresse muss zwischen 3 und 100 Zeichen lang sein.',
    'required' => 'Der vollständige Name ist notwendig.',
    'standard_text' => 'Der Benutzername enthält nicht erlaubte Zeichen',
  ),
  'password' => 
  array (
    'length' => 'Das Passwort muss zwischen 5 und 16 Zeichen lang sein',
    'login error' => 'Please check that you entered the correct password.',
    'matches' => 'Bitte geben Sie zweimal das richtige Passwort ein.',
    'required' => 'Das Passwortfeld ist notwendig.',
  ),
  'password_confirm' => 
  array (
    'matches' => 'Bitte geben Sie zweimal das richtige Passwort ein.',
  ),
  'resetemail' => 
  array (
    'email' => 'Die eMail-Adresse ist ungültig.',
    'invalid' => 'Sorry, wir finden Ihre eMail-Adresse nicht.',
    'required' => 'Die eMail-Adresse ist notwendig.',
  ),
  'roles' => 
  array (
    'alpha_numeric' => 'Ungültiges Rollen-Format',
    'length' => 'Die Feldlänge von ROLLE muss zwischen 5 und 30 Zeichen lang sein.',
    'required' => 'Du musst min. eine Rolle festgelegen',
    'values' => 'Du musst entweder ADMIN oder USER wählen.',
  ),
  'username' => 
  array (
    'admin' => 'Die Admin-Rolle kann nicht verändert werden.',
    'exists' => 'Sorry, der Benutzername ist bereits vergeben.',
    'length' => 'Der Benutzername muss zwischen 2 und 16 Zeichen lang sein.',
    'login error' => 'Please check that you entered the correct username.',
    'required' => 'Der Benutzname ist ein Pflichtfeld.',
    'superadmin' => 'Die Super-Admin-Rolle kann nicht verändert werden.',
  ),
);

