<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-19 12:03+0000
// PO revision date:  2012-07-12 21:25+0000

$lang = array (
  'captcha' => 
  array (
    'default' => 'Bitte geben Sie einen gültigen Sicherheitscode ein.',
    'required' => 'Bitte geben Sie den Sicherheitscode ein.',
  ),
  'email' => 
  array (
    'email' => 'Das eMailfeld scheint keine gültige eMailadresse zu enthalten.',
    'length' => 'Das eMailfeld muss mindestens 4 und höchstens 64 Zeichen lang sein.',
    'required' => 'Das eMailfeld ist erforderlich, wenn das Kästchen angehakt wurde.',
  ),
  'error' => 
  array (
    'required' => 'Das Fehlerfeld ist notwendig.',
  ),
  'subject' => 
  array (
    'length' => 'Das Betreffeld muss mindestens 3 Zeichen lang sein.',
    'required' => 'Das Betreff-Feld ist notwendig.',
  ),
  'yourname' => 
  array (
    'length' => 'Das Namensfeld muss mindestens 3 Zeichen lang sein.',
    'required' => 'Das Namensfeld ist notwendig.',
  ),
);

