<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-16 06:03+0000
// PO revision date:  2012-07-12 21:28+0000

$lang = array (
  'captcha' => 
  array (
    'default' => 'Bitte geben Sie einen gültigen Sicherheitskode ein.',
    'required' => 'Bitte geben Sie den Sicherheitskode ein.',
  ),
  'comment_author' => 
  array (
    'length' => 'Das Namensfeld muss min 3 Zeichen lang sein.',
    'required' => 'Das Namensfeld ist notwendig',
  ),
  'comment_description' => 
  array (
    'required' => 'Das Kommentarfeld ist notwendig',
  ),
  'comment_email' => 
  array (
    'email' => 'Das eMail-Feld scheint eine ungültige Adresse zu enthalten?',
    'length' => 'Die eMail-Adresse muss zwischen 4 und 64 Zeichen lang sein.',
    'required' => 'Das eMailfeld ist notwendig wenn die Box angekreuzt ist',
  ),
);

