<?php
	$lang = array(
	'config' => 'config file',
	'controller' => 'controller',
	'driver' => 'driver',
	'driver_implements' => 'The %s driver for the %s library must implement the %s interface',
	'driver_not_found' => 'The %s driver for the %s library could not be found',
	'errors_disabled' => 'Sie können auf die <a href="%s">home page</a> gehen oder <a href="%s"> es erneut versuchen</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'Konnte die Anforderung nicht erfüllen',
	'helper' => 'helper',
	'invalid_filetype' => 'Der angeforderte Dateityp, .%s, ist nicht erlaubt entsprechend Deinen Einstellungen',
	'invalid_method' => 'Ungültige Methode %s called in %s',
	'invalid_property' => 'Die %s property existiert nicht in der %s class.',
	'library' => 'library',
	'log_dir_unwritable' => 'Das log Verzeichnis ist nicht beschreibbar: %s',
	'model' => 'model',
	'no_controller' => 'Ushahidi war nicht in der Lage den Controller zu bestimmen für diese Anforderung: %s',
	'no_default_route' => 'Bitte setze eine Standardroute in config/routes.php',
	'page_not_found' => 'Die angefoderte Seite, %s, konnte nicht gefunden werden.',
	'report_bug' => '<a href="%s" id="show_bugs">Berichte diesen Punkt an Ushahidi</a>',
	'resource_not_found' => 'Die Anforderung %s, %s, konnte nicht gefunden werden',
	'stack_trace' => 'Stack Trace',
	'stats_footer' => 'Geladen in {execution_time} Sekunden, Speicherplatz {memory_usage}. Erzeugt von Ushahidi v%s.',
	'there_can_be_only_one' => 'Es kann nur eine Ushahidi Instanz geben pro Seitenanforderung.',
	'uncaught_exception' => 'Uncaught %s: %s in Datei %s in Linie %s',
	'view' => 'Zeige',
	'view_set_filename' => 'Du musst den Dateinamen festlegen bevor der Render aufgerufen wird',
	);
?>
