<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-21 00:04+0000
// PO revision date:  2012-08-19 22:45+0000
$lang = array(
	'driver_implements' => 'The %s driver for the %s library must implement the %s interface',
	'driver_not_found' => 'The %s driver for the %s library could not be found',
	'errors_disabled' => 'Sie können auf die <a href="%s">home page</a> gehen oder <a href="%s"> es erneut versuchen</a>.',
	'generic_error' => 'Konnte die Anforderung nicht erfüllen',
	'invalid_filetype' => 'Der angeforderte Dateityp, .%s, ist nicht erlaubt entsprechend Ihren Einstellungen',
	'invalid_method' => 'Ungültige Methode %s called in %s',
	'invalid_property' => 'Die %s property existiert nicht in der %s class.',
	'log_dir_unwritable' => 'Das log Verzeichnis ist nicht beschreibbar: %s',
	'no_controller' => 'Ushahidi war nicht in der Lage den Controller zu bestimmen für diese Anforderung: %s',
	'no_default_route' => 'Bitte setzen Sie eine Standardroute in config/routes.php',
	'page_not_found' => 'Die angefoderte Seite, %s, konnte nicht gefunden werden.',
	'report_bug' => '<a href="%s" id="show_bugs">Berichte diesen Punkt an Ushahidi</a>',
	'resource_not_found' => 'Die Anforderung %s, %s, konnte nicht gefunden werden',
	'stats_footer' => 'Geladen in {execution_time} Sekunden, Speicherplatz {memory_usage}. Erzeugt von Ushahidi v%s.',
	'there_can_be_only_one' => 'Es kann nur eine Ushahidi Instanz geben pro Seitenanforderung.',
	'uncaught_exception' => 'Uncaught %s: %s in Datei %s in Linie %s',
	'view' => 'Zeige',
	'view_set_filename' => 'Sie müssen den Dateinamen festlegen bevor der Render aufgerufen wird',
);
