<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-07 06:05+0000
// PO revision date:  2012-07-12 21:32+0000

$lang = array (
  'am' => 'vormittag',
  'friday' => 
  array (
    'abbv' => 'FR',
    'full' => 'Freitag',
  ),
  'monday' => 
  array (
    'abbv' => 'MO',
    'full' => 'Montag',
  ),
  'pm' => 'nachmittag',
  'saturday' => 
  array (
    'abbv' => 'SA',
    'full' => 'Samstag',
  ),
  'sunday' => 
  array (
    'abbv' => 'SO',
    'full' => 'Sonntag',
  ),
  'thursday' => 
  array (
    'abbv' => 'DO',
    'full' => 'Donnerstag',
  ),
  'tuesday' => 
  array (
    'abbv' => 'DI',
    'full' => 'Dienstag',
  ),
  'wednesday' => 
  array (
    'abbv' => 'MI',
    'full' => 'Mittwoch',
  ),
);

