<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-19 00:04+0000
// PO revision date:  2012-08-23 19:53+0000
$lang = array(
	'date' => 'Datum',
	'feed_name' => array(
		'length' => 'Der Name muss zwischen 3 und 70 Zeichen lang sein.',
		'required' => 'Bitte gib den Feed Namen ein.',
	) ,
	'feed_url' => array(
		'required' => 'Bitte URL eingeben.',
		'url' => 'Bitte gültige Adresse eingeben. Z.B. http://www.ushahidi.com.',
	) ,
	'source' => 'Quelle',
	'title' => 'Titel',
);
