<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-08-07 12:05+0000
// PO revision date:  2012-07-12 21:43+0000

$lang = array (
  'captcha' => 
  array (
    'default' => 'Bitte geben Sie einen gültigen Sicherheitscode ein.',
    'required' => 'Bitte geben Sie den Sicherheitscode ein.',
  ),
  'email' => 
  array (
    'email' => 'Das eMail-Feld scheint keine gültige Mailadresse zu enthalten.',
    'length' => 'Das eMail-Feld muss zwischen 4 und 64 Zeichen lang sein.',
    'required' => 'Das eMail-Feld ist erforderlich, wenn die Box angehakt wurde. ',
  ),
  'message' => 
  array (
    'required' => 'Das Kommentarfeld ist notwendig.',
  ),
  'name' => 
  array (
    'length' => 'Das Namensfeld muss min. 3 Zeichen lang sein.',
    'required' => 'Das Namensfeld ist notwendig.',
  ),
  'phone' => 
  array (
    'length' => 'Das Telefonfeld ist nicht gültig.',
  ),
);

