<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-31 12:04+0000
// PO revision date:  2012-07-12 21:45+0000

$lang = array (
  'admin_footer' => 'Diese Nachricht wurde von Deiner Webseite geschickt.',
  'admin_login_url' => 'Administrator Login',
  'admin_new_comment' => 
  array (
    'message' => 'Ein neuer Kommentar wurde eingereicht bezogen auf:',
    'subject' => 'Neuer Kommentar',
  ),
  'admin_new_email' => 
  array (
    'message' => 'Eine neue eMail wurde an Deine Website geschickt.',
    'subject' => 'Neue eMail.',
  ),
  'admin_new_report' => 
  array (
    'message' => 'Ein neuer Bericht wurde auf Deiner Website eingereicht.',
    'subject' => 'Neuer Bericht',
  ),
  'admin_new_sms' => 
  array (
    'message' => 'Eine neue Textnachricht wurde an Deine Website geschickt.',
    'subject' => 'Neue Textnachricht',
  ),
);

