<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-19 00:04+0000
// PO revision date:  2012-08-22 14:57+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Bitte bestätige, dass Du ein Element ausgewählt hast',
		'numeric' => 'Bitte bestätige, dass Du ein Element ausgewählt hast',
		'categories_required' => 'Berichte müssen kategorisiert werden, bevor sich bestätigt werden können',
	) ,
	'action' => array(
		'permission' => 'Du verfügst nicht über die nötigen Rechte, um diese Aktion durchzuführen',
	) ,
);
