<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-29 06:04+0000
// PO revision date:  2012-07-12 21:50+0000

$lang = array (
  'description' => 
  array (
    'length' => 'Das Feld \'Beschreibung\' muss zwischen 3 und 100 Zeichen lang sein.',
    'required' => 'Das Feld \'Beschreibung\' ist notwendig.',
  ),
  'name' => 
  array (
    'alpha_numeric' => 'Das Namensfeld darf nur Zeichen oder Zahlen beinhalten.',
    'length' => 'Das Namensfeld muss zwischen 2 und 30 Zeichen lang sein.',
    'nomodify' => 'Die Rolle SuperAdmin kann nicht verändert werden.',
    'required' => 'Das Feld Name ist notwendig.',
  ),
);

