<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-08-22 12:04+0000
// PO revision date:  2012-08-19 22:45+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'The allow comments field does not appear to contain a valid value?',
	) ,
	'allow_feed' => array(
		'between' => 'The include feed field does not appear to contain a valid value?',
	) ,
	'allow_reports' => array(
		'between' => 'The allow reports field does not appear to contain a valid value?',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'The stat sharing field does not appear to contain a valid value?',
	) ,
	'api' => array(
		'default_record_limit' => 'Standardanzahl von Records der API-Anforderung',
		'maximum_record_limit' => 'Maximale Anzahl an Records die pro API-Anfrage geholt werden.',
		'maximum_requests_per_ip_address' => 'Maximale Anzahl an API-Anfragen durch pro IP-Adresse',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'The Akismet field does not appear to contain a valid value?',
		'length' => 'The Akismet field does not appear to contain a valid value?',
	) ,
	'cache_pages' => array(
		'between' => 'Das Cache Feld ist notwendig.',
		'required' => 'Das Cache Feld ist ungültig',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'Das Cache Feld ist ungültig',
		'required' => 'Das Cache Feld ist notwendig.',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'It looks like your server is not configured to handle clean URLs. You will need to change the configuration of your server before you can enable clean URLs. See more info on how to enable clean URLs at this forum <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">post</a>',
		'clean_url_enabled' => 'This option makes Ushahidi to be accessed via "clean" URLs. Without "index.php" in the URL.',
	) ,
	'configure_map' => 'Konfiguriere Karte',
	'default_location' => 'Standardposition',
	'default_map_all' => array(
		'alpha_numeric' => 'The color feed field does not appear to contain a valid value?',
	) ,
	'default_map_view' => 'Standard Map View',
	'default_zoom_level' => 'Standard Zoom Level',
	'download_city_list' => 'Empfange Staedte von Geonames',
	'email_host' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'email_port' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'email_servertype' => array(
		'length' => 'The Mail server port field is too long',
	) ,
	'items_per_page' => array(
		'between' => 'The items per page (Frontend) field does not appear to contain a valid value?',
	) ,
	'items_per_page_admin' => array(
		'between' => 'The items per page (Admin) field does not appear to contain a valid value?',
	) ,
	'map' => array(
		'default_location' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
	) ,
	'map_provider' => array(
		'choose' => 'Wählen Sie einen Kartenanbieter',
		'enter_api' => 'Eingabe des API Key',
		'get_api' => 'Fordern Sie einen API Key an',
		'info' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
		'name' => 'Kartenanbieter',
	) ,
	'map_settings' => 'Karten Einstellungen',
	'multiple_countries' => 'Does this Ushahidi Deployment Span Multiple Countries',
	'select_default_location' => 'Bitte wählen sie ihr Standardland',
	'set_location' => 'Klicken Sie auf die Karte um Ihre exakte Position zu setzen.',
	'site' => array(
		'allow_clustering' => 'Cluster Reports auf Karte',
		'allow_reports' => 'Erlaube Nutzern Meldungen zu erzeugen.',
		'api_akismet' => 'Akismet Schlüssel',
		'cache_pages' => 'Cache Seiten',
		'cache_pages_lifetime' => 'Seitencache Lebenszeit',
		'copyright_statement' => 'Copyright Statement',
		'default_category_colors' => 'Standardfarbe für alle Kategorien',
		'display_contact_page' => 'Zeige Kontaktseite',
		'display_howtohelp_page' => 'Zeige "Hilfe" Seite',
		'email_alerts' => 'Email Addresse fuer Alarme',
		'email_notice' => '<span>Zum empfangen von Mails muessen Sie Ihre Email-Einstellungen konfigurieren.</span>',
		'email_site' => 'Seite Emailaddresse',
		'items_per_page' => 'Eintraege pro Seite - Front End',
		'items_per_page_admin' => 'Eintraege pro Seite - Admin',
		'language' => 'Sprache der Seite',
		'message' => 'Seiten Nachricht',
		'name' => 'Seitenname',
		'share_site_stats' => 'Share Site Statistics in API',
		'tagline' => 'Seiten Untertitel',
		'title' => 'Seiteneinstellungen',
		'twitter_configuration' => 'Twitter Credentials',
		'twitter_hashtags' => 'Hashtags - trennen durch Kommas ',
	) ,
	'site_email' => array(
		'email' => 'The site email field does not appear to contain a valid email address?',
	) ,
	'sms' => array(
		'clickatell_api' => 'Ihre Clickatell API Nummer',
		'clickatell_check_balance' => 'Checken Sie Ihr Clickatell Buthaben',
		'clickatell_load_balance' => 'Lade Guthaben',
		'clickatell_password' => 'Ihr Clickatell Passwort',
		'clickatell_text_2' => 'Geben Sie Ihre Clickatell Zugangsdaten ein.',
		'clickatell_username' => 'Ihr Clickatell Benutzername',
		'flsms_download' => 'Download Frontline SMS und installieren Sie es auf Ihrem PC',
		'flsms_instructions' => 'Nachrichten die in einem FrontlineSMS empfangen werden können mit Ushahidi synchronisiert werden. Detailierte Anweisungen finden Sie auf <strong><a href="http://wiki.ushahididev.com/doku.php?id=how_to_use_ushahidi_alpha#how_to_setup_frontlinesms_to_sync_with_ushahidi" target="_blank">here</a></strong>. You will require the key and link below to set up the sync with FrontlineSMS',
		'flsms_key' => 'Ihr Ushahidi Sync Key',
		'flsms_synchronize' => 'Synchronisiere mit Ushahidi',
		'flsms_text_1' => 'Geben Sie die Telefonnummer für die Verbindung zu Frontline SMS ein.',
		'flsms_text_2' => 'Geben Sie die Nummer ohne + oder Striche ein.',
		'option_1' => 'Option 1: Nutze Frontline SMS',
		'option_2' => 'Option 2: Nutze ein globales SMS Gateway',
		'title' => 'SMS Setup Optionen',
	) ,
	'sms_no1' => array(
		'length' => 'Das Telefonfeld 1 ist ungültig.',
		'numeric' => 'Das Telefonfeld 1 sollte nur Nummern enthalten.',
	) ,
	'sms_no2' => array(
		'length' => 'Das Telefonfeld 2 ist zu lang.',
		'numeric' => 'Das Telefonfeld 2 sollte nur Nummern enthalten.',
	) ,
	'sms_no3' => array(
		'length' => 'Das Telefonfeld 3 ist zu lang.',
		'numeric' => 'Das Telefonfeld darf nur Nummern enthalten',
	) ,
);
