<?php
	$lang = array(
	'allow_comments' => array(
		'between' => 'The allow comments field does not appear to contain a valid value?',
		'required' => 'The allow comments field is required.',
	),
	'allow_feed' => array(
		'between' => 'The include feed field does not appear to contain a valid value?',
		'required' => 'The include feed field is required.',
	),
	'allow_reports' => array(
		'between' => 'The allow reports field does not appear to contain a valid value?',
		'required' => 'The allow reports field is required.',
	),
	'allow_stat_sharing' => array(
		'between' => 'The stat sharing field does not appear to contain a valid value?',
		'required' => 'The stat sharing field is required.',
	),
	'api_akismet' => array(
		'alpha_numeric' => 'The Akismet field does not appear to contain a valid value?',
		'length' => 'The Akismet field does not appear to contain a valid value?',
	),
	'cleanurl' => array(
		'clean_url_disabled' => 'It looks like your server is not configured to handle clean URLs. You will need to change the configuration of your server before you can enable clean URLs. See more info on how to enable clean URLs at this forum <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">post</a>',
		'clean_url_enabled' => 'This option makes Ushahidi to be accessed via "clean" URLs. Without "index.php" in the URL.',
		'enable_clean_url' => 'Enable Clean URLs',
		'title' => 'Clean URLs',
	),
	'clickatell_api' => array(
		'length' => 'The Clickatell API number field must be no more 20 characters long.',
		'required' => 'The Clickatell API number field is required.',
	),
	'clickatell_password' => array(
		'length' => 'The Clickatell Password field must be at least 5 and no more 50 characters long.',
		'required' => 'The Clickatell Password field is required.',
	),
	'clickatell_username' => array(
		'length' => 'The Clickatell Username field must be no more 50 characters long.',
		'required' => 'The Clickatell Username field is required.',
	),
	'configure_map' => 'Konfiguriere Karte',
	'default_location' => 'Standardposition',
	'default_map_all' => array(
		'alpha_numeric' => 'The color feed field does not appear to contain a valid value?',
		'length' => 'The color field must be no more 6 characters long.',
		'required' => 'The color field is required.',
	),
	'default_map_view' => 'Standard Map View',
	'default_zoom_level' => 'Standard Zoom Level',
	'download_city_list' => 'Empfange Staedte von Geonames',
	'email_host' => array(
		'length' => 'The Mail server port field is too long',
		'numeric' => 'The Mail server port field should contain numbers only.',
	),
	'email_password' => array(
		'length' => 'The Mail Server Password field must be at least 5 and no more 50 characters long.',
		'required' => 'The Mail Server Password field is required.',
	),
	'email_port' => array(
		'length' => 'The Mail server port field is too long',
		'numeric' => 'The Mail server port field should contain numbers only.',
	),
	'email_servertype' => array(
		'length' => 'The Mail server port field is too long',
		'required' => 'The Mail Server Type field is required.',
	),
	'email_username' => array(
		'length' => 'The Mail Server Username field must be no more 50 characters long.',
		'required' => 'The Mail Server Username field is required.',
	),
	'google_analytics' => array(
		'length' => 'The Google Analytics field must contain a valid Web Property ID in the format UA-XXXXX-XX.',
	),
	'items_per_page' => array(
		'between' => 'The items per page (Frontend) field does not appear to contain a valid value?',
		'required' => 'The items per page (Frontend) field is required.',
	),
	'items_per_page_admin' => array(
		'between' => 'The items per page (Admin) field does not appear to contain a valid value?',
		'required' => 'The items per page (Admin) field is required.',
	),
	'map' => array(
		'default_location' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
		'zoom' => 'Zoom Level',
	),
	'map_provider' => array(
		'choose' => 'Waehlen Sie einen Kartenanbieter',
		'enter_api' => 'Eingabe des API Key',
		'get_api' => 'Fordern Sie einen API Key an',
		'info' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
		'name' => 'Kartenanbieter',
	),
	'map_settings' => 'Karten Einstellungen',
	'multiple_countries' => 'Does this Ushahidi Deployment Span Multiple Countries',
	'select_default_location' => 'Bitte waehlen sie ihr Standardland',
	'set_location' => 'Klicken Sie auf die Karte um Ihre exakte Position zu setzen.',
	'site' => array(
		'allow_clustering' => 'Cluster Reports auf Karte',
		'allow_comments' => 'Allow Users to Submit Comments to Reports',
		'allow_feed' => 'Include RSS News Feed on Website',
		'allow_reports' => 'Erlaube Nutzern Meldungen zu erzeugen.',
		'api_akismet' => 'Akismet Schluessel',
		'default_category_colors' => 'Standardfarbe f',
		'display_contact_page' => 'Zeige Kontaktseite',
		'display_howtohelp_page' => 'Zeige "Hilfe" Seite',
		'email_alerts' => 'Email Addresse fuer Alarme',
		'email_notice' => '<span>Zum empfangen von Mails muessen Sie Ihre Email-Einstellungen konfigurieren.</span>',
		'email_site' => 'Seite Emailaddresse',
		'google_analytics' => 'Google Analytics',
		'google_analytics_example' => 'Web Property ID - Format: UA-XXXXX-XX',
		'items_per_page' => 'Eintraege pro Seite - Front End',
		'items_per_page_admin' => 'Eintraege pro Seite - Admin',
		'kismet_notice' => 'Prevent comment spam using <a href="http://akismet.com/" target="_blank">Akismet</a> from Automattic. <BR />You can get a free API key by registering for a <a href="http://en.wordpress.com/api-keys/" target="_blank">WordPress.com user account</a>',
		'laconica_configuration' => 'Laconica Credentials',
		'laconica_site' => 'Laconica Site ',
		'language' => 'Sprache der Seite',
		'name' => 'Seitenname',
		'share_site_stats' => 'Share Site Statistics in API',
		'tagline' => 'Seiten Untertitel',
		'title' => 'Seiteneinstellungen',
		'twitter_configuration' => 'Twitter Credentials',
		'twitter_hashtags' => 'Hashtags - trennen durch Kommas ',
	),
	'site_email' => array(
		'email' => 'The site email field does not appear to contain a valid email address?',
		'length' => 'The site email field must be at least 4 and no more 100 characters long.',
	),
	'site_name' => array(
		'length' => 'The site name field must be at least 3 and no more 50 characters long.',
		'required' => 'The site name field is required.',
	),
	'site_tagline' => array(
		'length' => 'The tagline field must be at least 3 and no more 100 characters long.',
		'required' => 'The tagline field is required.',
	),
	'sms' => array(
		'clickatell_api' => 'Ihre Clickatell API Nummer',
		'clickatell_check_balance' => 'Check Your Clickatell Credit Balance',
		'clickatell_load_balance' => 'Load Credit Balance',
		'clickatell_password' => 'Your Clickatell Password',
		'clickatell_text_1' => 'Sign up for Clickatells service by <a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">clicking here</a>',
		'clickatell_text_2' => 'Enter your Clickatell access information below',
		'clickatell_username' => 'Your Clickatell User Name',
		'flsms_description' => 'FrontlineSMS is free open source software that turns a laptop and a mobile phone into a central communications hub. Once installed, the program enables users to send and receive text messages with large groups of people through mobile phones. Click on the grey box to request a download from FrontlineSMS.com',
		'flsms_download' => 'Download Frontline SMS and install it on your computer',
		'flsms_instructions' => 'Messages received into a FrontlineSMS hub can be synched with Ushahidi. Detailed instructions on how to sync can be found <strong><a href="http://wiki.ushahididev.com/doku.php?id=how_to_use_ushahidi_alpha#how_to_setup_frontlinesms_to_sync_with_ushahidi" target="_blank">here</a></strong>. You will require the key and link below to set up the sync with FrontlineSMS',
		'flsms_key' => 'Your Ushahidi Sync Key',
		'flsms_link' => 'FrontlineSMS HTTP Post LINK',
		'flsms_synchronize' => 'Sync with Ushahidi',
		'flsms_text_1' => 'Enter phone number(s) connected to Frontline SMS in the field(s) below',
		'flsms_text_2' => 'Enter the number without any + or dashes below',
		'option_1' => 'Option 1: Nutze Frontline SMS',
		'option_2' => 'Option 2: Nutze ein globales SMS Gateway',
		'title' => 'SMS Setup Options',
	),
	'sms_no1' => array(
		'length' => 'The phone 1 field does not appear to contain a valid value?',
		'numeric' => 'The phone 1 field should contain numbers only.',
	),
	'sms_no2' => array(
		'length' => 'The phone 2 field is too long',
		'numeric' => 'The phone 2 field should contain numbers only.',
	),
	'sms_no3' => array(
		'length' => 'The phone 3 field is too long',
		'numeric' => 'The phone 3 field should contain numbers only.',
	));
?>
