<?php
	$lang = array(
	'approved' => 'Kontrolliert',
	'categories' => 'Kategorien',
	'category_impact' => 'Betroffene Kategorien',
	'category_impact_description' => 'Diese Grafik gibt Ihnen einen Ueberblick der Meldungen ueber die Zeitspanne. Scrollen Sie von links nach rechts um die verschiedenen Kategorien zu sehen. Bewegen Sie die Maus ueber die Grafik fuer mehr Details.',
	'choose_date_range' => 'Datumsbereich waehlen',
	'countries' => 'Laender',
	'country' => 'Land',
	'country_breakdown' => 'Benutzerlaender',
	'description' => 'Hier ist der Statistikbereich. Nutzen Sie die Links und Untermenues oben',
	'error' => 'Fehler',
	'glossary' => 'Glossar',
	'hit_summary' => 'Trefferaufstellung',
	'legend' => 'Legende',
	'pageviews' => 'Seitenaufrufe',
	'pageviews_description' => 'Gesamtsumme der Seitenaufrufe der Gesamtseite.',
	'reports' => 'Reports',
	'reports_categories' => 'Meldungs-Kategorie',
	'reports_statistics' => 'Statistik der Meldungen',
	'reports_status' => 'Meldungsstatus',
	'report_stats' => 'Report Statistik',
	'stats_not_setup' => 'Statistik noch nicht eingestellt.',
	'time_range_1' => '1 Monat',
	'time_range_2' => '3 Monate',
	'time_range_3' => '6 Monate',
	'time_range_all' => 'Alle',
	'unapproved' => 'Nicht kontrolliert',
	'unique_visitors' => 'Besucher',
	'unique_visitors_description' => 'Anzahl der Benutzer, welche das System besuchen. Die Identifizierung erfolgt ueber Cookies. Im Fall das der Besucher Cookies gespert hat, erfolgt die Identifizierung ueber IP-Adresse, Aufloesung, Browser, Plugins, Betriebssystem etc',
	'unverified' => 'Ungeprueft',
	'verified' => 'Geprueft',
	'visitor_summary' => 'Besucheruebersicht',
	'visits' => 'Besuche',
	'visits_description' => 'Ein Besuch ist festgelegt wenn ein Besucher mindestens 30 Minuten vorher die Seite nicht besucht hat.',
	);
?>
