<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex

// I18n generated at: 2012-07-24 00:04+0000
// PO revision date:  2012-07-12 21:58+0000

$lang = array (
  'upgrade' => 
  array (
    'between' => 'Ungültige Eingabe. Enweder 1 für Ja oder 0 für Nein.',
  ),
  'upgrade_automatic' => 'Automatisches Update',
  'upgrade_available' => 'Verfügbare Updates',
  'upgrade_continue_btn_text' => 'Fortfahren',
  'upgrade_db_btn_text' => 'Aktualisieren',
  'upgrade_db_text_1' => 'So, Ich beginne damit Ihre Datenbank zu upgraden von Version',
  'upgrade_db_text_2' => 'auf die neueste Datenbank Version',
  'upgrade_db_text_3' => 'Klick auf den Update Button und relax während ich das Wunder vollbringe.',
  'upgrade_db_text_4' => 'Wen ich das Backup machen soll müssen SIe auf den Button klicken und ich werde mein Bestes geben :-).',
  'upgrade_db_text_5' => 'Backup machen vor dem Update? (<strong style="color:#FF0000;">Sehr zu empfehlen!!</strong>)',
  'upgrade_db_title' => 'Ushahidi Datenbank Aktualisierung',
  'upgrade_failed' => 'Aktualisierung fehlgeschlagen',
  'upgrade_manual' => 'Manuelles Update',
  'upgrade_status' => 'Ushahidi Aktualisierungsstatus',
  'upgrade_text_1' => 'Untenstehend ist erklärt, wie Sie Ihre Ushahidi-Instanz manuell aktualisieren können.',
  'upgrade_text_2' => '<strong>Schritt 1:</strong> Lade die neueste Ushahidi Version von <a href="http://download.ushahidi.com/">http://download.ushahidi.com</a> herunter',
  'upgrade_text_3' => '<strong>Schritt 2:</strong> Abhängig von dem Betriebssystem Ihres Webservers nutzen Sie den bevorzugtes/n Werkzeug/Modus (d.h.: telnet, ftp, ssh) um sich auf dem Webserver anzumelden und den Inhalt aller Ordner mit den neuesten Dateien zu ersetzen. <strong>Alle BIS AUF:</strong>',
  'upgrade_text_4' => 'Schritt 3: Nutzen Sie ihren bevorzugten Mysql Client (z.B.. phpMyAdmin ), und führen Sie die Datei<code>upgrade.sql</code> aus. Das Script sollten das Update durcführen und die Tabellen aktualisieren.',
  'upgrade_text_5' => 'Für ein automatisches Update klicken Sie auf die Schaltfläche unten.',
  'upgrading' => 'Updating...',
);

