<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-11 06:25+0000
// PO revision date:  2013-12-10 22:42+0000
$lang = array(
	'actions' => array(
		'add_to_category' => 'Esto inclúe informes de categorías adicionáis. Se selecciona Categoría 1 eiquíe o Informe xa ten a Categoría 2 vencellada, o Informe terá asociadas ambalasdúas.',
		'approve' => 'Aproba o informe ou non. Se o aproba, aparecerá publicado.',
		'assign_badge' => 'Poderá asignar un distintivo a un/ha usuario/a disparador/a',
		'between_times' => 'Trátase dun rango horario entre dous espazos de tempo en formato de 24hs. Se se introduce un tempo anterior no segundo campo, trocarase cara ao primeiro. Ambos tempos deben estar no mesmo día. Amais, este tempo é comparado co que se establecera no site nas configuracións e pode <strong>non estar definido</strong>necesariamente no mesmo fuso horario da/o usuaria/o que participa no Ushahidi.Deixe os valores a 00:00 e 00:00 para ignorar este habilitador.',
		'category' => 'Se quere activar un disparador só cando certa categoría estea sendo usada pode facelo eiquí. Esto permite cun disparador se active únicamente candose empregue determiñada categoría. Por exemplo, se se seleccionan as Categorías 1 e 2 eiquí e un informe he enviado empregando as Categorías  2 e 3, o informe pasará o test.',
		'days_of_the_week' => 'Se esas accións acontecen en certos días da semana, definao eiquí. Teña en conta que o día determíñase segundo o fuso horario configurado na súa instancia do Ushahidi. Empregue Shift, Command ou Control para seleccionar múltiples días.',
		'email_body' => 'Corpo do correo a enviar.',
		'email_subject' => 'Asunto do correo a enviar.',
		'feed_id' => 'O feed pode ser de todolos feeds ou dun feed específico. Se se quere que só certos feeds activen un disparador, debense escoller eiquí. En caso contrario deixe esto co valor predetermiñado: "todos"',
		'from' => 'Nome da/o usuario/a no Twitter (ou múltiples nomes separados por comas). Se ten intención de activar disparadores só para twits dun/ha usuario/a concreto/a introduza o seu nome eiquí (sen incluir a @)',
		'keywords' => 'Pódese deixar en branco se non se queren verificar palabras-chave. Se se engaden palabras eiquí, hai que separalas con comas (,). Por exemplo, se se queren activar disparadores cando alguén mencione "amor" ou "paz"na súa mensaxe, haberá que engadir: "paz, amor" na caixa de palabras-chave.',
		'location' => 'Pódese seleccionar calquera lugar ou unha localización específica. Neste último caso, solicitarase que debuxe unha caixa delimitando a área que require unha acción. Por exemplo, se se quere cun disparador se active cando alguén presente un informe sobre Ourense, hai que seleccionar "área específica" e deseguido debuxar unha "caixa" en torno a Ourense. Pódense facer éstas tan grandes ou pequenas como se queira. Tamén é posible debuxar múltiples caixas.',
		'on_specific_count' => 'Este habilitador activará o disparador na conta nº X contrastándoa contra o conxunto de usuarias/os ou para cada usuaria/o individualmente. Deixeo en branco se prefire ignoralo.',
		'report_title' => 'Este é o título predetermiñado para engadir a un informe.',
		'response' => 'Se todolos habilitadores enriba estibesen activos, o disparador iniciaría unha resposta. Esto pode se dende aprobar un Informe a enviar un email a un/ha usuario/a. Seleccione eiquí a resposta para activar opcións adicionáis para respostas específicas.',
		'send_to' => 'Se selecciona "Usuario/a Disparador/a", o correo será enviado a/ao usuaria/o que executou a acción concreta. Se se selcciona o botón de radio ao carón da caixa de entrada, poderá incluir un enderezo de correo persoalizado. Ésto é útil se se están configurando disparadores para notificar á xente cando certas zonas no mapa reciben informes, chekins ou calqueira outra actividade.',
		'specific_days' => 'Pode seleccionar múltiples días eiquí. As datas veñen determiñadas polo fuso horario definido na configuración do site. Se non selecciona nengunha data, o sistema amosará predetermiñadamente tódalas datas.',
		'trigger' => 'O disparador é o compoñente central na configuración das Accións Disparadoras.Eiquí é onde se determiña qué aconterá cando alguén envía un informe, fai un checkin, etc. Eiquí pode filtrar as respostas a esas accións despois de seleccionar un disparador.',
		'user' => 'A/o usuaria/o pode ser un/ha calquera ou un/ha específico/a. Se se quere traballar con un/ha concreto/a, hai que seleccionalo/a. En caso contrario, hai que deixar o valor a "calquera" xa que a maioría dos disparadores establécense para todolas/os usuarias/os que interactúan co sistema.',
		'verify' => 'Marca o informe como verificado ou non.',
	) ,
	'change_picture' => 'As páxinas de perfil no site empregan Gravatar. Ao premer na súa imaxe, será redirixida/o ao site Gravatar onde poderá trocar a súa foto de perfil.',
	'default_value' => 'Separe cada valor cunha cona, p.ex. valor1, valor2.',
	'radio_choices' => 'Separe cada valor cunha coma, p.ex. valor1, valor2. No caso de querer definir un valor predetermiñado, remate a súa lista de opcións con :: P.ex. se quere que o valor3 sexa o predetermiñado, a cousa sería: valor1, valor2, valor3::valor3',
	'dropdown_choices' => 'Separe cada elemento seleccionado cunha coma, p.ex.: Elemento1, Elemento2, etc.',
	'private_to' => 'Comence a escreber a lista de membros.',
	'private_subject' => 'Asunto da mensaxe privada',
	'private_message' => 'Mensaxe privada',
	'profile_color' => 'Pode seleccionar unha cor que será a que apareza baixo a súa imaxe no perfil público. Esta cor será tamén asociada aos puntos dos seus checkins no mapa.',
	'profile_email' => 'O seu enderezo de correo',
	'profile_name' => 'Este é un dos xeitos nos que será identificado no site. Téñao en conta, pois é un dato público!',
	'profile_new_password' => 'Se se define, ésta ha ser o seu novo contrasinal. Deixe o campo en branco se prefire manter o actual.',
	'profile_new_users_password' => 'Este é un requisito cando se crea un/ha novo/a usuario/a e establece os seus respectivos contrasináis. Debe avisar ás/aos novas/os usuarias/os de que troquen o seu contrasinal ao acceder por vez primeira á conta.',
	'profile_notify' => 'Ao seleccionar SÍ, recibirá alertas via mail en canto un novo informe ou un comentario sexa publicado no site.',
	'profile_password' => 'O seu contrasinal actual. É preciso que introduza o sue contrasinal para alguén sen autorización poda trocar cousas na súa conta.',
);
