<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-07 06:14+0000
// PO revision date:  2013-04-06 22:41+0000
$lang = array(
	'private_to' => array(
		'required' => 'Prejemnik je zahtevan',
		'exists' => 'Uporabnik, ki mu poskušate poslati sporočilo, ne obstaja',
	) ,
	'private_subject' => array(
		'required' => 'Potrebno je izpolniti okno z naslovom.',
		'length' => 'Naslov mora vsebovati med 3 in 150 znakov',
	) ,
	'private_message' => array(
		'required' => 'Potrebno je izpolniti okno z sporočilom.',
	) ,
);
